### ISSUE TITLE
[São Paulo] Fullstack Developer Javascript

### ISSUE THREAD

**Issue by sibelius** [react-brasil/vagas#1]
complete job information: https://github.com/entria/vagas

## Job Description
You going to be working on fullstack projects (backend, frontend, mobile) only using bleeding edge tech, mostly javascript.

## Challenge
Finish the challenge will give you advantage over others applicants - https://github.com/entria/vagas/blob/master/challenge.md

## Skills
What skill we would like you to have- https://github.com/entria/vagas/blob/master/skills.md

## Email
If you gotta interested by this job, apply sending an email to `vagas@entria.com.br` with your github, linkedin and resume

**Comment by nicholasess** [comment]
@sibelius a vaga ainda está em aberto? É presencial ou remoto?
