### ISSUE TITLE
[Uberlândia-MG] Arena - Desenvolvedor Front-End

### ISSUE THREAD

**Issue by rodrigoreis22** [react-brasil/vagas#10]
## Empresa
Arena is a platform for sports fans to chat with one another during live events. Working with sports like UFC, Arena gives fans a place to connect that's not as cluttered as Twitter or Facebook, and that's focused just on the live event. Arena boasts some impressive audience numbers, it has more than 700,000 monthly active users and had over 100,000 uniques on a single UFC event. The startup is building widgets to allow websites and blogs to host Arena chats directly on their site. A part of Techstars Chicago 2016 class, we recently raised our seed round from strategic sports investors and we are growing very quickly.
Check out our demo day pitch: https://techstars.wistia.com/medias/j33uigdvk9 

## Descrição da vaga
As a Front-End engineer you’ll work closely with our product team to build new exciting features. You will get to wear multiple hats as you work on APIs and UI, build systems, architecture and new features.

We believe in a strong, friendly engineering culture. Our team of hackers and thinkers is small, lean, and empathetic. We're looking for self motivated people who are excited about what we're working on and want to be a part of this project.

## Posição
Front-End Developer

## Tipo de contratação
Local - Uberlândia/MG. We're based in Silicon Valley and are building our engineering team in Brazil. You must be ok with occasional travel to San Francisco, all expenses paid.

###### Obrigatórios
1+ years of experience building Web Apps
B.S. in Computer Science or equivalent 
Experience with Javascript framework React or other popular frameworks (AngularJS, React, Backbone, EmberJS, Vue.js)
Experience with markup/styling languages (HTML5, CSS3, SASS)
Good understanding of cross browser compatibility issues
Eager to work in fast-paced startup environment and a desire to disrupt the sports industry 

###### Diferenciais
Previous startup experience
Remote work experience

## Benefícios
Opportunity for stock options
Impact-first work environment (no politics, no pandering, no BS) 
Huge company vision (build the future, not just maintain the status quo) 
Contribute to open source projects

## Como aplicar
E-mail com LinkedIn para rodrigo@arena.im ou contacte-me no Slack: @rodrigoreis 

## Contato
Rodrigo - CTO
rodrigo@arena.im

**Comment by nicholasess** [comment]
@rodrigoreis22 a vaga ainda está em aberto?

**Comment by rodrigoreis22** [comment]
Está fechada @nicholasess . Desculpa, esqueci de fechar a issue.
