### ISSUE TITLE
[São Paulo/Remoto] Full Stack JavaScript Developer na Sallve (Junior/Pleno/Senior)

### ISSUE THREAD

**Issue by jgcmarins** [react-brasil/vagas#1009]
## Descrição da vaga

- [Junior](https://github.com/sallve/jobs/blob/main/full-stack-engineer-junior-pt-BR.md)

- [Pleno](https://github.com/sallve/jobs/blob/main/full-stack-engineer-pleno-pt-BR.md)

- [Senior](https://github.com/sallve/jobs/blob/main/full-stack-engineer-senior-pt-BR.md)

## Local

Remoto ou Escritório em São Paulo - Pinheiros

## Benefícios

- Plano de saúde
- VA/VR de R$ 30/dia
- Auxílio para cursos
- Materiais para Home Office

## Contratação

CLT

## Nossa empresa

a [sallve](https://www.sallve.com.br/) é uma startup brasileira de beleza direct-to-consumer (DTC) 100% digital, [investida pelos principais fundos brasileiros](https://www.crunchbase.com/organization/sallve/company_financials) e crescendo rápido. somos obcecados pela experiência da nossa comunidade e por isso, nossa missão vai além de criar uma marca: estamos construindo um espaço que conecta pessoas, ideias e conteúdos sobre um novo mercado de beleza.

## Como se candidatar

Você pode se candidatar [aqui](https://sallve.breezy.hr/p/f62ac6f208af-pessoa-desenvolvedora-de-software-fullstack).

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 💰 5k-10k
- 💰 10k-15k

**Comment by italo-lima** [comment]
Aceita part time?

**Comment by jgcmarins** [comment]
Olá, @italo-lima, no momento só estamos aceitando full-time.

**Comment by PaulosSouza** [comment]
Olá @jgcmarins tudo bem? A vaga ainda está aberta para os três tipos (Junior, Pleno e Senior)?

**Comment by AbimaelAndrade** [comment]
Vamos conversar?

**Comment by AbimaelAndrade** [comment]
https://github.com/react-brasil/me-contrata/issues/86#issue-750759002

**Comment by AbimaelAndrade** [comment]
https://github.com/react-brasil/me-contrata/issues/86#issue-750759002
