### ISSUE TITLE
[Remote / Cascavel/PR] Desenvolvedor Frontend na TruckPag Meios de Pagamento

### ISSUE THREAD

**Issue by alexssandrog** [react-brasil/vagas#1020]
## A Empresa
A TruckPag Meios de Pagamento é uma startup com foco em gestão de abastecimento e pagamento de frete, sediada em Cascavel/PR e atuando há um ano e meio. 

Apesar da pouca idade, a empresa cresce a passos largos e precisa de uma equipe de desenvolvedores para ajudar a garantir que esse crescimento seja sustentável!

## Descrição da vaga
Estamos buscando pessoas desenvolvedoras, frontend ou fullstack, com experiência com ReactJS. 

Essa pessoa precisa ser proativa, que possa atuar bem em equipe e que possa ajudar colegas com menos experiências (já temos júnior na equipe).

O trabalho consiste na criação e manutenção de portais para atender ao negócio da empresa, incluindo a migração dos portais atuais para novas tecnologias e abordagens. O projeto legado, principal sistema da empresa, foi escrito em ASP.Net. Além dele, já tem alguns outros projetos em operação ou projeto.

## Local
Remoto ou Presencial, Cascavel/PR

## Requisitos
**Obrigatórios:**
- Stack atual: 
    - ReactJS
    - MaterialUI (ou outra lib equivalente)
    - Redux/Redux Toolkit
    - React Tesling Library
- Atenção à detalhes na implementação de layouts
- Uso de sistema de controle de versão (Git)
- Experiência de trabalho com APIs REST, ou integrar uma API de terceiros ou criar o seu próprio, quando necessário.

**Desejáveis:**
- Conhecimento básico de pelo menos uma linguagem server side (PHP, Node.js, etc)
- Experiência com UI e UX

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para ti@truckpag.com.br com seu GitHub/portifólio ou CV anexado - enviar no assunto: Vaga Desenvolvedor

## Labels

- Flexível
- Remoto
- Presencial
- Pleno
- PJ

**Comment by italo-lima** [comment]
somente full time?

**Comment by alexssandrog** [comment]
> somente full time?

Sim, somente full tile

**Comment by moreiraandre** [comment]
Essa vaga é Full Remoto?

**Comment by alexssandrog** [comment]
> Essa vaga é Full Remoto?

Sim, full remoto
