### ISSUE TITLE
[REMOTO] 2 vagas - Dev ReactJS Junior/Pleno

### ISSUE THREAD

**Issue by kamiarc** [react-brasil/vagas#1026]
## Descrição da vaga

Vaga para dev frontend em projeto de webapp whitelabel, projeto já iniciado com time ativo (projeto principal: webapp para feiras / eventos e outro projeto secundário, a decidir com base na experiência / fit)

## Local

Remoto

#### Diferenciais

- Horário flexível
- Full remoto

## Requisitos

**Obrigatórios:**
- 2+ anos de experiência com desenvolvimento, JS / ReactJS

**Desejáveis:**
- Redux / Hooks
- Router
- MaterialUI
- Firebase
- Webpack
- CSS/Sass avançado (sem utilizar libs)
- conhecimentos em AWS, Firebase e NoSQL (para melhor entendimento do projeto)

## Contratação

PJ a combinar

## Nossa empresa

A Onesight é uma multinacional com múltiplos focos no mercado tecnológico, desde apps para micronegócios, apps para feiras e eventos, uma plataforma inovadora para SmartAgro e outsourcing, atuando no mercado Brasileiro, Europeu e Australiano.

## Como se candidatar

Por favor envie um email para lucas@onesight.com.br com seu CV anexado, pretensão salarial e link do github/gitlab/site

## Labels
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ

**Comment by italo-lima** [comment]
vaga continua em aberto?

**Comment by kamiarc** [comment]
Sim!

Il dom 6 dic 2020, 22:58 Ítalo Lima <notifications@github.com> ha scritto:

**Comment by italo-lima** [comment]
te mandei invite no linkedin, para te indicar um dev

**Comment by MiguelS007** [comment]
Ok

Em dom, 6 de dez de 2020 22:22, Ítalo Lima <notifications@github.com>
escreveu:
