### ISSUE TITLE
[REMOTO, USA] Pessoa desenvolvedora JavaScript (React, GraphQL, NodeJS) na BEN

### ISSUE THREAD

**Issue by viniciusdacal** [react-brasil/vagas#1027]
## Descrição da vaga

Who YOU Are 
Do you have an affinity for technology?  Do you embrace the challenge as a technologist thriving on building systems that solve problems and contribute to others success?  Are you a seasoned developer with strong JavaScript skills with proven track record of delivery?  We are a full stack JavaScript team, but you don't have to be... yet, front end or backend specialist are encouraged to apply. We strongly believe in learning by doing and are excited to learn more with you. If you want to work with a highly talented, diverse, and motivated team with great camaraderie, this could be your dream job. As a Developer, your role would be to help design, build, implement and support the BEN platform as part of an application development team.  

## Responsibilities

 - Design, build, implement and support features for the product integration platform as part of an application development team 
 - Make our platform even better  

Qualifications & Skills
 - Minimum of 5 years’ hands-on experience with JavaScript (React or Node, ideally both) 
 - A track record in taking features from inception through to delivery and supporting them once live 
 - A passion for best practice design and code and a desire to develop innovative new ideas 
 - A strong understanding of the JavaScript ecosystem on the front and/or backend 
 - An experience with the entertainment industry (tv, film, music videos), social media (YouTube, Instagram, Twitch, TikTok etc) or gaming would be an advantage 
 - An experience with Product Placement, Influencer campaigns, Performance Marketing or Paid Media would also be an advantage 
- Most importantly - An inquisitive mind, someone who enjoys learning, delivering value to users and having success as a team 

## Local
Remote

## Contratação

PJ a combinar

## Nossa empresa
Who WE Are 
The Branded Entertainment Network (BEN) connects global brands to consumers through the power of popular entertainment. From the world-leading product integration platform to the global leader for rights clearances and representation (Greenlight). And most recently, TubeBuddy, the newest member of the BEN family and the most popular tool for YouTube creators. The Branded Entertainment Network helps elevate projects, amplify brands, empowers creators and captivate audiences.  Our team is global, with offices in Los Angeles (headquarters), New York, San Diego, London, Shanghai, and Provo.  BEN is privately held company, wholly owned by Bill Gates.  
 
At BEN, we recognize that our employees are the key to the company’s success and work hard to maintain our incredible company culture.  While BEN is a well-established organization and a recognized industry leader with a rich history of integration and licensing success stories, we have not abandoned our start-up mentality.  BEN continually evolves branding strategies through artificial intelligence and predictive modelling to meet the unique needs of our clients.  To that end, BEN is results-oriented, client-centric, and highly creative organization which offers candidates the opportunity to learn from the best and the brightest in this dynamic industry.  BEN offers a competitive benefits package and promotes an environment which supports our core values of Passion, Accountability, Teamwork, and Inclusion.   

## Como se candidatar

Interested? Sound like a team you would like to be part of? Would you like to know more? Let's talk!

Please answer some/all of the follow questions in your cover letter:

 - What links of yours should we read to get to know you better? GitHub, Blog, LinkedIn, etc

 - What editor/ide do you use and why?

 - Framework or Library?

 - Monolith or Micro services or Serverless?

 - What is your preferred way to handle asynchronicity in JavaScript and why?

 - What’s the latest module/technique/idea related to JavaScript that you found interesting/impressive.

 - What new (non-JavaScript) technology interests you?

 - Do you have any side projects/hobbies/interesting stories you would like to tell us about?

 - If you could have any superpower, what would it be?

Please apply via our careers page (the posting will say Provo UT, but we are considering submissions from Brazil: https://ben.productplacement.com/careers/?id=74c2f4d0-fbbd-4830-acdc-10f12d57f113

## Labels

- 🏢 Flexível
- 🏢 Remoto
- ⚖️ PJ

**Comment by lucasalmeida92** [comment]
Nice opportunity! Just applied ;]

**Comment by viniciusdacal** [comment]
Nesse momento, todas as vagas foram preenchidas. Agradeço a todos que aplicaram.
