### ISSUE TITLE
[Remoto/Itália] - React Developer Pleno/Sênior

### ISSUE THREAD

**Issue by fjuriolli** [react-brasil/vagas#1037]
## Descrição da vaga

Buscamos desenvolvedores com um perfil pleno/sênior para integrar o nosso time de desenvolvimento.

## Local

100% remoto, empresa com base na Itália, horário flexível.

## Requisitos

- Desenvolva código limpo, testável e de fácil manutenção.
- Contribua com todo o processo de desenvolvimento de software.
- Contribua nas discussões técnicas sobre os desafios encontrados.

**Obrigatórios:**
- 2 anos de experiência com Javascript, React.js, TypeScript.
- Experiência em projetos utilizando componentes de classe.

**Desejáveis:**

- Inglês para participar das nossas dailys.
- Experiência com styled components.
- Experiência com firebase.
- Experiência com metodologias ágeis.

## Contratação

PJ entre €1500 - €1800 (aproximadamente R$9.500 - R$11.500 líquido de acordo com a senioridade)
OBS: taxas de impostos brasileiras pagas pela própria empresa.

## Como se candidatar

Por favor envie um email para guilherme@hashtag.be e fernando@hashtag.be com seu CV e linkedin.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 10k-15k

**Comment by lucasalmeida92** [comment]
Currículo enviado ;]
