### ISSUE TITLE
Vaga Engenheiro de Aplicação Android - Manaus /AM

### ISSUE THREAD

**Issue by rose12fabi** [react-brasil/vagas#106]
Engenheiro de Aplicação Android
Oportunidade de trabalhar em melhorias de experiência do usuário, design em novos serviços de internet móvel, responsabilidades incluem análise de requisitos, design, codificação, revisão por pares, teste de unidade, teste de integração e correção de bugs.
3 + anos de experiência em desenvolvimento Android APP 
Conhecimento no framework de aplicativos Android 
Conhecimento em GIT 
Diferencial: Conhecimento do desenvolvimento de C / C ++ e JNI é uma vantagem
Local de Trabalho: Manaus – AM
Contratação CLT Full + Benefícios

Encaminhar currículo atualizado para roseli.reis@triadsystems.com.br / selecao@itriad.org.br

**Comment by danielGalvao** [comment]
Apenas vagas de React/RN

**Comment by danielGalvao** [comment]
Apenas vagas de React/RN

**Comment by danielGalvao** [comment]
Por favor postar em: https://github.com/androiddevbr/vagas
