### ISSUE TITLE
[São Bernardo do Campo] - Analista Progress

### ISSUE THREAD

**Issue by rose12fabi** [react-brasil/vagas#107]
Analista Programador Progress 
Experiência em desenvolvimento utilizando Progress 4GL/ Character.
Análise baseados em modelagem UML/RUP, levantamento e planejamento de requisitos, especificação funcional e técnica.
Diferenciais
Conhecimento em banco de dados Oracle.
Conhecimento em sistemas de Logística, Produção e Comércio Exterior.
Local de trabalho: São Bernardo do Campo
Contratação: CLT + Benefícios

Encaminhar currículo atualizado para roseli.reis@triadsystems.com.br com a sigla ANAL PROG.

**Comment by nicholasess** [comment]
@rose12fabi O foco desse repositório é somente vagas de React.

Vou fechar o repositório.

Obrigado
