### ISSUE TITLE
[Remoto/Itália] - React Native Developer Junior na Hashtag.be

### ISSUE THREAD

**Issue by fjuriolli** [react-brasil/vagas#1076]
## Descrição da vaga

Buscamos desenvolvedores com um perfil junior para integrar o nosso time de desenvolvimento.

## Local

100% remoto, empresa com base na Itália, horário flexível.

## Requisitos

- Desenvolva código limpo, testável e de fácil manutenção.
- Contribua com todo o processo de desenvolvimento de software.
- Contribua nas discussões técnicas sobre os desafios encontrados.

**Obrigatórios:**
- Experiência com desenvolvimento em React Native na criação de aplicativos para iOS e Android.
- Experiência com Typescript.

**Desejáveis:**

- Experiência com styled components.
- Experiência com firebase.
- Experiência com metodologias ágeis.
- Inglês para participar das nossas dailys.

## Contratação

PJ €1.000 (aproximadamente R$6.000 - R$6.500 líquido com a cotação atual do euro).
OBS: todas as taxas de impostos brasileiras são pagas pela própria empresa.

## Como se candidatar

Por favor envie um email com o título "React Native Developer Junior" para guilherme@hashtag.be e fernando@hashtag.be com seu CV e linkedin.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 💰 5k-10k

**Comment by AlissonBlaas** [comment]
Enviado!
