### ISSUE TITLE
[São Paulo] Especialista Tableau

### ISSUE THREAD

**Issue by rose12fabi** [react-brasil/vagas#108]
Especialista TABLEAU
Ampla experiência (03 anos ou +) em Tableau Desktop
Experiência em montagem avançada de reports, indicadores e dashboards utilizando Tableau.
Desenvolvimento de ETL (Cargas e transformações de dados de MODELO OLTP para MODELO DIMENSIONAL/MULTIDIMENSIONAL)
Montagem de Modelo Semântico no Tableau
Elaboração de especificação funcional e técnica.
Conhecimentos em Banco de Dados Oracle, PL/SQL, ETL.
Diferencial: Conhecimentos na instalação e manutenção do Tableau Server e desenvolvimento BI e DW.
Local de Trabalho: Região Av. das Nações Unidas
Contratação: CLT Full + Benefícios

Encaminhar currículo atualizado para roseli.reis@triadsystems.com.br

**Comment by nicholasess** [comment]
@rose12fabi o foco desse repositório é somente vagas de React.
Vou fechar a issue!

Obrigado
