### ISSUE TITLE
[São Paulo] Desenvolvedor(a) Azure Spring Cloud Senior na AVANADE

### ISSUE THREAD

**Issue by AndersonAmilton** [react-brasil/vagas#1087]
## Descrição da vaga

Atuará com os métodos ágeis de desenvolvimento em relação ao suporte operacional das plataformas.
Será responsável por projetar, desenvolver e testar soluções empresariais e outros projetos de desenvolvimento de aplicativos customizados
Realizará funções de criação, e manutenção dos aplicativos existentes
Atuação em todas as diferentes fases do projeto, desde a definição de requisitos técnicos, operacionais e do usuário até o planejamento, controle de qualidade e desenvolvimento
Responsável por criar uma arquitetura conceitual e/ou desenvolver opções de solução que correspondam às necessidades dos seus clientes, fazendo parcerias com equipes de tecnologia multifuncional para integrar soluções
Atuação com desenvolvimento, focado principalmente em Java 8, Springboot, SQL ou Oracle, Git ou Maven, JSF, JPA, Junit, Jenkins, Microsoft Azure App Service
Conhecimento no consumo de serviços SOAP (XML) e REST (JSON), Apache Camel, Métodologia Ágil (Scrum), arquitetura de aplicação ou técnica
Analisar, projetar, desenvolver e testar sistemas em diversos contextos será uma parte essencial do seu dia a dia Desenvolvimento de soluções de software customizadas e/ou baseadas em Web/App

## Local

Escritório, São Paulo

## Benefícios

Vale refeição ou alimentação
Vale transporte ou fretado
Assistência médica e odontológica
Certificações e treinamentos
Seguro de Vida
Previdência Privada
EF – Inglês
Avababy: acompanhamento da gestação e kit para os novos pais e mães Avanade
Horários flexíveis
Participação nos resultados da empresa
Gympass 
Auxílio creche
Career Advisor (um braço direito para orientar a sua carreira)
Exposição com times globais a depender do projeto
Avaliação formal de performance e carreira
Job Rotation (possibilidade de rotacionar entre projetos, conhecer mais tecnologias e diversos segmentos de mercado)
Buddy – aquela pessoa que irá te ajudar nos seus primeiros meses e na fase de adaptação à nossa cultura
Veículo corporativo, estacionamento e auxílio combustível para função gerencial ou superior

## Requisitos

**Obrigatórios:**
Experiência de pelo menos dois anos com Java
Experiência de pelo menos dois anos com orientação a objetos
Experiência de atuação com metodologias ágeis
Experiência com atuação com times de projetos

**Desejáveis:**
Spring Boot
Conhecimento em Kafka, Websphere, Docker, Java 11, Swagger, Momgodb e Angular
Conhecimento em Azure ou AWS
Certificação em Azure

## Contratação

CLT

## Nossa empresa

A Avanade é a consultoria líder em soluções inovadoras de digital e nuvem, soluções de negócios e experiências que levam design aos nossos clientes, entregues por meio do poder das nossas pessoas e do ecossistema Microsoft. Fazemos tudo aquilo que você espera de uma empresa líder em inovação digital, mas é o que você não espera o que nos torna diferente.  Somos 39.000 pessoas conectadas em 25 países, construindo histórias e fazendo acontecer.  

Sabemos que o trabalho não é sua única paixão e colocamos nosso valor em você - sua carreira, seus objetivos e seu desenvolvimento, para que você possa ser a sua melhor versão.

## Como se candidatar

Por favor envie um email para anderson.amilton@harpio.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor(a) Azure Spring Cloud Senior na AVANADE ou pelo link: https://cutt.ly/ghb736g

## Labels

- 🏢 Presencial
- 👴 Sênior
- 💰 5k-10k
- 💰 10k-15k
- 💰 15k+

**Comment by nicholasess** [comment]
Essa vaga não tem relação com React, por isso será fechada.

Abs

**Comment by AndersonAmilton** [comment]
Abraço,
Anderson Amilton
*https://www.linkedin.com/company/harpiodigital
<https://www.linkedin.com/company/harpiodigital>*


Em sex., 4 de dez. de 2020 às 22:49, Nicholas Eduardo <
notifications@github.com> escreveu:

**Comment by AndersonAmilton** [comment]
Você poderia me orientar de como divulgar a vaga neste portal?

Abraço,
Anderson Amilton
*https://www.linkedin.com/company/harpiodigital
<https://www.linkedin.com/company/harpiodigital>*


Em sex., 4 de dez. de 2020 às 22:49, Nicholas Eduardo <
notifications@github.com> escreveu:
