### ISSUE TITLE
[Remoto/Montes Claros] - React Native Developer na Infinite Tecnologia

### ISSUE THREAD

**Issue by Leo-o-Nardo** [react-brasil/vagas#1093]
![Vaga dev php react 2020](https://user-images.githubusercontent.com/41972521/101393973-a3470800-38a6-11eb-9f31-b46df3a20da0.jpeg)

## Descrição da vaga

Buscamos um desenvolvedor com experiencia em React Native para integrar o nosso time de desenvolvimento - 01 Vaga

## Local

Remoto ou Escritório, Montes Claros - MG

## Benefícios

* Ambiente casual que estimula e valoriza atitudes inovadoras;
* Vale-refeição/alimentação;
* Poder atuar com tecnologias modernas;

## Requisitos
- Domínio de React Native
- Experiência em arquitetura front-end
- Sólidos conhecimentos em HTML5, CSS, JavaScript
- Design Responsivo

## Contratação
CLT

## Nossa empresa
A Infinite Tecnologia nasceu em 2013, desenvolvendo soluções para postos de combustíveis, seja ele grande ou pequeno, nossas soluções são simples e inovadoras com o objetivo de simplificar o seu uso sem perder a integridade das informações, dando ao usuário praticidade no atendimento ao cliente.

Buscamos o que o mercado tem de melhor em tecnologia com profissionais capacitados para desenvolver o que os nossos clientes precisam. Acreditamos que a inovação, para ser eficiente, tem que ser simples e fácil de usar, e nisso baseamos nosso trabalho.

## Como se candidatar
Por favor envie um email para leandro@infinitetecnologia.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels
- 🏢 Presencial ou Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by ylanbenoliel** [comment]
Enviado 👍🏻
