### ISSUE TITLE
[Osasco/SP} React Native Developer 

### ISSUE THREAD

**Issue by Recrutas** [react-brasil/vagas#1097]
Descrição da vaga:
Estamos procurando pessoas que tenha uma vasta experiência em desenvolvimento em React Native

Local: Osasco/SP

Diferenciais
•	Ambiente ágil, descontraído e inovador 

Requisitos Obrigatórios:

• Buscamos por desenvolvedores experientes em desenvolvimento mobile com React Native, bem como experiência na publicação de aplicativos nas lojas da Apple e Google.
• É imprescindível que os desenvolvedores possuam muita experiência com desenvolvimento mobile em React Native.

Contratação: PJ

Nossa empresa:

A Pasquali Solution é uma consultoria com foco em Alocação de profissionais de TI reconhecida pelo seu trabalho rápido e com excelência.
Estamos há mais de 18 anos no mercado e somos altamente especializada em Tecnologia da Informação.
Como se candidatar
Envie seu currículo: https://bit.ly/2Wu2JH0

Labels
•	Alocado
•	PJ
•	Sênior

**Comment by SaMatheus** [comment]
@Recrutas  sou aqui de Osasco também, existe alguma vaga para estágio?

**Comment by Recrutas** [comment]
@SaMatheus no momento não
