### ISSUE TITLE
[São Paulo] Desenvolvedor Back-end Senior [TOTVS - iDEXO]

### ISSUE THREAD

**Issue by TiagoCastanho** [react-brasil/vagas#11]
A TOTVS lançou recentemente o iDEXO, um instituto com uma plataforma ABERTA de inovação, com foco em dar suporte e mentoria nas mais atuais estratégias de negócio e criar parcerias com os mais inovadores players. Tudo para que startups e empresas compartilhem seu conhecimento e construam as melhores soluções em tecnologia.

Estamos buscando Desenvolvedores Back-end de nível Senior com os seguintes skills:

-Python
-NodeJS
-Paradigma Funcional
-Machine Learning (Diferencial)
 
O local de trabalho é em São Paulo-Sp (Bairro de Santana) e os principais benefícios são:

-Assistência Médica
-Assistência Odontológica
-Seguro de Vida
-Previdência Privada
-PLR
-VR,VT

Para aplicar-se a essas vagas, lançamos um desafio que você pode acessar por esse link: https://bitbucket.org/idexoteam/desafio-backend

Dúvidas: tiago.castanho@totvs.com.br

**Comment by nicholasess** [comment]
@TiagoCastanho a vaga ainda está em aberto?

**Comment by TiagoCastanho** [comment]
Ainda temos vagas nos 3 perfis!!!
Link para os desafios: 
https://bitbucket.org/account/user/idexoteam/projects/IDEXO

**Comment by nicholasess** [comment]
@TiagoCastanho agora que reparei que a vaga é sobre backend, o foco das vagas são front ends, Poderia atualizar as informações para a vaga de front end? Obrigado

**Comment by danielGalvao** [comment]
@TiagoCastanho Vamos fechar a issue por não se tratar de vaga Front-end/React/ReactNative. Caso tenha vaga nessas condições, abra outra issue por gentileza.
