### ISSUE TITLE
[São Paulo,SP] React Developer na DBSP

### ISSUE THREAD

**Issue by MauricioDBSP** [react-brasil/vagas#1106]
>Vaga remoto durante a pandemia

## Descrição da vaga

A atuação correrá em vários projetos distintos para a criação de POCs e MVPs que validem hipóteses de inovação na Klabin, líder global em seu segmento. É um projeto com desafios importantes, em um time de alta performance, com grandes capacidades de aprendizado e desenvolvimento.

## Local

Remoto 

## Benefícios

Vale Refeição;
Vale Transporte;
Assistência médica e odontológica;
Dresscode: seja você!

## Requisitos

**Obrigatórios:**
Experiência anterior com Desenvolvimento em Node/React;
Conhecimento com Flutter;

**Diferenciais:**

Cultura Maker será considera um diferencial.

## Responsabilidades e Atribuições

Desenvolvimento em projetos de Inovação envolvendo Front- end e Back-end;
Pesquisar novas tecnologias, ferramentas, processos;
Contribuir para o desenvolvimento, correções ou melhorias em componentes de software;

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A DBSP é uma empresa de tecnologia, pensada, desenhada e formatada para atuar como parceira em digital.
Temos como serviços: Business Agility, Produtos Digitais, Plataformas e IT Services.

Por aqui temos um ambiente de muita interação com pessoas altamente qualificadas que se identificam com a busca pelo melhor resultado, pela melhor entrega, pelo crescimento contínuo, sem limite.

Nossa cultura é totalmente focada em pessoas!

De onde viemos: A DBSP é a DBServer em São Paulo, uma das maiores e melhores empresas de projetos e softwares no Brasil que atua há mais de 27 anos auxiliando grande organizações.
Para saber mais acesse: www.dpsp.pro

## Como se candidatar

Por favor envie um email para beapeer@dbsp.pro com seu CV anexado - enviar no assunto: Vaga React

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- ⚖️ PJ

**Comment by LucasNovaes2016** [comment]
Olá. Enviei meu currículo por email mas recebi a seguinte mensagem "The group beapeer only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.". Preciso de alguma autorização para enviar? (meu email é lucasmsn200@gmail.com)

**Comment by MauricioDBSP** [comment]
> Olá. Enviei meu currículo por email mas recebi a seguinte mensagem "The group beapeer only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.". Preciso de alguma autorização para enviar? (meu email é [lucasmsn200@gmail.com](mailto:lucasmsn200@gmail.com))

Oi, Lucas! Tudo bem?
Te mandei um e-mail :)

**Comment by agnezi** [comment]
> > Olá. Enviei meu currículo por email mas recebi a seguinte mensagem "The group beapeer only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.". Preciso de alguma autorização para enviar? (meu email é [lucasmsn200@gmail.com](mailto:lucasmsn200@gmail.com))
> 
> Oi, Lucas! Tudo bem?
> Te mandei um e-mail :)

> Olá. Enviei meu currículo por email mas recebi a seguinte mensagem "The group beapeer only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.". Preciso de alguma autorização para enviar? (meu email é [lucasmsn200@gmail.com](mailto:lucasmsn200@gmail.com))

Tive o mesmo problema que o colega acima ( jonas.agnezi@gmail.com)

**Comment by LucasNovaes2016** [comment]
> > Olá. Enviei meu currículo por email mas recebi a seguinte mensagem "The group beapeer only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.". Preciso de alguma autorização para enviar? (meu email é [lucasmsn200@gmail.com](mailto:lucasmsn200@gmail.com))
> 
> Oi, Lucas! Tudo bem?
> Te mandei um e-mail :)

Valeu. Mandei pra lá.
