### ISSUE TITLE
[Remoto] [Goiânia/GO] Full-Stack Developer

### ISSUE THREAD

**Issue by chgyn** [react-brasil/vagas#1128]
# Descrição da vaga

O candidato deverá estar capacitado a:
 - Executar projetos de desenvolvimento envolvendo Framework Laravel PHP
 - Ser capaz de executar projetos de desenvolvimento de interface usando VueJS ou ReactJS
 - Implementar sistema web / API Rest utilizando o framework Laravel PHP

#### Conhecimentos necessários: 

 - PHP
 - Laravel
 - MySQL / PostgreSQL
 - HTML5
 - CSS
 - Javascript
 - VueJS ou ReactJS 
 - API/Rest

#### Diferenciais:
 - Experiência com desenvolvimento utilizando Laravel PHP, VueJS
 - Laravel PHP
 - React Native
 - SCRUM

Experiência com desenvolvimento front-end utilizando como base:
 - Laravel PHP
 - ReactJS
 - VueJS
 - Conhecer e saber como lidar em times que executam SCRUM

## Local

Sede física da empresa, Alpha Coworking (Av. T-1, 2266 - St. Bueno, Goiânia) - (híbrido presencial / remoto)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento front-end 

**Desejáveis:**
- conhecimentos em Laravel PHP
- conhecimentos em API Rest
- Scrum

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para contato@wi-id.com com seu CV anexado - enviar no assunto: Vaga Front-End

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Pleno
- Sênior

**Comment by viniciusrma** [comment]
Perdi o (pouco) tempo livre que possui na semana do Natal desenvolvendo a solução-desafio e a empresa sequer forneceu feedback.
