### ISSUE TITLE
VAGA PARA PESSOA DESENVOLVEDORA - PLENO EM REACT WEB

### ISSUE THREAD

**Issue by haoni** [react-brasil/vagas#1134]
## Vaga para pessoa desenvolvedora - Pleno em React!  :rocket:

- Vaga full Remoto ou Escritório, Mato Grosso - Cuiabá

## Tá, mas o que eu vou fazer:interrobang:

- Criar telas bonitinhas, componentes, fazer versionamento no git, desenvolver testes e afins!

## E o que eu preciso saber? :books:
- React Web, JS, Redux, Jest, Git e lógica.
- Se você já conhece a metodologia ágil, será um diferencial (;

## E onde me inscrevo? :pencil2:
Em: [carreiras.nuvem.net](carreiras.nuvem.net)

## Mais sobre a empresa em: [nuvem.net](nuvem.net)

Vem fazer parte desse time! :blue_heart:

**Comment by souzasmatheus** [comment]
Aceita part-time, @haoni? :)

**Comment by israelcena** [comment]
Gostei da descrição de o que eu vou fazer

**Comment by haoni** [comment]
> Aceita part-time, @haoni? :)

Não mano, somente para programa de estágio.

**Comment by haoni** [comment]
> Gostei da descrição da vaga

Bem diferente, a cara da Nuvem!
