### ISSUE TITLE
[Remoto] Front-end Developer na D3.do

### ISSUE THREAD

**Issue by diogomoretti** [react-brasil/vagas#114]
Nós estamos buscando um(a) **Front-end Developer Júnior** que combine Design + Programação. Nós acreditamos no auto-gerenciamento, na mentalidade empreendedora e paixão para desenvolver **produtos digitais incríveis** =]

## O que esperamos de você?
* Curioso pelo universo digital
* Pró-ativo
* Alguém que se compromete com qualidade e com prazos
* Alguém que gosta de trabalhar em equipe
* Alguém que gosta do que faz
* Alguém bacana :)

## Requisitos
* Experiência com Front-end
* Entendimento básico de todo processo web (design, desenvolvimento e deploy)
* Git / Git Flow
* HTML / CSS
* JavaScript
* Frameworks/Libs JS (React / Vuejs / Angular)

## Local
Remoto

## Benefícios
* Plano de Saúde Bradesco
* Auxílio Academia
* Horário Flexível

## Sobre a D3
A D3 está há 16 anos no mercado contruindo produtos digitais para grandes empresas como Twitter, Fiat e Google. Acreditamos que tecnologia e design podem criar produtos digitais de uma forma incrível ;)

## Contratação
CLT ou PJ

## Como se candidatar
Topa o desafio? https://vem.d3.do 

## Labels
- alocação/Remoto
- experiência/Júnior
- regime/CLT
- regime/PJ

**Comment by adeonir** [comment]
Ae @diogomoretti eu preenchi esse form há um tempinho e não tive resposta.

**Comment by thiagolavor** [comment]
Ai pessoal da D3.do tudo bem?
A vaga esta aberto ainda?

**Comment by ribeiroevandro** [comment]
Pois é, também apliquei para essa e outras vagas, em nenhuma tive retorno... :(

**Comment by diogomoretti** [comment]
Pessoal, a vaga está aberta ainda... a medida que abrimos mais vagas estamos chamando. Infelizmente não conseguiremos dar retorno para todos... sou muito ativo aqui no Github, e quando a vaga fechar, eu fecho a issue aqui, fiquem tranquilos.

**Comment by thiagolavor** [comment]
Qual é o nível de experiência que é exigido para a vaga ? 
Sou desenvolvedor react junior.

**Comment by diogomoretti** [comment]
É mais pra Junior/Pleno mesmo @thiagolavor  =]
