### ISSUE TITLE
Programador Reactjs 🇺🇸

### ISSUE THREAD

**Issue by henrique9277** [react-brasil/vagas#1148]
## Descrição da vaga

5 Projetos Reactjs

## Local

REMOTO

## Benefícios

- PAGAMENTO POR HORA EM DÓLAR 

## Requisitos

**Obrigatórios:**
- 2 ano de experiência em reactjs firebase 

**Desejáveis:**
- conhecimentos em GraphQL/ NodeJs
- Fullstack

## Contratação

FreeLancer

## Como se candidatar
978-984-2340 chamar no WhatsApp 
enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- ⚖️ Estágio
- ⚖️ Freela
- 💰 1k-3k
- 💰 3k-5k

**Comment by lucianodiisouza** [comment]
Esse número não apareceu como contato no WhatsApp, está completo?

**Comment by castylho** [comment]
vou supor que tem que botar o zip code?
dai ficaria (+1) 978-984-2340 🤔
