### ISSUE TITLE
[Remoto] Front-end Developer na Assertive Yield

### ISSUE THREAD

**Issue by lucasavila00** [react-brasil/vagas#1152]
## Descrição da vaga

Estamos à procura de alguém para ajudar no desenvolvimento da plataforma que é usada para visualização de dados. A plataforma já está online mas estamos adicionando novas funcionalidades todos dias, à medida que os clientes as desejam.

## Local

Remoto

## Benefícios

- Monte seu próprio horário

#### Diferenciais

- Monte seu próprio horário

## Requisitos

**Obrigatórios:**
- experiência com Node
- experiência com react

**Desejáveis:**
- conhecimentos em SQL
- conhecimento em MongoDB
- conhecimento em Meteor

**Diferenciais:**
- projetos opensource

## Contratação

- Contrato assinado na Europa.

## Nossa empresa

A [Assertive Yield](https://www.assertiveyield.com/) trabalha com analytics de ads. Todos os funcionários trabalham remotamente. A empresa é da Holanda.

## Como se candidatar

Por favor envie um email para lucaxx@gmail.com com seu CV anexado - enviar no assunto: Vaga AY. O contato comigo pode ser em português. Depois eu vou encaminhar seu CV para o resto da equipe (neste ponto o CV precisa estar em inglês)

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- ⚖️ Outros
- 💰 5k-10k

**Comment by JoaquimAlvesFN** [comment]
Precisa falar inglês pra essa vaga?

**Comment by lucasavila00** [comment]
@JoaquimAlvesFN Sim, a empresa opera em inglês. Me desculpe por não deixar claro no post.
