### ISSUE TITLE
[Remoto] React Native Developer na Visionnaire Tecnologia

### ISSUE THREAD

**Issue by Vilcilaine** [react-brasil/vagas#1171]
## Descrição da vaga

Buscamos profissional com experiência em desenvolvimento de aplicativos móveis com React Native.

O projeto será para um sistema já existente, com Back-end desenvolvido em PHP e Magento, e que terá um novo Aplicativo Móvel sendo desenvolvido em React Native, onde a comunicação entre o Front-end (App) e o Back-end será feita via APIs. É importante que o candidato tenha experiência em já ter desenvolvido pelo menos um Aplicativo Móvel com React, bem como experiência de UI/UX (User Interface / User Experience) de Aplicativos Móveis Híbridos (para iOS e Android).

Requisitos Fundamentais:

Forte conhecimento de React.js e principalmente React Native;
Experiência de ter desenvolvido pelo menos um Aplicativo Móvel completo com React Native;
Experiência de fazer a comunicação do Front-end (App) com o Back-end através de APIs;
Conhecimento de boas práticas de UI/UX (User Interface / User Experience).

Requisito Desejável:
Conhecimento de desenvolvimento Back-end.

## Contratação

PJ a combinar

## Nossa empresa
A Visionnaire é uma Fábrica de Software de Curitiba com 24 anos de experiência e inovação. O Vagas Visionnaire é uma área dedicada aos talentos da nossa empresa e compartilhamento de oportunidades de emprego na área de TI.

Nossa demanda por profissionais produtivos, dinâmicos e criativos e alta. Se você esta por dentro das diversas tecnologias e metodologias atuais do mercado, venha fazer parte do time de Talentos da Visionnaire!

## Como se candidatar

Por favor, cadastre através do link https://visionnaire.abler.com.br/vagas/desenvolvedor-react-native-pleno-ou-senior-923161

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by anabeatrizzz** [comment]
No link diz que a vaga é para pleno ou sênior, então não deveria ter a label júnior.

**Comment by Vilcilaine** [comment]
> No link diz que a vaga é para pleno ou sênior, então não deveria ter a label júnior.

Olá Ana Beatriz, tudo bem?
Deixei no Label júnior pq estamos avaliando perfis nesse nível tbm, ok? Então pode se candidatar sim ;)
Obrigada!
