### ISSUE TITLE
[São Paulo / Remoto ] React Native na Treeze Solution

### ISSUE THREAD

**Issue by felipepimentel** [react-brasil/vagas#118]
## Descrição da vaga
Buscamos uma pessoa com experiência em React Native para um Freela de 3 meses.

## Local
Remoto ou Escritório, São Paulo - Santo Amaro (Bem próximo à estação Santo Amaro).

## Requisitos
**Obrigatórios:**
- Javascript (ES6)
- HTML e CSS
- Consumo de APIs
- GIT
- Experiências no desenvolvimento de aplicativos MOBILE (IOS e Android)

**Diferenciais:**
- Conhecimento em testes unitários e automatizados

## Contratação
Freela a combinar
Projeto de 3 meses

## Nossa empresa

Somos a Treeze Solution. Empresa especializada no desenvolvimento e automação de softwares para o Varejo brasileiro. Atualmente temos mais de 200 clientes, que procuramos atender da melhor maneira, Criando e entregando tecnologia de ponta de modo a coloca-los à frente da concorrência.

## Como se candidatar

Por favor envie um email para felipe.pimentel@treezebit.com com seu CV anexado - enviar no assunto: Vaga React Native.

## Labels
- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/Freela

**Comment by ribeiroevandro** [comment]
Enviado
