### ISSUE TITLE
[Porto Alegre - RS] Isobar contrata Lead Front End Developer (React) 

### ISSUE THREAD

**Issue by edurmaciel** [react-brasil/vagas#12]
Isobar Porto Alegre contrata **Lead Front End (React)** para um projeto internacional entre a Isobar US e Isobar Brasil. Link para a vaga:  https://iwsbrazil.workable.com/j/A67C6A0AA0

Exemplos de projetos da Isobar: http://bit.ly/2kyGdvl  

Para conhecer um pouquinho da Isobar Porto Alegre: https://www.facebook.com/iwsbrazilpoa/

**Comment by nicholasess** [comment]
@edurmaciel a vaga ainda está em aberto? Se sim, ela é presencial ou Remoto?

**Comment by danielGalvao** [comment]
@edurmaciel Vamos fechar a issue, se a vaga ainda estiver aberta reabrimos, ou você cria uma nova issue com novas informações.
