### ISSUE TITLE
[Curitiba] React Native Developer na Onde Pouso

### ISSUE THREAD

**Issue by RogerioAranibar** [react-brasil/vagas#1212]
Projeto pioneiro com potencial enorme de crescimento, App em fase de pre lançamento. Oportunidade para profissional com energia, pro atividade e foco no cliente. Full time ou part time. Fará manutenção, solução de bugs e melhorias para atender ás necessidades dos cientes.

## Local

- Remoto 

## Benefícios

- a combinar

#### Diferenciais

- fazer parte de um projeto que irá transformar a vida de muitos profissionais

## Requisitos

**Obrigatórios:**
- 2 anos experiência com desenvolvimento de app

## Contratação

- a combinar

## Nossa empresa

Startup com projeto inovador

## Como se candidatar

Por favor envie um email para contato@ondepouso.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- ⚖️ A-Combinar
- 💰 a combinar

**Comment by victorbiasibetti** [comment]
ainda está aberta esta vaga?

**Comment by RogerioAranibar** [comment]
Boa tarde, Victor.

 

Já contratamos o Dev, mas se você tem interesse, nos envie seu CV para o caso de expansão da equipe..

 

Obrigada pelo contato.

 

Maria Rosangela

Diretora Administrativa

Onde Pouso

 

De: Victor Biasibetti ***@***.*** 
Enviada em: segunda-feira, 15 de março de 2021 16:15
Para: react-brasil/vagas ***@***.***>
Cc: RogerioAranibar ***@***.***>; Author ***@***.***>
Assunto: Re: [react-brasil/vagas] [Curitiba] React Native Developer na Onde Pouso (#1212)

 

ainda está aberta esta vaga?
