### ISSUE TITLE
[REMOTO] Front-End Developer Junior/Pleno na Conquest One

### ISSUE THREAD

**Issue by lucasherodoto** [react-brasil/vagas#1225]
## Descrição da vaga

Projeto com Desenvolvimento Front-end.

## Local

Remoto

## Benefícios

Plano de Saúde/Odontológico Sulamérica
Seguro de Vida
VR de R$ 550/mês
VA de R$ 100/mês

## Requisitos

Uso de Angular 2+ e outros frameworks JS, como Vue.JS e React Native. 

**Obrigatórios:**

Mínimo de 2 anos de experiência 

**Desejáveis:**

Familiaridade com TDD.

## Contratação

CLT com benefícios

## Nossa empresa

 Conquest One é uma empresa especializada em Staffing de TI, sendo eleita 9 vezes como uma GPTW e agora está em busca de uma pessoa apaixonada por tecnologia e inovação para uma oportunidade incrível!

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga Front-End

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by HeitorRamos132** [comment]
Acredito que o email de contato está incorreto, alguém poderia confirmar?

**Comment by flakesrc** [comment]
@HeitorRamos132 tá claramente errado, acho que não deve ter editado. E o pior é que postou ontem e ainda não corrigiu.
