### ISSUE TITLE
Suécia - React Dev com 1 a 3 anos de Experiência

### ISSUE THREAD

**Issue by flavioislima** [react-brasil/vagas#1228]
## Dev Javascript + React

A empresa que trabalho está contratando Devs React **com entre 1 e 3 anos de experiência com React,** mid-senior level + Inglês.
Salário em Euro entre **4300 a 4800 euros** antes da taxas (negociável ainda)
Os requisitos não são altos, basicamente saber de React, Javascript atual e se souber Node é um plus.

A empresa tem produto no Brasil mas é sueca, eu moro na Suécia atualmente, mas devido a COVID o trabalho pode ser feito no Brasil de forma remota, mas se quiser se candidatar saiba que é possível que a empresa exija trabalho presencial no futuro. Mas ela cuida do visto e da mudança tanto do candidato quanto da famíila.

A vaga é pra trabalhar no meu time, são duas vagas. Meu perfil:
https://github.com/flavioislima
https://www.linkedin.com/in/flavioflima-dev/

## Local

Estolcomo Suécia. Início remoto mas com possibilidade de mudança no futuro.
A empresa arca com o visto do funcionários + familiares e a viagem + 2 meses de aluguel no apartamento da empresa.

## Benefícios

- Plano de saúde
- Seguro de vida
- 300 euros anuais pra gastos com Saúde e bem estar (academia, massagem, etc)
- 150 euros para gastos com equipamentos como teclados, fones de ouvido, mouse, etc.
- 2.5% do salário depositado em fundos de pensão sem ônus para o funcionário. Esse valor poder ser usado para comprar ações de diversas empresas suecas e de fora também.

#### Diferenciais

- 30 dias úteis de férias flexíveis (pode tirar a quantidade que quiser quando quiser)
- Horário flexível
- Macbook Pro 2019 i7 + 1TB + 16GB
- Iphone ou Android
- Plano de telefonia ilimitado

## Requisitos

**Obrigatórios:**
- 1 a 3 anos de experiência com React.
- conhecimento de Javascript moderno
- Inglês avançado (não precisa ser fluente basta saber entender legal e se expressar bem)
- Disponibilidade pra mudar para a Suécia no futuro

**Desejáveis:**
- conhecimento de NodeJS
- conhecimento de Typescript

**Diferenciais:**
- conhecimentos em GraphQL
- projetos opensource
- conhecimento de CI/CD
- Jenkins, docker, GCP, etc.

## Contratação

Contrato de trabalho. 6 meses probatório e depois fica definitivo.

## Nossa empresa

Empresa líder no ramo de casinos online na europa com presença em mais de 20 países e com mais de 900 funcionarios no mundo.
O produto é esse: www.leovegas.com

## Como se candidatar

Entre em contato via telegram com `flavioislima`. Envie Linkedin, Github, CV em inglês + Email
Descrição da Vaga: https://smrtr.io/4vG5V

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ Outros
- 💰 15k+

**Comment by marcusviniciusf** [comment]
Olá, tenho interesse. Porém não tenho telegram.

**Comment by flavioislima** [comment]
> Olá, tenho interesse. Porém não tenho telegram.

Puts, o Telegram é bom que aí posso te dar mais detalhes sobre a empresa e sobre o trabalho aqui. 

Faz aí que é grátis :D

**Comment by aribeirorj** [comment]
Oi Flavio te mandei uma msg no Telegram, abs

**Comment by andreyBento** [comment]
Bom dia, enviei mensagem no telegram, fico no aguardo.

Em qua., 3 de fev. de 2021 às 14:11, Flavio F Lima <notifications@github.com>
escreveu:

**Comment by andreyBento** [comment]
Bom dia Flávio, mandei mensagem para você no telegram, fico no aguardo.

Em qua., 3 de fev. de 2021 às 14:11, Flavio F Lima <notifications@github.com>
escreveu:

**Comment by flavioislima** [comment]
Fechando a thread pois já tive muitas aplicações,
