### ISSUE TITLE
[Remoto] React Native developer na Seabench Ltd, Londres 

### ISSUE THREAD

**Issue by chrisid** [react-brasil/vagas#1233]
## Descrição da vaga

Vaga para Freelancer para trabalhar em 2 Apps de Startups. 
100% remoto e horário de trabalho flexível.

## Local

100% Remoto
100% on Slack

## Benefícios
- Pagamento em Euros aonde for melhor para vc, Paypal, Conta Bancaria...
- Liberdade de horario, estamos interesados na entrega e nao no 9-5

## Requisitos
- 2-3 anos de experiência com desenvolvimento React Nativo
- Typescript
- Mobx
- Functional components
- Nao utilizar Expo

**Desejáveis:**
- Ingles intermediario
- Conhecimento de Native Modules é bonus
- Vontade de aprender e saber fazer as perguntas certas quando precisa de ajuda são bonus extra

## Contratação
- Freelancer com duração de aproximadamente 2 - 3 meses
- Contrato simples e NDA

## Como se candidatar
Por favor envie um email para chris@seabench.com ou chris@chrisid.com - enviar no assunto: Vaga React Native
No email, informe:
- Disponibilidade atual?
- Experiencia com Typescript e Mobx?
- Ambiente de dev que vc utiliza: Mac ou Windows?

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Freela

**Comment by raivieiraadriano92** [comment]
Oi Chris, tudo bem?
Enviei um e-mail para você. Valeu abraço...
