### ISSUE TITLE
[Remoto] Desenvolvedores Full-Time React Web/Native na RockApps

### ISSUE THREAD

**Issue by erickne** [react-brasil/vagas#1272]
## Descrição da vaga

Buscamos novos desenvolvedores de nível **JÚNIOR**,  **PLENO** e **SÊNIOR** para compor o time tecnológico. As vagas serão para React Native e ReactJS. A experiência em ambas tecnologias será um diferencial.

A principais atividades serão:
- Desenvolvimento de novas interfaces web em ReactJS;
- Desenvolvimento de aplicativos híbridos em React Native;
- Desenvolvimento e execução de testes.

## Local

- 100% Remoto
- Horário comercial

## Requisitos

**Obrigatórios:**
- Domínio em ReactJS e/ou React Native
- Domínio em React State Management (Redux)
- Integração de RESTFull APIs
- Boas noções de layout 
- Ótima comunicação verbal e escrita
- Bons conhecimentos em criação e execução de teste em **ReactJS** e/ou **React Native**

**Desejáveis:**
- Conhecimento em CI/CD (Jenkins, Fastlane)
- Conhecimento em gestão de projetos ágeis
- Conhecimento na biblioteca Expo

**Diferenciais:**
- Experiência em linguagens nativas
- Experiência em utilização do Figma

## Contratação

PJ a combinar
 ** Remuneração variável a cada 6 meses conforme performance **

## Nossa empresa

Desenvolvimento ágil e profissional de produtos e ideias, utilizando modernas tecnologias através de um modelo de custos acessível e flexível. A atuação de nossa empresa busca personalizar projetos e aplicações integrar soluções aos sistemas pré-existentes de nossos clientes. Sempre atualizados com as novas tecnologias de mercado, trazemos conosco aplicações inovadoras que certamente atenderão sua necessidade. Hoje em dia, a RK se consolidou no mercado, possuindo mais de 50 clientes e mais de 60 softwares e aplicativos criados. Realizações que nos mantém em andamento.
Conheça mais sobre nossa empresa em https://rockapps.com.br.

## Como se candidatar

Realize o preenchimento do formulário https://link.rockapps.com.br/vaga-dev-react.

## Labels

- 🏢 Remoto
- 👶 Estágio
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by thiagobutignon** [comment]
Boa tarde Erick,

tudo bem?

Eu gostaria de me candidatar para a vaga, mas confesso que o teste exigido pela empresa é extremamente extenso para avaliar os conhecimentos dos candidatos. Posso encaminhar um teste que realizei recentemente? Qual a pretensão salarial para desenvolvedores sênior?

Obrigado

**Comment by erickne** [comment]
> Boa tarde Erick,
> 
> tudo bem?
> 
> Eu gostaria de me candidatar para a vaga, mas confesso que o teste exigido pela empresa é extremamente extenso para avaliar os conhecimentos dos candidatos. Posso encaminhar um teste que realizei recentemente? Qual a pretensão salarial para desenvolvedores sênior?
> 
> Obrigado

Olá @thiagobutignon .

Pode sim. Preencha o formulário e vincule o repositório.

Abraços!

**Comment by filippobarcellos** [comment]
Olá Erick. Mandei o email com o desafio realizado tem uns 8 dias. Gostaria de confirmar se receberam ou não.
Obrigado
