### ISSUE TITLE
[Remoto] Fullstack React Developer na Semantix

### ISSUE THREAD

**Issue by saitodisse** [react-brasil/vagas#1280]
Fala pessoal, estamos aqui na [Semantix](https://semantix.com.br/) com vagas para Fullstack React. A equipe está bem pequena, só tem 3 pessoas por enquanto, e os projetos estão no início. Ótima hora para começar com a gente. Estamos buscando principalmente programadoras mulheres.

## Descrição da vaga

Atuar no desenvolvimento de produtos voltados para uma plataforma de atendimento ao cliente no modelo chat utilizando bots e inteligência artificial. Os sistemas estão sendo desenvolvidos em node, typescript e react. Estamos criando a plataforma do zero com as melhores e mais avançadas tecnologias do momento. O trabalho é full remoto.

## Local

Remoto, São Paulo

## Benefícios

- Vale transporte
- Vale refeição
- Vale alimentação
- Seguro saúde
- Plano odontológico
- Auxílio Creche
- Seguro de vida
- PLR
- Academy – Área focada no desenvolvimento de soft skills e hard skills afinal temos a preocupação que você continue se desenvolvendo.
- Curso de inglês e espanhol (in company) - Após 03 meses de empresa.
- Além disso, nossa sede possui um ambiente descontraído com alguns diferenciais como: Mesa de pebolim, videogames e copa com comes e bebes disponíveis. 

## Requisitos

_**Importante**_: nos envie seu link do seu github. Aproveite para colocar alguns projetos publicados em sites como github pages, netlify ou vercel (seu github é o melhor currículo)

**Obrigatórios:**

- pelo menos 2 anos de experiência com desenvolvimento web
- gostar muito de programar
- comprovada experiência com React
- CSS (sites responsivos)
- javascript: domínio em promises, async/await, map/reduce, import/export, destructuring e outras ES6 features
- Inglês Básico
- Git
- esteja disposto a fazer programação pareada

**Desejáveis:**
- Typescript ou alguma linguagem orientada a objetos tipada, como C#, Java, etc. Isso facilita bastante a adaptação com 
- TDD
- SQL (Postgresql)
- Conhecimentos de Design/UX
- Tailwind CSS ou CSS/SCSS
- Next.js (JAMStack)
- Hasura ou Prisma 2 (graphql)
- Conhecimentos em Devops é um bom diferencial
- Inglês Intermediário (capaz de assistir uma palestra em inglês sem legendas)

**Diferenciais:**
- usamos Next.js, Hasura, GraphQL, Vercel, Github. Só coisa fina.

## Contratação

CLT

## Nossa empresa

Com o propósito de impactar bilhões de vidas com dados, a Semantix foi fundada em 2010 no Brasil, e hoje, presente em toda a América, destaca-se por suas soluções no modelo Data Driven. Somos referência na oferta de tecnologia em Big Data, Analytics, Inteligência Artificial, e desenvolvemos soluções inovadoras e disruptivas para todos os setores da indústria e serviços.
Nos últimos anos fomos eleitos uma das 25 melhores provedoras de soluções em Inteligência Artificial em todo o mundo, e não pararemos aqui! Topa fazer parte deste time?

## Como se candidatar

Por favor envie um email para julio.saito@semantix.com.br e bruno.maia@semantix.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT

**Comment by rafaelfgyn** [comment]
Tem vaga pra Júnior não???

**Comment by saitodisse** [comment]
Oi @rafaelfgyn. Obrigado pela pergunta. 

Por enquanto estamos dando prioridade para plenos (pela demanda) + mulheres (pela diversidade). 

Estamos com uma equipe muito reduzida. Quem sabe mais pra frene a gente consiga ter mais estrutura pra pegar pessoal que está começando.

**Comment by LucieneSousa** [comment]
Tem vaga para estagiária?

**Comment by saitodisse** [comment]
> Tem vaga para estagiária?

Olá Luciene!
Obrigado pela pergunta. No momento estamos buscando pessoas devs com alguma experiencia prévia.
Possivelmente poderemos abrir vagas pra estágio no futuro mas agora não temos essas vagas.

**Comment by phenriquesantos** [comment]
Experiência comprovada poderia ser projetos acadêmicos ?

**Comment by saitodisse** [comment]
Poderia sim...
