### ISSUE TITLE
[Florianópolis - SC] Desenvolvedor Front-End Sênior (React.js) - [Conpass]

### ISSUE THREAD

**Issue by osnysantos** [react-brasil/vagas#13]
**O que buscamos**
- Alto conhecimento em HTML5 e CSS3
- Forte proficiência em JavaScript, incluindo manipulação de DOM
- Compreensão completa de React.js e seus princípios fundamentais (e Redux também)
- Familiaridade com as novas especificações do EcmaScript
- Familiaridade com APIs RESTful
- Experiência com ferramentas comuns de desenvolvimento de front-end como Babel, Webpack, NPM, etc.
- Capacidade de entender os requisitos de negócios e traduzi-los em requisitos técnicos
- Habilidade para benchmarking e otimizações
- Familiaridade com as ferramentas de controle de código (Git)
- Familiaridade com testes de navegador e depuração
- Familiaridade com o Agile

**Desejável**
- Conhecimento em UI e UX
- Experiência com Node / Mongo

Para mais informações: http://trabalheconosco.conpass.io/o/desenvolvedor-frontend-senior-reactjs

**Contratação**
CLT

**Como aplicar**
http://trabalheconosco.conpass.io/o/desenvolvedor-frontend-senior-reactjs

**Comment by nicholasess** [comment]
@osnysantos a vaga ainda está em aberto?

**Comment by osnysantos** [comment]
@nicholasess Sim, ainda está em aberto.

**Comment by danielGalvao** [comment]
@osnysantos A vaga está aberta ainda? Senão fecharemos a issue.
