### ISSUE TITLE
[Remoto] Desenvolvedor Pleno ReactJS na Inventae

### ISSUE THREAD

**Issue by juanhafliger** [react-brasil/vagas#1301]
## Requisitos
🎯  React.JS (2+ anos de experiência)
🎯  Javascript
🎯  Scrum

## Local
• Remoto

## Contratação
• PJ a combinar

## Como se candidatar
Email: juan@inventae.com.br, com o título: ReactJS Pleno
WhatsApp: https://shorturl.at/bgvGH

## Nossa empresa
A Inventae é uma empresa focada em desenvolvimento de projetos web e mobile com complexidade média e alta e atua há mais de 10 anos no mercado.

## Labels
Labels
• 🏢  Remoto
• 👨  Pleno
• ⚖️  PJ
• 💰  5k-10k

**Comment by jhefflg** [comment]
Aceita part-time?

**Comment by juanhafliger** [comment]
> a part-time?

Sim, desde que vc consiga cumprir as tarefas do dia.
