### ISSUE TITLE
[Campo Grande MS] Desenvolvedor FullStack React / Native / NodeJS

### ISSUE THREAD

**Issue by EmersonGarrido** [react-brasil/vagas#1324]
## Descrição da vaga
Estamos buscando profissionais para trabalhar local, que tenha experiencia ou queira aprimorar seus conhecimentos.

## Local
Escritorio no centro de Campo Grande MS

## Benefícios
- A Negociar

#### Diferenciais
- Massagista
- Area de Lazer
- Cursos e Plano de Carreira

## Requisitos
- Conhecimentos em React Native / React JS / Node Js

**Diferenciais:**
- projetos opensource
- conhecimento em php
- conhecimento jquery
- conhecimento em Curl

## Contratação
PJ a combinar

## Nossa empresa
Somos lideres em sorteios no instagram e plataformas de gestão/automação de marketing

## Como se candidatar
Por favor envie um email para job@dlweb.co com seu CV anexado - enviar no assunto: Vaga FullStack

## Labels

- 🏢 Presencial
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k
- 💰 10k-15k
- 💰 15k+

**Comment by alysson3dev** [comment]
Aceita propostas de outros estados?

**Comment by EmersonGarrido** [comment]
@alysson3dev  Aceitamos sim, estamos analisando a viabilidade de ser de outro estado ( inicialmente ) mas queremos futuramente local.

Pense na possibilidade de viajar/mudar a trabalhar!

**Comment by EmersonGarrido** [comment]
Re-Open
