### ISSUE TITLE
[Remote] Part-time | Desenvolvedor React Native

### ISSUE THREAD

**Issue by felipearaujoFA** [react-brasil/vagas#1352]
Venha fazer diferença com a Yogg

A Yogg é o primeiro buscador e comparador de Delivery da América Latina (estilo uma Skyscanner do delivery). Somos uma startup em estágio inicial e estamos buscando desenvolvedores com características empreendedoras.

Bora impactar o setor de delivery com a gente?!

O desenvolvedor selecionado irá trabalhar em horários flexíveis.

## Descrição da vaga
Projeto desenvolvido em React Native, buscamos não somente desenvolvedores, buscamos sonhadores que desejam causar um impacto significativo na indústria de Food Delivery. Procuramos pessoas dispostas a correr riscos visando o longo prazo. Você se encaixa? Nos mande um e-mail.

**O que procuramos em todos os candidatos​**

Quer começar sua própria empresa de tecnologia um dia (ou já o fez!);
Sente a necessidade de estar no controle de seu próprio sucesso ou fracasso;
Tem ideias únicas que são contrárias e corretas e tentou torná-las realidade;
Sabe que podem realizar qualquer coisa, com tempo suficiente, e tem feito isso;
Em outras palavras, buscamos determinação (não educação, anos de experiência, referências, inteligência ou qualquer outra coisa que uma grande empresa procuraria).

## Local

Remoto

## Benefícios

Horário flexível
Modelo de Stock option

## Requisitos

**Obrigatórios:**
Forte conhecimento em React Native e espírito empreendedor
Tenha ideias inovadoras para a Yogg

**Desejáveis:**
Conhecimento em Firebase

**Diferenciais:**
  Python
## Contratação

a combinar

## Nossa empresa
A Yogg é o Primeiro motor de busca e comparação de delivery da América Latina (um tipo de Skyscanner do delivery). Somos uma startup em estágio inicial em um mercado muito promissor.

www.yogg.com.br

## Como se candidatar
Por favor envie um email para Felipe@yogg.com.br com seu CV anexado - enviar no assunto: Vaga React Native

Setor
Serviços da informação
Tipo de emprego

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar

**Comment by MarcosNSouza87** [comment]
Essa oportunidade de vaga ja foi encerrada?
