### ISSUE TITLE
[Remoto] React + Python Developer na Finetune Learning (US)

### ISSUE THREAD

**Issue by tyagow** [react-brasil/vagas#1359]
## Descrição da vaga

Finetune procura desenvolvedores Python com habilidades em React para trabalhar em um projeto inovador usando OpenAI.
Você sera gerenciado por um Brasileiro portando não precisa ser 100% proficiente em Inglês.
Inicialmente projeto com duração de 6-8 meses com possibilidade de extensão de contrato para tempo indeterminado. (Melhorar a comunicação em Inglês fundamental para essa extensão)
Se você é um desenvolvedor com vontade de crescer rápido, evoluir seu inglês e trabalhar com um tecnologias de ponta, envie seu currículo para tiago@finetunelearning.com e vamos conversar! 

## Local

Remoto

## Benefícios

- Pagamento em Dolar.

#### Diferenciais

- Oportunidade de contrato permanente
- Oportunidade de desenvolver seu Ingles
- Trabalhar com Tecnologias de ponta (OpenAI / GPT-3)

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com desenvolvimento React
- 1 ano de experiência com desenvolvimento Python
- Habilidade de escrever código em inglês
- Ser capaz de ler tickets em Inglês

**Desejáveis:**
- conhecimentos em GraphQL
- Hasura

**Diferenciais:**
- Ingles Fluente

## Contratação

PJ

## Nossa empresa

[https://www.finetunelearning.com/custom.html](https://www.finetunelearning.com/custom.html)

## Como se candidatar

Por favor envie um email para tiago@finetunelearning.com com seu CV anexado - enviar no assunto: Vaga React + Python

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 A combinar

**Comment by decaf-programmer** [comment]
Dear Tiago.
I am very thankful for this opportunity.

I hope to get hired by you.
Can I talk with you now?
