### ISSUE TITLE
[REMOTO] - Product Owner (Dev Manager) na Foton

### ISSUE THREAD

**Issue by Felipepirova** [react-brasil/vagas#1368]
VAGA para Product Owner na https://fotontech.io!

Descrição:

Se você amar cuidar de pessoas e acredita que está na hora de fazer a transição para o cargo de PO/PM, estamos procurando por você!

Requisitos:

- React
- ReactNative
- GraphQL
- Inglês fluente.
- Amar pessoas (O mais importante)

Caso tenha interesse na vaga, recomendo entrar em contato através do meu Twitter @fpirova 

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by danielGalvao** [comment]
Vaga de PO nessas issues??? @jaburx 🌝

**Comment by nicholasess** [comment]
Não aceitamos vagas que não sejam de React

**Comment by jaburx** [comment]
Boa tarde senhores, a vaga é de React. Mas seria 1 perfil mais dev manager. Pusemos PO só pro pessoal entender.

**Comment by jaburx** [comment]
@nicholasess só ver na descrição o React escrito.

**Comment by nicholasess** [comment]
@jaburx muda o titulo, por que da margem para outras pessoas fazerem o mesmo.

**Comment by nicholasess** [comment]
Pronto, modifiquei

**Comment by Felipepirova** [comment]
Obrigado.

**Comment by jaburx** [comment]
Obg pessoal
