### ISSUE TITLE
Frontend (React/React-Native) Engineer - Remote US

### ISSUE THREAD

**Issue by danilowoz** [react-brasil/vagas#1378]
[REMOTO] [USA] 
Frontend (React/React-Native) Engineer

Qualquer dúvida pode falar comigo, trabalhei lá e recomendo. 
Não precisa de inglês super avançado, só o suficiente para conversar.
 
https://www.notion.so/Frontend-React-React-Native-Engineer-77db256cf1c84428959a56d9068b95e6

**Comment by RenanMomesso** [comment]
Boa tarde. Você tem whatsapp?

**Comment by danilowoz** [comment]
@RenanMomesso da um ping no slack do React BR, procura por danilowoz

**Comment by rvmelo** [comment]
Eu tenho interesse. Já mandei currículo para eles. Eles demoram para responder? Passam algum feedback?
