### ISSUE TITLE
[Remoto] Desenvolvedor Frontend/JS

### ISSUE THREAD

**Issue by dougcavalheiro** [react-brasil/vagas#138]
## Descrição da vaga

Venha trabalhar como líder Frontend em novos projetos incríveis

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com NodeJS, React e CSS (com bootstrap e Material design)
- Metodologias ágeis (Scrum e Kanban)
- Serviços REST

**Desejáveis:**
- Conhecimentos em Java / Spring
- Contato com outros frameworks como Angular ou VueJS

**Diferenciais:**
- Inglês - intermediário / fluente
- Prototipagem, habilidades em design

## Contratação

PJ a combinar

## Nossa empresa

Somos o Grupo Acert, especializados em softwares para o mercado óptico e temos oportunidades para pessoas com o desejo de construir ótimos produtos.

## Como se candidatar

Por favor envie um email para trabalheconosco@grupoacert.com.br com seu CV anexado - enviar no assunto: Vaga - Desenvolvedor Frontend/JS

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by gustavojnt** [comment]
Enviado!

**Comment by ricardoasgs** [comment]
Enviado
