### ISSUE TITLE
[Oportunidade Remota] - Dev. Front-End na Kyte

### ISSUE THREAD

**Issue by Startec-Jobs** [react-brasil/vagas#1387]
Dev. Front-End React na Kyte

## Descrição da vaga

A Kyte está com vaga aberta para uma pessoa desenvolvedora front-end! Estamos em busca de uma pessoa experiente, criativa e com proatividade para trazer novas ideias e abraçar o compromisso da empresa.

Atuará no time de Front, junto com o Head de Tecnologia, para o desenvolvimento e manutenção de componentes para o app, com design responsivo para Android e iOS. Precisará desenvolver com as melhores práticas utilizando metodologias para manter um código limpo.

## Local

Remoto 

## Benefícios

Vale refeição, Plano de saúde, Plano Odontológico, Auxílio Educação, Equipamentos, Auxílio Home Office, Day off no Aniversário, Vale Bem-Estar, Happy Hour Virtual, Cartão multi-benefícios

## Requisitos

**Obrigatórios:**
Experiência de pelo menos 4 anos em desenvolvimento front-end (CSS e Html), React e React-native, componentização e Git.
Para a vaga é importante ter conhecimento em JavaScript (ES6), em Gerenciamento de estado (Redux e React Hooks) e conhecimento algum pré-processador de CSS.

## Contratação

CLT - R$ 11.000,00

## Nossa empresa

A Kyte é uma startup que nasceu em Florianópolis e construí soluções para o crescimento de pequenos negócios, ajudando comerciantes a saírem do papel e da caneta e darem o primeiro passo na gestão e digitalização de seus negócios.

Fazem isso através do Kyte, seu app de vendas, gestão de estoque e loja virtual, que já atende mais de 30 mil clientes e está presente em mais de 143 países, como Brasil, EUA e México.

Mas não querem parar por aí: eles tem a ambição de atender cada vez mais clientes em todo o mundo e sabem como é essencial para a sobrevivência dos pequenos comércios terem suas operações online durante o período de pandemia.

“Ficamos felizes com as dezenas de depoimentos que chegam todos os dias contando como “salvamos” seus negócios. Estamos sempre pensando em melhorar, seja o produto, negócio, processos ou nós mesmos.”

Em um momento de expansão do negócio de base de clientes, contam com 30 colaboradores no time que estão distribuídos pelo país (principalmente em Florianópolis e São Paulo). E com a captação de investimento querem triplicar a equipe em 2021!

Com uma cultura ágil e pragmática, prezam pelo respeito e por uma comunicação aberta e transparente.

“Acreditamos que satisfação no trabalho é ter um grande desafio com as ferramentas adequadas e a visibilidade de que estamos sempre evoluindo. Sabemos que somente um time incrível de pessoas é capaz de grandes conquistas.”

A Kyte está crescendo e buscando profissionais incríveis para fazer parte da equipe!

Pós pandemia ficarão 100% remotos.

Conheça mais sobre a empresa em kyte.com.br/

## Como se candidatar

https://startecjobs.com/vagas/front-end-developer-kyte/

## Labels

- 👴 Sênior

**Comment by Ramon-Lobo** [comment]
Ainda estão aceitando inscrições?
