### ISSUE TITLE
[Belo Horizonte] Desenvolvedor(a) Mobile React Native

### ISSUE THREAD

**Issue by felipearimateia** [react-brasil/vagas#14]
Estamos procurando uma pessoa para trabalhar com Desenvolvimento Mobile aqui na MaxMilhas! Você é essa pessoa?

**O que a gente precisa:**

Que você seja apaixonado por tecnologia, é claro. E Tenha vontade de fazer parte de algo grandioso. Confira alguns de nossos números:

+1.200 acessos simultâneos
+100.000 visitas/dia
+3 milhões de acessos/mês
+800.000buscas/dia.
+2.000 passagens emitidas/dia

Nosso time de Engenharia conta com pessoas motivadas para entregar um produto de alta qualidade, trabalhando em um ambiente colaborativo e leve <3

**No dia a dia, você será responsável por:**

Planejar e desenvolver aplicações para Mobile
Aplicar a melhor UI e UX nos aplicativos
Resolver problemas complexos de desempenho e desafios de arquitetura
Buscar novas tecnologias que possam ser aplicadas em soluções mobile
Planejar e estimar tarefas junto ao time

**Requisitos obrigatórios:**

Conhecimentos em alguma das seguintes tecnologias: Android, iOS, React Native, Ionic
Conhecimentos em Orientação a Objetos
Conhecimento em alguma das seguintes linguagens: Java, Kotlin, Objective-c Swift, JavaScript
Conhecimento em ferramentas para controle de versão (Git)
Conhecimento em padrões de projetos
Conhecimento em API RestFul
Conhecimento básico em Banco de Dados

**Requisitos desejáveis:**

Conhecimento em ReactJS, Redux , CSS e Flexbox
Conhecimento em Firebase, Analytics e Crash Report
Conhecimento em testes unitários e automatizados
Ter trabalhado com metodologias ágeis

**Como aplicar:**
https://maxmilhas.gupy.io/jobs/4571

**Comment by nicholasess** [comment]
@felipearimateia É presencial? Não deixou claro na proposta

**Comment by felipearimateia** [comment]
Olá @nicholasess é presencial

**Comment by nicholasess** [comment]
Ainda está em aberto? @felipearimateia

**Comment by felipearimateia** [comment]
Está sim

**Comment by nicholasess** [comment]
@felipearimateia não está definido se é Junior, Pleno ou Senior. Obrigado

**Comment by felipearimateia** [comment]
@nicholasess está aberto para todos os niveis por isso não coloquei.

**Comment by danielGalvao** [comment]
@felipearimateia A vaga ainda está aberta? Senão fecharemos a issue.

**Comment by felipearimateia** [comment]
@danielGalvao acabamos de fechar ela

**Comment by danielGalvao** [comment]
BOA!
