### ISSUE TITLE
ETL

### ISSUE THREAD

**Issue by claudettealves** [react-brasil/vagas#1427]
[Piracicaba - SP e Região] RDesenvolvedor ETL na Empresa Smartbreeder

## Descrição da vaga:
   
⚠ Formação: Cursos relacionados a TI  
 
 📍Seria legal se você tivesse conhecimento em:  
✅ Lógica de programação;
✅ Linguagem SQL;  
✅ Banco de dados SQL Server e Oracle;  

## Local : Piracicaba e Região

Home - office em período de pandemia e pós pandemia Presencial - Piracicaba - SP

## Benefícios:
✅ Vale transporte;  
✅ Vale Alimentação;
✅ Assistência Médica;
✅ Assistência Odontológica;

#### Diferenciais:
✅ Programa de Capacitação;  
✅ Parceria Esalq MBA - 10% de desconto

- ## Requisitos:
  📍 O que você vai fazer no seu dia a dia:  
✅ Criar procedimentos, executar testes e validações utilizando SQL e Ferramentas ETL para garantir a congruência dos dados integrados;  
✅ Estruturação de Banco de dados;  

## Contratação : CLT
Se você deseja trabalhar em uma empresa pioneira em Inteligência Agronômica Digital, líder no mercado agro, criadora incansável de soluções inovadoras e fazer parte de um time que revoluciona a agricultura, chegou o momento! Venha ser um SMARTBREEDER!  
   
## Como se candidatar:

Por favor envie um email para curriculo@smartbreeder.com.br com seu CV anexado e colocar a pretensão salarial- enviar no assunto: Vaga Desenvolvedor ETL

## Labels

- 🏢 Remoto/ Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by nicholasess** [comment]
A vaga não é relacionada a React, por isso será fechada

**Comment by claudettealves** [comment]
Prezado Nicolas, bom dia!
Peço desculpas pelo equívoco, como eu faço para divulgar essa oportunidade de ETL?

Aguardo retorno!

Atenciosamente,

[cid:0f1d86de-5382-4709-a814-ddfe9c49f83b]

________________________________
De: Nicholas Eduardo ***@***.***>
Enviado: segunda-feira, 12 de abril de 2021 16:06
Para: react-brasil/vagas ***@***.***>
Cc: CURRICULOS - RH ***@***.***>; Author ***@***.***>
Assunto: Re: [react-brasil/vagas] ETL (#1427)


A vaga não é relacionada a React, por isso será fechada
