### ISSUE TITLE
[MULHERES] Fullstack React e Node na Sallve

### ISSUE THREAD

**Issue by ottusp** [react-brasil/vagas#1431]
## Requisitos
- Mulheres;
- Com experiência em NodeJS;
- Com experiência em ReactJS;
- Com experiência em TDD.

## Contratação

- CLT

## Nossa empresa

A Sallve é uma startup brasileira de beleza direct-to-consumer que quer levar a melhor experiência pra sua comunidade. Ainda é nova, mas já tá construindo um time multidisciplinar de alto nível e já conta com investimentos dos principais fundos de venture capital brasileiros.

## Como se candidatar

Essa vaga é muito especial, então se você se tem interesse, já pode se inscrever pelo link abaixo:

https://vagas-emb.byintera.com/2o6

Um sorriso de orelha a orelha =)

**Comment by brunaniehues** [comment]
Não estou dentro dos requisitos da vaga mas gostei muito. Estou cursando ADS e estudando por fora as tecnologias web (css, html, javascript), queria saber se posso me candidatar.

**Comment by ottusp** [comment]
@brunaniehues manda seu linkedin ou me chama lá, Bruna!

https://www.linkedin.com/in/otto-fernandes-0a3188196/

**Comment by brunaniehues** [comment]
@ottusp https://www.linkedin.com/in/brunaniehues/
