### ISSUE TITLE
[Florianópolis] Desenvolvedor FullStack C# e REACT na EXACT SALES

### ISSUE THREAD

**Issue by talentosexactsales** [react-brasil/vagas#1463]
## Descrição da vaga

E se você coda em C#, mas também gosta de front e tem experiência com React, essa vaga é para você!

Buscamos alguém com conhecimentos em C#, e que tenha atuado como fullstack. Aqui usamos ReactJS, então ter atuado com esta biblioteca será um ponto diferencial. Seu papel será desenvolver, manter e melhorar funcionalidades de nosso software, garantindo qualidade de código e fazendo o versionamento via git.

 

## Local

Remoto durante a Pandemia, depois atuará em nossa sede em Florianópolis

## Benefícios

- R$ 877 para usar como quiser

#### Diferenciais

-  A proposta salarial vai variar conforme sua vivência na área, mas estamos dispostos a negociar;
- Pacote de benefícios de R$ 877,00 (você compõe como quiser entre: vale alimentação, vale refeição, vale transporte, vale combustível, plano odontológico ou plano de saúde);
- Seguro de vida;
- Convênio com ACATE;
- Local para descanso (sim, você pode tirar aquele cochilo :)
- Bicicletário;
- Vídeo Game;
- No dress code;
- Biblioteca colaborativa;
- Espaço para refeições com geladeiras e microondas;
- Open café;
- Convênio com SESI;
- Happy Hours;
- Dia de folga no aniversário solidária;
- Trabalhar com profissionais que são referências no mercado.

## Requisitos

**Obrigatórios:**
- Ter  2 anos de experiência com C#;
- Ter experiência em ReactJs 
- Saber estruturar bem objetos JSON;
- Conhecimento em Banco de Dados SQL;

**Diferenciais:**
- Conhecimento em Git, Azure;
- Capacidade de realizar requisições em API's backend;
- Conhecimento sobre WebAPI, Entity Framework;

## Contratação

CLT

## Nossa empresa
Olá, somos a Exact Sales, criadores do maior Software de Sales Engagement da América Latina, o Exact Spotter. Em 2021 dobraremos de tamanho e buscamos pessoas com vontade de aprender e em busca de crescimento profissional.

## Como se candidatar

Por favor, clique  [AQUI](https://jobs.kenoby.com/exactsales/job/desenvolvedora-full-stack-c/605e39e46f34711e22048728?utm_source=website)

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- ⚖️ CLT
- 💰 5k-10k

**Comment by paulosjunior7** [comment]
Ótima vaga, pena não ser remoto permanente. https://www.linkedin.com/in/paulosjunior7/
