### ISSUE TITLE
[São Paulo] Desenvolvedor front-end ReactJS Sênior

### ISSUE THREAD

**Issue by MoniquePaiva** [react-brasil/vagas#1494]
## Descrição da vaga

Buscamos por um desenvolvedor Sênior Front End REACT.JS
O que buscamos tecnicamente:
- Framework REACT.JS;
- Linguagens de Programação (JavaScript e TypeScript);
- HTML e CSS - Conhecimento com UI (User interface);
- Conhecimento com UX (User Experience);
- Familiaridade com banco de dados principais;
- Conhecimentos em integração com APIs REST;
- Experiências com testes unitários (Jest, Enzyme);
- Experiência com deploy automatizado (CI/CD);
- Boas práticas de desenvolvimento de software como SOLID, Clean Code, Lint, Code Coverage.

Desejável:
- Profissionais multi skills e com a mente aberta para aprender novas tecnologias e ferramentas;
- Metodologias ágeis: Scrum e Kanban;
- Product & startup mindset;
- Testes automatizados;
- Framework Javascript mobile React Native
- Framework Node.js
- Experiência com e-commerce;

## Local

100% remoto (Base São Paulo) Profissional tem que residir no estado de São Paulo.

## Benefícios

15 dias férias remuneradas.

## Requisitos
Experiência de +3 anos com desenvolvimento Front End utilizando linguagem de programação Javascript ou Typescript com Framework React.Js.

## Contratação

PJ 

## Nossa empresa

Fintech, maior plataforma de apostas em loterias pela internet no Brasil , está em pleno crescimento e em busca de profissionais da área de tecnologia/engenharia de software para compor seu time multidisciplinar.

## Como se candidatar

https://www.99hunters.com/moniquepaiva até 03/05

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 10k-15k

**Comment by thalesf** [comment]
A vaga ainda está aberta ?
