### ISSUE TITLE
Vaga para Dev - Flexivel, ótima remuneração - Startup de Legaltech

### ISSUE THREAD

**Issue by esg877** [react-brasil/vagas#1516]
==================================================
Somos uma startup em fase inicial, gerida pelos fundadores. Desejamos contratar um desenvolvedor sênior ou pleno, engajado e comprometido com prazos, para rever e aprimorar todo nosso front end. Possibilidade de um contrato continuado e novos trabalhos, à medida em que formos crescendo. Desejamos estabelecer uma relação de confiança, e possivelmente de longo prazo. Pessoas engajadas e comprometidas podem crescer muito conosco, e até se tornar sócios. Temos um time pequeno, coeso, composto de devs experientes, sem ‘encheção de saco’, sem burocracias, sem nenhuma babaquice do mundo corporativo.

Descrição da vaga
Você estará trabalhando no desenvolvimento de uma startup de legaltech, voltada para advogados e profissionais do mundo jurídico. Temos uma plataforma revolucionária, que vai mudar a forma como se pratica a advocacia. Buscamos desenvolvimento front-end da plataforma, para web e mobile.

Local
Remoto

Requisitos:
Experiência com HTML5, CSS3 e Javascript
Experiência em React
Experiência em React, React Context & Hooks
Experiência em ferramentas de versionamento (como GitHub)

Contratação
PJ a combinar

Como me candidatar?
Por favor envie um email para contato@jurisbot.com.br com seu CV anexado.
Acusamos o recebimento de todos os e-mails em até 48 horas.

Regime
PJ/MEI

Nível
Pleno ou Sênior

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-15k

**Comment by mayconbalves** [comment]
Aceita freela ?
