### ISSUE TITLE
[Remoto] Full Stack Developer (React, Rails, Mongo) na bxblue

### ISSUE THREAD

**Issue by nuk** [react-brasil/vagas#153]
## Descrição da vaga

Temos hoje um time super enxuto que trabalha super bem pra construir nosso produto. Estamos a procura de pessoas diferentes que possam contribuir não apenas em número mas com um DNA diferente pro nosso time.

## Local

Remoto

## O que você PRECISA para concorrer a essa vaga?

- Saber se comunicar em Inglês e Português
- Se sentir a vontade no desenvolvimento de aplicações web
- Ter disponibilidade para trabalhar em período integral

## O que você NÃO PRECISA para concorrer a essa vaga?

- Morar perto da gente (somos remotos)
- Fazer parte de qualquer grupo (seja por idade, genética, geografia, escolha pessoal ou acaso do destino)
- Saber a nossa Stack de Desenvolvimento

## Contratação

CLT

## Nossa empresa

A bxblue é uma fintech com a missão de ajudar as pessoas a ter acesso ao crédito pessoal mais barato do país. Fomos investidos por grandes nomes do cenário nacional e internacional. Dentre eles a Y Combinator (Aceleradora responsável por empresas como AirBnB, Dropbox, Heroku, Docker e Twitch). Também tivemos a honra de sermos selecionados pelo Banco do Brasil para co-criarmos juntos a primeira API de Empréstimo do Brasil.

## Como se candidatar

Basta preencher esse formulário [bit.ly/bxdev201810](https://bit.ly/bxdev201810)

## Labels

- alocação/Remoto
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior
- regime/CLT

**Comment by rodrigo-tavares** [comment]
Fala pessoal da bxblue, o link do form está quebrado.

**Comment by nuk** [comment]
Valeu @rodrigo-tavares . Corrigido =]

**Comment by thiagolavor** [comment]
Ai pessoal da bxblue tudo bem?
Para concorrer a vaga precisar precisar trabalhar das 8 hrs ás 18 hrs ou pode dividir durante o dia?
Pois faço faculdade então gostaria de saber?

**Comment by nuk** [comment]
O horário é flexível Thiago, então não tem problema ter alguma quebra no
dia.
‌

**Comment by ribeiroevandro** [comment]
CLT e Home office no mesmo contexto... Essa empresa merece muito respeito.
