### ISSUE TITLE
[Campinas] Desenvolvedor iOS Sr

### ISSUE THREAD

**Issue by Carollinecovre** [react-brasil/vagas#156]
## Descrição da vaga

Responsabilidades:
- Conhecimento profundo em desenvolvimento orientado a objetos;
- Proficiência com Objective-C, Swift e Cocoa Touch.
- Proficiência com ferramentas de versionamento de código.
- Experiência com ARKit.
- Experiência em construção de aplicações complexas para iPhone ou iPad.
- Experiência com programação Multi-Threaded.
- Familiaridade com openCV e técnicas de processamento de imagem.
- Desenvolvimento de aplicações tanto a nível de interface quanto a nível de sistema.
- Conhecimento de ferramentas de performance do iOS e técnicas de otimização.
- Alta capacidade para resolução de problemas, análise crítica e comunicação.

É preciso:
- Experiência com ARKit com foco em FaceTracking.
- Graduado ou Pós-Graduado em Ciência da computação ou áreas correlatas.
- Proficiência com Objective-C
- Conhecimento de bibliotecas baseadas em C de baixo nível.

## Local
Campinas - SP

## Contratação

PJ

## Como se candidatar

Por favor envie um email para ct@sharerh.com com seu CV anexado - enviar no assunto: Vaga Desenvolvedor iOS Sr

**Comment by danielGalvao** [comment]
Somente React e React Native
