### ISSUE TITLE
[Campinas] Desenvolvedor Android Pleno

### ISSUE THREAD

**Issue by Carollinecovre** [react-brasil/vagas#157]
## Descrição da vaga

Responsabilidades:
- Criação de Layouts em XML;
- Conceito de Programação Reativa;
- Criação de códigos de boa qualidade a partir de designs de wireframes;
- Criação e manutenção da arquitetura, identificação e manutenção de bugs e gargalos de performance em alguns dos aplicativos do grupo;

É preciso:
- Conhecimentos em Java e Kotlin;
- Familiaridade com arquitetura e boas práticas para Android;
- Conhecimento de ferramentas como GIT, Android Studio, Fastlane;
- Graduado ou Pós-Graduado em Ciência da computação ou áreas correlatas.

## Local

Campinas

## Contratação

PJ.

## Como se candidatar

Por favor envie um email para ct@sharerh.com com seu CV anexado - enviar no assunto: Vaga Android

**Comment by danielGalvao** [comment]
Somente React ou React Native
