### ISSUE TITLE
[São Paulo] React Developer na CONFITEC

### ISSUE THREAD

**Issue by JulianaSoave2018** [react-brasil/vagas#166]
## Descrição da vaga

Fará parte do time responsável pelo desenvolvimento (Front End) de aplicações web voltadas ao mercado segurador. 

## Local

No Escritório, São Paulo - Zona Sul- ao lado do Morumbi Shopping.

## Benefícios

- Plano de saúde e odonto
- VR de R$ 24,30/dia
- Auxílio creche
- VT
- PLR 
- Treinamentos

#### Diferenciais

- café da manhã às sextas-feiras
- festa de aniversariantes do mês
- campeonatos de Poquer e futebol

## Requisitos

**Obrigatórios:**
- Ensino superior completo em cursos de TI/Web (ou cursando último ano da graduação);
- Vivência com desenvolvimento com a biblioteca Javascript React.

**Diferenciais:**
-  Atuação anterior em projetos envolvendo Java e/ou Python. 

## Contratação

CLT 

## Nossa empresa

A Confitec é uma empresa de Tecnologia da Informação especialista no mercado de Seguros. 

## Como se candidatar

Por favor envie um email para curriculos@confitec.com.br com seu CV anexado - enviar no assunto: Vaga React. 

## Labels

- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/CLT

**Comment by thaisfalbo** [comment]
Enviado! 😄
