### ISSUE TITLE
[Remoto] Frontend Developer na Devel Blockchain - React JS

### ISSUE THREAD

**Issue by DevelBlockchain** [react-brasil/vagas#1691]
Vaga Front-end React JS
Devel Blockchain está recrutando Desenvolvedores(as) Front-end para participar do nosso time de desenvolvedores. 

# Nossa empresa

Entregamos soluções em blockchain, Inteligência artificial, Contratos inteligentes, Sistema de gerenciamento financeiro, Apps e Sites. Saiba mais em develblockchain.com

# O Stack solicitado:
- Inglês para leitura/escrita
- Experiência com HTML, HTML5, JS, jQuery, CSS, SASS
- ReactJS
- Conhecimento em arquitetura de APIs / JSON / REST;
- Conhecimentos em Git e/ou similares (controle de versão, pipelines, integração, etc);

# Diferenciais:
Conhecimento em React Native
Conhecimento em mercado financeiro e mercado cripto
Disposição para aprender

# Oferecemos:
Horário Flexível
Trabalho remoto
Ótimo ambiente para inovar e aprender novas tecnologias
Contrato CLT ou PJ;

# Como se candidatar
Enviar CV para: contact@develblockchain.com

# Labels
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ CLT
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k

**Comment by alessandrordgs** [comment]
Olá, a vaga ainda está aberta ?

**Comment by DevelBlockchain** [comment]
Muito obrigado por todos que se inscreveram. A vaga foi preenchida.
