### ISSUE TITLE
[Recife] Desenvolvedor ReactJS na Wololo

### ISSUE THREAD

**Issue by gusfune** [react-brasil/vagas#17]
A Wololo procura um desenvolvedor ReactJS nível Pleno ou Sênior para integrar núcleo de desenvolvimento de produto. Procuramos um profissional para atuar tanto de home-office, quanto alocado em nosso escritório no Porto Digital em Recife/PE.

No papel de desenvolvedor reactJS você vai ser responsável por: 

- Trabalhar no desenvolvimento de sistema, implementando funcionalidades previstas e desenhadas pela equipe de design e produto 
- Manter e melhorar código organizado e reutilizável dentro dos frameworks ReactJS, Redux e SASS.
- Garantir a melhor qualidade, performance e segurança de nossa aplicação 
- Identificar e corrigir bugs na plataforma em conjunto com time de Qualidade e Suporte 
- Trabalhar junto a equipe de Web e Mobile para garantir evolução das diversas plataformas previstas no projeto 
- Colaboração com diversos stakeholders de cada área do projeto para garantir entrega dentro do cronograma projetado

## Requisitos 

- Conhecimentos sólidos de HTML5, CSS3 e Javascript
- Programação orientada a objetos
- MVC, restful API
- Git
- Experiência prévia com ReactJS, Redux e SAAS, ou similares
- Conhecimento básico de cloud computing
- Inglês intermediário
- Boa organização e documentação de código-fonte
- Atitude “arregaçar as mangas e resolver a treta” - queremos alguém com atitude proativa de resolver problemas.
- Disponibilidade para viagens, no caso de profissionais não alocados em Recife

## Desejável 

- Experiência com metodologias ágeis (ex. scrum)
- Graduação (ou experiência equivalente no mercado) em ciência da computação, engenharia de software ou área correlata
- Experiência prévia com GatsbyJS
- Experiência prévia com infraestruturas cloud: amazon web services
- Experiência com continuous integration e automatização de processos

## Benefícios

- Equipamento de última geração cedido pela empresa durante realização do projeto
- Bônus em participação de empresa baseado em desempenho e sucesso
- Ambiente de inovação, bons resultados, dedicação e foco
- Oportunidades para apresentar seus próprios projetos, ser convidado para participar de outros ou ser contratado pela empresa ou vir a ser um associado

## Informações importantes
Candidatos sem portfolio serão desconsiderados. Programadores devem fornecer link para GitHub ou outro local em que consigamos conferir o trabalhado realizado e parte do código fonte para avaliação do conhecimento de programação.

Interessados devem enviar apresentação, currículo e portfólio em [link](http://app.pipefy.com/public/form/4iAE1cr_)

**Comment by renweb** [comment]
Boa tarde, quero me aplicar para a vaga mas o link não funciona, pode me ajudar?

**Comment by nic** [comment]
@renweb Acho que é um problema com o github. Utilize o link com o underscore no final "_".

"https://app.pipefy.com/public/form/4iAE1cr_"

**Comment by nicholasess** [comment]
@nic obrigado pela dica, atualizei a descrição da vaga.
@renweb tente novamente

**Comment by renweb** [comment]
Obrigado @nic, Consegui!

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criarem uma nova issue, com informações mais atualizadas.
