### ISSUE TITLE
[São José dos Campos] React Developer na Sistema Pallas

### ISSUE THREAD

**Issue by hugofialho** [react-brasil/vagas#170]
## Local

São José dos Campos, Jardim das Indústrias, remoto até 3 dias da semana, vai depender da nossa sinergia.

## Benefícios

- VT
- VR
- Horário flexível

## Requisitos

**Obrigatórios:**
- Experiência sólida com React JS
- Git

**Diferenciais:**
- experiência com Material-UI
- experiência com arquitetura serverless, especialmente Firebase

## Contratação

CLT

## Como se candidatar

Por favor envie perfil do Github e currículo para vagas@sispallas.com.br

## Labels

- alocação/Flexível
- experiência/Júnior
- experiência/Pleno
- regime/CLT

**Comment by ribeiroevandro** [comment]
Enviado
