### ISSUE TITLE
[Remoto] Desenvolvedor JavaScript (React Native, NodeJs) na Hupper

### ISSUE THREAD

**Issue by raffaelmarfara** [react-brasil/vagas#171]
## Descrição da vaga

A Hupper usa inteligência artificial para criar programas de bem estar corporativo personalizados para melhorar a saúde de cada funcionário! Estamos procurando um desenvolvedor para desenvolver essa aplicação mobile utilizando react native do zero junto com a gente!

## Local

Remoto (mas ficamos em São Paulo!)

#### Diferenciais

- Homeoffice
- Flexibilidade de horarios
- 100% de autonomia 
- Alta probabilidade de crescimento (um dos primeiros colaboradores da Hupper)
- Construção de um projeto do zero

## Requisitos

**Obrigatórios:**
- Experiência com React Native
- Experiência com Node.js
- Experiência com PostgreeSQL

## Contratação

PJ salário de até R$ 5000

## Como se candidatar

Por favor envie um email para r.marfara@hupper.life com seu CV anexado - enviar no assunto: Vaga React Native GitHub

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by ricardoasgs** [comment]
Enviado
