### ISSUE TITLE
[REMOTO] Front-End React na Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [react-brasil/vagas#1737]
## Descrição da vaga

Já pensou em trabalhar em um ambiente colaborativo, dinâmico, com muito aprendizado e autonomia? Neste momento estamos buscando uma pessoa com experiência e conhecimento para área de Front-End React.

## Local

Remoto 

## Benefícios

- Plano de saúde (Cooperação com o plano de saúde da Unimed, 60% a empresa paga, 40% o membro paga) 
- Plano de carreira estruturado
- VR/ VA de R$ 23/dia
- Alura Cursos + Alura Linguas
- Auxilio psicológico na plataforma Vittude

#### Diferenciais

- Plano de carreira estruturado
- Hierarquia Horizontal
- 100% Remoto
- Horários Flexíveis

## Requisitos

**Obrigatórios:**
- HTML;
- CSS;
- Javascript;
- Experiência no desenvolvimento de aplicações web utilizando React;

## Contratação

CLT

## Nossa empresa

O time da Nave.rs é experiente e atua como uma consultoria em todos os momentos do desenvolvimento das soluções. Somos especialistas na construção de produtos digitais utilizando o que há de mais inovador no mercado de aplicativos e sistemas. Alinhamos nossos conhecimentos em inovação com a experiência de mercado dos clientes e criamos soluções capazes de renovar os processos das empresas e impactar a vida das pessoas através da tecnologia.

## Como se candidatar

inscreva-se através do link: [link aqui](https://nave-team.gupy.io/jobs/1043957)

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior

- ⚖️ CLT

- 💰 1k-3k

**Comment by andreCaetano225** [comment]
Inscrição feita!

**Comment by Juninhoww2** [comment]
Top!

**Comment by evertonfxavier** [comment]
Inscrição feita!
