### ISSUE TITLE
[São Paulo, SP] Desenvolvedor React Pleno | Pixter

### ISSUE THREAD

**Issue by FelipePaiva1992** [react-brasil/vagas#178]
**Empresa: Pixter (www.pixter.com.br)**

Somo uma empresa de tecnologia, voltada para desenvolvimento de software para clientes de grande relevância no mercado.
Utilizamos alta tecnologia e metodologias ágeis.
Construímos um time de excelência e trabalhamos com projetos selecionados de alto padrão.
Temos uma oportunidade de desenvolvedor, para integrar equipe de Front End.

**Requisitos**:
- Interesse em aprender novas tecnologias e compartilhar conhecimento
- Curtir trabalhar em equipe
- Vestir a camisa da empresa
- Adaptável a mudanças no decorrer do projeto
- Experiência com metodologia ágil – SCRUM/Kanban
- Conhecimento da ferramenta JIRA
- Ter trabalhado com metodologias ágeis
- Vontade de aprender Node.JS, React Native, entre outras tecnologias;

**Requisitos técnicos**:
- Experiencia em React;
- Conhecimento em ES6;
- Conhecimento com Prettier, ESLint
- Conhecimento com bibliotecas como Firebase;
- Criar layouts baseados em UI/UX
- Conhecimento em versionamento GIT

**Diferenciais**:
- Experiencia em Angular;
- Experiencia em NodeJS;

## Contratação
- Regime PJ
- Presencial

Interessados, que atendam aos requisitos, devem enviar CV e link do Github para fernanda.monteiro@pixter.com.br - Assunto: Desenvolvedor Front End - React

**Comment by ribeiroevandro** [comment]
Mandei email ontem por indicação de um amigo...
