### ISSUE TITLE
[São Paulo, SP] Desenvolvedor Node.JS - Backend Pleno | Pixter

### ISSUE THREAD

**Issue by FelipePaiva1992** [react-brasil/vagas#179]
**Empresa: Pixter (www.pixter.com.br)**

Somo uma empresa de tecnologia, voltada para desenvolvimento de software para clientes de grande relevância no mercado.
Utilizamos alta tecnologia e metodologias ágeis.
Construímos um time de excelência e trabalhamos com projetos selecionados de alto padrão.
Temos uma oportunidade de desenvolvedor, para integrar a equipe de Back-End.

**Requisitos**:
- Interesse em aprender novas tecnologias e compartilhar conhecimento
- Curtir trabalhar em equipe
- Vestir a camisa da empresa
- Adaptável a mudanças no decorrer do projeto
- Experiência com metodologia ágil – SCRUM/Kanban
- Conhecimento da ferramenta JIRA
- Ter trabalhado com metodologias ágeis
- Vontade de aprender outras tecnologias e/ou frameworks;

**Requisitos técnicos**:
- Experiencia em NodeJS;
- Experiencia em Express e/ou Hapi;
- Conhecimento em SQL e NOSQL (Usamos muito MongoDB e MySql);
- Conhecimento em ES6;
- Conhecimento com Prettier, ESLint
- Conhecimento com bibliotecas como Firebase;
- Conhecimento em versionamento GIT

**Diferenciais**:
- Experiencia e/ou Conhecimento em React
- Experiencia e/ou Conhecimento em GraphQL

## Contratação
- Regime PJ
- Presencial

Interessados, que atendam aos requisitos, devem enviar CV e link do Github para fernanda.monteiro@pixter.com.br - Assunto: Desenvolvedor Back-End - NodeJS

**Comment by brunooomelo** [comment]
Enviado.
