### ISSUE TITLE
[Remoto] Dev. Front-End Sênior React (R$ 14.000,00)

### ISSUE THREAD

**Issue by Startec-Jobs** [react-brasil/vagas#1791]
## Descrição da vaga
Mob2con

Nascemos do impulso de inovar e tornar mais eficiente a cadeia de suprimentos do varejo. Essa natureza autêntica e cheia de energia inspira diariamente uma equipe talentosa, unida e que, dia após dia, cria e celebra junta a cultura Mob2Con. Nosso escritório é um ambiente de amizade, diversidade e descontração.

O ideal de ganha-ganha que move nosso modelo de negócio vale para todos, clientes, parceiros e colaboradores. Para isso contamos com uma equipe que cultiva em parceria com a liderança três valores centrais da cultura profissional da empresa: auto responsabilidade, liberdade para criar e foco na entrega. 

Nosso time é formado por profissionais de diversas áreas com mentes abertas, dedicação aos compromissos individuais sem abrir mão do cuidado colaboração para o alcance de um objetivo comum: superar as expectativas dos clientes, criando soluções que ultrapassem os paradigmas atuais do mercado e criem verdadeiras disrupções na operação e interação entre varejo, indústria e agências de promotores.

## Local

Remoto 

## Benefícios

- Plano de saúde

## Requisitos

**Obrigatórios:**
• React 
• Typescript
• HTML /CSS

Você se dará bem na Mob2con se for uma pessoa compreensiva, respeitosa, independente, aberta a colaboração, tenha foco no cliente e queira construir uma carreira na empresa.

## Contratação

PJ - R$ 12.000,00 - R$ 14.000,00

## Como se candidatar

Inscrições no link: https://app.startecjobs.com/vaga/27956a75-0ca3-41b9-a3db-ece8b1630797

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 12k-14k

**Comment by thalesf** [comment]
Aceita part-time job ?

**Comment by marquinbatera** [comment]
Aceita part-time??
