### ISSUE TITLE
[São Paulo] React Native para Produto na CROWD

### ISSUE THREAD

**Issue by oVerde** [react-brasil/vagas#185]
## Descrição da vaga

Vaga para React Native. Você trabalhará alocado em nossa sede no *Largo da Batata* ao lado do metrô Faria Lima - São Paulo, focado na programação da UI e integração com nossos serviços. Você também participará nas tomadas de decisões estratégicas. O _core_ do projeto gira entorno de um messenger, cada conversa tem sua timeline interativa de chat ao-vivo com regras de negócio.

## Local

São Paulo - Pinheiros, no Largo da Batata ao lado do metrô Faria Lima

## Requisitos

Espero de você como Developer:
— Conhecimentos em Front End
— Bons conhecimentos em JavaScript/ES6;
— Alguma base com mobile e ecossistema iOS e Android;
— Conseguir **ler** bem em inglês.

Gostarei mais de você se:
— Compreender o _State_ da aplicação;
— Possuir algum entendimento de Graphql;
— Experiência básica com git-flow;
— Gostar de resolver desafios e de aprender novas ferramentas.

## Contratação

PJ

## Nossa empresa

A CROWD existe desde 2013, e estamos na corrida para lançar a versão 2.0 da nossa plataforma em 2019. Nossa plataforma é a primeira full-service de comunicação e tecnologia com atendimento aos clientes que se assemelha a uma agência e com toda a sua equipe de produção remota. Digitalizamos os processos do mundo real e não utilizamos das práticas comuns em plataformas de free-lancers. Mais em https://CROWD.br.com

## Como se candidatar

Só me chamar no meu email danilo@crowd.br.com contanto sobre você e com um CV anexado
Assunto: [VAGA] React Native

## Labels

- alocação/Flexível
- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/CLT
- regime/PJ

**Comment by guilhermeoa07** [comment]
ainda em aberto?

**Comment by oVerde** [comment]
@guilhermeoa07 a vaga reabriu sim (:

**Comment by adeonir** [comment]
@oVerde possibilidade de ser 100% remoto?

**Comment by oVerde** [comment]
> @oVerde possibilidade de ser 100% remoto?

Por enquanto não há, até o então lançamento e entrada na fase de manutenção estaremos só com o time local.
