### ISSUE TITLE
[Ribeirão Preto - SP] Desenvolvedor Frontend ou Full Stack @ ZeroSoft

### ISSUE THREAD

**Issue by nihey** [react-brasil/vagas#189]
## A Empresa

Nascida no final de 2017, a Zerosoft Tecnologia está em constante crescimento! Possui alguns clientes chave no fornecimento de outsourcing, além de estar almejar diversos projetos inovadores! O foco dos produtos é análise, visualização e inteligência de dados.

## As Vagas

* Estagiário (30h a 40h semanais)
* Desenvolvedor Frontend Junior (30h a 40h semanais)
* Desenvolvedores Frontend Pleno (30h a 40h semanais)
* Desenvolvedores Full-Stack Pleno (30h a 40h semanais)

## Requisitos

É esperado de todos os cargos vontade de crescer e aprender mais. Todos os dias temos novos desafios!

* Frontend
  * JavaScript/Node.js (preferencialmente com ES6)
  * React/React Native
  * Redux
  * Git
  * REST

- Full-Stack (além dos requisitos para Frontend)
  - Python
  - Django, Flask ou frameworks afins
  - Bom conhecimento sobre ORMs
  - Bom conhecimento de base de dados relacionais (e.g. postgresql)
  - Conhecimento de base de dados NoSQL (e.g. mongodb) (diferencial)

* Diferenciais
  * Ser autodidata
  * Gostar de desafios tecnológicos
  * Possuir bons conhecimentos de Linux
  * Ter capacidade de assimilar conhecimento rapidamente

## Contratação

- Local
  - Presencial (preferencialmente)
  - Remoto

* Regime CLT ou PJ

## Como se candidatar

Interessado? Envie um email para hireme@zerosoft.com.br com o seu curriculo ou link do linkedin. Adicione também seu perfil do github, link de algum projeto que desenvolveu, etc.

**Comment by rodrigoleite89** [comment]
Essa vaga exige experiência? Eu não tenho experiência na área ainda, mas tenho algumas coisas feitas.

**Comment by nihey** [comment]
> Essa vaga exige experiência?

@rodrigoleite89 Não necessariamente, vamos passar alguns testes para o pessoal que está se aplicando e avaliar o desempenho neles. Acreditamos que um bom profissional não necessariamente precisa ter anos de experiência para poder se destacar :)

**Comment by devlex777** [comment]
Todos os requisitos para front end são obrigatórios?

**Comment by nihey** [comment]
@devlex777 Não são obrigatórios, mas é bom que o candidato tenha algum conhecimento nessas àreas pois isso irá ajudar no processo seletivo. No geral, se a capacidade de aprendizado for boa, é possível suprir a falta conhecimento nestas áreas.

**Comment by devlex777** [comment]
ótimo, me candidatei!

**Comment by andersonmendesdev** [comment]
Enviado!

**Comment by soaresderik** [comment]
Enviado!
