### ISSUE TITLE
[Remoto] ReactJS Developer na SophaTech

### ISSUE THREAD

**Issue by vinibispo** [react-brasil/vagas#1925]
## Descrição da vaga

Desenvolvedor Júnior, Pleno ou Senior de ReactJS e Ruby On Rails na SophaTech

## Local

Remoto

## Requisitos

**Obrigatórios:**
-  Dominar HTML, CSS e JS
- Espirito empreendedor, com vontade de crescer, fazer a diferença, construir um legado e impactar com tecnologia!

**Desejáveis:**
- conhecimentos no básico do ReactJS
- Bancos de Dados Postgresql/Redis
- Visão de arquitetura de sistemas e integração com APIs, webservices, arquivos, fila, tópico

**Diferenciais:**
- projetos opensource
- conhecimento em webpack
- experiência com upgrade de versões do react

## Contratação

PJ a combinar

## Nossa empresa

Uma startup dedicada ao segmento de móveis e decoração!
O pensamento que nos motiva é o da possibilidade de transformação das coisas através da tecnologia. Não simplesmente dos bits e bytes, mas da experiência, design, inovação e em tudo que a tecnologia pode ser inserida para transformar as nossas vidas.
Evoluir o que somos hoje para algo que ainda nem imaginamos que possamos ser, sempre olhando para o que está além dos nossos olhos...
## Como se candidatar

Por favor envie um email para thiago@sopha.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS

## Labels

- 🏢 Flexível
- 🏢 Remoto

- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by vinibispo** [comment]
Sim

**Comment by vinibispo** [comment]
Sim

**Comment by dudunog** [comment]
Opa, podemos conversar melhor sobre a vaga?

**Comment by luanargolodev** [comment]
Currículo enviado!

**Comment by Thirki** [comment]
Currículo enviado!

**Comment by GiovaneVerbinnen** [comment]
Curriculo enviado

**Comment by vinibispo** [comment]
Pode mandar também pra giovane@sopha.com.br
