### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Pleno / Senior

### ISSUE THREAD

**Issue by taianeuchoa** [react-brasil/vagas#199]
## Descrição da vaga

Oportunidade para atuar como Desenvolvedor FullStack alocado em grande industria do ramo cosmético.
Atuará na sustentação de sistemas diversos desenvolvidos pela corporação para uso interno.

## Local

Escritório localizado na Vila Jaguará, Zona Oeste de São Paulo

## Benefícios

- Plano de saúde
- VR de R$ 22,00
- Auxílio creche
- Plano de Saúde Amil
- Plano Odontológico
- PLR

#### Diferenciais

- Ambiente inovador. Companhia é conhecida no mercado devido a ser uma das melhores empresas para se trabalhar.

## Requisitos

**Obrigatórios:**
- Conhecimento de metodologias ágeis, como Lean, Scrum e Kanban;
- Mandatório o conhecimento de React Web e Node.JS;

**Desejáveis:**
- Desejável o conhecimento de Redux, Java, PHP, JavaScript, Bootstrap, HTML, CSS;
- Desejável conhecimento de design, construção e consumo de API's;
- Desejável conhecimento de SQL e estrutura de banco de dados;
- Desejável o conhecimento de UI/UX.

## Contratação

CLT a combinar

## Nossa empresa

A Mazzatech é uma consultoria de TI que atua há 10 anos no mercado, buscando profissionais para atuar em grandes projetos.

## Como se candidatar

Por favor envie um email para rhmazza@mazza.tech com seu CV anexado - enviar no assunto: Vaga FullStack.

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/CLT
- regime/Outros
- regime/PJ

**Comment by igorsfreitas** [comment]
Enviado

**Comment by maiconrs95** [comment]
Enviado!!!

Meu curriculum: https://maiconrs95.github.io/me
