### ISSUE TITLE
[São Paulo] Dev Front End React.Js

### ISSUE THREAD

**Issue by EderMiola** [react-brasil/vagas#1991]
Dev Full Stack - Foco em Front End React.Js

## Descrição da vaga
Atuará no desenvolvimento de novas features e manutenção das já existentes em nosso sistema, passando por APIs, integrações com parceiros do setor financeiro e ferramentas internas. Deverá projetar e implementar recursos e componentes de backend. Trabalhará em sistemas altamente escaláveis que devem ser rápidos e seguros. Interagir com a equipe de produto para entender melhor os requisitos. Estudar e aprender novas tecnologias para melhorar nossos sistemas e processos.

## Localização
Remoto - São Paulo

## Benefícios
- Plano de saúde
- Férias Remuneradas

#### Diferenciais
- Horário Flexível
- Home Offce

## Requisitos
React.js
Metodologias ágeis
Terminal e Git

**Desejáveis:**
- conhecimentos em GraphQL

**Diferenciais:**
Arquitetura de micros serviços e Serverless
Nuvem AWS
Bancos de dados não-relacionais (DynamoDB)
Bancos de dados relacionais (MySQL)
TDD

## Contratação
PJ 

## Nossa empresa
Somos agentes de transformação no setor de serviços financeiros. 
Oferecemos soluções inovadoras de forma ágil, prático e segura.

## Como se candidatar
Por favor Clica nesse link: https://ewally.solides.jobs/vacancies/96640

## Labels
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 3k-6k

**Comment by mtheusvalle** [comment]
Opa, link está indo para uma vaga de Desenvolvedor Full Stack Node.Js Pl-Sr

**Comment by EderMiola** [comment]
Link da vaga está arrumado :)
