### ISSUE TITLE
[São Paulo] Desenvolvedor React Native

### ISSUE THREAD

**Issue by jgrossineto** [react-brasil/vagas#2]
## Descrição da vaga
Experiência na criação de apps com React Native para as plataformas Android e iOS. É preciso ter experiência com a adaptação do layout para diferentes resoluções e plataformas.

## Necessário
React Native, Javascript, ES6, CSS, FlexBox e boa lógica de programação.

## Desejável
Redux, APIs Rest, Firebase, Objective C/Java para o desenvolvimento de módulos nativos e Selenium.

## Local
Remoto ou Escritório, São Paulo - Vila Gertrudes (próximo ao shopping morumbi)

## Tipo de contratação
PJ. Freela de aproximadamente 3 semanas. 

## Candidaturas
jose.grossi@candowell.com

**Comment by nicholasess** [comment]
@jgrossineto a vaga ainda está em aberto?

**Comment by jgrossineto** [comment]
Bom dia @nicholasess . Está sim. 
Pode enviar seu CV e material que tiver disponível para jose.grossi@candowell.com

**Comment by nicholasess** [comment]
@jgrossineto eu estou organizando o repositório de vagas do react brasil, por isso a pergunta. Tem nível de exp (Junior, Pleno, Senior)?
