### ISSUE TITLE
[Remoto] React Native Junior/Senior para projeto inovador

### ISSUE THREAD

**Issue by hdoria** [react-brasil/vagas#206]
## Descrição da vaga
A Popcode é uma empresa especializada no desenvolvimento de aplicativos para iOS e Android. Recentemente passamos a utilizar react-native em todos os projetos. No momento, estamos com duas vagas para desenvolvedor react native para atuar em um projeto de leilão, de presença nacional.

## Local
Remoto

#### Diferenciais
* Homeoffice
* Flexibilidade de horarios
* 100% de autonomia
* Alta probabilidade de crescimento
* Projeto inovador em seu seguimento

## Requisitos
**Obrigatórios:**

* Experiência com React Native
* Experiência com Node.js
* Experiência com Java Script

## Contratação
PJ ou CLT

## Como se candidatar
Por favor envie um email para [hugo@popcode.com.br](mailto:hugo@popcode.com.br) com seu CV anexado - enviar no assunto: Vaga React Native GitHub

## Labels
* alocação/Remoto
* experiência/Junior
* experiência/Pleno
* experiência/Sênior
* regime/PJ

**Comment by raivieiraadriano92** [comment]
Opa, boa tarde, enviado :)

**Comment by italomlp** [comment]
Enviado!

**Comment by Claudio-code** [comment]
Curriculo enviado
