### ISSUE TITLE
[Rio de Janeiro] React Js Pleno/Senior na adopets

### ISSUE THREAD

**Issue by jhansonpk** [react-brasil/vagas#207]
## Descrição da vaga

Como Front-end web development na adopets, você participará no desenvolvimento do melhor sistema de adoção de animais no mundo, atualmente presente em todo o território dos Estados Unidos pelas plataformas iOS e Web. Você trabalhará ao lado de um time multicultural e também remoto, com o objetivo de salvar os mais de 2.3 milhões de pets sendo eutanasiados todos os anos nos EUA pela ineficiência dos abrigos e sistemas de adoção. Para isso, você vai precisar ter muita paixão e dedicação, sem medo de errar, aprender e fazer cada vez melhor.

## Local

Nos primeiros 4 meses será remoto, após no escritório em Niterói ou Centro do RJ. 

## Benefícios [após o periodo remoto]

* Vale Transporte
* Vale Refeiçao

#### Diferenciais

* Informal
* Horários flexíveis
* Aberta a novas idéias e sugestões

## Requisitos

**Obrigatórios:**
- ReactJS
- TypeScript
- ECMAScript 9
- Experiência com POO
- Código em Inglês

**Desejáveis:**
- Experiência com Git para versionamento de código
- Experiência com UI e UX
- Experiência com Interfaces customizadas
- Conhecimento aprofundado em sólidos princípios de programação
- Conhecimentos em otimização para performance de Front-end

## Contratação

PJ / MEI - Remoto nos primeiros meses, após será no escritório
Salário de $1.350 a $1.750 Dólares 

## Nossa empresa

A adopets é uma startup Estadunidense fundada por Brasileiros, em Boston, MA, que tem o objetivo de transformar/salvar a vida de milhões de animais e pessoas através da adoção eficiente e consciente. Somos ambiciosos e determinados a resolver um problema global através de uma tecnologia simples de usar e acessível, tanto para abrigos de animais quanto para adotantes. Atualmente estamos presentes apenas nos Estados Unidos, mas já planejamos estar no Brasil no primeiro semestre de 2019.

Fazemos parte da TechStars, uma importante aceleradora, estamos na sede de Boston no GSVLabs.

Somos atualmente um time multicultural, entre brasileiros, canadenses , indianos e estadunidenses, portanto, um domínio avançado de comunicação em inglês (leitura/escrita/conversação) é fundamental. Não buscamos ninguém perfeito, ou com o inglês perfeito, pois todos no time sempre temos muito a melhorar, mas é ideal que um boa comunicação seja possível de ser estabelecida para uma equipe forte e integrada.

## Como se candidatar

Por favor envie um email para andre@adopets.org com seu CV anexado - enviar no assunto: Vaga React JS

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by overdadeiro** [comment]
Dois pontos que eu gostaria de perguntar:

1- Por que tirar o benefício do trabalho remoto depois de 4 meses?
2- Empresa de Boston/MA, presente em todo o território Americano, pagando pra Dev um salário abaixo do salário mínimo de Boston, por que? Eu acho um sacanagem isso, se fosse contratar um americano pra trabalhar na sede ia ter que pagar no mínimo 60k+ dólares por ano pra uma vaga dessas, e quer oferecer 21k pra um brasileiro.

Minha intenção não é esculachar a vaga, o salário é relativamente razoável para um pleno (embora seja PJ), só queria expor mesmo essas 2 questões. O trabalho de vocês é algo que me identifico muito, mas quando vi o salário fiquei até triste. :(
