### ISSUE TITLE
[São Paulo] React Native Developer na Quanto

### ISSUE THREAD

**Issue by nic** [react-brasil/vagas#21]
## Descrição da vaga

Estamos procurando uma desenvolvedora ou desenvolvedor que esteja afim de criar tecnologia financeira para **mudar o jogo**.

## Local

Presencial, São Paulo - Vila Madalena (Próximo a estação Fradique Coutinho)

## Diferenciais

- No coração da Vila Madalena
- Escritório próprio
- Jardim com churrasqueira
- Faça seu próprio setup de máquina
- GitHub / Slack / Google Apps

## Requisitos

**Obrigatórios:**
- Mínimo 6 meses de experiência com React Native
- Mínimo 2 anos de experiência com desenvolvimento Android Nativo (Java, Kotlin ou NDK)
- Ser organizado, autodidata e detalhista
- Morar em São Paulo ou ter disponibilidade para mudança

**Desejáveis:**
- Experiência com desenvolvimento iOS Nativo (Objective-C ou Swift)
- Experiência com uso de GraphQL

**Diferenciais:**
- Full Stack Developer
- CI / CD
- Shell Script
- Experiência com criptografia assimétrica
- Experiência com NFC
- Experiência com hardware de criptografia
- Relay, Apollo, Recompose, Styled Components, Redux, Sagas, Redux Logics, Jest, Enzyme, Immutable, Storybook
- Projetos opensource

## Contratação
A combinar

## Nossa empresa
Estamos transformando o open banking no Brasil.
Somos uma plataforma que possibilita:
- Um único Internet Banking para todas as suas contas
- Fluxo de caixa automatizado através de uma API GraphQL
- Obter crédito sem ficar preenchendo vários formulários
- Mudar de banco com poucos cliques
- [Sua ideia aqui..]
- [Ideia de outras centenas de fintechs que ainda serão criadas..]

Saiba mais em: https://contaquanto.com.br

## Como se candidatar
Por favor envie um email para nic+vagareactnative@contaquanto.com.br com seu CV anexado com links para o que achar pertinente - enviar no assunto: Vaga React Native. Se você não for selecionado para entrevista, irei te responder mesmo assim. #respeitoEGratidaoAoSeuInteresse :)

## Labels
- alocação/Presencial
- experiência/Sênior
- regime/A-Combinar

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criar uma nova issue, com informações mais atualizadas caso a vaga ainda esteja aberta.
