### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack na prontoAP

### ISSUE THREAD

**Issue by Sergiofernandocoelho** [react-brasil/vagas#210]
[São Paulo] Desenvolvedor Full Stack na prontoAP

Você trabalhará com uma equipe de altíssimo nível técnico na construção de uma ambiciosa plataforma de decoração e obras residenciais 100% online. Trata-se de uma jornada incrível, com muitos desafios técnicos, café e grandes aprendizados. 
Esta vaga é para uma posição importante dentro do time de tecnologia da prontoAP. Sua responsabilidade será a de evoluir as plataformas existentes com as quais nossos clientes, parceiros e time interno fazem interface. Serão desafios de todos os tipos: arquitetura, performance, segurança, usabilidade, etc. 
Aqui o fundamental é saber trabalhar em grupo e em ambientes onde a operação é crítica. São milhares de clientes que nos proverão feedback para que possamos melhorar nossos produtos constantemente. 

Local

Escritório, São Paulo - Pinheiros

Pré-requisitos:
- Experiência de no mínimo de 3 anos com desenvolvimento de websites utilizando as tecnologias ReactJS, HTML, CSS 
e Javascript;
- Sólidos conhecimentos com utilização de grids para diagramação de conteúdo (como, por exemplo, o Bootstrap);
- Construção de websites responsivos para diversos tipos de device (desktop, celulares, tablets, etc.);
- Experiência com construção de APIs RESTFul utilizando Python e o framework Flask;
- Experiência com banco de dados MySQL;
Desejável/diferenciais:
- Conhecimentos nas tecnologias React Native;

Contratação

PJ a combinar

Como se candidatar

Por favor envie um email para scoelho@prontoap.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Full Stack

**Comment by julioxavierr** [comment]
Quais as labels?
