### ISSUE TITLE
React N- Brazil

### ISSUE THREAD

**Issue by BenTuring** [react-brasil/vagas#2113]
I´m Ben, Turing’s Recruiting Specialist, and I'm hiring remote React Native engineers through Turing.com for very important companies across the US (indeed, Coinbase, ) 
We offer USD payment salary, full Remote work, and being part of the most amazing & talented people across the world.

We are looking for the best devs with:
- Advance English
- Good skills using React Native (+3yrs)
- Full-time availability

Are you looking for a new opportunity? Let me know!

Have a great day : )

**Comment by MariaFF** [comment]
Hi Ben :) is it still available ? If yes, could we talk ?

**Comment by BenTuring** [comment]
Hey thanks for your reply!

We can schedule a quick call and I'll tell you more about this position at
Turing.

https://calendly.com/d/cd9-tcn-pqb/15-minute-meeting


Kind regards,

Ben
