### ISSUE TITLE
[REMOTO ou SP] - React/HTML/JavaScript - BillionRun e Fantasy Torcedores

### ISSUE THREAD

**Issue by gmenegatti** [react-brasil/vagas#212]
## Descrição da vaga

Estamos em busca de desenvolvedores front-end (React/HTML/JavaScript) de nível pleno ou sênior para trabalhar **remotamente** na Fábrica 18, empresa responsável pelos jogos fantasy BillionRun [1] e Fantasy Torcedores [2].

Por favor, caso tenha interesse, peço gentilmente que envie um email para gabriel@simbioseventures.com com seu CV ou LinkedIn **e sua atual remuneração**.

Qualquer dúvida, estamos à inteira disposição.

## Local

Remoto ou Escritório São Paulo na Av. Faria Lima.

## Benefícios

Nenhum.

## Requisitos

Profundo conhecimento de React, HTML e JavaScript

## Contratação

CLT ou PJ.

## Nossa empresa

[1] - http://www.billionrun.com.br/
[2] - http://fantasy.torcedores.com

## Como se candidatar

Por favor, caso tenha interesse, peço gentilmente que envie um email para gabriel@simbioseventures.com com seu CV ou LinkedIn **e sua atual remuneração**.

## Labels

- CLT
- PJ
- Pleno
- Remoto
- Sênior

**Comment by diegohaz** [comment]
> **e sua atual remuneração**

Eu entendo que isso é confortável pra quem emprega, mas não é legal pra quem vai se candidatar. 

Vou deixar aqui algumas opiniões que eu vejo por aí (tem mais nos links):

> Anchoring salary negotiations around what someone was paid previously, so you can get away with being as little as possible, is a deceptive, abusive, and corrosive practice. A culture of fair, equal pay for equal experience and responsibilities is worth far more.
>
> — https://twitter.com/dhh/status/1093533527415681024

> Let's not forget that its also lazy. Co's ask expectations so they can decide to move you forward or not. Are you going to be within what we want to pay for this work or not. Are you worth our time, or not? Instead, build a relationship, create teams and roles that are inspiring.
>
> — https://twitter.com/pkingdesign/status/1093622003183935488

**Comment by OtacilioN** [comment]
@gmenegatti mas essa vaga não é pra trabalhar 10 horas+ por dia, incluindo fins de semanas, não né?

**Comment by gmenegatti** [comment]
Essa vaga não, pois é para uma outra empresa.

**Comment by OtacilioN** [comment]
Certo.
