### ISSUE TITLE
[Remoto] Front-end React na @Nave.rs

### ISSUE THREAD

**Issue by BrunaSouzaPaes** [react-brasil/vagas#2120]
## Descrição da vaga

A Nave.rs está procurando uma pessoa com perfil de nível júnior a pleno, que tenha experiência na área de desenvolvimento Front-end, experiência com clientes e projetos.
Como developer para a área de Front-end, você irá utilizar linguagem React . Na empresa trabalhamos com a metodologia ágil Scrum, sendo assim, temos cerimônias como planning, weekly e retro. O seu dia a dia de trabalho irá basear-se nas cerimônias e no projeto que você irá entrar.

## Local

Remoto 

## Benefícios

- Assistências médica e odontológica;
- Auxilio psicológico;
- VR de R$ 24,10/dia
- Auxilio Educação (acesso a plataformas de cursos)
- Horário flexível e possibilidade de home office.

#### Diferenciais

- Hierarquia Horizontal
- Plano de carreira estruturado

## Requisitos

**Obrigatórios:**
- HTML
- CSS
- JavaScript
- Experiência no desenvolvimento de aplicações web utilizando React;
- Experiência com projetos
- Boa comunicação
- Bom gerenciamento de tempo

**Diferenciais:**
- Experiência com projeto
- Experiência com clientes

## Contratação

CLT + Benefícios

## Nossa empresa

Trabalhar com a nave.rs significa que você conhece e colabora com as pessoas que realmente fazem o trabalho. Unimos tecnologia e criatividade para criar soluções digitais efetivas que se tornam memoráveis e impactam positivamente a vida das pessoas.
Nossa missão é ajudar empresas a entender antes de agir, a agir com precisão e a lucrar a partir de mudanças.

## Como se candidatar

Inscreva-se através do link: [link aqui](https://nave-team.gupy.io/jobs/1346873)

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ CLT
- 💰 1k-3k

**Comment by raf2019** [comment]
vaga encerrada
