### ISSUE TITLE
[REMOTE] Tech Lead React @JungSoft 

### ISSUE THREAD

**Issue by izabellarch** [react-brasil/vagas#2124]
**Our work environment**
**No trivial work**
We continuously push ourselves to improve by taking on challenging projects, applying emerging technologies and testing their boundaries.

**Define the cutting edge**
We’re at the forefront of software engineering and digital product design. We contribute to them in open source and help define the best practices of software development.

**Always flexible**
We want everyone to grow and, wherever possible, our team members can switch internal projects to those that could potentially contribute further to their development.

**The company**
We are a startup based in Florianópolis and Berlin, whose focus is to be a tech partner for companies with highly demanding projects around the world. With a focus on the long-term, we have an end-to-end ownership, from building the tech foundation with our partners, to planning new projects, executing them, deploying, analyzing and iterating.

**The Position**
We are looking for a  Frontend Lead Engineer to help us scale our team, increase the overall quality of our deliverables and boost the team's performance. We expect this to be achieved through great technical decisions on a daily basis combined with insightful a leadership style.

**You will mainly work with the following technologies**
Typescript and Javascript
React and React Native
GraphQL
Automated testing with React Testing Library, Jest and Cypress

**Your responsibilities here**
Architect and plan the structure in and around the frontend
Choose the technologies, frameworks and libraries to be used collaboratively
Help defining company wide standards and best practices
Code reviews
Mentor and lead other developers
Help other engineers in the team to grow, both technically and as people
Build beautiful UIs that bring unique and efficient user experiences
Follow high-fidelity layouts, but also navigate and iterate on less clear requirements during discovery phases
Take ownership

**Required skillset:**
Experience leading successful projects
React
Typescript and Javascript
GraphQL (mainly using Apollo Client)
Fluency with Git
To be able to work remotely effectively
Experience with planning and requirements gathering
Self management and organisation

**Bonus:**
Working proficiency in English
Testing frameworks with React
Knowledge in agile methodologies 
Experience working with open-source projects
Experience with UI/UX and requirements iteration

## Como se candidatar
(https://jungsoft-io.breezy.hr/preview)

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👶 Estágio
- 👴 Sênior
- ⚖️ PJ
- 💰 15k+

**Comment by EternalQuasar0206** [comment]
Se a vaga é de Tech Lead por que está com tag de estágio?
