### ISSUE TITLE
[Curitiba / Remoto] React.js / React Native Developer na BRQ

### ISSUE THREAD

**Issue by rlecheta** [react-brasil/vagas#2139]
## Descrição da vaga

Projeto React e React Native para cliente do mercado de Agro Negócios. É uma aplicação muito grande de compra e venda de grãos (milho, soja, etc) que conecta o vendedor (produtor agropecuário) com os compradores.

## Local

Remoto. 

## Benefícios

- Plano de saúde
- Seguro de vida
- VT/VR
- Gympass
- Telemedicina / Nutricionista
- Curso de inglês gratuito
- ...

#### Diferenciais

- Ótimo plano de carreira
- Empresa em pleno crescimento e com oportunidades internacionais
- ...

## Requisitos

**Obrigatórios:**
- 2/3 anos experiencia ou React ou React Native.

**Desejáveis:**
- conhecimentos em react native e emuladores Android/iOS
- React hooks
- Publicação de apps nas lojas Google e Apple

**Diferenciais:**
- Conhecimentos em Redux

## Contratação

CLT

## Nossa empresa

BRQ: https://www.brq.com

## Como se candidatar

Por favor envie um email para rlecheta@brq.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k

**Comment by devartwa** [comment]
Enviado!
