### ISSUE TITLE
[Remoto] React Native na Rocketlab

### ISSUE THREAD

**Issue by nativedone** [react-brasil/vagas#214]
![rn vaga](https://user-images.githubusercontent.com/20998754/52627132-dae20480-2f08-11e9-85ae-e7a18f942637.png)

## Descrição da vaga

Oi pessoal,

Tem 2 vagas do meu time aqui de Sydney/AU:

Vanilla react native projects, TouchID , Google maps  and push notifications using OneSignal.

Ingles: tem que falar pelo menos o suficiente pra se comunicar. Pode falar cometendo erros de gramatica, etc... mas tem que falar.

## Local

100% Remoto 

## Benefícios

* Flexibilidade de horarios
* Pagamento em $AUD
* Contrato: `full-time`, `part-time` ou `freelance`

## Requisitos

**Obrigatórios:**
- Vanilla react native projects
- TouchID
- Google maps
- Push notifications using OneSignal.

**Desejáveis:**
- GraphQL

## Contratação

A combinar. Nossas faixas salariais sao de entranda. Como o processo de entrada eh bem simples, os valores podem ajustados de acordo com o desempenho/experiencia (comprovada durante seu trabalho dentro da nossa empresa).  

## Nossa empresa

https://www.rocketlab.com.au/ - mobile and web apps

## Como se candidatar

* Compatilhar links de aplicativos na loja e/ou codigos. (Me envie uma messagem privada em https://twitter.com/nativedone)
* Teste agendado de 50 min
* Contratacao ou feedback em ate 2 dias

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- remuneração/3k-5k
- remuneração/5k-10k

**Comment by nicholasess** [comment]
@nativedone faltou colocar a faixa salarial das vagas, pode ser convertido e estimado o valor

**Comment by nativedone** [comment]
> @nativedone faltou colocar a faixa salarial das vagas, pode ser convertido e estimado o valor

Descricao atualizada @nicholasess

**Comment by rodriigovieira** [comment]
Alguma maneira de entrar em contato além do Twitter?

**Comment by nativedone** [comment]
> Alguma maneira de entrar em contato além do Twitter?

Slack do React-brazil. Mas, a thread lah some com o tempo.
