### ISSUE TITLE
[Remoto] Frontend ReactJS Pleno ou Sênior - Banco Digital forsellers.com.br

### ISSUE THREAD

**Issue by marcelosv** [react-brasil/vagas#2152]
## Descrição da vaga

A vaga é de ReactJS e participar do nosso time de desenvolvimento.

## Local

Remoto ou Escritório, São Paulo - Vila Madalena

## Benefícios

- R$ 1300,00
- ...

#### Diferenciais

- Trabalho remoto
- Horário flexível
- Liberdade
- ...

## Requisitos

**Obrigatórios:**
- Conhecimento em React

## Contratação

Cooperativa a combinar

## Nossa empresa

 Sellers
O BANCO DIGITAL DO VENDEDOR 

Muito prazer, somos a Sellers!
Para nós as relações humanas são o motor das organizações. É por isso que aqui, nós acreditamos nessa força/engrenagem para potencializar negócios.
Somos o Branco Digital do Vendedor.
Nascemos para simplificar todo o processo de gestão, comunicação e distribuição de remunerações variáveis.
Nosso compromisso é potencializar suas vendas, de forma simples e ágil.
Através de uma plataforma digital completa, solucionamos todo o processo de incentivo de vendas, desde a comunicação em massa e acompanhamento de resultados em tempo real, até a distribuição de remunerações variáveis. Tudo em único lugar, de forma fácil e escalável.

## Como se candidatar

Por favor envie um email para marcelo@forsellers.com.br com seu CV anexado - enviar no assunto: [Remoto] Frontend ReactJS Pleno ou Sênior

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 10k-15k
- 💰 15k+

**Comment by AlissonBlaas** [comment]
enviado!
