### ISSUE TITLE
[BRASIL TODO] Vagas de Full Stack em grandes empresas na Plataforma GeekHunter

### ISSUE THREAD

**Issue by penelopevitoria** [react-brasil/vagas#216]
Boa tarde, gente :)

Tudo certinho?

Estou aqui hoje em nome da GeekHunter, que é uma plataforma de recrutamento inteligente de profissionais de TI. 

Estamos com uma quantidade consideráveis de vagas para Desenvolvedores React, nas cidades-polos do país. Nosso trabalho é conectar empresas fod#%W$ a profissionais fod@#%#.

Você pode ser Júnior, Pleno ou Sênior e trabalhar nas principais capitais do país - e até da Europa. E o melhor, em empresas incríveis!

Também existe a possibilidade de trabalhar remoto, presencial, PJ ou CLT. Uma prévia de algumas empresas que estão na plataforma:

* Amazon
* Mercado Livre
* Peixe Urbano
* Hostgator
* GuiaBolso
* Contabilizei
* Aurum
* Blueticket

Cadastrem-se aqui: http://bit.ly/2X3GmWL

Ah, se tiverem dúvidas, falem comigo. Um abraço!

**Comment by brunooomelo** [comment]
Eu acredito que se a GeekHunter postar algumas vagas aqui e redirecionar para o site deles para cadastro, tudo certo. mas cadastrar pra ver as vagas lá

**Comment by fdaciuk** [comment]
@nic

**Comment by sibelius** [comment]
Por favor, @penelopevitoria postar vagas individualmente aqui com as devidas labels
