### ISSUE TITLE
[Remoto] Sr. React Frontend Engineer @ Vigil - United Kingdom

### ISSUE THREAD

**Issue by renato-obst** [react-brasil/vagas#2160]
## Descrição da vaga

Esta é uma oportunidade rara que reúne:

* Trabalho 100% remoto
* Projeto internacional / English-First (Reino Unido)
* Time de alto nível técnico
* Ótimo ambiente de trabalho, que preza pelo equilibrio Vida / Trabalho
* Ótimo salário fixado em Euros e no modelo PJ - Faixa de 4.5K a 5.5k de Euros
* Contrato de longo termo

Estamos procurando Senior React Frontend Engineer que possua interesse nesta oportunidade e esteja qualificado(a) para assumir a responsabilidade de:

* Fazer parte de um time de alto nível técnico trabalhando em parceria com uma das maiores empresas de tecnologia no setor de Game & Gambling do mundo.
* Contribuir com a criação de um produto global altamente estratégico
* Liderar o processo de prova de conceito e definição arquitetural da principal aplicação frontend do produto
* Colocar a mão na massa e contribuir com a execução da aplicação planejada
* Definir e implementar toda a pipeline de CI/CD da aplicação, incluindo deploy automatizado para todos os ambientes

A Vigil é uma consultoria de tecnologia europeia e com presença no Brasil e que atende exclusivamente clientes da Europa em projetos estratégicos onde um alto nível técnico é necessário. 

## Local

100% Remoto - Work anywhere

#### Diferenciais

- Modelo PJ com 20 dias úteis de férias remuneradas
- Feriados do Brasil
- Salário fixo em Euro

## Requisitos

**Obrigatórios:**

- 4+ years of web application development experience
- 3+ years of ReactJS - Proven end to end experience
- Strong Javascript knowledge
- Experience in developing enterprise web applications consuming internal APIs
- Experience with Agile and leading agile teams
- Experience in frontend automated tests
- Strong English communication skills - Reading, Listening and Speaking

**Desejáveis:**
- GraphQL
- Cypress
- GO CD
- AWS

## Contratação

PJ 
Faixa salarial - 4.5K a 5.5k de Euros

## Nossa Empresa

A Vigil é uma consultoria de tecnologia europeia e com presença no Brasil e que atende exclusivamente clientes da Europa em projetos estratégicos onde um alto nível técnico é necessário.

## Como se candidatar

É só aplicar para a oportuniade aqui: https://www.vigil.global/frontend-engineer-react

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 15k+

**Comment by AlissonBlaas** [comment]
done!

**Comment by Adonis11300522** [comment]
Hello, my name is Alex Dean based in Toronto. I have a goal to work as a remote frontend developer for a reputed tech company. My background in bachelor’s degree in Computer Science and bachelor’s degree in Business Administration  taught  me how to work with programming languages. Diplomas in Web Development and Web designing taught me how to work with React, Html , CSS , Javascript , Php and database. It would be great if you could help me with any remote opportunity! Thanks

**Comment by Adonis11300522** [comment]
Hello, my name is Alex Dean based in Toronto. I have a goal to work as a remote frontend developer for a reputed tech company. My background in bachelor’s degree in Computer Science and bachelor’s degree in Business Administration  taught  me how to work with programming languages. Diplomas in Web Development and Web designing taught me how to work with React, Html , CSS , Javascript , Php and database. It would be great if you could help me with any remote opportunity! Thank
[Alex_Dean_CV.pdf](https://github.com/react-brasil/vagas/files/7762189/Alex_Dean_CV.pdf)
s
