### ISSUE TITLE
[REMOTO] React Jr Developer na Kolabs

### ISSUE THREAD

**Issue by MatheusKemer** [react-brasil/vagas#2191]
## Descrição da vaga

Vaga aberta para desenvolvedores React com experiência em Styled Components. Nossa empresa trabalha com desenvolvimento de produtos nacionais e internacionais nas áreas da educação, mercado financeiro, gestão e entretenimento.

Buscamos um dev junior que já possui alguma experiência na stack js React e com experiência em HTML e CSS. Mesmo que elas sejam acadêmicas. 

O foco do trabalho é no desenvolvimento de layouts e componentes totalmente responsivos criados pela nossa equipe de design.

Nossa horário é totalmente flexível e aceitamos candidaturas de devs com 120 horas mensais (6 horas diárias) ou até menos! Mande um e-mail pra gente e vamos conversar sobre isso.
## Local

100% remoto

## Requisitos

- Conhecimento em GIT
- Conhecimento em HTML e CSS
- Conhecimento em React Js
- Conhecimento em Styled Component

## Contratação

PJ a combinar

## Nossa empresa

Somos um laboratório colaborativo de tecnologia.. Nossos projetos contém tecnologia de ponta e possuem todos os tipos de inovações para uma entrega única e diferente.

## Como se candidatar

Por favor envie um email para matheus@kolabs.com.br com seu CV anexado e **pretensão salarial** (negociável) - enviar no assunto: Vaga React Jr.

## Labels

- 🏢 Flexível
- 👶 Estágio
- 👦 Júnior
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ PJ
- 💰 1k-3k

**Comment by Elton-Freitas-X** [comment]
Ainda disponivel ??
