### ISSUE TITLE
[São Paulo] Dev Rails, REACT, MySQL e ElasticSearch.

### ISSUE THREAD

**Issue by ArthurFreitasCampos** [react-brasil/vagas#2193]
Oi, pessoal, tudo bem? 
Eu sou o Arthur da TechNation. Atualmente estamos recrutando um desenvolvedor de Rails, REACT, MySQL e ElasticSearch. 
Aqui há mais informações sobre a empresa e a vaga: 

[bit.ly/devSr](https://bit.ly/devSr)

Se alguém tiver interesse, é só me mandar mensagem ou comentar aqui no post que entro em contato com os próximos passos . Caso prefira, aqui está minhas outras formas de contato 🤩
[https://flow.page/art0](https://flow.page/art0)

Muito obrigada! Abraços 😄

P.S.: A TechNation é uma startup que tem como missão contribuir com o recrutamento de programadores, fazemos isso auxiliando empresas, assim como atuando diretamente com programadores (via uma comunidade, uma plataforma de educação e testes avaliativos). 👩‍💻👨‍💻🚀

## Local

Remoto e um mês presencial de integração (Butantã - São Paulo)

## Requisitos

- Pessoa Jurídica com disponibilidade de integração presencial em torno de 1 a 30 dias em São Paulo, na região do Butantã e o período restante na modalidade remota. 
- Ter interesse e domínio nas tecnologias de Rails, REACT, MySQL e ElasticSearch para extração de dados na Internet.
-Alguém para realizar um projeto de 12 meses com 15 dias de férias remuneradas, trabalhando em horário comercial  

## Labels

- 🏢 Flexível
- 🏢 Presencial 
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k

**Comment by LeAlencar** [comment]
Boa tarde, os links estão quebrados.

**Comment by moabebatista** [comment]
Boa tarde, tenho interesse!! cliquei no link mas tá quebrado. Caso veja a minha mensagem pode entrar em contato!!

**Comment by ArthurFreitasCampos** [comment]
Olá, peço desculpas pelo inconveniente. Segue os links
[https://bit.ly/devSr](https://bit.ly/devSr) 

[Meus Contatos](https://flow.page/art0)
