### ISSUE TITLE
[Rio de Janeiro-RJ] Desenvolvedor Web JR (ReactJS) na DOT.LIB

### ISSUE THREAD

**Issue by vlamirsanto** [react-brasil/vagas#221]
## Descrição da vaga

Desenvolver sites e sistemas responsivos com ReactJS.

## Local

Barra da Tijuca, RJ

## Benefícios

- Vale transporte
- Plano de saúde
- Plano odontológico
- Vale Refeição ou Vale Alimentação

#### Diferenciais

- Equipe unida e divertida.
- Cafeteira sempre cheia :P
- O gerente às vezes paga o almoço.
- Emendas em feriados nacionais.

## Requisitos

**Obrigatórios:**
- 1 ano de experiência em desenvolvimento de sites e sistemas responsivos com ReactJS.
- Controle de versões (GIT).

**Diferenciais:**
- Frameworks PHP: Laravel ou Codeigniter;
- Conhecimentos em Linux.

## Contratação

Salário a combinar.

## Nossa empresa

A Dot.Lib distribui conteúdo online científico e acadêmico a centenas de instituições espalhadas pela América Latina. Temos como parceiras algumas das principais editoras científicas nacionais e internacionais. Além de prover conteúdo, criamos soluções que atendem às necessidades de nossos clientes e editoras.

## Como se candidatar

Por favor envie um email para curriculo@dotlib.com.br com seu CV anexado. Enviar no assunto: Vaga Desenvolvedor Web Jr.

## Labels

- alocação/Presencial
- experiência/Júnior
- regime/A-Combinar
- regime/CLT

**Comment by diegohaz** [comment]
@vlamirsanto Pode colocar a faixa salarial nas labels, por favor?

**Comment by AzevedoDev** [comment]
enviado

**Comment by raivieiraadriano92** [comment]
Boa noite, alguma possibilidade de trabalho remoto?

**Comment by vlamirsanto** [comment]
@raivieiraadriano92 infelizmente não. A vaga é presencial.
