### ISSUE TITLE
[Remoto ou São Paulo] DevOps na FindMe

### ISSUE THREAD

**Issue by findmesp** [react-brasil/vagas#2219]
## Sobre a FindMe

A FindMe está revolucionando o mercado de segurança e facilities do Brasil, através da transformação digital de suas operações.

Nessa revolução, acreditamos que um time de desenvolvimento excepcional é fundamental para construir a melhor plataforma de gestão operacional do mercado de segurança e facilities. Dessa forma, estamos buscando um DevOps.

## Descrição da vaga

Você fará parte do squad Produto & Tecnologia, o time responsável pelos produtos e todo apoio tecnológico necessário da FindMe, composto por desenvolvedores full cycle, P.M., P.O. e UX/UI Designer.

Nele você será responsável pelo planejamento, construção, operação e manutenção da infraestrutura dos nossos produtos, além de ajudar o time a ser cada vez mais eficiente, eficaz e inteligente.

Nós acreditamos no aprendizado contínuo e juntos traçaremos um plano de desenvolvimento individual (PDI) para que você possa evoluir cada vez mais suas habilidades técnicas, tornando-se um Engenheiro com maior senioridade, capaz de gerenciar a construção e operação de produtos revolucionários.

## Requisitos

**Essenciais:**

- Experiência em configuração e operação de serviços em Cloud Providers (AWS e/ou Google Cloud);
- Experiência com CI/CD e Git;
- Conhecimento em arquitetura de softwares e servidores;
- Conhecimento em Cloud, Microsserviços e Kubernetes;
- Know-how em performance, segurança e monitoramento.

**Desejáveis:**

- Conhecimento em Métodos ágeis;
- Experiência em desafios semelhantes.

## Local
Remoto ou Escritório, São Paulo - Av. Paulista

## Contratação
PJ

## Como se candidatar?
Candidate-se agora pelo link: https://trampos.co/oportunidades/724968-devops

## Labels
👦 Júnior
👨 Pleno
🏢 Flexível
⚖️ PJ
💰 6k-7k

## Mais informações
Para mais informações e outras oportunidades, acesse nossa página de carreiras: https://findme-tecnologia.trampos.co/

**Comment by nicholasess** [comment]
@findmesp infelizmente devOps não tem relação com React, por isso vou fechar

abs
