### ISSUE TITLE
[Remoto] Fullstack Developer React.js/Node.js na Robô Laura

### ISSUE THREAD

**Issue by Startec-Jobs** [react-brasil/vagas#2236]
## Descrição da vaga

A Laura oferece soluções de inteligência artificial com o objetivo de democratizar a saúde por meio da tecnologia e gerar impacto social positivo em escala, acompanhando toda jornada do paciente.  

## Local

Remoto 

## Benefícios

- Descanso remunerado
- Bônus anual de 1 salário
- Gympass
- Laura Care
- Horário Flexível (porém não faz sentido alguém que queira dois empregos)

## Requisitos

**Obrigatórios:**
- 2 anos de experiência ou mais como desenvolvedor
- Experiência com Node.js e React.js
- Padrão de API (RESTful)
- Banco de dados não relacionais e relacionais 

**Desejáveis:**
- conhecimentos em GraphQL
- Arquitetura de Microserviços
- Conhecimento em WebSockets
- Conhecimento em TypeScript

## Contratação

PJ 5k - 6k (podendo chegar até 7,8k com o benefício anual que pode ser dividido mensalmente)

## Nossa empresa

A Laura oferece soluções de inteligência artificial com o objetivo de democratizar a saúde por meio da tecnologia e gerar impacto social positivo em escala, acompanhando toda jornada do paciente.  

Nosso primeiro produto, a Robô Laura, é implantado em instituições de saúde para identificação antecipada dos riscos de deterioração clínica. Por meio de inteligência artificial e tecnologia cognitiva, faz a priorização de atendimento em instituições de saúde, assim como o gerenciamento de dados da rotina hospitalar, emitindo alertas para a equipe assistencial. 

Ativa desde 2016, a Robô já analisou mais de 8,6 milhões de atendimentos, reduziu em 25% a taxa de mortalidade hospitalar e ajudou a salvar cerca de 24 mil vidas. Já o Pronto Atendimento Digital, lançado durante a pandemia da Covid-19, atua como um instrumento de monitoramento digital inteligente que auxilia instituições de saúde e o poder público a operacionalizar o atendimento virtual dos pacientes para várias linhas de cuidado.

Se você busca trabalhar em um local com cultura totalmente horizontal, que valoriza seus colaboradores para que todo mundo cresça junto programando com amor e responsabilidade, achou o lugar certo! Vem crescer com a gente?!

## Como se candidatar

Inscrições no link: https://app.startecjobs.com/vaga/5cc9f3bb-da88-4620-bc63-15bbd018bcb9

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-7,5k

**Comment by Fabricio-Joaquim** [comment]
a vaga é para junior ou para pleno?
