### ISSUE TITLE
[Belo Horizonte] Mobile Manager (React Native) - NUVEM SHOP / TIENDA NUBE

### ISSUE THREAD

**Issue by fhott** [react-brasil/vagas#224]
### O que fazemos no time de Produto?

Nós temos o desafio de oferecer um excelente produto para os nossos clientes! Estamos constantemente melhorando features que já oferecemos e implementando novas. Temos também o desafio de oferecer a melhor experiência para empreendedores e compradores, além de assegurar uma infraestrutura estável e solução de todos os problemas que possam surgir.

Você estará trabalhando em um time 100% autônomo, focado em conquistar seus objetivos. Além disso, seu trabalho terá impacto direto em nosso crescimento.

### O que fazemos no time de Mobile?

Trabalhamos em conjunto com o time de Web para oferecer ao nosso cliente lojista uma experiência de gestão do negócio que seja a mesma independentemente do device que utilize. Estamos fazendo um redesign de nosso aplicativo para React Native com objetivo de compartilhar o código não somente entre iOS e Android, mas também entre Web e Mobile.

### Quais serão suas responsabilidades?

Ser a referência em desenvolvimento mobile dentro do time da Nuvem Shop! Nosso manager terá atividades de desenvolvimento também, assim irá contribuir tecnicamente com o nosso desafio.
As atividades do Mobile Manager terão uma divisão de 50/50 entre tarefas de gerenciamento de pessoas e tarefas de contribuição individual (desenvolvimento).
Assegurar a produtividade do nosso time e que ele tenha as pessoas certas para realizar o trabalho, acompanhando a performance de todos;
Utilizar o feedback como ferramenta para o crescimento pessoal e profissional, tanto recebendo quanto oferecendo feedbacks para os colaboradores;
Identificar pontos de melhorias nos processos do time, nas metodologias e nas ferramentas utilizadas;
Sair da sua zona de conforto e amar aprender novas coisas;
Ter a flexibilidade de trabalhar em diferentes projetos com pessoas diferentes e cuidar minuciosamente da geração de resultados e impactos;
Recrutar, selecionar, fazer o onboarding e desenvolver nossa equipe mobile.

### O que esperamos de você?

Estar disponível para passar e receber feedbacks do seu time;
Compreender seus objetivos e metas dentro da empresa;
Ter uma comunicação assertiva para transmitir com clareza visão, planos e objetivos;
Garantir entrosamento dos liderados, desenvolvimento da equipe e senso de pertencimento;

## Local

Remoto ou Escritório (Belo Horizonte ou willing to relocate)

#### Benefícios

- A possibilidade de trabalhar com excelentes profissionais, aprender e se desenvolver ao máximo na Nuvem Shop - compartilhamos um ambiente enriquecedor e desafiador;
- Temos um ambiente de trabalho dinâmico, com equipes multidisciplinares que tomam suas próprias decisões para criar um grande impacto;
- A oportunidade de aprender sobre a cultura de startups e o ecossistema empreendedor na América Latina;
- Flexibilidade de horário, já que nos concentramos em alcançar grandes resultados, não em cumprir um horário de trabalho fixo;
- Temos como ferramenta a possibilidade de variar o local de trabalho de acordo com as demandas, já que não existe somente um lugar para fazer um excelente trabalho;
- Aulas de espanhol;
- Plano de saúde e odontológico Bradesco;
0 Seguro de vida;
- VT (ou VC) + VR (ou VA);

## Requisitos

*É essencial*:

Ser um desenvolvedor fantástico - habilidades acima da média em codificação, assim como experiências de sucesso em projetos de desenvolvimento;
Conhecimento consolidado em melhores práticas de desenvolvimento Mobile;
Excelente comunicação oral e escrita;
Excelente capacidade de análise e foco em resultados;
Conhecimento de metodologias ágeis;

*Será um diferencial*:

Conhecimento em Javascript;
Experiência anterior com React Native;
Experiência anterior em startups e com o ecossistema de inovação;
Experiência em liderança, coaching, mentoria de times de desenvolvimento de software e entregas destes projetos.

## Contratação

CLT

## Como se candidatar

Por favor, se aplique no link: https://tiendanube-nuvemshop.workable.com/j/C74B7B110A

• alocação/Flexível
• alocação/Remoto
• experiência/Sênior
• regime/CLT
• remuneração/10k-15k

**Comment by julioxavierr** [comment]
Favor adicionar faixa salarial

**Comment by fhott** [comment]
> Favor adicionar faixa salarial

Feito.
