### ISSUE TITLE
[100% Remoto] Frontend Developer React.js Pleno/ Sênior @Redspark

### ISSUE THREAD

**Issue by MonicaRodrigues19** [react-brasil/vagas#2284]
**Descrição da vaga**

Estamos com diversas oportunidades para Frontend Developer de níveis Pleno e Sênior

**Local de trabalho**
100% Remoto

**Requisitos da vaga**
Framework React.js
Conhecimentos em javascript ES6/ES7, HTML5, CSS3, 
PRÉ PROCESSADORES (SASS)
SPA, DESIGN RESPONSIVO WEB
NPM, GULP, WEBPACK
Styled-components 

**Forma de contratação**
CLT

**Benefícios da empresa**
Cartão de Benefícios Flexíveis Caju (VA/VR)
Assistência Médica e Odontológica Bradesco
Convênio SESC
Convênio FIAP
Convênio Udemy
Ajuda de custo para Inglês de até R$189,00/ mês
Auxilio Creche para filhos até 5 anos
Day Off
100% Home office flexível (Mesmo após pandemia)

**Range Salarial**
Estamos trabalhando com pretensão

**Sobre a empresa**
A Redspark é uma empresa que a 15 anos cria experiências em Produtos Digitais alinhando tecnologia e design.

Com cases de projetos em empresas como Hospital Albert Einsten, Sesc, Claro, Banco Mercedes Benz. Buscamos sempre a inovação com a perspectiva de construir soluções que sejam aderentes aos negócios e principalmente desejável para as pessoas.

**Como se candidatar**
Envie seu CV para o e-mail: pessoas@redspark.io com o assunto: Vaga Frontend React

**Tempo médio de feedbacks**
Costumamos enviar feedbacks em até 3 dias (úteis) após cada processo.

**Labels**
CLT
Pleno
Sênior
Remoto

**Comment by lucasf10** [comment]
Boa noite. Vocês aceitam part-time?

**Comment by JeanGrijp** [comment]
Boa noite, enviei meu CV ;)

**Comment by MonicaRodrigues19** [comment]
> Boa noite. Vocês aceitam part-time?

Olá Lucas

As oportunidades são full time
Vem conversar com a [gente](https://abre.ai/areadepessoasredspark)
