### ISSUE TITLE
[Joinville / SC] Front-End Developer na NG

### ISSUE THREAD

**Issue by vitorebatista** [react-brasil/vagas#229]
## Descrição da vaga
Buscamos um **Front-End Developer** para se juntar ao nosso time. Você irá participar do planejamento, desenvolvimento e implementação de novas funcionalidades em nossa plataforma. Temos um grande caminho pela frente e você terá bastante liberdade para trabalhar com **React, React Native e Typescript** no desenvolvimento de aplicações em um ambiente que valoriza as boas práticas de programação (ex. testes automatizados, unitários, code review, etc) e metodologias de desenvolvimento ágil.

## Local
[Av. Santos Dumont, nº 935, 3º Andar - Santo Antônio - Joinville/SC](https://goo.gl/maps/f5mLxtRkd892)

## Benefícios
* Vale alimentação ou refeição
* Vale transporte ou vale combustível
* Plano de saúde
* Plano odontológico
* PLR (Participação nos Lucros e Resultados)

**Diferenciais**

* Ambiente extremamente propício à aprendizagem;
* Liberdade para sugerir novas tecnologias e melhorar o processo de desenvolvimento da equipe;
* Mesa de sinuca para jogar nos intervalos e almoço;
* Flexibilida de 1 - 2 horas para horário de almoço;
* Café + bolachas/biscoitos + frutas todos os dias;
* Microondas para esquentar seu almoço e lanches.

## Requisitos
**Obrigatórios:**

* 1+ anos de experiência de mercado;
* Ter autonomia e pró-atividade;
* Conhecimento de React;
* Conhecimentos em HTML, CSS e Javascript;
* Experiência anterior com API's RESTful com resposta em JSON;
* Experiência com Git para versionamento de código;
* Inglês técnico (👀  stackoverflow);
* Morar em Joinville ou ter disponibilidade para se mudar para a cidade;

**Desejáveis**
* Conhecimento GraphQL e/ou Redux;
* Familiaridade com desenvolvimento ágil;
* Ser autodidata;
* Ter espírito empreendedor;
* Gostar de aprender e testar conceitos de UX.

**Diferenciais:**

* GitHub ativo;
* Functional programming (❤️ Ramda);
* Conhecimento de CLI, bundlers e automações de front-end;
* Banco de dados não relacional (MongoDB) e/ou relacional (PostgreSQL);
* Conhecimento técnico e prático em memes!

## Contratação
CLT a combinar

## Nossa empresa
A [NG Informática](www.ngi.com.br) é responsável pelos módulos de Manutenção de Ativos (SIGAMNT), Medicina e Segurança no Trabalho (SIGAMDT) e Gestão Ambiental (SIGASGA) do ERP Protheus (TOTVS). Também possuímos as plataformas de gestão de alertas chamado [Rung](https://www.rung.com.br) e o SAAS para gestão de manutenção chamado [Keepfy](https://www.keepfy.com).

**O que usamos:**

* GIT + Scrum + Kanbam + TFS
* React + GraphQL + Apollo + React Native + Typescript
* Jenkins
* GitHub (:heart: open source)
* Slack

## Como se candidatar
Por favor, envie um email para [curriculo@ngi.com.br](mailto:curriculo@ngi.com.br) com seu CV anexado e link do Github com o assunto: Vaga Front-End Developer - Github/React Brasil.

## Labels
* CLT
* Júnior
* Pleno
* Presencial
* React
* GraphQL
* React Native
* Typescript

**Comment by raivieiraadriano92** [comment]
Boa tarde, alguma possibilidade de trabalho remoto?

**Comment by vitorebatista** [comment]
@raivieiraadriano92 pra esta vaga infelizmente não... 😢 
Mas esperamos abrir novas vagas no futuro que permitam... 🚀

**Comment by adeonir** [comment]
@vitorebatista também tenho interesse em vagas remotas... o/

**Comment by jacksjm** [comment]
Pessoal, a vaga ainda está aberta!!! Vamos lá \o/

**Comment by vitorebatista** [comment]
O time está crescendo e precisamos de novos profissionais, então a vaga está aberta sim... :rocket:

**Comment by higoncesar** [comment]
@vitorebatista aceitam pessoas de outro estado que estão dispostas a mudar para Joinville? Se sim, a parte de entrevista e pré-contratação pode ser feita remoto, via Skype, Zoom dentre outros?

**Comment by vitorebatista** [comment]
@higoncesar aceitamos sim, a entrevista podemos fazer remoto. :)

**Comment by higoncesar** [comment]
@vitorebatista muito obrigado, enviando meu currículo. =D
