### ISSUE TITLE
[Remoto] React Native Junior Software Engineer no JurisHand (Somos afirmativos para a diversidade)

### ISSUE THREAD

**Issue by joaotmachado** [react-brasil/vagas#2297]
Front-End Software Enginner (Somos afirmativos para a diversidade)

**Somos a mão amiga do ecossistema jurídico brasileiro**

O [JurisHand](https://jurishand.com) tem a missão de se tornar a principal solução diária de apoio ao profissional de  Direito no Brasil e LatAm. Em 2019, lançamos o nosso primeiro produto, um app mobile  onde nossos usuários podem ter a melhor experiência de leitura e interação com a  legislação federal brasileira já vistas na AppStore e Google Play. Dentro de poucos meses,  criaremos novos modelos de negócio e melhorias sensíveis que vão ajudar a escalar nossa  solução como top of the mind para os profissionais de Direito.  

O nosso time de engenharia de software é altamente focado em entregar features que  requerem uma coordenação muito próxima entre database, API, front-end, e mobile. Trabalhamos constantemente com novas tecnologias, por isso valorizamos  profissionais que estão abertos a aprender, independentemente de zonas de conforto  pré-existentes. 

**Os desafios que você vai superar**

- Construir uma experiência de usuário inigualável, baseada no uso criativo das tecnologias disponíveis;
- Projetar e desenvolver componentes e aplicações visando simplicidade, eficiência, manutenibilidade e reaproveitamento de código;
- Continuous integration e Deployment constante em AWS;
- Microserviços e componentes horizontalmente escaláveis em React Native, NodeJS, entre outras linguagens;
- Assegurar a qualidade da solução através de testes automatizados; 
- Guardar data em Realm.

**O que você precisa ser / ter**

- Graduado na área de Computação ou Exatas em geral;  
- Preocupado com entrega de alta qualidade, através de uma lógica de  desenvolvimento, testing e deploy;  
- Atenção ao detalhe – perfect pixel eye;  
- Foco em User Interface e animation skills;
- Experiência em trabalhar com metodologias ágeis e ter mindset de start-up;
- Experiência na tomada de decisões usando métricas e dados;
- Boas habilidades de comunicação sendo inclusivo no processo de decisão;
- Conhecimentos de HTML, CSS, JavaScript, JSON e React Native;
- Mínimo de 2 anos de experiência com React Native;
- Conhecimentos Realm/Watermelon DB;  
- Conhecimento de GraphQL.

**Benefícios**

- Remuneração competitiva;
- 100% remoto;
- Revisão salarial periódica: a cada 6 meses;
- Horário Flexível: trabalhe no horário que se sentir mais produtivo;
- Oportunidade de ganhar equity ownership (participação em ações) do JurisHand, com possibilidade de fazer parte do time fundador da companhia;
- Aprender com um time de empreendedores com experiências de sucesso no Brasil e em outros países (principalmente Europa);
- Bônus por indicação: nos ajude a trazer os melhores devs para nosso time
- Cursos: realize cursos durante o expediente para aprimorar seu know-how;
VR;
- Gympass: programa de academias e de cuidado com a saúde mental.  

**Como se candidatar**

Por favor envie um email para **joao@jurishand.com** seu CV anexado - enviar no assunto do e-mail: Vaga React Native.

#Labels

- 🏢 Remoto
- 👨 Junior
- 👨 Pleno
- 🚀 Early Stage Startup
- 🏢 Flexível
- 💰 R$ 3.5k-6.5k
- ⚖️ CLT
- ⚖️ PJ

**Comment by lucasf10** [comment]
Boa noite. Vocês aceitam part-time?
