### ISSUE TITLE
[ São Paulo ] Desenvolvedor React ou React Native [ FCamara ]

### ISSUE THREAD

**Issue by jakeliny** [react-brasil/vagas#230]
## Descrição da vaga
Para você que gosta de desafios, estou buscando Desenvolvedor React e Desenvolvedor React Native, CLT ou PJ

## Como se candidatar
Interessados ou indicações, enviar CV para [jakeliny.pereira@fcamara.com.br](mailto:jakeliny.pereira@fcamara.com.br)

## Nossa empresa
A FCamara Formação e Consultoria iniciou suas atividades em 2008 com o objetivo de servir com excelência as demandas de verificação de desempenho de aplicações e organização de times de desenvolvimento. Hoje, somos referência em transformação digital através de um método próprio, o High Performance Team, que ajuda empresas a desenvolver projetos e ideias de negócio de forma mais eficiente. Inovação, tecnologia e empreendedorismo fazem parte de quem somos. Queremos ser uma empresa útil e funcional. Útil porque possuímos serviços e produtos necessários. Funcional porque nossos serviços e produtos realmente solucionam e representam valor agregado ao Cliente.

Venha fazer parte do #SangueLaranja. Seja um de nossos clientes ou consultores. Aqui suas ideias tem valor!

## Labels
- CLT
- PJ
- REACT
- REACT NATIVE

**Comment by adeonir** [comment]
Oi @jakeliny é junior, pleno ou senior? Alocado ou pode ser remoto?

**Comment by jakeliny** [comment]
@adeonir é alocado, temos vagas para todos os níveis :)

**Comment by nicholasess** [comment]
@jakeliny é necessário colocar a faixa salarial.

**Comment by nicholasess** [comment]
@jakeliny e seguir o template da vaga facilita as pessoas que estão lendo a vaga e nós de adicionarmos as tags.

obrigado :)
