### ISSUE TITLE
Vaga dev React Adekzti home office

### ISSUE THREAD

**Issue by adekzti** [react-brasil/vagas#2302]
Pessoal, blza?

Temos vagas abertas pra desenvolvedor aqui na empresa. Diversos níveis de conehcimento nas seguintes áreas:

React Native, React/NextJS e Node JS

100% home office

Adekz TI (www.adekz.com)
Quem tiver interesse favor mandar curriculo em nossa seção de vagas:
https://www.adekz.com/trabalhe_conosco  ou email para contato@adekz.com

**Comment by venturion** [comment]
Anuncie em https://devance.com.br 👍
