### ISSUE TITLE
[Remoto][Califórnia] Oportunidade Front-End ReactJS Developer 

### ISSUE THREAD

**Issue by andriussperque** [react-brasil/vagas#231]
## Descrição da Vaga

Desenvolvimento com ReactJS, ReactNative & Redux.

## Local

Remoto ou Silicon Valley, SJ-CA

## Benefícios

- Oportunidades de crescimento de carreira.

#### Diferenciais

- Viagem de treinamento por 3 meses nos US.

## Requisitos

- Mínimo de 2 anos de experiência com desenvolvimento ReactJS.

**Desejáveis:**
- conhecimentos em Marketplace
- conhecimentos em Redux
- conhecimentos em React Native
- conhecimentos em Sketch, ou Zeplin ou Figma para tradução do estilos. 

**Diferenciais:**
- Especialista no assunto

## Contratação

Trabalho remoto no Brasil a combinar (part-time ou full time)

## Nossa empresa

Youcanevent.com - Online Marketplace - One stop shop for Event Organizers - Startup Americana. 

## Como se candidatar

Por favor envie um email para andriussperque@gmail.com com seu CV anexado  ou LinkedIn - assunto: [Remoto][Califórnia] Oportunidade Front-End ReactJS Developer.

## Labels

- alocação/Flexível
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/Freela

**Comment by arthur-melo** [comment]
@andriussperque O email para contato está como o padrão da template!

**Comment by andriussperque** [comment]
Obrigado, Arthur.
Já atualizei o email.
Valeu pelo toque. Abs.
ᐧ

**Comment by andriussperque** [comment]
> @andriussperque O email para contato está como o padrão da template!

**Comment by ribeiroevandro** [comment]
Email, enviado.

**Comment by cleandersonlobo** [comment]
@andriussperque Ainda está recebendo CV?

**Comment by mrangel-jr** [comment]
@andriussperque Está recebendo CV ?
