### ISSUE TITLE
[Joinville] Desenvolvedor Mobile na Sofit

### ISSUE THREAD

**Issue by dougfani** [react-brasil/vagas#233]
# Descrição da vaga

Você fará parte do time de desenvolvimento do aplicativo Sofit View, atuando na análise e desenvolvimento das funcionalidades construídas no aplicativo.

## Local

Escritório, Joinville [SC] - Bairro América

## Benefícios

- Vale Transporte
- Plano de saúde (Sem desconto em folha para o titular)
- Vale Refeição ou Alimentação (R$ 20,00 por dia, sem desconto em folha)
- Salário compatível com as suas responsabilidades
- Flexibilidade de horário (banco de horas)
- Ambiente de trabalho ágil e informal

## Requisitos

**Obrigatórios:**
- Ter formação ou estar cursando algum curso superior na área de Tecnologia da Informação
- Experiência em desenvolvimento de aplicações mobile com React Native
- Experiência com os padrões JSON e REST
- Saber usar GIT
- Saber trabalhar em equipe, ter comprometimento e interesse em aprender
- Ser viciado em tecnologia
- Residir em Joinville - SC ou ter disponibilidade para mudança

**Diferenciais:**
- Orientação a resultados
- Conhecimento em desenvolvimento web com NodeJS
- Conhecimento em tecnologias Web: HTML5, CSS3, jQuery, Bootstrap, etc.
- Conhecimento em banco de dados (Postgres, MySQL, MongoDB…)
- Conhecimento em BPMN
- TDD
- Linux
- XP

## Contratação

CLT

## Nossa empresa

A Sofit é um SaaS B2B que oferece tudo o que as empresas precisam para gerenciar o caos da operação de frotas, substituindo planilhas complexas, sistemas insuficientes e pilhas de papéis.

Somos apaixonados por facilitar a gestão de frotas para que as empresas possam passar mais tempo concentrando-se em sua própria missão.

## Como se candidatar

Acesse o link e cadastre-se: http://bit.ly/2EEBCQe

## Labels

- alocação/Presencial
- experiência/Júnior
- regime/CLT
- remuneração/1k-3k
- remuneração/3k-5k

**Comment by raivieiraadriano92** [comment]
Boa tarde, alguma possibilidade de ser remoto?
