### ISSUE TITLE
Adicionar label para React Native?

### ISSUE THREAD

**Issue by SrBrahma** [react-brasil/vagas#2346]
Oi, proponho uma label para filtrar vagas para React Native, para acharmos elas mais facilmente.

**Comment by SrBrahma** [comment]
Up

**Comment by nicholasess** [comment]
@SrBrahma digitar pela busca não resolve o problema?

https://github.com/react-brasil/vagas/issues?q=is%3Aissue+is%3Aopen+React+Native

**Comment by SrBrahma** [comment]
> @SrBrahma digitar pela busca não resolve o problema?
> 
> https://github.com/react-brasil/vagas/issues?q=is%3Aissue+is%3Aopen+React+Native

Se tu ver os resultados, verá que muitas vagas são de React... o bom de ter um label é que isso não aconteceria.

**Comment by SrBrahma** [comment]
Up
