### ISSUE TITLE
{São Paulo} Desenvolvedor Front-end React na Avanade

### ISSUE THREAD

**Issue by Avabelo** [react-brasil/vagas#2355]
## Descrição da vaga

Você irá trabalhar com desenvolvimento Front-end, focado principalmente em React, seguindo metodologias trabalho ágil. Analisar, projetar, desenvolver e testar sistemas em diversos contextos. Desenvolver soluções de software específicas do cliente e/ou baseadas em Web/App, atuar no desenvolvimento de aplicações de códigos complexos e design de componentes. Além disso, ter uma boa comunicação é um fundamental pois você irá interagir muito com os nossos clientes e seus colegas de trabalho no dia a dia. 

##São Paulo- SP

Remoto e Escritório, São Paulo - Av Paulista

## Benefícios

Vale refeição ou alimentação; 
Vale transporte ou fretado; 
Convênio médico e odontológico 
Telemedicina; 
Telepsicologia; 
Certificações e treinamentos;  
Seguro de Vida; 
Previdência Privada; 
Curso de Inglês; 
Avababy: acompanhamento da gestação e kit para os novos pais e mães Avanade;  
Horários flexíveis;  
Participação nos resultados da empresa;  
Gympass;  
Auxílio creche; 
Career Advisor - Um braço direito para orientar a sua carreira; 
Exposição com times globais a depender do projeto; 
Job Rotation - Possibilidade de rotacionar entre projetos, conhecer mais tecnologias e diversos segmentos de mercado; 
Buddy – Uma pessoa que irá te ajudar nos seus primeiros meses e na fase de adaptação à nossa cultura; 
Para função gerencial ou superior - Veículo corporativo, estacionamento e auxílio combustível. 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento React 

**Desejáveis:**
- conhecimentos em Devops

## Contratação

CLT

## Nossa empresa

Somos uma consultoria de tecnologia que tem como objetivo promover soluções inovadoras para seus clientes, através de um robusto portfólio de tecnologias. Aqui, trabalhamos focados para desenvolver experiências inesquecíveis. Globalmente, somos mais de 36.000 pessoas em 24 países, mas não pense que aqui você é mais um número. Na Avanade, valorizamos o seu talento e investimos em qualificações e aprendizado para você se tornar o melhor no que faz!

## Como se candidatar

Por favor entre em contato com o número:11 94590-9066

**Comment by venturion** [comment]
Anuncie em https://devance.com.br 👍
