### ISSUE TITLE
[Remoto] React Native Developer no TON (Stone Co)

### ISSUE THREAD

**Issue by Luanna220** [react-brasil/vagas#2366]
## Descrição da vaga:

Aqui no Ton você atuará na elaboração de novas features, manutenção do nosso app, documentações, refinamentos.

Somos um time jovem com bastante disposição de gerar valor através de códigos, estrutura e arquitetura de app de qualidade, sempre seguindo padrões e normas da companhia, pois outras squads também trabalham em nosso App, com liberdade para opinar, sugerir e implementar novas ideias para protagonizar e mostrar suas soluções;

Interação e participação constante em refinamento e troca de idéias com nosso time de UX
para novas demandas.

## Local: 
Remoto 

## Benefícios:
- Assistência Médica + Plano Odontológico (Bradesco TNQ2);
- Auxílio Creche (R$ 342,00/mês – para filhos até 5 anos de idade);
- Seguro de Vida (Porto Seguro);
- Vale Alimentação/Refeição (R$ 600,16/mês);
- Vale Transporte (opcional);
- Gympass

## Requisitos:

**Obrigatórios:**
- Experiência com React/React Native;
- Experiência com JavaScript/TypeScript;
- Noção de Git;
- Noção de organização de código;
- Noção de testes;
- Experiência com metodologia ágil, preferencialmente SCRUM.

**Desejáveis:**
- Noção da arquitetura Serverless;
- Noção com IaC (Terraform/serverless framework);
- Experiência com cartão e certificação de terminal de pagamento;
- Dinamismo e cabeça de dono (ter o projeto como teu);

#Sobre o Ton

Você tem paixão por fazer a vida do cliente melhor através de uma experiência incrível? Então, vem pro Ton!

O Ton é uma empresa focada no empreendedor autônomo e faz parte do Grupo Stone Co. Através das soluções desenvolvidas no Ton o autônomo faz a gestão do seu negócio, ou seja, o Ton é mais que uma maquininha, o Ton tbm é cartão, conta digital, aplicativo. O Ton é a solução. #seliganoton (https://www.youtube.com/watch?v=QFwC6sInVmo)

Aqui, você terá a oportunidade de trabalhar com um time de apaixonados por desafios, sempre preocupado em atender da melhor forma os nossos clientes e buscando as melhores escolhas técnicas para entregar o resultado. E mais importante, tudo isso em um ambiente descontraído.

Junte-se a nós! **#seliganoton**

## Como se candidatar

Por favor envie um e-mail para luana.cordeiro@stone.com.br o seu currículo ou linkedin no corpo do e-mail - enviar no assunto: **Vaga React Native**

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT
- 💰  Remuneração competitiva com o mercado em posições pleno/sênior

**Comment by SrBrahma** [comment]
Valor?
