### ISSUE TITLE
[Amsterdam] React Native App Developer at PVH Europe

### ISSUE THREAD

**Issue by fabiopaiva** [react-brasil/vagas#239]
## Descrição da vaga

As React Native App Developer, you play a key role in shaping our digital future with the MYTOMMY app. You bring a best-in-class, personal experience to Tommy Hilfiger customers by being in forefront of seamless mobile experiences.

## Local

Amsterdam - Netherlands

## Benefícios

- Wide range of courses at PVH University to satisfy your learning appetite;
- Great colleagues (curious, ambitious, and fun);
- International working environment;
- Relocation assistance, from A to Z (if you live abroad);

#### Diferenciais

- A challenging position in a growing and expanding team with a strong start-up mentality;
- Competitive salary with benefits;
- State-of-the-art campus facilities;
- ‘All-you-can-eat’ healthy lunches and amazing events;
- Arrange your own workstation: Macbook/iPhone and all other options a techie could dream of;

## Requisitos

**Obrigatórios:**
- You have good communication skills in English
- React/React Native experience

**Desejáveis:**
-  NodeJS
- Android(Java/Kotlin)
- iOS(Objective C/Swift)

## Contratação

Working contract

## Nossa empresa

We are PVH, one of the world’s leading apparel companies with over $8 billion in revenues in 2017. PVH consists of three business groups: Tommy Hilfiger, Calvin Klein and Heritage Brands.

It is a dynamic, entrepreneurial, energetic environment where people get opportunities to grow and show their creativity. In our Amsterdam offices we gather people from all over the world, over 50 nationalities. We work hard, have fun and create an amazing culture.

## Como se candidatar

https://www.linkedin.com/jobs/view/1171842997/

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/Outros

**Comment by nicholasess** [comment]
@fabiopaiva faltou a pretensão salarial para Pleno e Senior, se for em outra moeda, coloca o equivalente.

Obrigado

**Comment by fabiopaiva** [comment]
Isso pode variar bastante. Os recrutadores avaliam o quanto a pessoa pode agregar à empresa.
O que pode se ter como referência do mínimo possível é a tabela de salário mínimo por idade do governo holandês, menos que isto o visto nem é aprovado:

Highly skilled migrants 30 years or older | ​€ 4,500 gross per month
​Highly skilled migrants younger than 30 years | ​€ 3,299 gross per month
