### ISSUE TITLE
[Rio de Janeiro] Dev Fullstack na Beliquid Consultoria e Serviços

### ISSUE THREAD

**Issue by eaalcantara** [react-brasil/vagas#2401]
## Descrição da vaga

Trata-se de um projeto para desenvolvimento de sprints de acréscimos funcionais e correções de issues em uma plataforma na web (www.lgpdcanaldotitular.com.br).
É um aplicativo web também responsivo em mobile.
As sprints são especificadas em detalhe, inclusive com queries mais complexas e layouts de formulários.
Os textos de ajuda são desenvolvidos e postados pelo especificador, não envolvendo o desenvolvedor.
Total disponibilidade do especificador para esclarecimentos de dúvidas via WA ou Call.
O desenvolvedor fará o dimensionamento de tempo, custo e discutirá com o desenvolvedor.
Antes do dimensionamento da primeira sprint o especificador fornecerá todos os fontes via github e senhas de homologação para conhecimento pelo desenvolvedor.
Todas as entregas será homologadas pelo especificador que retornará relatório detalhado com os pontos de ajuste requeridos com base na especificação.

## Local

Remoto

## Requisitos

**Obrigatórios:**
Pleno conhecimento de desenvolvimento fullstack usando REACT, ADONIS, MYSQL, GITHUB, além de domínio de deployment em ambiente linux.

## Contratação

PJ ou freelancer a combinar

## Nossa empresa

Somos uma empresa que desenvolve sistemas em ambiente web.

## Como se candidatar

Por favor envie um email para eduardo.alcantara@beliquid.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ PJ

**Comment by dudunog** [comment]
Olá, podemos conversar melhor sobre a vaga?
