### ISSUE TITLE
[Remoto ou São Paulo] Back-End (React & Node) na @appedidos

### ISSUE THREAD

**Issue by prepararh** [react-brasil/vagas#2404]
## Descrição da vaga
- Desenvolver novas funcionalidades de acordo com as demandas;
- Construir, evoluir e escalar arquiteturas distribuídas e micro serviços para soluções específicas;
- Criar e manter soluções de APIs e micro serviços que serão consumidos.

## Local
Remoto ou Escritório, São Paulo/SP /-Araçatuba/SP

## Requisitos

**Obrigatórios:**
- Experiência de pelo menos 3 anos na área;
- Conhecimentos em JavaScript, ReactJS e NodeJS;
- Padrões HTTP;
- Criação de APIs em NodeJS e Express;
- Conhecimento de PostgreSQL e comandos SQL.

**Desejáveis:**
- Possui competência em Inglês (leitura);
- Tem conhecimento em Cloud (AWS).

## Contratação
PJ a combinar

## Nossa empresa
Olá muito prazer, somos a PreparaRH, especialistas em Gestão estratégica de Pessoas! Estamos recrutando Desenvolvedor Back-End para a appedidos! Uma startup brasileira que nasceu com o propósito de oferecer a melhor experiência no delivery. Eles unem tecnologia com paixão e comida, são movidos todos os dias para serem referência no mercado, oferecendo a melhor experiência aos clientes, parceiros e colaboradores.

Buscamos um(a) Desenvolvedor(a) Back-end para atuar no time de tecnologia e levar essa missão ainda mais longe com os produtos que impactam milhares de pessoas todos os dias.

Visite nossos sites:
https://www.appedidos.com.br/
https://www.prepararh.com.br/

## Como se candidatar
Cadastro através do site https://prepararh.gupy.io/companies/jobs/1552676/ em caso de dúvidas entrar em contato através do whatsapp (18) 99725-4785.

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ

**Comment by theogandara** [comment]
Não estou conseguindo me candidatar pelo link.

**Comment by prepararh** [comment]
Bom dia Théo, tudo bem?

Poderia estar entrando em contato através do nosso whatsapp de 
recrutamento e seleção (18) 99725-4785 ai você fala com a karen ou com a 
juliane, elas que fazem o acompanhamento dos candidatos e auxiliam caso 
haja problema na plataforma, está bem?

Desde já agradeço seu contato e desejo a você boa sorte!

Atenciosamente,

Em 2022-04-12 16:21, Théo Gândara escreveu:

> Não estou conseguindo me candidatar pelo link.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>



Links:
------
[1] 
https://github.com/react-brasil/vagas/issues/2404#issuecomment-1097123652
[2]
