### ISSUE TITLE
[Remote] [full-time] React/React Native Developers @ Popstand.com

### ISSUE THREAD

**Issue by tgmarinho** [react-brasil/vagas#2412]
## Descrição da vaga

[Popstand ](https://popstand.com/)is a US based software development company consisting of 40+ awesome team members from all over the world. We build bespoke web and mobile applications for industry leaders such as Disney, MLB, Verizon, Evernote, Blockfolio, Topps and their millions of customers.

This is a full-time position with competitive compensation and great perks on a salary basis.

Our work environment is highly collaborative and team focused and we take great care in following best practices to ensure high quality of life while developing, such as continuous integration and deployments (CI/CD), code review, and a dedicated, in-house quality assurance (QA) team for support and testing.

You will work regularly with designers, product managers and quality assurance engineers throughout development process to build best-in-class software solutions.

## Local

- Remote

## Benefícios

- Unlimited Paid Time Off (PTO)
- Paid vacation days
- Seasonal and incentivized bonuses
- Any desired educational material or courses
- Hardware (Mac, iPhone and/or Android, headphones, etc.)

#### Diferenciais
- $ USD Americano
- [Payoneer](https://www.payoneer.com/) for international payments

## Requisitos

**Obrigatórios:**
- 3+ years professional experience with React / React Native
- Proficient verbal English

**Desejáveis:**

- Other technology / stack experience is beneficial
- Team lead
- PHP, MongoDB, .Net (C#) can help us sometime :)

**Diferenciais:**
- Experience working with open-source projects
- web3 techonologias 

## Contratação

- Independent contractor

## Como se candidatar

Please send an email **to** [info@popstand.com](mailto:info@popstand.com) with **subject** "React-Brasil Developer Job Posting - by Thiago Marinho", with **cc**/ [thiago@popstand.com](mailto:thiago@popstand.com) and [pedro@popstand.com](mailto:thiago@popstand.com), with content, and please include and fill out the following to be considered:
Hi Chris!

I’m **XXXXXX**, I come from React Brasil community, indicating by Thiago Marinho, to work with you as React Developer at Popstand.

SUGGESTION: [I’ve been working for 2.5+ years with JavaScript, TypeScript, ReactJS, and the ecosystem related. I also have experience developing APIs in the NodeJS ecosystem]

Availability (part-time or full-time):
Do you have a Mac:
When can you start:
Technologies/experience (answer in years/months anos/meses ie: 3yr, 6mo, 3.5yr)
Overall years of experience programming (start to present day):
React.js -
React Native -
Firebase -
Graphql -
Apollo -
Hasura -
Typescript -
Node.js -
Next.js -
Other unlisted languages -

Open source reference links:

LinkedIn: [https://www.linkedin.com/in/tgmarinho/](https://linkedin.com/in/tgmarinho/)

Github: [https://github.com/tgmarinho](https://github.com/tgmarinho)

Best regards!
**XXXXXX**
Software Engineer

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 10k-15k
- 💰 15k+

**Comment by Victorvikson1996** [comment]
I don’t have  3.5 urwara experience but I can work as an intern

**Comment by matheuscvp** [comment]
Essa vaga é apenas para profissionais com no mínimo de 3.5 anos de experiência profissional, ou há a possibilidade de entrar como junior tendo um ano de experiência?
