### ISSUE TITLE
[Alphaville] React Native Developer na WEDIGITEK

### ISSUE THREAD

**Issue by wedigitek** [react-brasil/vagas#242]
## Descrição da vaga

Procuramos Desenvolvedor com experiencia em React Native para nosso escritório de Alphaville.
Estamos adicionando funcionalidades aos nossos produtos e migrando versões antigas para React Native.

## Local

Escritório em Alphaville, próximo à Alameda Rio Negro.

## Benefícios

- Plano de saúde
- VR de R$ 25/dia
- VT de acordo com a Deslocação

#### Diferenciais

- 1 hora de almoço
- MacBook Pro novo
- Frigobar sempre cheio
- Sala de jogos

## Requisitos

**Obrigatórios:**
- 1 anos de experiência com desenvolvimento IONIC
- 2 anos de experiência com desenvolvimento Mobile (Android e/ou iOS)

**Desejáveis:**
- conhecimentos em Firebase, Parse Server

**Diferenciais:**
- projetos opensource
- projetos mobile

## Contratação

CLT
Remuneração: De acordo com a experiência comprovada.

## Nossa empresa

Na Wedigitek tornamos os sonhos dos clientes em Realidade. Somos uma empresa jovem com vários clientes de nome no mercado.

## Como se candidatar

Por favor envie um email para rh@wedigitek.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/CLT

**Comment by raivieiraadriano92** [comment]
Bom dia, alguma possibilidade de trabalho remoto?

**Comment by wedigitek** [comment]
> Bom dia, alguma possibilidade de trabalho remoto?

Bom dia Raí, necessitamos que seja local.
