### ISSUE TITLE
[ Remoto ] React Native Developer na MateRate

### ISSUE THREAD

**Issue by eduduardo** [react-brasil/vagas#243]
## Descrição da vaga

Depois de 3 anos de desenvolvimento, no fim de 2018 lançamos o MateRate, um app brasileiro, concebido para ser a referência mundial em filmes e séries. Estamos em busca de desenvolvedores(as) para integrar a equipe de desenvolvimento do nosso aplicativo híbrido. Procuramos alguém que lide bem com a pressão de uma startup, que curta desafios e saiba gerenciar seu próprio tempo trabalhando remotamente. 

## Local

Remoto.

## Benefícios

- Completamente remoto

#### Diferenciais

- Flexibilidade no horário de trabalho

## Requisitos

**Obrigatórios:**
- Domínio de Javascript / ES6+
- Experiência com React.JS, React Native e Redux
- Experiência prévia com desenvolvimento de aplicativos, nativo ou híbridos para Android e iOS.

**Desejáveis:**
- Ter projetos ou aplicativos já publicados nas lojas

**Diferenciais:**
- Conhecimentos em otimização e performance

## Contratação

PJ ou CLT a combinar

## Nossa empresa

MateRate é um aplicativo gratuito que te ajuda a escolher o filme ou a série perfeita de forma rápida, prática e descolada. Lançamos nossa plataforma no fim de 2018 do ano passado e estamos crescendo, com pretensão de lançar diversas features e expandir nosso alcance global.

Conheça nosso app em [https://materate.com](https://materate.com)

## Como se candidatar

Por favor, enviar currículo e pretensão salarial como PJ ou CLT e, se possível, com portfólio ou exemplo de projetos para hello@materate.com, com o título "Vaga React Native Developer - GitHub".

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- remuneração/3k-5k

**Comment by brunooomelo** [comment]
> valor máximo do salário é 5k? em qual tipo de contratacao?
PJ ou CLT a combinar.
3k - 5k.

**Comment by eduduardo** [comment]
Vaga finalizada. Agradeço a todos que enviaram email para nós!
