### ISSUE TITLE
[Florianópolis] React Developer - STUDOS

### ISSUE THREAD

**Issue by CaioPaiola** [react-brasil/vagas#246]
## Descrição da vaga

Estamos em busca de desenvolvedores Reactjs e React Native para participar do nosso time. 

## Local

Florianópolis - Parque Tecnológico Alfa

## Requisitos

**Obrigatórios:**
- React, Redux;
- HTML5;
- CSS3;
- Consumo de APIs REST;
- Git.

**Desejáveis:**
- Goste de aprender;
- Se comunique bem;
- Já ter zerado Super Mario World e Donkey;
- Tenha experiência com Open source;
- Saiba conversar fluidamente com Designers e Back-ends;
- Se preocupe não só com a qualidade do seu código, mas também com a experiência do usuário.

**Diferenciais:**
- Gostar de café;
- Conhecimentos em PHP, PYTHON, MYSQL, ELASTICSEARCH, AWS...

## Contratação

PJ ou CLT a combinar.

## Nossa empresa

A Studos é uma Startup do setor de tecnologia e educação, localizada em Florianópolis – SC.

Uma empresa "sangue no zóio", focada em seu objetivo principal, que é transformar a educação através da tecnologia com pessoas muito legais. 😎

Hoje, atuamos nas áreas de vestibular, concursos públicos, pré-militar e OAB.

Oferecemos uma plataforma Web e um aplicativo educacional que visam melhorar o desempenho dos estudantes e facilitar o trabalho de professores e coordenadores.
Nossa empresa é jovem, e possui valores ligados ao comprometimento, profissionalismo, espírito inovador, foco nos resultados, sustentabilidade e ecoinovação.

E ai tem coragem?

## Como se candidatar

Por favor, envie um e-mail para curriculos@studos.com.br com seu CV anexado OU um e-mail com uma breve descrição sua OU enviar um Whatsapp pro Caio (11) 95122-5659! - Assunto: Vaga Desenvolvedor React

## Labels

- alocação/Flexível
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/PJ
- remuneração/1k-3k
- remuneração/3k-5k
- remuneração/5k-10k

**Comment by raivieiraadriano92** [comment]
Boa tarde Caio, alguma possibilidade de ser remoto?

**Comment by guilhermeoa07** [comment]
ainda em aberto?
