### ISSUE TITLE
[REMOTO VOLUNTARIADO] Desenvolvedor Web React e Node.js

### ISSUE THREAD

**Issue by tech4covidbrasil** [react-brasil/vagas#2468]
## Tech4Covid - Plataforma Doar Bem

Somos uma plataforma de contato entre pessoas que querem praticar o bem da doação e organizações que necessitam da doação para praticar o bem. Estamos nas fases finais de lançamento de nosso [site](https://doarbem.com.br/), por onde ONGs poderão criar campanhas de doação, assim facilitando o trabalho delas e aumentando o alcance de suas campanhas
de doação ao nos estabelecer como um centro para doações físicas no Brasil

Estamos precisando da ajuda de desenvolvedores que queiram voluntariar e nos apoiar na construção da plataforma. Trabalhamos com as seguintes linguagens e ferramentas:
HTML5
CSS3
Javascript
React
Node-JS
Typescript
Firebase

Então se você quer treinar suas habilidades como DEV, conhecer outros DEVs ao redor do Brasil e praticar o bem do voluntariado mande um oi no Telegram: @Felipe_Tedesco ou no Discord: FelipeLT#8984 com seu CV ou somente um resumo do seu conhecimento como DEV. Entraremos em contato com você.

Nosso instagram: DoarBem (@doar_bem) 

## Descrição da vaga

Desenvolvedor Web - Voluntariado

## Local

Remoto 

## Benefícios

- Praticar o voluntariado e fazer o bem para muita gente. 
- Botar em prática o seu conhecimento como DEV em um projeto super bacana. 
- Fazer relacionamento e aprender com outros colegas DEVs.
- Divulgar no seu Linkedin que vc é f@da e ajuda outras pessoas através da tecnologia. 

#### Diferenciais

- Se vc se interessou em ser voluntário, então já é diferenciado. Vêm com a gente.
- Está iniciando como DEV. Bora, partiu com a gente.
- Conhece ou tem interesse em atividades de BackEnd. Fechou todas. 

## Requisitos

- Querer ser voluntário;
- Dispor de um tempo para codar com a turma. 
- Ter a capacidade de assumir compromissos e cumprir com as entregas. 
- Estar a fim de conhecer pessoas que se ajudam e que querem fazer o bem para os outros.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ Voluntário

**Comment by Alicesinha** [comment]
Adorei a iniciativa e quero participar, mandei convite la no discord :)

**Comment by luquita78** [comment]
Gostei da iniciativa também. Entrarei em contato pelo disc.

**Comment by Alicesinha** [comment]
ate hj nao me responderam kk

**Comment by luquita78** [comment]
Temi que isso fosse acontecer hahaha

Em ter., 12 de jul. de 2022 às 16:14, Alice Sousa ***@***.***>
escreveu:

**Comment by salmomascarenhas** [comment]
Ainda ta rolando ?
Gostaria de me voluntariar!

**Comment by GilsonAlvesdeSouza** [comment]
Gostaria de participar

**Comment by xdtr27** [comment]
Ainda está funcionando?

**Comment by vanemoraess** [comment]
Ainda está funcionando? Vou mandar mensagem lá no telegram, adorei a iniciativa

**Comment by alife-echo** [comment]
ainda funciona ?

**Comment by globodanzante** [comment]
ainda esta funcionando, quero participar

**Comment by jefersonferreira27** [comment]
Olá! Tenho interesse em participar.

**Comment by otaviohenrique1** [comment]
Tenho interesse em participar.

**Comment by Marcelo-Magal** [comment]
Boa tarde, tenho interesse no projeto.

**Comment by cauefsantos** [comment]
Boa tarde! Tenho interesse em participar do projeto

**Comment by wlmda** [comment]
Tenho interesse em participar da vaga

**Comment by pascoalkahamba** [comment]
Olá. Tenho interesse em participar.

**Comment by adaomagalhaes03** [comment]
Quero participar para esta vaga

**Comment by siomara777** [comment]
Quero participar dessa vaga

**Comment by janainabatista** [comment]
quero

**Comment by rafael-p-s** [comment]
Gostaria de participar.

**Comment by jorgelgf** [comment]
Opa. Quero participar! :)

**Comment by janainabatista** [comment]
quero participar

**Comment by ThiagoSilva20** [comment]
Quero participar, como faço para me inscrever para voluntariado ?

**Comment by JeanCarloPx** [comment]
Olá, bom  dia, adoraria participar, não entrei seu nome de usuário (FelipeLT#8984), poderia me passar informações atualizadas?

**Comment by GilsonAlvesdeSouza** [comment]
Podem tirar o cavalinho da chuva galera esse post aí eu me inscrevi  a mais de 2 anos e ninguém  responde

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Lucashpinheiro** [comment]
Eu tenho muito interesse em ser volutário, como faço para me inscrever?
