### ISSUE TITLE
[REMOTO] Next js Jr Developer na Kolabs

### ISSUE THREAD

**Issue by MatheusKemer** [react-brasil/vagas#2488]
## Descrição da vaga

Vaga aberta para desenvolvedores React com experiência em Styled Components. Nossa empresa trabalha com desenvolvimento de produtos nacionais e internacionais nas áreas da educação, mercado financeiro, gestão e entretenimento.

Buscamos um dev junior que já possui alguma experiência na stack js React e com experiência em HTML e CSS. Mesmo que elas sejam acadêmicas.

O foco do trabalho é no desenvolvimento de layouts e componentes totalmente responsivos criados pela nossa equipe de design.

Nossa horário é totalmente flexível e aceitamos candidaturas de devs com 120 horas mensais (6 horas diárias) ou até menos! Mande um e-mail pra gente e vamos conversar sobre isso.

## Local

100% remoto

## Requisitos

Conhecimento em GIT
Conhecimento em HTML e CSS
Conhecimento em React Js, Next js e typescript
Conhecimento em Styled Component

**Desejáveis / Opcionais**
- Conhecimento em React Native

## Contratação

PJ a combinar

## Nossa empresa

Somos um laboratório colaborativo de tecnologia.. Nossos projetos contém tecnologia de ponta e possuem todos os tipos de inovações para uma entrega única e diferente.

## Como se candidatar

Por favor envie um email para matheus@kolabs.com.br com seu CV anexado e **pretensão salarial** (negociável) - enviar no assunto: Vaga React Jr.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ PJ
- 💰 1k-3k

**Comment by luanargolodev** [comment]
Currículo enviado!

**Comment by Ranbut** [comment]
Currículo enviado!

**Comment by RyanHenriqueBelfort** [comment]
CV sended!

**Comment by DanyLass** [comment]
Currículo enviado, obrigada!

**Comment by YesMarsh** [comment]
Currículo Enviado!

**Comment by Ranbut** [comment]
Currículo Enviado!

**Comment by matheusobarboza** [comment]
*** Informações enviadas com sucesso! *** :)

**Comment by DanielKitanaxiFilipe** [comment]
CV Enviado

**Comment by iagob28** [comment]
Enviado

**Comment by Thirki** [comment]
Enviado

**Comment by CarlosAmorim94** [comment]
Possuo as exigências da vaga, mandei em email 😁 inclusive estou desenvolvendo um projetinho pessoal com NextJS, Typescript e Styled-components, está tudo aqui no meu Github.

**Comment by matosmarcio10** [comment]
Enviado

**Comment by PauloMarquess** [comment]
Enviado

**Comment by thiagopabreu** [comment]
Enviado

**Comment by Gardium** [comment]
Enviado!

**Comment by volpatocode** [comment]
Enviado.

**Comment by kauan777** [comment]
CV enviado, agradeço desde já a oportunidade de me candidatar

**Comment by Ericckm** [comment]
CV enviado.

**Comment by sittes** [comment]
Enviado!

**Comment by JoaoEduardo10** [comment]
CV enviado

**Comment by montteiropedro** [comment]
Currículo enviado!

**Comment by juniorvilas** [comment]
Curriculo enviado!

**Comment by ErickMarllon** [comment]
Currículo enviado!

**Comment by DarcioCarvalho** [comment]
Olá, Matheus. Tudo bem?

Enviei no e-mail indicado o meu currículo e informações adicionais.

Abraços!!!

**Comment by ViniZap4** [comment]
## Hey @MatheusKemer, tudo bem com você?

Enviei um **e-mail com o meu CV**, espero muito fazer parte da _**Kolabs**_!

**Comment by racalixta** [comment]
Enviado

**Comment by rafaelsilva81** [comment]
Enviado!

**Comment by FeRiffo** [comment]
Enviado!

**Comment by danibex** [comment]
CV Enviado
