### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Javascript Júnior/Pleno

### ISSUE THREAD

**Issue by proamobile** [react-brasil/vagas#249]
## Descrição da vaga

Olá! Nós somos a PROA Tecnologia Criativa e estamos buscando uma nova pessoa para embarcar em nosso navio! Irá trabalhar diretamente com Javascript no back e front. Estamos introduzindo o React Native como ferramenta de desenvolvimento de aplicativos e você irá chegar já codificando e iniciando o projeto.

## Local

Presencial - Escritório no centro de São Paulo (6 minutos da estação São Bento - Linha Azul)

## Procuramos alguém que...
- Não tem medo de desafios!!!
- Tem um perfil maker e investigativo;
- Comprometido com resultados e prazos;
- Curte um ambiente de startup, descontraído (mas com muito trabalho para ser feito);
- Queira crescer junto com a empresa;
- Gosta de aprender e se arriscar;

## Manja de...
- Javascript <3. Aqui nós usamos Node no back, Vue.js no front, Titanium/React Native no mobile;
- MongoDB;
- CSS3, HTML5;
- Git;
- Construção e consumo de web services e APIs;

## Em nosso navio tem:
- Vale-transporte;
- Vale-refeição ou alimentação;
- Assistência médica e odontológica;
- Possibilidade de home-office 1x por semana;
- Incentivo a cursos e participação em eventos;
- Flexibilidade de horário;
- Ambiente descontraído
- #PROAParty, nossa festa mensal \o/
- No dress code (pode trabalhar de bermuda, camiseta, vestido...)

## Contratação:
- CLT ou PJ;
- Salário a combinar mediante conhecimento da(o) canditada(o).

## Sobre a embarcação:
A PROA Tecnologia nasceu para criar soluções inovadoras em desenvolvimento de aplicativos móveis, sistemas, integrações, robôs de atendimento, consultoria e pesquisa por meio de uma imersão na realidade de cada cliente. Cada projeto é encarado como um novo desafio e estruturado sob medida para atender e superar as expectativas de cada empresa. Acesse nosso site: www.proatecnologia.com.br

## Como se candidatar

Por favor, envie um e-mail para mobile@proatecnologia.com.br com seu CV anexado (feat. pretensão salarial) com o assunto "Alô Capitão, estou aqui para a vaga de JS"

## Labels:
- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/A-Combinar
- regime/CLT
- regime/PJ

**Comment by juulhao** [comment]
ahhaha massa! Estou enviando meu CV Capitão!

**Comment by guilhermeoa07** [comment]
A seleção pode ser feita remotamente?

**Comment by proamobile** [comment]
> A seleção pode ser feita remotamente?

podemos fazer sim, mas a vaga é pra navegar presencial com a gente.
