### ISSUE TITLE
[SP] Front-end Developer Jr no Grupo GPS

### ISSUE THREAD

**Issue by araujovicthor** [react-brasil/vagas#2519]
[SP] Front-end Developer Jr no Grupo GPS

## Descrição da vaga
Exemplo: Implementar, testar e manter interfaces responsivas focadas na interação do usuário assim como buscar e propor novas soluções e também interagir com pessoas envolvidas para a criação do melhor produto/resultado.

## Local
SP - Home office

## Requisitos
**Obrigatórios:**
- ReactJS
- Javascript ou Typescript (Preferencialmente)
- HTML5, CSS3
- Git
- Preocupação com interfaces e experiência do cliente
- Integração com API's

**Desejáveis:**
- React hooks
- Next.js
- styled-components, SASS ou LESS
- Testes de frontend
- Técnicas de SEO
- PWA
- CI/CD
- Metodologias ágeis

**Ficaríamos impressionados se você soubesse:**
- Micro-frontend
- GraphQL
- Criação de bibliotecas

## Benefícios
- Assistência médica e odontológica
- VR/VA

## Contratação
CLT

## Como se candidatar
Por meio do aplicativo corporativo GPSvc

## Labels
Desenvolvimento de Software, Programação Funcional, Responsividade, Frontend, Interação entre equipes, Métodos ágeis, Testes.

## Alocação
Remoto

## Regime
CLT

## Nível
Júnior
![Front-end](https://user-images.githubusercontent.com/33492333/171279440-a4deb728-871a-4130-91d4-01c28f551fa4.png)

**Comment by Cientista-Avogadro** [comment]
Disponível para a vaga

**Comment by jerlyssonm** [comment]
Gostaria de concorrer a essa oportunidade... Incrições para a vaga só pelo app GPS?

**Comment by Cientista-Avogadro** [comment]
Sim gostaria

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Vttos** [comment]
Como faço para me candidatar pra vaga?

**Comment by luizgutemberg** [comment]
Ainda é possível se candidatar ?

**Comment by diegocozer** [comment]
Gostaria de me candidatar para a vaga
