### ISSUE TITLE
[Remoto] Software Engineer na Hubla

### ISSUE THREAD

**Issue by jurussano** [react-brasil/vagas#2545]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/vagas/senior-software-engineer-210117665?utm_source=github&utm_medium=react-brasil-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p><strong>A Hubla </strong>busca <strong>Sênior Software Engineer</strong> para compor seu time!</p>
<p>A Hubla nasceu para dar liberdade para que pessoas trabalhem fazendo o que amam. Nós oferecemos toda a infraestrutura para que criadores de conteúdo possam monetizar e engajar suas comunidades, liberando tempo para o criador prover o melhor conteúdo e experiências únicas para as suas comunidades.</p>
<p>Em novembro de 2021 a Hubla levantou série A de mais de 10M USD pela Kaszek, o que vem nos ajudando a crescer continuamente. Hoje contamos com milhares de criadores dos mais diversos segmentos - saúde, fitness e bem-estar, finanças, investimentos, gastronomia, música, turismo, entre outros.</p>
<p>Mas queremos ir além, criar o futuro do trabalho.</p>
<p>Estamos buscando uma pessoa para atuar como Sênior Software Engineer (fullstack, backend ou frontend) para desenvolver features end-to-end em um dos Squads da Hubla.</p>
<p><strong>RESPONSABILIDADES</strong></p>
<ul>
<li>Desenvolver funcionalidades no produto da Hubla do início ao fim, incluindo definições de arquitetura, testes e rollout em produção;</li>
<li>Desenhar a solução técnica de novas funcionalidades ou sistemas, assim como revisar desenhos de outras pessoas;</li>
<li>Revisar o código de colegas;</li>
<li>Manter os sistemas existentes, priorizando demandas de melhorias e bug fixes.</li>
</ul>

## Hubla: 
 <p>A Hubla é uma empresa de tecnologia líder na Passion Economy / Creator Economy no Brasil. <br>Lançada em 2020, permite aos criadores administrar sua própria comunidade paga usando uma plataforma de gerenciamento inteligente e rápida.<br>Estamos transformando talentos em comunidades ao possibilitar que qualquer pessoa crie um negócio online por meio de plataformas de chat em grupos como WhatsApp ou Telegram. <br>Nossa missão é permitir que as pessoas tenham liberdade para trabalhar fazendo o que amam e ganhar a vida compartilhando seus talentos e experiências com o mundo.</p>
</p>

 ## Habilidades: 
 - Node.js 
- Typescript 
- React.js 
- Next.js 
- Flutter
## Local: 
 100% Remoto
## Requisitos: 
 - Sólida experiência profissional com desenvolvimento de software; 
- Ter conhecimento de boas práticas de programação e aplicá-las; 
- Consegue decompor problemas complicados em tarefas pequenas e simples; 
- Sente-se à vontade de pedir ajuda quanto tiver dificuldades; 
- Se comunica claramente, sendo ativo em discursões da direção do Squad; 
- Apesar de ter foco em Backend ou Frontend tem noções de como funciona toda a stack; 
- Entende a necessidade de testes automatizados e é capaz de implementá-los; 
- Entende e navega bem os tradeoff entre velocidade vs qualidade; 
- Inglês Intermediário.
## Diferenciais: 
 - Inglês avançado; 
- Familiaridade com a Stack de software da Hubla.
## Benefícios: 
 - Stock options com alto potencial de valorização; 
- Plano de saúde e odontológico nacional sem co-participação; 
- Seguro de vida e Seguro viagem: incluso no plano de saúde tanto nacional como internacional para colaboradores e seus dependentes; 
- Vale refeição e alimentação via cartão Caju; 
- Auxílio home office e/ou vale transporte; 
- Gympass; 
- Aulas de inglês online; 
- Horário de trabalho flexível; 
- Modalidade de trabalho flexível e/ou home office; 
- Um ambiente de trabalho e time únicos, que estão trabalhando com paixão e intensidade para ter os melhores resultados nesse momento de hiper crescimento!
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Software Engineer na Hubla](https://coodesh.com/vagas/senior-software-engineer-210117665?utm_source=github&utm_medium=react-brasil-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Regime
CLT
#### Categoria
Full-Stack

**Comment by PedroL22** [comment]
Desenvolvedor Full Stack com 4 anos de experiência construindo sistemas fintech em produção na Suíça usando TypeScript, React, Node.js e tecnologias web modernas.

Atualmente na datalution GmbH, arquiteto aplicações type-safe em escala usando React 19, Next.js 15 e tRPC com 50+ routers. Implementei sistemas completos de PWA, autenticação OAuth, pagamentos via Stripe e internacionalização em 4 idiomas usando Prisma ORM e PostgreSQL.

Também CEO/CTO da 22AI, uma plataforma de bate-papo com IA rápida e multilíngue, com opções flexíveis de modelos, conversas compartilhadas e fluxos de trabalho focados em produtividade.

1. https://github.com/PedroL22
2. https://www.pedrolucena.com e https://22ai.app
3. 4 anos como tech lead e dev full-stack
4. 5000 USD/month
5. Dia 1 do mês seguinte

**Comment by victorbiasibetti** [comment]
> # [CONTRATAÇÃO] Desenvolvedor(a) Full Stack Sênior (Next.js / React / TypeScript) – Remoto
> ## Sobre o Projeto
> 
> Estamos desenvolvendo uma plataforma moderna de e-commerce focada no mercado de futebol japonês, oferecendo uma experiência premium para torcedores e consumidores apaixonados por esportes.
> 
> Nosso objetivo é construir uma plataforma escalável, segura e de alta performance, combinando e-commerce, experiência do usuário e tecnologias web modernas.
> 
> Buscamos um(a) Desenvolvedor(a) Full Stack Sênior para colaborar no desenvolvimento da plataforma, participando desde as decisões de arquitetura até a entrega em produção.
> ## Posição
> 
> **Desenvolvedor(a) Full Stack Sênior**
> 
> **Modalidade:** Remoto
> 
> **Tipo de Contratação:** Freelancer / Contrato de Longo Prazo
> 
> **Fuso Horário:** Flexível
> ## Stack Tecnológica
> ### Front-end
> 
>     * Next.js
> 
>     * React
> 
>     * TypeScript
> 
>     * Tailwind CSS
> 
> 
> ### Back-end
> 
>     * Node.js
> 
>     * APIs REST
> 
>     * PostgreSQL ou MySQL
> 
> 
> ### Ferramentas
> 
>     * GitHub
> 
>     * Vercel
> 
>     * Docker
> 
>     * AWS (desejável)
> 
> 
> ## Responsabilidades
> 
>     * Desenvolver e manter funcionalidades em ambiente de produção;
> 
>     * Construir soluções escaláveis e de fácil manutenção;
> 
>     * Participar das definições de arquitetura e decisões técnicas;
> 
>     * Integrar APIs de terceiros e sistemas de pagamento;
> 
>     * Otimizar desempenho, SEO e experiência do usuário;
> 
>     * Realizar revisão de código e colaborar com outros membros da equipe;
> 
>     * Escrever código limpo, documentado e testável;
> 
>     * Identificar e corrigir bugs e problemas de produção.
> 
> 
> ## Requisitos
> 
>     * Experiência sólida com Next.js e React;
> 
>     * Domínio de TypeScript;
> 
>     * Experiência profissional com Node.js;
> 
>     * Experiência no desenvolvimento de aplicações web em produção;
> 
>     * Conhecimento em APIs REST e modelagem de banco de dados;
> 
>     * Familiaridade com Git e fluxo de trabalho utilizando GitHub;
> 
>     * Boa comunicação e capacidade de trabalho remoto;
> 
>     * Capacidade de atuar de forma independente e resolver problemas complexos.
> 
> 
> ## Diferenciais
> 
>     * Experiência com plataformas de e-commerce;
> 
>     * Experiência com integrações de pagamento (Stripe, PayPal ou similares);
> 
>     * Conhecimento em deploy e infraestrutura na Vercel;
> 
>     * Experiência com SEO técnico;
> 
>     * Experiência com AWS ou outras plataformas cloud;
> 
>     * Interesse por futebol, esportes ou mercado japonês.
> 
> 
> ## O que Oferecemos
> 
>     * Projeto de longo prazo;
> 
>     * Horário flexível;
> 
>     * Trabalho 100% remoto;
> 
>     * Participação em decisões técnicas e estratégicas;
> 
>     * Ambiente colaborativo e focado em resultados;
> 
>     * Oportunidade de construir um produto com potencial de crescimento internacional.
> 
> 
> ## Como se Candidatar
> 
> Por favor, envie:
> 
>     1. Perfil do GitHub;
> 
>     2. Portfólio ou projetos relevantes;
> 
>     3. Experiência com Next.js, React e Node.js;
> 
>     4. Pretensão de valor (hora ou mensal);
> 
>     5. Disponibilidade para início.
> 
> 
> ## Contato
> 
> Telegram: @fabio_cto
> 
> Ou responda diretamente nesta Issue com uma breve apresentação e links para seus projetos.
> 
> Estamos em busca de profissionais apaixonados por tecnologia e interessados em construir produtos de alta qualidade.

nao vale mais a pena abrir uma nova issue?
Essa foi fechada ja
