### ISSUE TITLE
[Remoto] Desenvolvedor Mobile React Native na TOTVS Labs

### ISSUE THREAD

**Issue by Bruno-Furtado** [react-brasil/vagas#255]
## Descrição da vaga

TOTVS Labs is looking for a Senior Mobile Developer to work on the mobile app of our Machine Learning Platform, Carol.

Some things our app can do with our Platform: Answer questions about our customers' businesses (via voice and text), predict business outcomes, present valuable and beautiful insights, recognize faces, objects and actions.

## Local

Remoto

## Benefícios

- Contrato para prestação de serviços negociável.

## Requisitos

**Obrigatórios:**
- High proficiency in mobile development with apps deployed to the App Store and Play Store.
- Extensive programming experience in Java, Cocoa Touch, & Objective-C and/or C++.
- Strong object-oriented skills including design, coding, and testing patterns.
- Experience with third-party libraries and APIs.
- Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies
- UI Skills - You can develop pixel perfect interfaces and are passionate about delivering a great user experience

**Desejáveis:**
- Knowledge of UI and animation frameworks, touch user interface.
- Proficiency using devices sensors e.g., camera, microphone, gps, etc; and interacting with them
- Good experience with Git and GitHub.

**Diferenciais:**
- BIG Plus: Experience with React-Native.

## Contratação

Contrato de prestação de serviço com a TOTVS Labs, localizada nos EUA (na grande maioria dos casos PJ).

## Nossa empresa

TOTVS Labs develops innovative and disruptive technology for enterprises, enabling them to accelerate growth to become more competitive in a global economy. 

## Como se candidatar

https://totvslabs.recruiterbox.com/jobs/fk0mcaj/

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/PJ
- remuneração/5k-10k

**Comment by Bruno-Furtado** [comment]
A vaga ainda está disponível.

**Comment by emersonbrs** [comment]
Caso não tenhamos ainda projetos na PlayStore, ainda assim posso me candidatar?
Posso enviar meu CV em português? Ou deve ser em inglês?

**Comment by Bruno-Furtado** [comment]
Olá @emersonbrs, 

Sem problemas, pode se inscrever mesmo que sem projetos na PlayStore.

Com relação ao currículo, o ideal é que seja enviado em inglês.
Não se preocupe, compreendemos que esse não é o idioma nativo dos brasileiros.
Entendendo e conseguindo se comunicar, está valendo.

Segue link abaixo:
https://totvslabs.recruiterbox.com/jobs/fk0mcaj/

**Comment by Bruno-Furtado** [comment]
A vaga ainda está disponível.

**Comment by Bruno-Furtado** [comment]
A vaga ainda está disponível.
