### ISSUE TITLE
[Remoto] React Developer Pleno/Sênior na Fit Anywhere

### ISSUE THREAD

**Issue by ComunicaFit** [react-brasil/vagas#2564]
## Descrição da vaga
* Criação e manutenção do webapp, dashboard e mobile

## Local
* Remoto

## Requisitos
*Obrigatórios:*

* Experiência com React
  * Hooks
  * Custom Hooks
  * Redux
  * Router
* Firebase (Realtime Database, Firestore, Functions, Hosting)
* Bons conhecimento em JavaScript e SCSS

*Desejáveis:*

* Typescript
* Styled-components
* React Native
* Testes unitários e end-to-end

## Benefícios
* Férias pagas

## Contratação
* PJ

## Nossa empresa
A Fit Anywhere é o maior aplicativo de wellness do Brasil, presente em mais de 25 mil residências. Nosso objetivo é transformar a vida das pessoas levando mais saúde e qualidade de vida a todos os brasileiros, com muita praticidade e excelente custo x benefício, além de uma elevada variedade de treinos, para que cada cliente ache algo que ama fazer e FAÇA!
Então, se você gosta de um ambiente dinâmico, tem visão empreendedora, é ousado e quer transformar o mundo da prática de exercício físico no Brasil, a Fit é o seu lugar!

## Como se candidatar
Envie um email com o assunto *"Vaga React"* para [comunicacao@fitanyw.com.br](mailto:comunicacao@fitanyw.com.br) com o seu CV e pretensão salarial.

## Labels
- 🏢 Flexível
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by Cientista-Avogadro** [comment]
ja me inscrevi
