### ISSUE TITLE
[Remoto][Rio de Janeiro] Mobile Front-End Developer / React Native no ProEnem

### ISSUE THREAD

**Issue by aroff** [react-brasil/vagas#260]
## Descrição da vaga

*ProEnem* é uma das startups de ensino à distância que mais cresce no Brasil e está contratando desenvolvedores para atuar em projetos baseados em React Native.

## Local
Remoto

## Requisitos

**Obrigatórios:**
- Pelo menos 1 ano de experiência profissional com React Native
- Pelo menos 5 anos de experiência em desenvolvimento em geral
- Disponibilidade para viagem (2 vezes ao ano) para a sede da empresa, no Rio de Janeiro

**Desejáveis:**
- Typescript
- NodeJs

## Contratação

PJ a combinar. 

## Nossa empresa

Nós somos cerca de 100 colaboradores e nosso escritório fica no Centro Metropolitano, próximo ao Shopping Metropolitano, com uma infra-estrutura super moderna!
Referências: www.proenem.com.br e https://www.youtube.com/user/ProENEMOficial

## Como se candidatar

Por favor envie um email para reactdev@proenem.com.br com seu CV anexado - enviar no assunto: "Vaga React Native". 

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis.

## Labels

- PJ
- Pleno
- Remoto
- Sênior

**Comment by raivieiraadriano92** [comment]
Bom dia, tudo bem?
A mensagem está voltando dizendo que o e-mail não existe, teria algum outro e-mail para contato?

**Comment by igorsfreitas** [comment]
Boa tarde ! O email está voltando, como não existente, tem outro email que possa enviar ?

**Comment by aroff** [comment]
> Bom dia, tudo bem?
> A mensagem está voltando dizendo que o e-mail não existe, teria algum outro e-mail para contato?

Por favor, pode enviar novamente. Já foi resolvido!

**Comment by raivieiraadriano92** [comment]
Enviado :)

**Comment by leonardorpr** [comment]
Enviado (:

**Comment by Ramon-Lobo** [comment]
Enviado :)
