### ISSUE TITLE
[Remoto] React Native Developer @ Grupo Primo

### ISSUE THREAD

**Issue by brenooliveira** [react-brasil/vagas#2603]
# JOB DESCRIPTION
Buscamos pessoas com experiência em lançamento de apps nas lojas (Google Play e Apple Store), ter conhecimentos em TypeScript e JavaScript (ES6+), trabalhará no desenvolvimento de alguns aplicativos Mobile (Android e iOS) com React Native. Além de fazer publicação do aplicativo nas Plataformas Play Store (ANDROID) e App Store (IOS) e outras atividades.

#MAIN RESPONSIBILITIES
Desenvolvimento do nossos aplicativos Mobile (Android e iOS) com React Native;

Publicação do aplicativo nas Plataformas Play Store (ANDROID) e App Store (IOS);

Construir componentes e bibliotecas reutilizáveis;

#REQUIREMENTS AND SKILLS
 - Experiência com desenvolvimento frontend web/mobile;
 - Conhecimento em React Native;
 - Experiência com consumo de APIs REST;
 - TypeScript e JavaScript (ES6+);

# Desejáveis
 - Testes automatizados (TDD/BDD);
 - Redux

# Diferencial

 - Um bom GitHub e contribuições Open-source
 - Swift ou Kotlin;
 - Entendimento de serviços financeiros, uma pessoa com experiência no mercado financeiro também é um plus.

## Tecnologia
 - TypeScript e JavaScript;
 - React
 - ReactNative

# ADDITIONAL INFORMATION
Salário compatível com o mercado (Contratação poderá ser PJ ou CLT)
Vale Refeição
Vale Alimentação
Vale Transporte
Plano de Saúde Amil
Seguro de Vida

#Envie seu currículo para
https://grupoprimoio.gupy.io/jobs/2606615

# SOBRE NÓS
O Grupo Primo é uma empresa que nasceu de um único propósito: Dar acesso.

Somos um ecossistema que busca democratizar o acesso ao conhecimento para pessoas que almejam conquistar liberdade financeira. Por meio de canais de audiência e tecnologia proprietárias, distribuímos conteúdo de alta qualidade e facilitamos sua aplicação em diferentes segmentos de mercado.

Contamos com uma equipe de 189 pessoas apaixonadas pelo que fazem e perseguem juntas um plano de crescimento ambicioso em um conglomerado com quase 20 marcas.

Ambição justificável pelo tamanho dos nossos números: alcance digital das marcas e plataformas é de mais de 11 milhões de seguidores no Instagram, mais de 7 milhões de inscritos no Youtube, 200 mil alunos entre cursos e plataformas e alguns dos podcasts mais ouvidos do Brasil, como Primocast e Os Sócios. Temos a assinatura dos cursos de marketing digital, finanças e tecnologia como principal fonte de receita.

Por meio da nossa expertise em finanças, performance e tech, agregamos as marcas e plataformas:

https://staage.com/

https://www.finclass.com/

[instagram.com/oprimorico](http://instagram.com/oprimorico)

[instagram.com/bruno_perini](http://instagram.com/bruno_perini)

[instagram.com/joeljota](http://instagram.com/joeljota)

[instagram.com/carlosbusch/](http://instagram.com/carlosbusch/)

A ação conjunta dessas empresas garante sinergias de negócios que promovem um modelo educacional focado em conhecimento, empregabilidade e entretenimento à comunidade na qual está inserida.

**Comment by matheuscastro77** [comment]
Olá, tenho interesse
Como me candidato a vaga?
