### ISSUE TITLE
[São Paulo] - Front End Developer no iFood

### ISSUE THREAD

**Issue by JrFarias** [react-brasil/vagas#262]
Valorizamos a diversidade e estamos em busca de todos os ingredientes que se complementam e fortalecem nossa cultura e valores.

O que você irá entregar:

- Desenvolver produtos web utilizados por clientes internos garantindo a qualidade e performance
- Participar da concepção de APIs
- Integração com o backend
- Participar da priorização de evoluções no produto, levando em conta os melhores ganhos de valores para o negócios

Conhecimentos necessários:

- Ser apaixonado por desenvolvimento de software
- Javascript (ES5, ES6), HTML e CSS
- Experiência com ReactJS e Redux
- Automatização de builds / tooling (NPM, Webpack)
- Experiência com testes automatizados, unitários e comportamentais
- Tenha experiência com ferramentas de versionamento de código, preferencialmente Git;
- Já tenha trabalhado em culturas de desenvolvimento ágil e metodologias como Kanban e/ou Scrum.
- Noções de UX e design de interação.

O que vamos te entregar:

- Autonomia para trabalhar com um produto que realmente afeta a vida de milhões de usuários, que está em um mercado de constante crescimento.
- Empresa que cresce 300% ao ano e que ainda mantém a cultura e dia a dia de uma Startup.
- Contratação CLT com benefícios
- Participação nos Lucros - PLR;
- Ambiente altamente colaborativo, com grande autonomia e baixa burocracia

 - Link: https://jobs.kenoby.com/ifood/job/desenvolvedor-frontend-pleno/5ca7c31816ed1627a166e420

slack: React Brasil - Junior Farias

Labels:
- alocação/Presencial
- experiência/Pleno
- regime/CLT

**Comment by julioxavierr** [comment]
@JrFarias favor adicionar as labels para marcação

**Comment by Joaovsa7** [comment]
Nivel pleno?

**Comment by JrFarias** [comment]
@Joaovsa7 Nivel pleno para Senior haha
