### ISSUE TITLE
Remoto | Desenvolvedor (a) React Native @Develcode

### ISSUE THREAD

**Issue by milena-zlonghi-develcode** [react-brasil/vagas#2620]
**Nossa empresa**

A Develcode é uma empresa especializada no desenvolvimento de software, reconhecida pelo GPTW e por sua excelência. Os profissionais que a compõem possuem uma sólida experiência no mercado de TI. Há mais de 7 anos no mercado, atua com projetos diversificados, proporcionando soluções de valor para atender as necessidades do cliente e seu negócio. Possuímos grandes clientes que atuam no Brasil e no mundo, trabalhando com desenvolvimento ágil através de SQUADs.
Nossa matriz se encontra em Caxias do Sul - RS, mas nossa equipe é composta por mais de 70 colaboradores está por todo o território brasileiro.

-> https://www.develcode.com.br/
__________________________________________________________________________________________________________

**Descrição da vaga**

Buscamos Desenvolvedor (a) Sênior React Native para atuar como mentor de profissionais júniors.
__________________________________________________________________________________________________________

**Local**

Remoto
__________________________________________________________________________________________________________

**Benefícios**

- Vale Alimentação;
- Auxílio creche;
- Auxílio saúde;
- Auxílio Home Office;
- Inglês in Company;
- Plataforma de Cursos Alura;
- Benefícios flexíveis.
- E muita troca de conhecimento e experiências.
__________________________________________________________________________________________________________

**Requisitos**

- Imprescindível experiência com React Native, Node e Typescript;
- Conhecimentos em Graphql. Firebase, Aws Continuous Integration;
- Conhecimentos em metodologias ágeis;
- Boa comunicação;
- Desejo e motivação para ensinar.
__________________________________________________________________________________________________________

**Contratação**

CLT
__________________________________________________________________________________________________________

**Carga horária**

Full time, em horário comercial.
__________________________________________________________________________________________________________

**Nível**

Sênior
__________________________________________________________________________________________________________

**Para se candidatar** 

Por favor, envie um email para milena.longhi@develcode.com.br com seu CV anexado - enviar no assunto: Vaga React Native.
__________________________________________________________________________________________________________

Buscamos desenvolver e encontrar novos talentos, e você pode ser um deles! Vem pra Devel!
![React Native novo](https://user-images.githubusercontent.com/108018549/180245878-6de18f5d-2d79-4b32-94dc-46fd6b75c471.png)

**Comment by andriele-silveira-develcode** [comment]
Excelente oportunidade!!!
