### ISSUE TITLE
VAGA FECHADA [Joinville-SC - Híbrido/Presencial] Front-end Developer React CLT/PJ JR na CREDINET 

### ISSUE THREAD

**Issue by larissazz** [react-brasil/vagas#2631]
## Descrição da vaga

Desenvolvedor(a) Front End Júnior, com pelo menos um ano de experiência com React, Html e CSS, para integrar nossas equipe de desenvolvimento e manutenção de softwares relacionados a meios de pagamentos e gestão de recebíveis.

## Local

Joinville-SC - Híbrido/Presencial

## Benefícios

-Almoço (sem desconto em folha)
-Café da Tarde
-Vale transporte (sem desconto em folha)

## Requisitos

O que você precisa conhecer
-React
-HTML
-CSS

Pra ter aquela vantagem extra
-Formação em TI
-Redux/Context
-Hoocks
-AWS
-Ux/UI
-Graphql
-Metodologia Solid

## Contratação

CLT ou Pessoa Jurídica

## Nossa empresa

Somos uma empresa de meios de pagamento que vem crescendo muito nos últimos anos. Queremos cada vez mais proporcionar aos nossos clientes um sistema completo que proporcione agilidade e praticidade na gestão de recebíveis.
Nossos valores são: Disciplina Estratégica; Valorização das pessoas; Compromisso com o Crescimento e Resultados; Prática da Inovação.

Com todo esse crescimento, precisamos de profissionais diferenciados para nos ajudar nesse crescimento.
Se você gostou dos nossos valores, vamos conversar!

## Como se candidatar

Saiba mais sobre essa grande oportunidade e se candidate no site (basta fazer login e inserir seus contatos): https://vagas.hunterco.com.br/job/62f29e568c6141001eaaa1cb?r=hmshlf&c=4740

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 5 dias úteis após cada processo. Depois da candidatura no site, entraremos em contato para alinhamento e marcar entrevista.

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Híbrido
- 👦 Júnior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 6k-10k

**Comment by SmokeBr** [comment]
Ops... Esta vaga não está mais ativa...

**Comment by larissazz** [comment]
Para + vagas em React acesse: https://vagas.hunterco.com.br/search?c=4740&q=react
