### ISSUE TITLE
DESENVOLVEDOR FRONT END - REACT - REMOTO - INTELLIMETRI

### ISSUE THREAD

**Issue by gabrielanatascha** [react-brasil/vagas#2653]
Estamos em busca de um Desenvolvedor FRONT-END Pleno ou Sênior:

Se você gostaria de entrar para um time tendo como principal objetivo contribuir com a Transformação Digital por meio de inteligência artificial e do Machine Learning, essa vaga é para você!

Requisitos: curso superior completo ou cursando nas áreas de programação;  experiência mínima de três anos no desenvolvimento atuando com React, conhecimento de metodologias ágeis, disponibilidade para atuar remoto e full time. 

Modelo de contrato: PJ 
- Remuneração á combinar. 

Interessados encaminhar currículo para: [gabriela@escolhacertarh.com.br](mailto:gabriela@escolhacertarh.com.br). 

#escolhacertarh #vagasti #desenvolvimento #react #javascript #frontend #vagasc #developer

**Comment by rafaelsatyro** [comment]
Enviado!
