### ISSUE TITLE
[REMOTO] React Native em Meshme - próximo unicórnio!

### ISSUE THREAD

**Issue by reichert** [react-brasil/vagas#2664]
## Descrição da vaga
- Desejamos trazer o primeiro desenvolvedor para uma empresa inovadora com alto potencial de crescimento e internacionalização, que pode ser o próximo unicórnio brasileiro;
- Gostaríamos de alguém que esteja conosco no longo prazo, sabendo tomar decisões e sendo líder dos próximos que vierem depois de você;

## Habilidades que esperamos
- Senso de dono;
- Senso de urgência;
- Capacidade de se organizar e priorizar suas atividades;

## Local
- Possibilidade de 100% Remoto;
- Horário de trabalho das 8h30 as 17h30 com flexibilidade de ajustes (a combinar);

## Benefícios
- Bônus por lançamento do aplicativo no prazo
- Day off no dia do aniversário
- Vale Alimentação
- Férias remuneradas
- Décimo terceiro salário
- Remuneração a combinar

### Diferenciais
- Day off no aniversário
- Abertura com os fundadores e sócios
- Proximidade com a startup que estará junto a fundos de investimento e venture capital

## Requisitos **Obrigatórios:**
- 3 anos de experiência com desenvolvimento React Native
- Experiência com serviços REST
- Capacidade de aprender o fluxo de negócio da aplicação

## Requisitos **Desejáveis:**
- Experiência de publicação nas lojas Apple Store e Google Play
- Conhecimentos de autenticação com JWT

## Contratação
- CLT ou PJ (a combinar)

## Como se candidatar
- Por favor envie um email para rh@meshme.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k

**Comment by carmonaleonardo** [comment]
E-mail enviado!

**Comment by CaioChristhian** [comment]
e-mail enviado
