### ISSUE TITLE
[São Paulo] Front-End Developer ReactJS na vetfy 

### ISSUE THREAD

**Issue by felipealvarenga** [react-brasil/vagas#267]
Você quer construir a revolução da saúde dos Pets?

Possibilidade de se tornar dono da empresa dependendo unica e exclusivamente do seu desempenho?

É front-end developer - HTML, JavaScript (ReactJS/React-Native) e CSS ?

Então essa vaga é para você!

## Descrição da vaga

Participar do time de desenvolvimento da plataforma, desenvolvendo na atual arquitetura em HTML/ReactJS/React Native, com firebase de backend.  

Aqui você não será uma máquina de produzir código, e sim uma cabeça pensante que será desenvolvida pelo nosso time, para crescer junto a empresa.

## Local

Remoto(eventualmente) / WeWork (Av das Naçoes Unidas 14261)

#### Diferenciais

- Participar de um desenvolvimento de startup em crescimento exponencial
- Ser Dono! Sociedade no médio prazo
- Ter voz ativa no desenvolvimento dos produtos
- Trabalhar em CoWorking WeWork

## Requisitos

**Obrigatórios:**
- Gostar de Pet
- Vontade de aprender
- Vontade de realizar algo que nunca fez antes na vida
- HTML/JavaScript(ReactJS/React Native)/CSS

## Contratação

PJ a combinar

## Nossa empresa

Nós somos uma plataforma que conecta os donos de animais de estimação aos veterinários, para realizarem atendimentos em domicilio (Consultas, Exames e Vacinas). 
Temos como objetivo de levar a todos os lares do Brasil, a saúde que os pets merecem!

## Como se candidatar

Por favor, email para contato@vetfy.com.br com seu CV anexado - enviar no assunto: Vaga Front-End ReactJS.

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Júnior
- regime/PJ
- remuneração/1k-3k
- remuneração/3k-5k

**Comment by felipealvarenga** [comment]
- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Júnior
- regime/PJ
- remuneração/1k-3k
- remuneração/3k-5k

**Comment by gabrielferreiraa** [comment]
Possível 100% remote?

**Comment by felipealvarenga** [comment]
@gabrielferreiraa É possível sim!
