### ISSUE TITLE
Vagas para Programador conhecimento em React

### ISSUE THREAD

**Issue by rodriggozr** [react-brasil/vagas#2672]
## Empresa:
**React JS Developer na Brajan Sistemas [www.brajan.com.br](url)**

## Descrição da vaga

Projeto Diversos com React 

## Local

Remoto ou Escritório, Vitória - ES

**Obrigatórios:**
Conhecimento em HTML,JS,CSS, React, 

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para curriculo@brajan.com.br  com seu CV anexado - enviar no assunto: Vaga React 

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Estágio
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ
- 💰 1k-3k

**Comment by saviocunha2** [comment]
mandei currículo e moro em vitória

**Comment by jonatasvaz** [comment]
Currículo enviado

**Comment by rafaelsatyro** [comment]
Cv enviado!

**Comment by CaioChristhian** [comment]
currículo enviado

**Comment by Asmodaeuz** [comment]
Feito!

**Comment by Ari-Neto-dev** [comment]
Boa Sorte ! a todos e todas

**Comment by brunoro7** [comment]
Enviei o currículo.

**Comment by ItaloRAmaral** [comment]
Currículo Enviado

**Comment by lnabesima** [comment]
CV Enviado!

**Comment by pdiegoneves** [comment]
Currículo enviado

**Comment by pumba-dev** [comment]
Done!

**Comment by PauloAbrahao** [comment]
Enviado!

**Comment by DarcioCarvalho** [comment]
Olá. Tudo bem?

Enviei no e-mail indicado o meu currículo e informações adicionais.

Abraços!!!

**Comment by walissonwaal** [comment]
Boa tarde! 

Currículo e portfólio enviados. 

Att, 

Walisson Gomes.

**Comment by racalixta** [comment]
Currículo enviado!

**Comment by RuanHeleno** [comment]
Currículo enviado!

**Comment by PauloAbrahao** [comment]
Boa tarde!
Enviei meu currículo e portfólio! 
Desde já agradeço a oportunidade :)

**Comment by rafaelsilva81** [comment]
Enviado!! 🚀

**Comment by LukeRocha** [comment]
Enviei o meu também!

**Comment by FeRiffo** [comment]
enviado!

**Comment by PhilipeF** [comment]
Atendo todos os requisitios da vaga, currículo enviado!

**Comment by Bikel20** [comment]
cv enviado !

**Comment by ArthuurTorres** [comment]
Boa tarde, enviado!

**Comment by taciodev** [comment]
Acabei de enviar meu CV.

**Comment by leonardo-cabral67** [comment]
CV Enviado!
