### ISSUE TITLE
[Remoto] React Developer na Envolti Sistemas

### ISSUE THREAD

**Issue by elzaneicmelo** [react-brasil/vagas#2691]
## Descrição da vaga

O profissional vai atuar em projeto desenvolvido zero, codificando diretamente na Squad de Front-End com React - será desenvolvido  um sistema voltado ao gerenciamento de produtos. 

## Local
Atuação 100% remota.

## Requisitos

**Obrigatórios:**
- ReactJS (Create-React-App e NextJs);
- Gerenciamento de estado (Redux, MobX e Recoil);
- Separação e desenvolvimento de componentes;
- Isolamento de responsabilidade;
- Definição de estilo;
- Bibliotecas de UI;
- Ferramentas de testes (Jest e Cypress).

**Desejáveis:**
- Javascript e Typescript;
- HTML e CSS;
- Versionamento de código com Git e pipeline via Gitlab.

**Diferenciais:**
- Conhecimento básico em containers (Docker e Kubernetes);
- Metodologia de desenvolvimento ágil (Scrum e Kanban).

## Contratação

Modalidade PJ - Valor a negociar

## Nossa empresa

A Envolti Sistemas possui um histórico de mais de 10 anos de experiência no segmento de TI, no decorrer dessa trajetória auxiliamos nossos clientes nos projetos e na sustentação diária de sistemas, com foco no aumento da produtividade, redução de custos, na melhor utilização e investimento dos seus ativos de TI. Tudo alinhado às melhores práticas e ao que o mercado precisa.

## Como se candidatar

Por favor envie um email para rh1@envolti.com.br com seu CV anexado - enviar no assunto: Vaga React Developer

## Labels
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by MateusHoffman** [comment]
Enviado!

**Comment by rafaelsatyro** [comment]
Enviado!

**Comment by GabriellCastro** [comment]
Enviado 😎
