### ISSUE TITLE
[São Paulo] Desenvolvedor Front-End Sênior (React Native)

### ISSUE THREAD

**Issue by taiananegrelli** [react-brasil/vagas#272]
## Descrição da vaga

Participar das etapas de ideação, prototipação e codificação dos aplicativos e interfaces web;
Escrever código… Mas tem que ser limpo, lógico e funcional para aplicações;
Sugerir melhorias e soluções para aplicações existentes;
Definir e atender os requerimentos técnicos e de design das aplicações;
Administrar a própria energia e encorajar, servir de exemplo e recompensar boas energias dos colegas.

## Local

Av. Engenheiro Luis Carlos Berrini, 1748. São Paulo, SP 04571-000

## Benefícios

Vale alimentação R$500/mês
Vale transporte
Pacote de stock options da empresa

## Requisitos

Tenha sólido conhecimento em programação, padrões de projeto e engenharia de software;
Tenha experiência em React e React Native;
Tenha experiência em APIs REST;
Tenha experiência com o processo de distribuição da App Store e Google Play;
Tenha experiência em Cloud (Azure, AWS, Google Cloud ou outro);
Tenha participado de todas as etapas do desenvolvimento de aplicativos mobiles e sites;
Acompanhe e implemente boas práticas de segurança da informação;
Saiba aplicar guidelines (Apple, Google ou outro);
Goste de opinar na arquitetura dos produtos;
Goste muito de UI e UX;
Tome café;

**Desejáveis:**
Node
Mongo
PHP
mySQL
Nginx
Java
Git
IOT
Arduino
Raspberry Pi

## Contratação

CLT

## Nossa empresa

BovControl é uma plataforma que esta digitalizando a cadeia da pecuária. Com mais de 50 mil usuários no mundo todo, a startup tem por objetivo diminuir a fome no mundo empoderando pecuaristas com tecnologia.

www.bovcontrol.com

## Como se candidatar

Candidatura simplificada através do link:
https://vagas.hunterco.com.br/job/5cab5353ae3a9c00160f646e

**Comment by cbarauna** [comment]
A possibilidade de trabalho remoto?
