### ISSUE TITLE
[São Paulo] React Native Developer na DOTZ(Fintech)

### ISSUE THREAD

**Issue by bognarjunior** [react-brasil/vagas#274]
## Descrição da vaga

Estamos procurando desenvolvedores(as) para trabalhar no nosso novo projeto de meio de pagamentos da DOTZ. 

## SOBRE A DOTZ

O maior programa de fidelidade do varejo.
A Dotz é a moeda que faz a vida render mais para as pessoas e empresas. Uma extensão da renda de milhares de brasileiros. Tudo isso construído por pessoas que fazem a diferença diariamente, protagonizam a história da companhia e são apaixonadas pela nossa causa.

## Local

Escritório, Rua Joaquim Floriano, 553 - São Paulo - Itaim Bibi

## Benefícios

- VR de R$ 27/dia
- Reembolso estacionamento  R$ 150 
- PLR, mediante metas até 2 salários
- Férias remuneradas (20 dias)
- 13 salário

#### Diferenciais

- Horário flexível 
- Benefícios criativos em Dotz
- Day off no aniversário
- Dress Code

## Requisitos

**Atividades a serem desempenhadas:**
- Desenvolvimento de Apps em ambiente Cross-platform (React Native, Appcelerator, Flutter)
- Migração de código Nativo (Java/Kotlin e Object-C/Swift) para Cross-platform
- Manutenção de projetos existentes

**Obrigatórios:**
- Experiência com projetos mobile de médio e grande porte
- Conhecimentos avançados em JavaScript/ECMA
- Conhecimentos sólidos na construção e consumo de API’s
- Conhecimentos sólidos em OOP/FP
- Experiência com React Native / Redux
- Conhecimentos sólidos em versionamento de código com Git

**Desejáveis:**
- Conhecimentos em Java / Kotlin / Obj-C / Swift
- Conhecimentos em Appcelerator / Flutter
- Testes automatizados / TDD
- Ter apps já publicados na loja

**Diferenciais:**
- Experiência com Fabric / Firebase / GraphQL

## Contratação

PJ a combinar

## Nossa empresa

Hey, já imaginou trabalhar em um lugar que faz a sua vida render mais dentro de um ambiente leve e feliz construindo grandes realizações para sua carreira?! A Dotz é o maior programa de fidelidade do varejo e, além disso, uma extensão da renda de milhares de brasileiros. Tudo isso construído por pessoas que fazem a diferença diariamente, protagonizam a história da companhia e são apaixonadas pela nossa causa. Curtiu? Então venha ser um Dotzeiro! Confira as novas vagas que separamos para vc!

## Como se candidatar

Por favor envie um email para vagasbr@dotz.com com seu CV anexado - enviar no assunto: Vaga React Native

[https://www.vagasdotz.com/vagas](https://www.vagasdotz.com/vagas)

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ
- remuneração/5k-10k
- remuneração/10k-15k

**Comment by raivieiraadriano92** [comment]
Bom dia, tudo bem?
Alguma possibilidade de ser remoto?

**Comment by bognarjunior** [comment]
> Bom dia, tudo bem?
> Alguma possibilidade de ser remoto?

Rai, bom dia, infelizmente não, mas envia seu currículo lá, se por ventura eles abrirem remoto entram em contato.
