### ISSUE TITLE
[International/Remote] Senior Front-End Developer( React) on Turing 

### ISSUE THREAD

**Issue by Catiacamila** [react-brasil/vagas#2764]
## Description

A U.S.-based edtech company transforming the educational system by building customized learning solutions for young kids is looking for a Senior Front-End React Developer. The developer will take charge of improving the performance of front-end elements across all devices and browsers. The company is committed to helping students use the strength of cutting-edge contemporary technologies to achieve their educational and learning goals. The company has managed to raise close to $110 mn in funding. This position requires 6+ hours of overlap with the PST and EST time zones. 

## Job Responsibilities:

Create reusable, high-quality code to create a dynamic user interface across several platforms
Work together on project planning, idea sharing, code demonstrations, bug fixing, and bug fixing with senior developers, business partners, and project managers
Enhance front-end components' performance across all devices and browsers
Help team members adhere to the necessary industry standards and ensure that the architecture is compliant
Keep track of the status and development of the tasks that have been given to project teams and managers

## Job Requirements:

Bachelor’s/Master’s degree in Engineering, Computer Science (or equivalent experience)
At least 5+ years of relevant front-end development experience
Expertise in React
Deep architecture skills
Proficiency in English

##About Turing

Based in Palo Alto, California, Turing aims to unleash the world’s untapped human potential. We use AI to source, evaluate, hire, onboard, and manage engineers 100% remotely via a bigger platform that we call the “Talent Cloud”.
Today, Turing is one of the fastest-growing unicorns, with a valuation of $1.1B, after raising over $140M over four rounds of funding. 100+ companies including the likes of Johnson & Johnson, Pepsi, Dell, Disney +, and Coinbase have hired Turing developers.

## 💥Link to apply:

https://admin.goboon.co/job-post/1n4pU722Ea4ueQ6aqu

Note: It is necessary for the candidate to take a quick technical test to confirm that he has the skills informed in the registration.

Dollar remuneration 💰
Remote work 🏡
Labels:
🏢 Remoto
👨 Pleno
👴 Sênior
💰 5k-10k U$$

catiacamila.recruiter@gmail.com

**Comment by joaoromeira** [comment]
Hey! How are you? Unfortunately I don't have English proficiency, my current level is B1, but I will be happy if you save my resume in talent base for future opportunities. Could i send it to you? @Catiacamila

**Comment by Catiacamila** [comment]
Olá João, tudo bem?
Claro, pode me enviar😊

Em qui., 15 de dez. de 2022 às 08:22, João ***@***.***>
escreveu:
