### ISSUE TITLE
[FECHADA] React Developer (Junior) na Payfy

### ISSUE THREAD

**Issue by tavarescarolina** [react-brasil/vagas#2774]
Devido a alta procura, não estamos mais aceitando candidatos

## Descrição da vaga

Estamos em busca de um desenvolvedor frontend junior para trabalhar com React e Typescript. Não é necessário ter experiência previa na área ou com as tecnologias mencionada, apenas ter noção sobre linguagens de programação, estar disposto a se dedicar a estudar e a crescer e a trabalhar em equipe.

## Local

Vaga 100% remota

## Contratação

PJ com salário até 3k

## Nossa empresa

A payfy é uma fintech gastos corporativos para equipes com visão de futuro.
Permitimos que os funcionários comprem o que precisam para o trabalho, enquanto mantemos as empresas no controle total de todos os gastos.
Com a ajuda de tecnologia inovadora e cartões corporativos, a payfy elimina relatórios de despesas, reduz a complexidade administrativa e simplifica a contabilidade.
Os nossos clientes são empresas de médio e grande porte e que precisam gerenciar suas despesas corporativas de forma mais eficiente.

## Como se candidatar
Entre em contato no linkedin https://www.linkedin.com/in/carolina-pinheiro-tavares/ ou mande um email para carolina@payfy.io

## Labels

- 🏢 Remoto
- 👦 Júnior
- ⚖️ PJ
- 💰 1k-3k

**Comment by danyelica** [comment]
Currículo enviado!

**Comment by RRyanDEV** [comment]
Currículo enviado!

**Comment by wuzue** [comment]
Enviado! :)

**Comment by Henry001-prog** [comment]
Enviado

**Comment by marcossnikel** [comment]
Enviei uma mensagem no Linkedin , gostei muito da vaga

**Comment by JenifferMendes** [comment]
Enviado!

**Comment by praxeds** [comment]
Enviado ^^

**Comment by Asmodaeuz** [comment]
Enviado!

**Comment by ribeirojer** [comment]
Enviado! 👋

**Comment by YannFigueiredo** [comment]
Enviado! ^u^

**Comment by ViniZap4** [comment]
Hey @tavarescarolina, te enviei um e-mail!, espero poder fazer parte do time e poder crescer na payfy!

**Comment by Italogoncalves1** [comment]
Falei no Linkdin

**Comment by gxmxntx** [comment]
Enviado!

**Comment by PhilipeF** [comment]
Olá Carolina currículo enviado por email, e se preferir pode acessar o meu site portfólio [(https://philipef-dev.vercel.app/)] onde também é possível fazer download currículo, conferir um pouco da minha caminha até aqui, as skills e projetos ja desenvolvidos.

**Comment by arlisson314** [comment]
Olá Carolina já enviei meu currículo por email, também te enviei uma mensagem no Linkedin.

**Comment by devpolatto** [comment]
Boa tarde! Carolina! Enviei o meu currículo por e-mail

**Comment by JVMC42** [comment]
Bom dia, já enviei mensagem no linkedin e email

**Comment by antoniornneto** [comment]
Boa tarde, currículo enviado por e-mail. Boa sorte a todos!

**Comment by thiagocef** [comment]
Enviado

**Comment by EnriqueSantos-dev** [comment]
Enviado mensagem no LinkedIn

**Comment by Gabriela74** [comment]
Boa noite, e-mail enviado !!

**Comment by KaminskiFking** [comment]
Boa noite, email e curriculo enviado!

**Comment by DarcioCarvalho** [comment]
Olá, Carolina. Tudo bem?

Enviei no e-mail indicado o meu currículo e informações adicionais.

Abraços!!!

**Comment by GabrielBento299** [comment]
Bom dia!! Currículo enviado por e-mail.

**Comment by nayonsg** [comment]
Olá, Carolina! Tudo joia?

Te enviei um e-mail com meu currículo e portfolio e aguardo sua resposta!

Abraços!

**Comment by brunocarmena57** [comment]
Enviado!

**Comment by thalesfelippe** [comment]
Oi Carolina, enviei um e-mail com meu currículo e portfolio

**Comment by PauloAbrahao** [comment]
Oi Carolina! Enviei um email contendo meu currículo e portfólio!

**Comment by felipejesus-front** [comment]
Enviado Carol! Currículo e um projeto mais recente.

**Comment by f3rnandorj** [comment]
currículo enviado, tanto LinkedIn quanto e-mail

**Comment by eemr3** [comment]
Currículo enviado.

**Comment by marelps** [comment]
Currículo enviado!

**Comment by Sustavo** [comment]
Currículo enviado por email !

**Comment by Francisco-Fetapi** [comment]
Currículo enviado.

**Comment by Ari-Neto-dev** [comment]
[curriculo-the-best.pdf](https://github.com/react-brasil/vagas/files/10536078/curriculo-the-best.pdf)

**Comment by FeRiffo** [comment]
Enviado!

**Comment by eemr3** [comment]
Enviado!
