### ISSUE TITLE
[São Paulo] React JS Developer na CrediHome (Jr/Pleno)

### ISSUE THREAD

**Issue by Andreia-Marques** [react-brasil/vagas#278]
## Descrição da vaga

Estamos com uma oportunidade para Desenvolvedor React JS na Credihome, uma startup de crédito imobiliário que esta em um mercado de R$ 60 bi, um dos maiores do Brasil.
O ambiente é bem dinâmico com várias Startups, além de dividir muro com o Parque Ibirapuera.

## Local

Escritório, São Paulo - Moema

## Benefícios

- Não

#### Diferenciais

- Próximo ao Parque Ibirapuera

## Requisitos

**Obrigatórios:**
Javascript
- ReactJS
- CSS

**Diferenciais:**
- Conhecimentos em SASS e Redux

## Contratação

PJ de R$4 a R$6 (dependendo da experiência)

## Nossa empresa

Credihome, uma startup de crédito imobiliário que esta em um mercado de R$ 60 bi, um dos maiores do Brasil.

## Como se candidatar

Por favor envie um email para am@individuals.io com seu CV anexado - enviar no assunto: Vaga React JS Developer na CrediHome (Jr/Pleno)

## Labels

- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/PJ
- remuneração/4k-10k

**Comment by ribeiroevandro** [comment]
Enviado.

**Comment by jrquadros** [comment]
Enviado

**Comment by Joaovsa7** [comment]
Enviado.
