### ISSUE TITLE
[Remoto] Engenheiro(a) de Software Full Stack Pleno (React & Node) na Findme

### ISSUE THREAD

**Issue by findmesp** [react-brasil/vagas#2783]
### **📌 Descrição da vaga**
A FindMe está revolucionando o mercado de segurança e facilities do Brasil, através da transformação digital de suas operações.
Nessa revolução, acreditamos que um time de desenvolvimento excepcional é fundamental para construir a melhor plataforma de gestão operacional do mercado de segurança e facilities. Dessa forma, estamos buscando um Desenvolvedor Full Stack.

Antes de requisitos técnicos, avaliaremos os seus valores, os que buscamos são:
- Transparência;
- Foco em crescimento (aprendizado e resultados);
- Atitude empreendedora;
- Adaptabilidade;
- Sangue no olho.

Você fará parte do squad Produto & Tecnologia, o time responsável pelos produtos e todo apoio tecnológico necessário da FindMe, composto por desenvolvedores full cycle, um P.O. e um UX/UI Designer.

Nele, você será responsável pelo planejamento, desenvolvimento, teste e manutenção de alguns de nossos produtos, além da criação de ferramentas para os demais núcleos da FindMe.

Juntos traçaremos um plano de desenvolvimento individual (PDI) para que você possa evoluir cada vez mais suas habilidades técnicas, tornando-se um desenvolvedor full cycle - responsável por todo o ciclo de desenvolvimento das plataformas - e também interpessoais, podendo liderar times e projetos de acordo com o nosso crescimento.

### **🏠 Local**
Remoto ou Escritório, São Paulo, Av. Consolação

### **📝 Requisitos**

- Experiência nas linguagens: React, React Native e Node.js;
- Experiência com Postgres;
- Conhecimento em Git e Docker.

### **📝 Desejável**

- TDD;
- Metodologias ágeis;
- Conhecer AWS, GCP ou Azure;
- Conhecimento de CI/CD;
- Conhecimento de microservices;
- MongoDB.

### **🚀 Benefícios**
✅ Plano de desenvolvimento individual;
✅ Gympass;
✅ Day off de aniversário;
✅ Remuneração Variável.

### **➕ Outras Informações**
Cultura de acolhimento, aprendizado contínuo e alta performance!;
Modelo de trabalho remoto ou presencial em São Paulo, com total liberdade geográfica;
Gostou da proposta? Você que gosta de aprender, se desafiar todos os dias e evoluir com um time incrível... Vem ser um Finder! [Candidate-se aqui!](https://trampos.co/oportunidades/743517-desenvolvedor-a-full-stack-react-node-pleno) ou pelo link [trampos.co/oportunidades/742270-engenheiro-de-software-full-cycle](https://trampos.co/oportunidades/743517-desenvolvedor-a-full-stack-react-node-pleno)

### **💰 SALÁRIO**
De R$ 6000,00 a R$ 7000,00

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by JoneBulande** [comment]
Olá espero que estaeja bem.
qual é o seu email no qual eu posso enviar a minha canditatura?
Desde já, demostro o meu interesse para a vaga.
