### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Fullstack Sênior na Cresol

### ISSUE THREAD

**Issue by jessymdrs** [react-brasil/vagas#2795]
## Local

Remoto 

## Benefícios

Vale Alimentação e/ou Refeição R$1.900,00
Seguro de Vida
Plano de Saúde Unimed
Plano odontológico
Previdência Privada 
PPR (Programa de Participação nos Resultados) 
Cartão Natal 
Auxílio Creche 

## Requisitos

Ampla experiência com desenvolvimento em Java 8.0;
Ampla experiência com Struts e React;
Conhecimento em arquitetura de sistemas;
Conhecimento em ambientes CLOUD e infraestrutura on premisse.

## Contratação

CLT

## Como se candidatar

Por favor envie um email para headhunter.jessica@gmail.com com seu CV anexado e/ou Linkedin - enviar no assunto: Pessoa Desenvolvedora Fullstack Sênior

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ CLT
- 💰 10k-15k

**Comment by joaoromeira** [comment]
@jessymdrs, tudo bem? Não possuo conhecimento em Java, porém tenho forte skill em React, posso deixar meu currículo para futuras oportunidades?

**Comment by jessymdrs** [comment]
Olá, João! Espero que esteja bem.

Pode sim, por favor.

Atenciosamente,
Jéssica Medeiros.

**Comment by joaoromeira** [comment]
Enviado!
