### ISSUE TITLE
[Joinville/SC] Pessoa Desenvolvedora FullStack Pleno na Method

### ISSUE THREAD

**Issue by jessymdrs** [react-brasil/vagas#2797]
## Local

Híbrido

## Contratação

PJ

## Como se candidatar

Por favor envie um email para headhunter.jessica@gmail.com com seu CV anexado - enviar no assunto: Vaga Pessoa Desenvolvedora FullStack Pleno

## Labels

- 🏢 Flexível
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by devRukasu** [comment]
Tem vaga pra WebDev Full Stack Jr?

**Comment by FeRiffo** [comment]
Enviado!
