### ISSUE TITLE
[Joinville/SC] Pessoa Desenvolvedora de Sistemas na Univille

### ISSUE THREAD

**Issue by jessymdrs** [react-brasil/vagas#2798]
## Local

Presencial - Joinville/SC

## Benefícios

Unimed Joinvile - Após 3 meses com coparticipação
Uniodonto - Após 3 meses com coparticipação
Bolsa de estudos em curso de graduação e pós graduação na Univille, após 3 meses (até 50%0
Vale alimentação valor R$440,00 a universidade subsidia 50% e o colaborador paga 50%.
Triênio, 3% do salário a cada 3 anos limitado a 21%.
Seguro de vida.
Psicólogo e Assistente Social para suporte e acolhimento.

## Requisitos

Conhecimento em Desenvolvimento de Software (qualquer linguagem, seria interessante conhecer front e back);
Experiência com SQL Server ou Oracle;
Experiência com sistema Totvs RM é essencial;
Experiência com mapeamento de dados;

## Contratação

CLT

## Como se candidatar

Por favor envie um email para headhunter.jessica@gmail.com com seu CV anexado e/ou Linkedin - enviar no assunto: Vaga Pessoa Desenvolvedora de Sistemas

## Labels

- 🏢 Presencial
- 👦 Júnior
- ⚖️ CLT
- 💰 5k-10k

**Comment by ribeirojer** [comment]
Currículo enviado!

**Comment by FeRiffo** [comment]
Enviado!

**Comment by Pedrohamoura-Git** [comment]
Enviado.

**Comment by luanargolodev** [comment]
Enviado! :)
