### ISSUE TITLE
Joinville-SC Pessoa Desenvolvedora Fullstack Pleno

### ISSUE THREAD

**Issue by Livia-Tech** [react-brasil/vagas#2800]
Desenvolvedor FullStack Pleno

Híbrido - Joinville/SC

PJ

Remuneração pode chegar a R$ 6.500,00

REQUISITOS OBRIGATÓRIOS:

Experiência de mercado com C# + Vue.js 

ou 

C# + JavaScript

ATIVIDADES:

Desenvolvimento de um sistema de gestão para indústria/varejo/postos de combustíveis.

ME CHAMA NO WHATSAPP (32) 98442-6808!

#desenvolvimento #javascript #varejo #csharp #vuejs

**Comment by ribeirojer** [comment]
Oi Lívia! Dá uma olhadinha aqui no meu GitHub, moro em Joinville e tenho conhecimento em Vue.

**Comment by Livia-Tech** [comment]
Me chama no whatsapp (32)98442-6808 e me envia seu currículo e linkedin lá


Livia Maria

Tech Recruiter
(32) 98442-6808
________________________________

**Comment by Livia-Tech** [comment]
Vaga fechada.
