### ISSUE TITLE
[Remoto] Frontend ReactJS Pleno ou Sênior - Sellers.com.br

### ISSUE THREAD

**Issue by marcelosv** [react-brasil/vagas#2801]
## Descrição da vaga

A vaga é de ReactJS e participar do nosso time de desenvolvimento.

## Local

Remoto

## Benefícios

- R$ 1300,00
- ...

#### Diferenciais

- Trabalho remoto
- Horário flexível
- Liberdade
- ...

## Requisitos

**Obrigatórios:**
- Conhecimento em ReactJS

## Contratação

Cooperativa

## Nossa empresa

Sellers
https://www.sellers.com.br/

Muito prazer, somos a Sellers!
Para nós as relações humanas são o motor das organizações. É por isso que aqui, nós acreditamos nessa força/engrenagem para potencializar negócios.
Somos o Branco Digital do Vendedor.
Nascemos para simplificar todo o processo de gestão, comunicação e distribuição de remunerações variáveis.
Nosso compromisso é potencializar suas vendas, de forma simples e ágil.
Através de uma plataforma digital completa, solucionamos todo o processo de incentivo de vendas, desde a comunicação em massa e acompanhamento de resultados em tempo real, até a distribuição de remunerações variáveis. Tudo em único lugar, de forma fácil e escalável.

## Como se candidatar

Por favor envie um email para marcelo@sellers.com.br com seu CV anexado - enviar no assunto: [Remoto] Frontend ReactJS Pleno ou Sênior

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Cooperado

**Comment by lucioroadtoglory** [comment]
Encaminhado.

**Comment by luanargolodev** [comment]
Encaminhado.

**Comment by LeonardoPereira21** [comment]
Encaminhado
