### ISSUE TITLE
[REMOTO] [São Paulo] React Native/ ReactJS developer

### ISSUE THREAD

**Issue by CatBia** [react-brasil/vagas#2805]
## Descrição da vaga

Estamos com vaga disponível para programador React / React Native no Brasil 100% Home Office.

Qualificações obrigatórias:

## Local

:world_map: Remoto 

## Requisitos

**Obrigatórios:**
- Experiência mínima comprovada de 3 ~ 4 anos como desenvolvedor.
- Experiência em Javascript, ReactJS ou React Native
- Experiência em uso de estrutura de dados e algoritmos.
- Estudos em Ciências de Informação, Engenharia da computação e afins.

**Desejáveis:**

- Experiência com CD/CI Github Actions
- GraphQL Client-side (Opcional)
- TDD and Unit Test. Jest, Enzyme. (Opcional)
- Firebase (Opcional)
- Sass, Styled Componet ou CSS 3

## Contratação

PJ a combinar

## Nossa empresa

Aqui somos uma empresa líder na América Latina em  soluções de streaming

## Como se candidatar

Por favor envie um email para fmostaro@mediastre.am com seu CV anexo - enviar no assunto: Vaga React JS

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- :moneybag: A-Combinar
- ⚖️ PJ

**Comment by GabrielGuedess** [comment]
Enviado 🚀

**Comment by Remato** [comment]
Enviei agorinha! parece bem interessante :)
