### ISSUE TITLE
Programador REACT NATIVE Pleno

### ISSUE THREAD

**Issue by marinafps** [react-brasil/vagas#281]
Profissional irá atuar como Analista Desenvolvedor Mobile.
Conhecimentos técnicos: Mobile: conhecimento avançado de React Native Front: React.
Diferencial: Testes Unitários.
Local: Avenida Paulista
Interessados enviar CV com pretensão PJ para set.marina@triggolabs.com - Assunto: React Native

==================================================
POR FAVOR, SÓ POSTE SE A VAGA FOR PARA TRABALHAR COM REACT OU TECNOLOGIAS DO ECOSSISTEMA!

Exemplo: `[São Paulo] React Native Developer na NOME DA EMPRESA`
==================================================
-->

## Descrição da vaga

Projeto supimpa com React Native, etc..

## Local

Remoto ou Escritório, São Paulo - Vila Madalena

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Android Nativo
- 2 anos de experiência com desenvolvimento iOS Nativo

**Desejáveis:**
- conhecimentos em GraphQL

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Estágio
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/CLT
- regime/Estágio
- regime/Freela
- regime/Outros
- regime/PJ
- remuneração/1k-3k
- remuneração/3k-5k
- remuneração/5k-10k
- remuneração/10k-15k
- remuneração/15k+

**Comment by guilhermeoa07** [comment]
3 anos de experiência também para Júnior?

**Comment by adeonir** [comment]
@guilhermeoa07 o template foi mal preenchido =/

**Comment by wesleysd1989** [comment]
Se não se dá o trabalho de preencher corretamente, imagino como seria trabalhar....

**Comment by nic** [comment]
@marinafps o template foi mal preenchido! Envie novamente seguindo o template por favor!
