### ISSUE TITLE
Pessoa Desenvolvedora Frontend

### ISSUE THREAD

**Issue by Livia-Tech** [react-brasil/vagas#2817]
Desenvolvedor Front-end Pleno

Remoto

Atuará inicialmente só para o desenvolvimento orientando a layouts a partir do Figma, utilizando-se as bibliotecas Material UI, Vite entre outras a se definir. Iniciará projeto do zero, podemos opinar sobre tecnologias, metodologias e organização a serem utilizadas. Sendo gerenciado por líder técnico e scrum master. Trabalho em home office com gestão ágil visando a auto-gestão focada no resultado, esperando-se entregas rápidas e constantes com excelente qualidade, englobando documentação e testes. 

Experiências indispensáveis:

● 3+ Anos desenvolvimento React 

● 1+ Ano TypeScript 

● 1+ Ano criação de layout a partir do Figma 

● Consumo de API/REST 

● Gestão ágil, SCRUM 

● Controle de versionamento GIT/GITFLOW 

● Ferramentas de testes automatizados unitários e E2E 

Experiências Desejáveis (Diferenciais):

● Material UI 

● Vite 

● Node.js (Back-end) 

● Nest.js (Back-end)

Benefícios:

CLT
Remuneração R$5.000,00
VR R$15,00 por dia útil
Plano de Saúde (co-participativo)
Auxílio Homeoffice de R$200,00

**### Me chama no whats (32)98442-6808**

**Comment by matheusmcz** [comment]
Já falei pelo whats 😄

**Comment by walterfcarvalho** [comment]
pode ser remoto fora do Brazil
