### ISSUE TITLE
[São Paulo/Recife/Remoto] Engenheiro de Software Front-end na AllowMe

### ISSUE THREAD

**Issue by andremelo87** [react-brasil/vagas#2820]
## Descrição da vaga

Projeto supimpa com React Native, etc..

## Local

Remoto, Recife e São Paulo

## Benefícios

- Plano de saúde
- VR
- Auxílio creche

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com React JS
- 3 anos de experiência com desenvolvimento Web
- HTML/CSS
- JavaScript e TypeScript
- Consumo de APIs REST;
- Git
- Consumo de APIs REST;
- Testes (Jest, Cypress, outros);

**Desejáveis:**
- Bundlers (Webpack, outros);

**Diferenciais:**
- projetos opensource

## Contratação

CLT a combinar

#### O que é o AllowMe?

O AllowMe é uma unidade de negócios da Tempest e tem como proposta proteger identidades digitais, ajudando empresas a melhorar seus resultados de forma segura e simples. Analisamos mais de 200 milhões de transações por ano, protegendo a identidade do usuário durante toda a sua jornada digital.

#### O que fazemos no time de Engenharia de Software do AllowMe?

Nós auxiliamos empresas a prevenir fraudes e mitigar riscos de toda a jornada digital de seus clientes, construindo soluções web escaláveis e SDKs. 

#### Quais os valores que temos no time?

No time, buscamos cuidar das pessoas, garantir o desenvolvimento e excelência técnica. Valorizamos as pessoas, o time, o trabalho em equipe e o compartilhamento de conhecimento e ideias onde todos(as) têm voz ativa, independente do cargo ou experiência.

## Como se candidatar

Por favor se candidate através do link [Vaga Frontend AllowMe](https://allowme.gupy.io/job/eyJzb3VyY2UiOiJndXB5X3B1YmxpY19wYWdlIiwiam9iSWQiOjQ2NjM1MjB9?jobBoardSource=gupy_public_page)

## Labels

- 🏢 Flexível
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by brunooomelo** [comment]
Enviado.

**Comment by matheusmcz** [comment]
Enviado! 🌴

**Comment by thejoaov** [comment]
Enviado!

**Comment by Luciano-Ferreira** [comment]
Enviado.
