### ISSUE TITLE
[Remoto] Desenvolvedor(a) Front-End Next.JS Pleno na Andra Sistemas

### ISSUE THREAD

**Issue by andrasistemaserp** [react-brasil/vagas#2829]
## Descrição da vaga

Buscamos um profissional Front-End Pleno que seja apaixonado por desenvolvimento, inovação e novas tecnologias, para integrar nosso time em projetos baseados em Next.JS

**Atividades e Responsabilidades:**
- Desenvolvimento, manutenção e revisão de sistema ERP
- Desenvolvimento de novas funcionalidades e melhorias
- Atuará na análise, desenvolvimento e manutenção de projetos novos e existentes, testando, corrigindo, utilizando códigos limpos (clean code), visando a manutenibilidade, escalabilidade, performance, disponibilidade e segurança

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Formação superior completa ou cursando em Ciências da Computação, Engenharia da Computação, Tecnologia da Informação, Análise de Sistemas ou áreas afins
- Experiência em desenvolvimento de aplicações Web em HTML 5, CSS 3, JavaScript, React.JS, Next.JS, Material UI
- Experiência de 3 anos ou mais com React.JS ou Next.JS
- Experiência em desenvolvimento de sites responsivos
- Experiência em consumo de APIs RESTful (usando JSON e/ou XML)
- Experiência em JWT para autenticação
- Experiência em ferramentas de versionamento de código (Git, GitHub, GitLab)
- Experiência em integração contínua (CI/CD)
- Conhecimento em metodologias ágeis (Scrum, Kanban, OKR\'S)
- Possuir compromisso com prazos, senso de responsabilidade com a equipe, capacidade de auto-gestão no trabalho em home-office
- Ser organizado, colaborativo, criativo, questionador, comunicativo, opinar em soluções e gostar compartilhar experiências e absorver conhecimento
- Se preocupar com o cliente que está utilizando aquilo que desenvolvemos
- Manter-se atualizado e sempre estar por dentro de novas tecnologias
- Imune a stress
- Sentimento de dono no que atua

**Desejáveis:**
- Conhecimento em integração para emissão de documentos fiscais eletrônicos (NF-e, NFC-e, NFS-e, SAT CF-e, etc.)
- Conhecimento em sistemas ERP
- Conhecimento em Typescript
- Conhecimento em bancos de dados (MySQL, SQL, MongoDB, Oracle, etc.)
- Conhecimento em Node.JS
- Conhecimento em UI e UX (Figma, Photoshop, etc.)
- Conhecimento em desenvolvimento para versão mobile (Android e/ou iOS)
- Conhecimento em serviços Cloud (AWS, GCP, Azure, etc.)
- Conhecimento em Delphi/Pascal

**Diferenciais:**
- Experiência em TDD (Test Driven Development)
- Experiência em algum projeto, seja opensource ou não, criado do zero no GitHub/GitLab com contribuições relevantes
- Experiência em desenvolvimento de aplicação completa (Front + Back + DB)

## Contratação

PJ

## Nossa empresa

A Andra Sistemas está a 28 anos no mercado, sendo uma empresa movida pela paixão por programação, inovação, tecnologia e atendimento de excelência que atua exclusivamente no desenvolvimento de sistemas ERP e aplicações de integração voltadas para micro e pequenas empresas de diferentes ramos de atividade.

Somos comprometidos com os desafios da TI dos nossos clientes, trabalhando em ambiente horizontal e colaborativo, com autonomia e foco no cliente.

## Como se candidatar

Interessad@s favor preencher o formulário no link abaixo:
https://www.andrasistemas.com.br/contato-colaborador/

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 4k-6k

**Comment by oc-garcia** [comment]
Que vaga legal! Enviei minha candidatura! Obrigado pela atenção!

**Comment by andrasistemaserp** [comment]
@oc-garcia, recebemos sua candidatura. Obrigado.!

**Comment by fernaoshiotsuki** [comment]
Candidatura enviada, sinta-se livre para me contactar!

**Comment by BrunoFerreira95** [comment]
Entrei na lista dos quem querem trabalhar para Andra Sistemas, de uma olhada no meu github, pena que a maioria dos meus trabalhos são privados. 
Mas eu e o meu time lançou um produto de segurança para as escolas, onde um professor pode apertar o botão, assim a central de segurança da cidade, recebe o sinal e o sistema ajuda a abrir as cameras do local.
Além de outros projetos em andamento, vem falar comigo a respeito da vaga!
