### ISSUE TITLE
[Remoto] - React Native Senior na Abilitya.tech

### ISSUE THREAD

**Issue by valentim-guilherme** [react-brasil/vagas#2837]
## Descrição da vaga

A Abilitya, uma de tecnologia, está buscando um(a) Desenvolvedor(a) Sênior especializado(a) em React Native para se juntar à nossa equipe de desenvolvimento. Se você possui experiência sólida em desenvolvimento de aplicativos móveis, esta é uma oportunidade para você.

PS: Ingles NĀO é obrigatorio, mesmo recebendo em euro.

**Responsabilidades:**

 - Desenvolver aplicativos móveis utilizando React Native, garantindo a entrega de produtos de alta qualidade e performance.
 - Trabalhar em estreita colaboração com designers, analistas e outros membros da equipe de desenvolvimento para compreender os requisitos do projeto e garantir a implementação eficiente das funcionalidades.
 - Participar ativamente do processo de revisão de código e colaborar com os membros da equipe para garantir a manutenibilidade e a qualidade do código.
 - Identificar e resolver problemas de desempenho, usabilidade e compatibilidade de dispositivos.
 - Manter-se atualizado(a) com as últimas tendências e avanços em desenvolvimento de aplicativos móveis, especialmente na plataforma React Native.

## Local

100% remoto, horário flexível.

## Requisitos

**Obrigatórios:**

- Experiência comprovada no desenvolvimento de aplicativos móveis utilizando React Native.
- Sólido conhecimento em JavaScript, incluindo conceitos avançados e boas práticas de desenvolvimento.
- Excelentes habilidades de resolução de problemas e capacidade de depurar problemas complexos.
- Familiaridade com ferramentas de integração contínua e entrega contínua (CI/CD).
- Excelentes habilidades de comunicação e trabalho em equipe.

**Requisitos Opcionais (serão considerados diferenciais):**
 
- Experiência sólida em testes automatizados para aplicativos móveis, utilizando frameworks como Jest, Detox ou similares.
- Experiência prévia com desenvolvimento de aplicativos móveis nativos (iOS/Android).
- Conhecimento em outras tecnologias relacionadas, como React.js, Redux, TypeScript, Firebase, entre outras.
- Participação em projetos de código aberto ou contribuições para a comunidade de desenvolvedores.

## Contratação
PJ entre [€2000 - €2800] inicial líquido. Impostos do modelo empresarial brasileiro (7,68%) sendo pagos além deste valor. Ajuste de até 6% anual + bonus por performance.

## Como se candidatar
Por favor envie um email para guilherme@abilitya.tech com o título "Vaga React Senior" com seu GitHub e linkedin.

## Tempo médio de feedbacks

Costumamos enviar feedbacks no máximo até 2 dias após cada processo.

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Senior

**Comment by Remato** [comment]
Enviado!

**Comment by alexandreerick** [comment]
Enviado

**Comment by valentim-guilherme** [comment]
> Enviado!

Email por gentileza reenvir para guilherme@abilitya.tech.

**Comment by Remato** [comment]
> guilherme@abilitya.tech

opa eu corrigi, e reenviei para o novo e-mail! obrigado

**Comment by alexandreerick** [comment]
Enviado.

**Comment by devartwa** [comment]
@valentim-guilherme te respondi no e-mail, qualquer coisa to a disposição.

**Comment by thejoaov** [comment]
@valentim-guilherme enviado!

**Comment by AndMorMat** [comment]
Enviado!
