### ISSUE TITLE
[Remoto Freela] [MaterialUI] Pessoa desenvolvedora React pleno - inicial hourly flexível

### ISSUE THREAD

**Issue by gpkc** [react-brasil/vagas#2838]
## Descrição da vaga

Nosso projeto se trata de um Gerenciador de Feeds de E-Commerce modernizado. "Feed" neste sentido se trata de "feed de produtos", que é basicamente a lista de produtos do seu e-commerce (por exemplo em formato CSV). Este tipo de ferramenta tem como objetivo transformar os dados de feeds para formatos utilizados em diversos canais de marketing como Google Shopping, Facebook etc.

## Local

100% Remoto
Inicialmente hourly (5-10h por semana), com oportunidade de extensão para part-time ou full-time após algumas semanas, ou permanência como hourly caso você prefira. Trabalhe nos dias e horários que preferir, com syncs feitos conforme necessário.

## Requisitos

**Obrigatórios:**

- Experiência comprovada como dev react
- Conhecimento sólido em Typescript
- Conhecimento ou desejo de trabalhar em MaterialUI

**Desejáveis:**
- Experiência e interesse em UX e estética

**Diferenciais:**
- Contribuições Open-Source
- Participação (apresentação) em conferências

## Contratação

Freela a combinar

## Como se candidatar

Por favor envie um email com seu **hourly rate e CV anexado** para e8dsbeopg@mozmail.com (assunto VAGA REACT), e um breve parágrafo sobre você

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ Freela

**Comment by natamartins** [comment]
Curriculo enviado!

**Comment by edito13** [comment]
Currículo enviado!

**Comment by PedroLimass** [comment]
Currículo enviado!
