### ISSUE TITLE
Contratando desenvolvedor react js

### ISSUE THREAD

**Issue by sittes** [react-brasil/vagas#2839]
## Requisitos

**Obrigatórios:**

Estamos buscando um profissional para a posição de Desenvolvedor Frontend com experiência em React.js, consumindo APIs Rest, e familiaridade com a metodologia MVC. Além disso, é necessário ter habilidades em desenvolvimento Backend com Node.js e Express, bem como conhecimento em modelagem de dados No-SQL baseada em Firebase.

Valorizamos também conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS, pois essas habilidades podem ser relevantes para as responsabilidades da posição.

Resumindo, os requisitos para a contratação são:

- Experiência em desenvolvimento Frontend utilizando React.js e consumo de APIs Rest.
- Familiaridade com a metodologia MVC.
- Habilidades em desenvolvimento Backend utilizando Node.js e Express.
- Conhecimento em modelagem de dados No-SQL baseada em Firebase.
- Conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS.

Se você possui essas habilidades e está pronto para assumir esse desafio, gostaríamos de conhecer você melhor!

Por favor envie um email para ivipcoin@ivipcoin.com seu CV anexado - enviar no assunto: Vaga React js

## Labels

- 🏢 Remoto
- 👦 Júnior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 1k-2k

**Comment by edito13** [comment]
Currículo Enviado!

**Comment by Ruan-Init** [comment]
Currículo Enviado.

**Comment by MathMendesReis** [comment]
Curriculo enviado.

**Comment by natamartins** [comment]
Curriculo enviado!

**Comment by PedroLimass** [comment]
Currículo Enviado!

**Comment by ionansantos** [comment]
enviado !! estou a disposição para inicio imediato

**Comment by YuriMont** [comment]
Currículo Enviado!

**Comment by matheuslima99** [comment]
Currículo enviado!

**Comment by vitor-nogueira-dev** [comment]
Currículo enviado ✅

**Comment by matheusmcz** [comment]
Enviado!

**Comment by TommiL90** [comment]
Enviado!
