### ISSUE TITLE
[São Paulo] Mid/Senior Frontend Software Engineer na MZ

### ISSUE THREAD

**Issue by geovanerocha** [react-brasil/vagas#284]
## Descrição da vaga
Buscamos um(a) front pra nos ajudar com nosso produto, em fase inicial, utilizando React.

## Local

WeWork Nações Unidas (Av. das Nações Unidas, 14261) 

## Benefícios (caso CLT)

- Plano de saúde
- VR
- VT

#### Diferenciais
- Cultura de compartilhar conhecimento.
- Voz ativa e participação **REAL** nas decisões técnicas.
- Ping pong =)

## Requisitos
- React
- Gerenciamento de estado (Redux, moBx, PubSub)
- Teste funcional e E2E
- SOLID
- SASS

## Contratação
CLT, PJ.

## Nossa empresa

MZ is a global leader in investor relations solutions. Through innovative technology and exceptional customer service we empower our clients’ investor relations strategy. Our full suite of communications and intelligence solutions, including websites, webcasting, compliance filling, and intelligence empower our customers to be ahead of the market by providing them with all the tools and insights they need to make effective decisions and better engage with the market.

## Como se candidatar

Por favor envie um email para tech.vagas@mzgroup.com com seu CV/LinkedIn anexado =)
Enviar no assunto: Vaga Frontend

## Labels

- alocação/Presencial
- experiencia/Pleno
- experiencia/Sênior
- regime/CLT
- regime/PJ

**Comment by andrevvalle** [comment]
@geovanerocha existe possibilidade de trabalho remoto?

**Comment by geovanerocha** [comment]
A posição ainda está disponivel

**Comment by gadielkalleb** [comment]
Posso me candidatar? Rs
