### ISSUE TITLE
Analista Desenvolvedor Sênior - CRM (Freelancer/HomeOffice) na BHS

### ISSUE THREAD

**Issue by PriscilaRocha** [react-brasil/vagas#2848]
[## Descrição da vaga
· Gerenciamento e monitoramento da plataforma de CRM;
· Desenvolver e evoluir API's de integração com o CRM;
· Realizar integração do CRM com o sistema externo através de plugin;
· Ajustar fluxos locais de trabalho do CRM e evoluir de acordo com a necessidade do cliente.

## Local
Remoto

## Benefícios
· Programa de indicações! Você e a sua indicação saem ganhando;
· Gympass para você se exercitar;
· Parceria com o SESC que oferece acesso a teatro, dança, hotéis, passeios, entre outras atividades;
· Crédito Consignado: parceria com a Creditas que facilita na contratação de um empréstimo consignado;
· Parcerias e convênios diversos (Universidades, escolas de Idioma, academias, clínicas de saúde...);
· Programas de conteúdo, como o Deu Match! e uma rotina com aprendizado colaborativo constante;

Buscamos a inclusão da diversidade no nosso dia a dia e acreditamos que equipes plurais têm melhor desempenho. Todas as pessoas são bem-vindas.
#vempraBHS #somosBHS #LI-Remote

## Requisitos
**Obrigatórios:**
·  Metodologia Agile/Azure;
·  Microsoft Dynamics;
·  API integração
·  CRM 2011;
·  Plugin;
·  C# (versão 2017);
·  T-SQL (Transact-SQL);
·  Testar, colocar em produção e homologar demandas do CRM.

## Contratação
PJ a combinar

## Nossa empresa

Nós somos a BHS!
Temos aproximadamente 28 anos de experiência no mercado ofertando soluções modernas de TI.
Reconhecida como a MELHOR empresa para se trabalhar em MG pelo GPTW - Great Place to Work. 

O que a gente espera de você?
· Habilidade de relacionamento com pessoas de diferentes áreas e de diversos níveis de hierarquia;
· Autogerenciamento;
· Colaboração;
· Ser proativo e saber trabalhar fora da zona de conforto;
· Alguém que queira fazer parte de projetos incríveis e crescer junto com a BHS.

## Como se candidatar

Por favor se candidatar no link: https://bhs.gupy.io/jobs/5269675](https://bhs.gupy.io/jobs/5269675)

**Comment by nicholasess** [comment]
Vaga sem relação com stack de react, por isso será fechada
