### ISSUE TITLE
[Curitiba] Desenvolvedor React (Pleno ou Sênior) na MadeiraMadeira

### ISSUE THREAD

**Issue by williamnvk** [react-brasil/vagas#285]
## Descrição da vaga

> Há várias vagas abertas

Sua missão será integrar ao time de Desenvolvedores da Madeira afim de proporcionar o crescimento digital e escalabilidade em nossos processos.

Adoramos pessoas com estas atitudes:

**Colaboração**: Que criam parcerias e trabalham em equipe.
**Resiliência**: Que se recobram ou se adaptam frente a mudanças e/ ou pressão.
**Senso de dono**: Que assumem a responsabilidade total dos processos e projetos na sua mão, desde o seu início até o fechamento.
**Empreendedorismo**: Que apresentam capacidade de criar, melhorar, inovar e que assumem riscos calculados.
**Paixão pelo que faz**: Que demonstram estar apaixonadas e entusiasmadas no exercício de sua atividade.

## Local

Escritório, Curitiba - Centro

## Benefícios

- Quitanda com frutas fresquinhas
- Café, chocolate quente, cappuccino à vontade para você recarregar sua energia
- Estacionamento para bikes
- Bike Sharing
- Desconto em restaurantes locais e outros comércios
- Convênio com Universidades e parcerias para cursos diversos
- Local de descompressão com: videogames e jogos de realidade virtual, pebolim, redes e fliperama ;D
- Temos DOIS Pokéstops no prédio
- Cafeteria exclusiva com várias delícias para saborearmos
- Espaços de conveniências
- Biblioteca para seu desenvolvimento
- Programa de Orientação Pessoal
- Um kit de Boas Vindas com itens EXCLUSIVOS da MadeiraMadeira ;D

#### Diferenciais

- Vale Refeição (R$ 16,50/dia)
- Vale Alimentação (R$ 180,00/mês)
- Plano de Saúde
- Plano Odontológico
- Seguro de Vida
- GymPass

## Requisitos

**Obrigatórios:**

- Ter experiência em desenvolvimento de aplicações com Javascript/Typescript.
- Ter conhecimento das stacks de desenvolvimento de front end moderna (WebPack, Babel, Yarn, NPM e etc);
- Ter bom conhecimento de ES6, JSX e Node.
- Compreensão dos princípios do REST e exposição a APIs de back-end.
- Ter conhecimento dos problemas de compatibilidade entre navegadores e formas de contorná-los.
- Ter compromisso em produzir código bem estruturado, testado e escalável.

**Diferenciais:**

- Estar antenado às recentes evoluções da linguagem Javascript (ECMA6+).
- Ter experiência no desenvolvimento, lançamento e manutenção de aplicativos React.js ou React Native.
- Flux, Redux ou MobX.
- GIT

## Contratação

CLT, salário a combinar

## Nossa empresa

Somos uma empresa em crescimento exponencial, ano passado haviam aproximadamente 350 colaboradores, hoje temos mais de 500 e o time de TI não para de crescer. Somos, antes de tudo, uma empresa de tecnologia.

## Como se candidatar

Por favor envie um email para william.novak@madeiramadeira.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- alocação/Flexível
- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/CLT
- remuneração/5k-10k

**Comment by HaluDeCassia** [comment]
@williamnvk Existe possibilidade de ser full remoto? A vaga é bem bacana

**Comment by Goufix** [comment]
Por isso penso que deveria aprender mais sobre _React_, problema mesmo é ter ideias pra colocar no portfólio. Um dia eu chego lá. Deixei um e-mail mesmo assim. Quem sabe...

**Comment by williamnvk** [comment]
> @williamnvk Existe possibilidade de ser full remoto? A vaga é bem bacana

Olá @HaluDeCassia não, somente presencial.
