### ISSUE TITLE
Pessoa Desenvolvedora Full Stack Pleno (Presencial/BH) na BHS

### ISSUE THREAD

**Issue by PriscilaRocha** [react-brasil/vagas#2851]
## Descrição da vaga
· Atuação em fintech com produtos de integração e fluxo, atendendo às necessidades complexas e regulatórias do setor.;
· Desenvolvimento em tecnologias: [Asp.net](http://asp.net/) core e MVC, banco de dados SQL Server, ambiente em nuvem AWS, entre outros;
· Construção e sustentação de aplicações BackOffice atuando como Backend e Frontend;
· Elaborar documentação Swagger;
· Participação de sprints, brainstormings e processos de ideação para construir projetos, páginas e materiais em conjunto com a equipe de marketing.

## Local
Presencial em BH

## Benefícios
· Plano de saúde e Assistência Odontológica;
· Vale Refeição/ Alimentação no cartão Flash, sem descontos;
· Vale transporte, auxilio estacionamento ou auxílio mobilidade (opcional);
· Programa de indicações! Você e a sua indicação saem ganhando;
· Gympass para você se exercitar;
· Parceria com Holus - Central de Atenção Terapêutica, que garante acesso a atendimentos Psicológicos e nutricionais com preços acessíveis para você e sua família;
· Participação nos lucros;
· Licença Maternidade/Paternidade estendida;
· Parceria com o SESC que oferece acesso a teatro, dança, hotéis, passeios, entre outras atividades;
· Seguro de vida, sem desconto nenhum para o colaborador;
· Crédito Consignado: parceria com a Creditas que facilita na contratação de um empréstimo consignado;
· Parcerias e convênios diversos (Universidades, escolas de Idioma, academias, clínicas de saúde...);
· Incentivos à educação e ao desenvolvimento (Pós-Graduações, certificações, treinamentos e até inglês);
· Programas de conteúdo, como o Deu Match! e uma rotina com aprendizado colaborativo constante;
· Cultura de Feedback contínuo, com: Feedbacks semestrais, 1:1, PDI (Plano de Desenvolvimento Individual) e BHS Experience.

Buscamos a inclusão da diversidade no nosso dia a dia e acreditamos que equipes plurais têm melhor desempenho. Todas as pessoas são bem-vindas.
#vempraBHS #somosBHS

## Requisitos
**Obrigatórios:**
· Graduação em Ciência da Computação ou áreas afins;
· Habilidades analíticas, como a compreensão de questões complexas, resolução de problemas conceituais e criativos;
· Experiência prática em .NET MVC, Core e C#/.NET, API's, Git, Microserviços , Dapper e SOLID;
. Atuação com bando de dados SQL Server;
· Conhecimento em Metodologias ágeis.

Diferencial:
· Experiência prática em HTML, CSS, Java Script, SASS, TyperScript, ES6, Azure DevOps e CI/CD e RabbitMQ.
· Atuação em AWS.

## Contratação
CLT

## Nossa empresa
Nós somos a BHS!
Temos aproximadamente 28 anos de experiência no mercado ofertando soluções modernas de TI.
Reconhecida como a MELHOR empresa para se trabalhar em MG pelo GPTW - Great Place to Work. 

O que a gente espera de você?
· Habilidade de relacionamento com pessoas de diferentes áreas e de diversos níveis de hierarquia;
· Autogerenciamento e responsabilidade;
· Colaboração e trabalho em equipe;
· Facilidade de comunicação com cliente e de adaptação;
· Alguém que queira fazer parte de projetos incríveis e tenha muita vontade de aprender, ensinar e crescer junto com a BHS.

## Como se candidatar
Favor se cadastrar no link: https://bhs.gupy.io/jobs/5269151

**Comment by nicholasess** [comment]
Vaga sem relação com stack de react, por isso será fechada
