### ISSUE TITLE
Pessoa Desenvolvedora Flutter Pleno (Híbrido/BH) na BHS

### ISSUE THREAD

**Issue by PriscilaRocha** [react-brasil/vagas#2857]
## Descrição da vaga
· Atuação em Flutter/Dart, arquitetura de software e práticas para melhorar a manutenção de software;
· Propor novas funcionalidades e arquitetura, realizando desenvolvimento através de linguagem Dart de novas telas com objetivo de garantir evolução técnica dos aplicativos da empresa;
· Validar as novas funcionalidades das aplicações;
· Executar a manutenção dos sistemas, fazendo eventuais correções necessárias, visando atender às necessidades dos usuários.

## Local
Híbrido em Belo Horizonte, Minas Gerais - Centro de BH

## Benefícios
· Plano de saúde e Assistência Odontológica;
· Vale Refeição/ Alimentação no cartão Flash, sem descontos;
· Vale transporte, auxilio estacionamento ou auxílio mobilidade (opcional);
· Auxílio Híbrido mensal, sem descontos;
· Programa de periodicidade! Você e sua indicação saem ganhando;
· Gympass para você se exercitar;
· Participação nos lucros;
· Licença Maternidade/Paternidade contínua;
· Parceria com o SESC que oferece acesso a teatro, dança, hotéis, passeios, entre outras atividades;
· Seguro de vida, sem desconto nenhum para o colaborador;
· Crédito Consignado: parceria com a Creditas que facilita a contratação de um empréstimo consignado;
· Parcerias e convênios diversos (Universidades, escolas de Idioma, academias, clínicas de saúde...);
· Incentivos à educação e ao desenvolvimento (Pós-Graduações, certificações, treinamentos e até inglês);
· Programas de conteúdo, como o Deu Match! e uma rotina com aprendizado colaborativo constante;
· Cultura de Feedback Contínuo, com: Feedbacks semestrais, 1:1, PDI (Plano de Desenvolvimento Individual) e BHS Experience.

## Requisitos
· Flutter;
· Dart;
· REST API;
· Gerenciamento de estado;
· Java.

## Contratação
CLT

## Nossa empresa
#SOMOSBHS
Estamos construindo nossa cultura para que pessoas incríveis possam fazer o melhor. Acreditamos no potencial de transformação da tecnologia e que ela é (e deve ser) acessível. Se você compartilha dessa verdade, vai querer se juntar a nós!
Reconhecida como a melhor empresa para se trabalhar em MG pelo GPTW - Great Place to Work.

O QUE NÓS FAZEMOS
Somos especialistas em estratégia de TI. Desenvolvemos, adaptamos e gerenciamos soluções integradas utilizando a tecnologia para resolver os desafios dos nossos clientes. E eles são muitos.

COMO FAZMOS
Somos uma empresa formada por pessoas que são diferentes entre si. Acreditamos na máxima de que duas cabeças pensamos melhor do que uma. Apostamos na diversidade e na inclusão, que trazem outros pontos de vista para alcançarmos os melhores resultados.

## Como se candidatar
Gentileza realizar cadastro em nossa plataforma da página de carreiras: https://bhs.gupy.io/jobs/5344832?jobBoardSource=gupy_public_page

## Labels
- 🏢 Flexível
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- 💰 5k-10k

**Comment by nicholasess** [comment]
Vaga sem relação com stack de react, por isso será fechada
