### ISSUE TITLE
[Remoto ou Híbrido] Desenvolvedor React Pleno @Rhitmo Tech

### ISSUE THREAD

**Issue by gabirecruiter** [react-brasil/vagas#2862]
Somos a **RHITMO Tech** e aqui desenvolvemos tecnologia para pessoas! 💙

Um time que está sempre pronto para decolar e é capaz de criar e desenvolver projetos que mudam positivamente a vida das pessoas, solucionando problemas e transpondo obstáculos. Essa é a nossa missão e procuramos por talentos para compor o nosso time de tecnologia e nos apoiar nessa jornada, atuando com Desenvolvimento Moblie Flutter 📱

Quer conhecer um pouco mais sobre nós? Nossas redes sociais: 📱

https://rhitmotech.com.br/
https://www.instagram.com/rhitmotech/
https://br.linkedin.com/company/rhitmotech_

## Descrição da vaga

Vamos atuar em um projeto de pagamentos/plataforma! Então você vai:

- Desenvolver e manter aplicações web responsivas utilizando React.
- Integrar interfaces com APIs e serviços externos.
- Trabalhar em colaboração com nossa equipe de design e back-end para garantir a melhor experiência do usuário.
- Participar de revisões de código e contribuir para a melhoria contínua de nossos processos de desenvolvimento.

## Requisitos

É necessário que você tenha:

- +2 anos de experiência com React e seu ecossistema (Redux, React Router, Next.js, Typescript)
- Profundo conhecimento em hooks, context API e componentização.
- Experiência com soluções CSS-in-JS, como Styled Components ou Emotion.
- Familiaridade com testes unitários utilizando Jest ou React Testing Library.
- Boas práticas de código e atenção aos detalhes.
- Capacidade de trabalhar em equipe e excelente comunicação.

## Sobre a vaga: 

- Modelo de contratação: PJ
- Interrupção remunerada de 15 dias;
- Bonificação por indicação de Desenvolvedores;

## Como se candidatar

**Envie o seu currículo + pretensão para o e-mail: rh@rhitmo.com.br** 📧

Pode se conectar comigo no linkedin também: https://www.linkedin.com/in/mariagabrielacs 👩‍💻

### Nível

- Pleno/Sênior;

### Alocação

- Remoto
- Híbrido em Belo Horizonte

#VEMPRARHITMO 🚀

**Comment by nicholasess** [comment]
@matmatias eu atualizei pra ela, obrigado por avisar

**Comment by jhefflg** [comment]
CV, enviado.
