### ISSUE TITLE
[Remoto] React Native Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [react-brasil/vagas#2863]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/react-native-developer-195830031?utm_source=github&utm_medium=react-brasil-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos uma empresa inovadora no setor de tecnologia, comprometida em criar soluções digitais de alto impacto para nossos clientes. Estamos em busca de uma pessoa React Native developer Pleno, altamente talentosa e apaixonada por tecnologia para se juntar à nossa equipe e ajudar a impulsionar nossos projetos para o próximo nível.</p>
<p><strong>Responsabilidades:</strong></p>
<ul>
<li>Desenvolver e manter aplicativos móveis usando React Native.</li>
<li>Colaborar com equipes multifuncionais para projetar e implementar novos recursos.</li>
<li>Solucionar problemas e otimizar o desempenho dos aplicativos.</li>
<li>Garantir a qualidade e o desempenho dos aplicativos através de testes e revisões de código.</li>
<li>Manter-se atualizado com as melhores práticas e tendências do mercado em desenvolvimento React Native.</li>
</ul>
## Koepe: 
 <p>Uma desenvolvedora de aplicações em versões WEB e para aplicativos de soluções eficientes para serviços de logística.</p>
<p>A Koepe surgiu da busca por desafios e da persistência de seus fundadores, que associaram suas experiências adquiridas em outros empreendimentos a esse novo projeto, que viria a se transformar nesta grande inovação tecnológica.</p><a href='https://coodesh.com/companies/koepe'>Veja mais no site</a>

 ## Habilidades: 
 - React Native 
- React.js 
- Node.js
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência comprovada em desenvolvimento React Native; 
- Conhecimento sólido em React e Node.js; 
- Experiência em integração com APIs RESTful; 
- Familiaridade com ferramentas de controle de versão, como Git; 
- Habilidade para colaborar efetivamente em uma equipe multidisciplinar; 
- Excelente capacidade de resolução de problemas e atenção aos detalhes; 
- Compreensão de princípios de design e experiência do usuário.
## Diferenciais: 
 - Espanhol avançado 
- Ter atuado em projetos de mobilidade e logística

## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [React Native Developer na Koepe](https://coodesh.com/jobs/react-native-developer-195830031?utm_source=github&utm_medium=react-brasil-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Mobile

**Comment by YuryRegis** [comment]
Vaga congelada...
