### ISSUE TITLE
Vaga Desenvolvedor FullStack

### ISSUE THREAD

**Issue by sittes** [react-brasil/vagas#2868]
**Requisitos Essenciais:**

Estamos em busca de um talentoso Desenvolvedor Frontend com expertise em React.js, expertise em consumo de APIs Rest e familiaridade com a metodologia MVC. Além disso, é fundamental ter sólidas habilidades em Desenvolvimento Backend usando Node.js e Express, bem como experiência em modelagem de dados No-SQL com base em Firebase ou MongoDB.

**Também valorizamos:**

Conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS, pois essas competências podem ser relevantes para as responsabilidades do cargo.

Em resumo, os requisitos para a posição incluem:

- Experiência em Desenvolvimento Frontend com React.js e habilidade no consumo de APIs Rest.
- Familiaridade com a metodologia MVC.
- Habilidades sólidas em Desenvolvimento Backend com Node.js e Express.
- Conhecimento em modelagem de dados No-SQL baseada em Firebase.
- Familiaridade com banco de dados não relacional MongoDB.
- Conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS.

Se você possui essas habilidades e está pronto para enfrentar esse desafio, gostaríamos muito de conhecê-lo melhor!

Por favor, envie seu currículo para ivipcoin@ivipcoin.com.

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 1k-2k

**Comment by PauloAbrahao** [comment]
Boa tarde, currículo enviado!

**Comment by cauesilva1** [comment]
currículo enviado!!

**Comment by pascoalkahamba** [comment]
Currículo enviado.
