### ISSUE TITLE
[Remoto] React Native Developer na Nexmuv

### ISSUE THREAD

**Issue by HelenNexmuv** [react-brasil/vagas#2871]
## Local

Remoto 

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento de aplicações em React Native. 
Conhecimento prático no mundo mobile, arquiteturas, tendências e tecnologias emergentes; 
Entendimento de testes automatizados e pirâmide de testes em React Native; 
Preocupação com interfaces visuais e experiência do cliente; 
Embasamento teórico, habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento (clean code, TDD, design de código, padrões de projeto, integração contínua-pipelines de CI/CD, etc.); 
Familiaridade com metodologias ágeis;

**Diferenciais:**
Desenvolvimento nativo para iOS ou Android é considerado diferencial; 

## Contratação

PJ a combinar

## Nossa empresa
Nexmuv 
Somos uma empresa de tecnologia que aplica inovação em tudo aquilo que entrega. Existimos para ajudar nossos clientes a se adaptarem a um mundo em constante transformação.

## Como se candidatar

Por favor envie um email para helen.matos@nexmuv.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 15k+

**Comment by Scohati** [comment]
Boa tarde! CV enviado.
