### ISSUE TITLE
[REMOTO] Sênior React Native (candidaturas: https://impulso.link/FWoP8r)

### ISSUE THREAD

**Issue by Gabrielaimpulso** [react-brasil/vagas#2878]
Buscamos desenvolvedor/a mobile React Native, perfil Sênior que tenha experiência e domínio robusto com ambientes mobile, grandes projetos de alta performance e escala, Javascript com foco em React Native e Detox.
Que mande bem em testes automatizados e pirâmide de testes em React Native, que tenha habilidade e cuidado com a excelência técnica e boas práticas de desenvolvimento.
Super importante conhecer e vivenciar as metodologias ágeis baseadas em Kanban ou Scrum para influenciar e conduzir o time.

**O que esperamos de você:**

⚪ Perfil de liderança para colaborar com a evolução das skills técnicas do time e foco na melhoria contínua.
⚪ Excelente comunicação síncrona e assíncrona, realizando a gestão do tempo e priorizando assuntos e soluções;
⚪ Profissional com foco no desenvolvimento de pessoas com abertura para dar e receber feedbacks continuamente;
⚪ Empatia, respeito e inteligência emocional;
⚪ Que valorize a inclusão e a diversidade no ambiente de trabalho.

**Sobre o cliente:**

É uma startup brasileira do segmento de serviços financeiros, atuando como uma das principais plataformas online de crédito com garantia do Brasil. Trouxe muita inovação nessa área, apostando em tecnologias para facilitar o processo de contratação de empréstimos e tentando auxiliar ao máximo todo o processo para o cliente final.

**Sobre a Impulso:**

Somos uma empresa Remote First e estamos no mercado há mais de 10 anos. Montamos e alocamos times tech de qualquer perfil e stack, com fit perfeito para projetos e desafios de empresas como Veloe, M4U, Kroton e Take. Além disso, criamos uma plataforma que conecta uma comunidade com mais de 80.000 profissionais de tecnologia.

- Oportunidade turbinada;
- Full Time;
- 100% Remoto;
- 1 posição;
- Contratação PJ. 

💰 Remuneração: entre R$ 14.560 e R$ 16.000/mês.

Acesse o link e clique no botão (quero me inscrever) para se candidatar: https://impulso.link/FWoP8r

**Comment by erikbrito** [comment]
Já faz semanas que estou inscrito nessa oportunidade e nunca recebi uma resposta
