### ISSUE TITLE
[Remoto] Front-end Engineer @ Conecta Capital Humano

### ISSUE THREAD

**Issue by raissaime** [react-brasil/vagas#2879]
## Descrição da vaga
Engenheiro de Software Front-end +5XP - Typescript + React

## Principais Responsabilidades
- Trabalhar diariamente em um time multifuncional com Engenheiros de Software, Designers e Product Owner para desenvolver e evoluir produtos UOL Host utilizando metodologias ágeis;
- Construir painéis administrativos responsivos, seguindo fielmente os layouts e especificações determinados pelo time de Designers;
- Evoluir nossa biblioteca de componentes baseada em React e documentada com Storybook;
- Integrar o front-end com serviços back-end;
- Desenvolver aplicações visando simplicidade, eficiência, manutenibilidade e reaproveitamento de código;
- Atuar em tecnologias designadas dentro do time, independente da linguagem de programação.
- Realizar review de código de outros desenvolvedores e dar feedback.
- Ser responsável pela qualidade dos sistemas definindo e executando testes (inclusive manuais) com uma visão de usuário final;
- Atuar em soluções de problemas e manutenção de sistemas existentes
- Participar da definição e implantação dos sistemas;
- Gerar documentação técnica.

## Local

Remoto ou Escritório, São Paulo - Pinheiros.

## Requisitos

**Obrigatórios:**
- Desenvolvimento de aplicações front-end (React, Typescript, HTML, CSS);
- Desenvolvimento de testes automatizados (Jest, Cypress);
- Versionamento de código (GIT);
- Integração e evolução de APIs REST;

## Contratação

PJ a combinar

## Nossa empresa

A conecta faz hunting dos melhores talentos para fit com cliente. 

## Como se candidatar

[https://tally.so/r/nGR6LO](url)

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 10k

**Comment by YuryRegis** [comment]
Olá tenho interesse mas parece que o link para candidatura está quebrado.

**Comment by pilgerj** [comment]
Oi, eu também não consegui acessar o link

**Comment by oc-garcia** [comment]
Também tenho interesse mas não consegui visualizar a vaga.

**Comment by LucasHBG** [comment]
O link está errado, mas se copiarem o texto, vai funcionar.

Link corrigido:
[https://tally.so/r/nGR6LO](https://tally.so/r/nGR6LO)
