### ISSUE TITLE
[Híbrido - Niterói - RJ] Front-end Developer na Internit

### ISSUE THREAD

**Issue by Fredpeixoto** [react-brasil/vagas#2882]
## Nossa empresa

Com 25 anos de mercado, a Internit é uma empresa consolidada com um ótimo ambiente de trabalho somado a desafios constantes. Temos projetos com empresas como Gafisa, Cyrela, PDG, Brasil Brokers, Accor, Best Western, Anhanguera Educacional, Stefanini, Sankhya, Riocard, Climario, dentre outros.
Estamos situados em uma rua tranquila em Santa Rosa - Niterói com facilidade de estacionamento, além de termos um bicicletário na empresa.

## Descrição da vaga

Desenvolvimento e manutenção de sistemas, sites e lojas virtuais.

## Local

Híbrido, [RJ], [NITERÓI], [SANTA ROSA]

## Requisitos

**Obrigatórios:**
Vivência em Html, CSS, Java Script, GIT, docker e React.
O candidato deve estar na faculdade e ter seu currículo cadastrado em nosso site. 

## Como se candidatar

Por favor se cadastrar em https://internit.com.br/curriculo

#### Alocação
- Alocado / Híbrido
- Remoto

#### Regime
- Trainee 
- Estágio

#### Nível
- Júnior

**Comment by caioalvesp** [comment]
Currículo enviado!

**Comment by MathMendesReis** [comment]
curriculo enviado

**Comment by patandrade09** [comment]
enviado :D

**Comment by jp-xaxa** [comment]
Currículo enviado!

**Comment by pasteleirodorio** [comment]
Vaga Sensacional, estarei enviando um currículo!
