### ISSUE TITLE
[REMOTO] React Native Developer na Helloworlds

### ISSUE THREAD

**Issue by silviosampaio** [react-brasil/vagas#2885]
## Descrição da vaga

Procuramos um desenvolvedor de software sênior para trabalhar em projetos de clientes internacionais. Não é necessário inglês (mas seria um diferencial)

## Local

Totalmente Remoto

## Benefícios

- N/A

#### Diferenciais

- N/A

## Requisitos

**Obrigatórios:**
- 4+ anos de experiência com desenvolvimento mobile React Native (Android & iOS)
- 4+ anos de experiência com desenvolvimento front-end ReactJS
- 4+ anos de experiência com desenvolvimento back-end com NestJS

**Desejáveis:**
- Conhecimentos em MongoDB
- Conhecimentos em Supabase/Firebase

**Diferenciais:**
- Apps publicados (Android & iOS)

## Contratação

PJ, R$ 10.000,00/mês

## Nossa empresa

Somos uma empresa enxuta, mas com operação 100% internacional. Oferecemos flexibilidade de horário + remuneração adequada, mas também levamos a frase "com grandes poderes, grandes responsabilidades" muito a sério :) 

## Como se candidatar

Basta comentar o seu LinkedIn nessa issue, bem simples :) 

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by erikbrito** [comment]
Tenho interesse! 

LinkedIn: https://www.linkedin.com/in/erik-brito-8b2b02b6/

**Comment by felipefln** [comment]
https://www.linkedin.com/in/felipe-weiduschadt-de-carvalho/

**Comment by robertolemesp** [comment]
https://www.linkedin.com/in/roberto-lemes-padilha-472748217/

**Comment by lucasfontinele** [comment]
https://www.linkedin.com/in/lucasfontinele/

**Comment by RilsonO** [comment]
https://www.linkedin.com/in/rilson-costa-de-oliveira-1560a7109/

**Comment by rafaelaugustos** [comment]
https://www.linkedin.com/in/rafaelaugustos/

**Comment by Gabriel9Stresser** [comment]
https://www.linkedin.com/in/gabriel-augusto-soler-stresser-366719100/

**Comment by rodrigogaraujo** [comment]
https://www.linkedin.com/in/rodrigo-g-araujo/

**Comment by nearghale** [comment]
https://www.linkedin.com/in/celsoaraujo13/

**Comment by rodrigoarka** [comment]
https://www.linkedin.com/in/rodrigoarka/

**Comment by andrecampll** [comment]
Opa, tenho muito interesse!

https://www.linkedin.com/in/andrecampll/

**Comment by marcus6n** [comment]
https://www.linkedin.com/in/marcus6n/

**Comment by erikbrito** [comment]
Alguém aqui já recebeu algum contato pra essa vaga?

**Comment by patrick-narciso** [comment]
https://www.linkedin.com/in/patricknarciso

**Comment by hallss93** [comment]
https://www.linkedin.com/in/hallss93

**Comment by AstonCreat** [comment]
https://www.linkedin.com/in/italoasouzati/

**Comment by italoSouzaTI** [comment]
https://www.linkedin.com/in/italoasouzati/

**Comment by ChrisFrontDev** [comment]
https://www.linkedin.com/in/christian-santos-front-end/

**Comment by Michaelmascarenhas90** [comment]
https://www.linkedin.com/in/michaeliurimascarenhas/

**Comment by Michaelmascarenhas90** [comment]
https://www.linkedin.com/in/michaeliurimascarenhas/

**Comment by cosmo-rodrigues** [comment]
https://www.linkedin.com/in/cosmo-rodrigues/

**Comment by fauzerjunnior** [comment]
https://www.linkedin.com/in/fauzerjunnior/

**Comment by PopyDeveloper** [comment]
https://www.linkedin.com/in/rafael-silva-664677101/

**Comment by flipdemoura** [comment]
https://www.linkedin.com/in/felipe-de-moura/
