### ISSUE TITLE
[Recife-CE] Desenvolvedor Front-End ReactJS (100% remoto)

### ISSUE THREAD

**Issue by alepmedeiros** [react-brasil/vagas#2888]
## Vaga para desenvolvedor frontend Reactjs

Projeto para uma empresa com foco 100% no mercado delivery, com crescimento na area

## Recife - CE

Remoto, Recife 

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento ReactJS

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

NFCFiscal

## Como se candidatar

Por favor envie um email para alemedeiros@bsd.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by gabyrodrigues** [comment]
Olá! Enviado

**Comment by eltonfreitasx** [comment]
CV enviado !!

**Comment by pascoalkahamba** [comment]
Olá. Espero que está mensagem o encontre bem currículo enviado com sucesso.

**Comment by jhefflg** [comment]
Up!

**Comment by ChrisFrontDev** [comment]
enviado, possuo 8 anos de xp

**Comment by Dirosaki** [comment]
Currículo enviado!

**Comment by IagoPuzer** [comment]
Currículo enviado

**Comment by tarciosillva** [comment]
Enviado!

**Comment by alepmedeiros** [comment]
recebido diversos curriculos, agradecemos a participação de todos, e estaremos realizando o processo seletivo para o nosso futuro Dev

**Comment by pascoalkahamba** [comment]
Boas estamos a espera dos resultados.
