### ISSUE TITLE
DESENVOLVEDOR  IOS 

### ISSUE THREAD

**Issue by Sueli321** [react-brasil/vagas#29]
Profissional irá atuar com desenvolvimento, arquitetura de software, manutenção e pesquisa de aplicativos na plataforma iOS, definição e implantação da arquitetura seguindo padrões do cliente. 
Necessário conhecimento com:
Desenvolvimento orientado à componentes Storyboards;
Git. 
Arquitetura iOS 
Gerenciadores de dependências 
Apple Watch, 
Apple TV 
Automação de builds 
Ferramentas de crashlogs 
Desenvolvimento de frameworks. 
Conhecimentos avançados em Objective-C e Swift 

Local de atuação: Osasco (cliente do seguimento Bancário)
Contratação: CLT Full + Benefícios 
Interessados enviar cv para: sueli.patricio@triadsystems.com.br

**Comment by nicholasess** [comment]
@Sueli321 pelo que eu vi, a vaga não tem como rotina a utilização do React. Você pode confirmar?
