### ISSUE TITLE
[REMOTO] Desenvolvedor Front End - JavaScript Pleno na iClinic

### ISSUE THREAD

**Issue by mauriciord** [react-brasil/vagas#290]
## Descrição
Com o propósito de Descomplicar a Saúde no Brasil, através de um sistema que entregue soluções incríveis para os nossos usuários, a iClinic é uma plataforma SaaS líder de mercado no país.

Estamos crescendo e desenvolvendo nosso produto constantemente, como parte disso, estamos aumentando a nossa equipe de tecnologia, de forma a garantir que a nossa ferramenta continue entregando valor aos nossos clientes.

Como desenvolvedor(a) Front End, você tem que manter o equilíbrio entre criatividade e produtividade em projetos inovadores.

## Quais os próximos passos?

Primeiro leia a vaga, veja se você se identifica, faça a sua candidatura e você terá seu primeiro desafio como requisito do nosso processo, que está descrito logo a seguir. E aí topa?

### O que você vai fazer?

- Irá ajudar a desenvolver novas funcionalidades de acordo com o roadmap do produto;
- Ajudará a encontrar soluções para problemas no sistema;
- Na maioria das vezes você irá trabalhar com equipes multidisciplinares em um ambiente ágil;
- Trabalhará com diversas pessoas brilhantes (como você) tendo uma troca de conhecimento muito bacana;

### O que esperamos de você:

- Estar sempre em busca de novos conhecimentos, lendo artigos, newsletters, participando de grupos;
- Demonstrar proatividade com as tarefas, projetos, ideias, e contribuir com resultados;
- Saber trabalhar em equipe, compartilhando seus conhecimentos, estar aberto a dar e receber feedbacks;
- Se importar com arquitetura de projetos, Design Patters e boas práticas de código;
- Boa comunicação;
- Metodologias de testes;
- Arquitetura de projetos, Design Patters e boas práticas de código;
- Alta capacidade para resolução de problemas: Entende o problema e consegue implementar a solução do início ao fim, sendo positivo, ágil e assertivo;

### O que você precisa ter?

- HTML: Api's, semântica, SEO;
- CSS: Ferramentas(pré e pós processadores), padrões, boas práticas de responsivo;
- React(V-dom's), gerenciamento de estado de apliçações, componentização, lidar com recursos e bibliotecas assíncronas
- HTTP request's;
- Git de forma geral (branchs, pull requests e etc..);
- Ambientes Node.JS e CLI(comand line);
- Teste unitários;
- Fluxo de trabalho com ambientes ágeis(CI, CD, Metodos agile);
- Noções clean code, noções de imutabilidade e funcional(Manipulação de estrutura de dados, Redux Saga) e arquitetura de projetos;
- Webpack e similar;

### Nice to have:

- Autodidata;
- Participar de comunidade;
- React Native;
- Entender Renderização (Lifecycle do browser, render, re-render, repaint, reflow);
- Experiência com Node.JS.

---

## Local
**Remoto** ou Escritório, em Ribeirão Preto, SP - Av. Presidente Vargas

## Benefícios

- Possibilidade de trabalho remoto;
- Plano de saúde;
- Vale alimentação;
- Plano de Participação dos Resultados;
- Trabalhe com os melhores computadores da apple;
- Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- Sem dress code. Trabalhe de calça, bermuda, chinelo, pantufa ou de qualquer outro jeito que achar confortável;
- Rango open: café da manhã, frutas ao longo do dia e copa para refeições. Além do sagrado cafezinho moído na hora;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Possibilidade de rápido crescimento na carreira.

## Como se candidatar

Você pode aplicar [aqui](https://iclinic.workable.com/j/1209823F78)

## Labels

- 🏢 Remoto
- 👴 Pleno
- ⚖️ CLT

**Comment by mrangel-jr** [comment]
@mauriciord , a vaga já foi preenchida ?

**Comment by mauriciord** [comment]
Já @mrangel-jr. Obrigado!
