### ISSUE TITLE
REMOTO/Empresa de SP - Desenvolvedor Fullstack Pleno/Sênior (React/Node) - 19103

### ISSUE THREAD

**Issue by KatiaGoisJacob** [react-brasil/vagas#2900]
## Descrição da vaga

Conhecimento em linguagens de programação
JavaScript (Node.js)
Java
Spring e Spring Boot
Ruby, entre outras.
APIs e integrações:
Experiência em RESTful APIs
Conhecimento em cloud computing:
Conhecimento em AWS

Segurança da informação:
Conhecimento em práticas de segurança da informação
Autenticação
Autorização
Criptografia
Prevenção de ataques.

## Local

Remoto, São Paulo - Alphaville/Barueri-SP

## Benefícios

- Plano de saúde (opcional)
- VR de R$28,00/dia
- VT (opcional) 

## Requisitos:
O que seria muito legal se soubesse:
Familiaridade com frameworks ágeis (Scrum, Kanban, etc...)
Conhecimento em ferramentas Atlassian: JIRA e Confluence.
Experiência HTML, CSS e JavaScript
Experiência React e React Native
Axway - API Gateway
Conhecimento em Continuous Integration: Git, Jenkins e Docker
Mensageria
Bancos de dados relacionais e não relacionais.
Conhecimento em Plataforma de Engajamento de Clientes
Twilio
TaskRouter
Console
Studio
Functions
Flex Application Platform
Flex Insights
Event Streams, entre outros.

## Contratação

CLT 

## Nossa empresa

(https://vagas.taking.com.br/home)

## Como se candidatar

Por favor envie um email para katia.jacob@taking.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Fullstack Pleno/Sênior

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior

- ⚖️ CLT
- 💰 10k-15k

**Comment by arielmell0** [comment]
🚀

**Comment by lucianomenddes** [comment]
currículo enviado 
[Link para portfolio](https://lucianomenddes.github.io/)
