### ISSUE TITLE
Contratando desenvolvedor react js

### ISSUE THREAD

**Issue by sittes** [react-brasil/vagas#2904]
Obrigatórios:

Estamos buscando um profissional para a posição de Desenvolvedor Frontend com experiência em React.js, consumindo APIs Rest, e familiaridade com a metodologia MVC. Além disso, é necessário ter habilidades em desenvolvimento Backend com Node.js e Express, bem como conhecimento em modelagem de dados No-SQL baseada em Firebase.

Valorizamos também conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS, pois essas habilidades podem ser relevantes para as responsabilidades da posição.

Resumindo, os requisitos para a contratação são:

Experiência em desenvolvimento Frontend utilizando React.js e consumo de APIs Rest.
Familiaridade com a metodologia MVC.
Habilidades em desenvolvimento Backend utilizando Node.js e Express.
Conhecimento em modelagem de dados No-SQL baseada em MongoDB.
Conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS.
Se você possui essas habilidades e está pronto para assumir esse desafio, gostaríamos de conhecer você melhor!

Por favor envie um email para vagas@ivipcoin.com seu CV anexado - enviar no assunto: Vaga React js

🏢 Remoto
👦 Pleno
⚖️ A-Combinar
⚖️ PJ
💰 3k

**Comment by glhrme** [comment]
2k - 3k por pleno no PJ? Ta certo isso?

**Comment by nicholasess** [comment]
@glhrme não está certo, esse valor é de junior
mas nós não fechamos a issue e deixamos para quem quiser se candidatar

**Comment by sittes** [comment]
> 2k - 3k por pleno no PJ? Ta certo isso?



> @glhrme não está certo, esse valor é de junior mas nós não fechamos a issue e deixamos para quem quiser se candidatar

Pode ser um profissional Júnior em transição para Pleno.

---

**Comment by sittes** [comment]
> 2k - 3k por pleno no PJ? Ta certo isso?

@glhrme Esta sim!

**Comment by pascoalkahamba** [comment]
Olá Paulo Fagner.

Estou entusiasmado com a oportunidade na IPVCOIN, onde posso combinar minha experiência em trading amador em Forex com mais de três anos como programador fullStack. Estou ansioso para aplicar minhas habilidades técnicas e minha paixão pelo mercado financeiro para contribuir com o objetivo da IPVCOIN de educar e capacitar indivíduos interessados em se tornarem traders profissionais. 

Enviei meu currículo e estou disponível para discutir mais sobre como posso agregar valor à equipe.

**Comment by eltonfreitasx** [comment]
Currículo enviado !!

**Comment by MathMendesReis** [comment]
currículo enviado

**Comment by Francisco-Fetapi** [comment]
Fiquei interessado na vaga, sou trader forex amador e programador full-stack ha mais de 4 anos, fiquei entusiasmado com a proposta da ipvcoin de ajudar pessoas a aprenderem mais sobre o mercado financeiro e a se tornarem traders mais bem informados e preparados. 

Acabei de mandar o meu curriculo.

**Comment by ghost** [comment]
curriculo enviado

**Comment by jonathasborges1** [comment]
up
