### ISSUE TITLE
[Remoto] Frontend React Developer na Coodesh

### ISSUE THREAD

**Issue by FrancieleGhizzoni** [react-brasil/vagas#2907]
## Descrição da vaga: 
Esta é uma vaga de um parceiro da plataforma Coodesh, ao candidatar-se você terá acesso as informações completas sobre a empresa e benefícios.

Fique atento ao redirecionamento que vai te levar para uma url [https://coodesh.com](https://coodesh.com/jobs/desenvolvedor-frontend-210422543?utm_source=github&utm_medium=react-brasil-vagas&modal=open) com o pop-up personalizado de candidatura. 👋
<p>Somos uma startup inovadora que fornece soluções de software de atendimento por videochamadas para grandes clientes, incluindo bancos, seguradoras e redes de universidades.</p>
<p>Estamos à procura de um Desenvolvedor Frontend para se juntar à nossa equipe e construir conosco uma tecnologia inovadora ao lado de profissionais dedicados e um ambiente leve e desafiador.</p>
<p><strong><em>Responsabilidades:</em></strong></p>
<ul>
<li>&nbsp;&nbsp;Desenvolver aplicações e páginas web completas, que fornecem soluções de atendimento por videochamadas inovadoras e eficientes.&nbsp;&nbsp;</li>
<li>&nbsp;&nbsp;Planejar e propor soluções técnicas para os desafios do produto, contribuindo com novos padrões de desenvolvimento e garantindo a qualidade do código.&nbsp;&nbsp;</li>
<li>&nbsp;&nbsp;Implementar e supervisionar o desenvolvimento de funcionalidades, garantindo o correto funcionamento, escalabilidade e segurança dos sistemas.&nbsp;&nbsp;</li>
<li>&nbsp;&nbsp;Colaborar com a equipe no processo de análise e elaboração da arquitetura dos projetos, bem como na disseminação de conhecimento e na revisão de código.&nbsp;&nbsp;</li>
<li>&nbsp;&nbsp;Desenvolver e ampliar testes unitários para garantir a qualidade e a confiabilidade das aplicações.&nbsp;&nbsp;</li>
</ul>
## NuVidio: 
 <p>As videochamadas já vinham apresentando grande crescimento e massificação do uso há alguns anos. Agora com a pandemia e o isolamento social tudo se acelerou, conversar por vídeo deixou de ser uma atividade corporativa e se tornou “mainstream”.&nbsp;</p>
<p>Com o mesmo impulso, o e-commerce se expande como nunca e está tomando o mercado das vendas físicas. Além disso, as pessoas, cada vez mais sozinhas, passaram a valorizar mais as interações humanas.</p><a href='https://coodesh.com/companies/nuvidio'>Veja mais no site</a>

 ## Habilidades: 
 - Typescript 
- React.js 
- CI/CD 
- Jest
## Local: 
 100% Remoto
## Requisitos: 
 - Experiência profissional como Desenvolvedor Web utilizando React. 
- Typescript / HTML / CSS 
- Escrever código limpo, de fácil manutenção e de alta testabilidade. 
- Habilidade com resolução de problemas e gerenciamento de tempo e tarefas. 
- Conhecimento sobre Arquitetura de Software e como melhor organizar o projeto. 
- Conhecimento em princípios da programação. 
- Conhecimento e utilização de ferramentas de linting (ESLint, Prettier). 
- Conhecimento de processos CI/CD (Vercel, AWS, Github Actions, etc..). 
- Testes unitários utilizando Jest / Vitest. 
- Ecossistema React: React Hooks, React Hook Form, Tailwind, React Query, I18n, Redux.
## Diferenciais: 
 - Ser independente e proativo. 
- Trabalho em equipe. 
- Facilidade de aprendizado. 
- Ser comunicativo e buscar soluções rápidas.
## Benefícios: 
 - Participação ativa no desenvolvimento de soluções tecnológicas de ponta. 
- Ambiente de trabalho colaborativo e criativo, onde suas ideias e contribuições são valorizadas. 
- Possibilidade de crescimento junto com a startup 
- Totalmente home-office;
## Como se candidatar:
Candidatar-se exclusivamente através da plataforma Coodesh no link a seguir: [Frontend React Developer na NuVidio](https://coodesh.com/jobs/desenvolvedor-frontend-210422543?utm_source=github&utm_medium=react-brasil-vagas&modal=open)

Após candidatar-se via plataforma Coodesh e validar o seu login, você poderá acompanhar e receber todas as interações do processo por lá. Utilize a opção **Pedir Feedback** entre uma etapa e outra na vaga que se candidatou. Isso fará com que a pessoa **Recruiter** responsável pelo processo na empresa receba a notificação.
#### Alocação
Remoto
#### Categoria
Front-End

**Comment by victorbiasibetti** [comment]
o site ta bugado acho para essa vaga
![image](https://github.com/react-brasil/vagas/assets/25385783/89dae89d-cd2d-47c0-bc20-7ad50f67bc78)

**Comment by FrancieleGhizzoni** [comment]
Bom dia @victorbiasibetti Acho que é só porque está carregando, eu testei aqui e abriu normalmente, se tiver dificuldades pode acessar a vaga pela nossa plataforma também coodesh.com

**Comment by victorbiasibetti** [comment]
tenteii em modo anonimo e normal 
a pagina finaliza de carregar e fica assim como no print 

bizarro

**Comment by victorbiasibetti** [comment]
@FrancieleGhizzoni no payload da pagina ta vindo isso como `job`

`"job": {
                                            "desenvolvedor-frontend-210422543": {
                                                "data": {
                                                    "message": "Cannot read property 'getItem' of undefined"
                                                }
                                            }
                                        },`

**Comment by julianlbs** [comment]
Eu consegui ver a vaga apenas depois de criar conta na plataforma

**Comment by victorbiasibetti** [comment]
mas nao pode ser que isso so acontece na minha conta, nem login consigo fazer

**Comment by FrancieleGhizzoni** [comment]
@Cristiano Albano ***@***.***>

Consegue dar uma olhada nessa questão?


Franciele Ghizzoni - Head de Recrutamento e Retenção Tech
2023, Coodesh
+55 (49) 99995-2308
https://coodesh.com
***@***.*** <http://coodesh.com/>


Em sex., 19 de abr. de 2024 às 10:12, Victor Biasibetti <
***@***.***> escreveu:

**Comment by FrancieleGhizzoni** [comment]
@victorbiasibetti Encontramos o erro e foi normalizado, obrigada pelo aviso.

**Comment by victorbiasibetti** [comment]
@FrancieleGhizzoni 
nao sei pq, nao consigo logar na minha conta e nem criar uma nova com emails diferentes


![image](https://github.com/react-brasil/vagas/assets/25385783/032ef88e-a47d-4277-be6f-80ed86cec809)
