### ISSUE TITLE
[Remote] Senior React Native Engineer at Rocket.Chat

### ISSUE THREAD

**Issue by diegolmello** [react-brasil/vagas#2936]
### Your Team 👥

You will report to our Engineering Manager and join the Mobile team. On [TheOrg](https://theorg.com/org/rocket-chat) you can view the complete structure of our organization, including information about every team member, hiring managers and the size of each department.

### Your Responsibilities ✏️ 

As a Senior Mobile Engineer at Rocket.Chat, you will play a critical role in developing our mobile applications, ensuring they are high-performing, high-quality, and responsive. Working closely with cross-functional teams, you will help define, design, and ship new features. Additionally, you will identify and resolve bottlenecks, bugs, and performance issues, staying abreast of industry trends and technologies to drive continuous improvement and innovation in our mobile offerings.

### What You'll Do 🖥️

- Write highly scalable, performant, and reliable features;
- Own new features from specification to production release;
- Diagnose and fix bugs and performance bottlenecks;
- Leverage native APIs for deep integrations with both platforms (iOS and Android);
- Write reusable, testable, and efficient code;
- Work collaboratively with other engineers and product managers;;
- Propose and drive improvements to the software proactively;
- Implement and manage best practices for maintaining source code repositories and branching/merging strategies for multiple codebases and applications;
- Maintain open-source repositories and contribute to the community.

## Local

Remote

## Benefícios

- Flexible Working Hours
- Fully Remote
- Unlimited Paid Time Off
- Holidays and Vacation Days
- Company Laptop and Headphone
- Remote Benefit
- iTalki
- Courses and Books 
- Stock Options
- Multicultural environment with colleagues in over 26 countries
- Vibrant Company Culture

Check out our [handbook](https://handbook.rocket.chat/) to dive into each of our awesome benefits! At Rocket.Chat, we have tailored base pay ranges according to work locations. This approach ensures that we can competitively and consistently compensate our employees across different geographic markets.

### Mandatory Hard Skills 🎯
- Extensive experience with React Native and TypeScript;
- Fluent English;
- Strong knowledge of mobile app development best practices and design patterns;
- Proven track record of diagnosing and fixing bugs and performance bottlenecks in mobile applications;
- Experience with native APIs and deep platform integrations;
- Solid understanding of mobile UI/UX design principles;
- Experience with writing testable and efficient code.
- Deep understanding of Git's/Github workflow model and versioning strategies for software development

### Desirable Hard Skills 💕 
- Experience with open-source projects and maintaining repositories;
- Knowledge of other programming languages and mobile development frameworks;
- Experience with CI/CD pipelines and automated testing;
- Familiarity with Agile development methodologies.

### Soft Skills ✨
- Communication: conveys information clearly, listens actively, and engages effectively with others, especially in asynchronous mode. 
- Passion: Genuine enthusiasm for what you do and how it contributes to our company's mission;
- Dream: Proactively seek out opportunities and challenges to achieve extraordinary results. If you're someone who takes initiative and is always striving to improve, you'll fit right in;
- Own: Take ownership of your work, set high standards for yourself, and be accountable for outcomes demonstrating a strong sense of responsibility and commitment; 
- Trust: Recognizing the importance of trust and support and actively working towards a collaborative and inclusive workplace;
- Share: Communicating openly and transparently, ensures clarity and honesty in interactions. 

## Contratação

CLT/PJ

## Nossa empresa

‍Rocket.Chat is the world's largest open-source communications platform. Built for organizations needing more control over their communications, it enables collaboration between colleagues, partners, customers, communities, and even platforms without compromising data ownership, customizations, or integrations.

Tens of millions of users in over 150 countries and organizations such as Deutsche Bahn, the U.S. Navy and Credit Suisse trust Rocket.Chat every day to keep their communications completely private and secure. As Rocket.Chat we believe in reconnecting the world, one conversation at a time! 

## Como se candidatar

Apply on https://www.rocket.chat/job?gh_jid=5228503004

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 15k+

**Comment by victorbiasibetti** [comment]
vaga fechada?
