### ISSUE TITLE
Oportunidade Imperdível: Desenvolvedor Frontend e Backend com Foco em React.js e Node.js - Trabalho Remoto

### ISSUE THREAD

**Issue by sittes** [react-brasil/vagas#2937]
### Obrigatórios:

Estamos buscando um profissional para a posição de Desenvolvedor Frontend com experiência em React.js, consumindo APIs Rest, e familiaridade com a metodologia MVC. Além disso, é necessário ter habilidades em desenvolvimento Backend com Node.js e Express, bem como conhecimento em modelagem de dados No-SQL baseada em Firebase.

Valorizamos também conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS, pois essas habilidades podem ser relevantes para as responsabilidades da posição.

Resumindo, os requisitos para a contratação são:

Experiência em desenvolvimento Frontend utilizando React.js e consumo de APIs Rest.
Familiaridade com a metodologia MVC.
Habilidades em desenvolvimento Backend utilizando Node.js e Express.
Conhecimento em modelagem de dados No-SQL baseada em Firebase.
Conhecimentos básicos em configuração de domínios DNS, hospedagem e VPS.
Se você possui essas habilidades e está pronto para assumir esse desafio, gostaríamos de conhecer você melhor!

Por favor envie um e-mail para vagas@ivipcoin.com seu CV anexado - enviar no assunto: Vaga React js 

🏢 Remoto
👦 Sênior
⚖️ PJ
💰 5k a 7k

**Comment by frontsennin** [comment]
Email enviado com interesse na candidatura

**Comment by pascoalkahamba** [comment]
Olá, Paulo Fagner,

Tenho mais de três anos de experiência com tecnologias como TypeScript, React.js, Next.js e Node.js. Estou confiante de que minhas habilidades podem agregar grande valor ao seu time, e estou muito empolgado com a possibilidade de contribuir para o desenvolvimento do projeto.

Acabei de enviar meu currículo e fico à disposição para conversarmos assim que possível.

**Comment by Willian-Barbo** [comment]
Enviei meu curriculo, e tenho interesse na vaga
