### ISSUE TITLE
[São Paulo] TECH LEAD REACT FRONT-END NA LINTE

### ISSUE THREAD

**Issue by niisereis** [react-brasil/vagas#294]
## Descrição do job

Estamos buscando alguém que manje de Stack em React e TypeScript para atuar com Programação Funcional. Como estamos em um momento de concepção e construção de um novo produto, esse profissional seria o responsável por gerir um incrível time de desenvolvedores na arquitetura Front-End do produto.

## Local

WeWork - Cubo (Vila Olímpia)

## Benefícios

- Plano de saúde (Sulamerica)
- Gympass
- Vale alimentação (p/ super mercados) ou VR (p/ restaurantes, bares, etc..) no valor de R$ 750 mensal
- Vale Transporte (neste caso, valor repassado pelo colaborador) ou Subsidio Transporte no valor de R$180 mensal (p/estacionamento,gasolina, aluguel de bike, patinete,etc...)
- Home office
- Day off
- Free beer
- Free coffe
- Auxílio creche

## Obrigatório

- Ter conhecimento sólido em React

- Conhecimentos em GraphQL

## Contratação

PJ

## Nossa empresa

A Linte é uma startup de software SaaS B2B, aqui usamos a tecnologia para devolver às pessoas o tempo que hoje é desperdiçado com tarefas operacionais. Nosso objetivo é fazer com que as pessoas trabalhem de maneira mais inteligente e estimulante, através da eliminação do retrabalho e do desperdício de informações.

Trabalhar na Linte é ter a oportunidade de sair da zona de conforto e aprender bastante, além disso, nossa equipe é incrível e muito próxima, pois acreditamos que a construção dos relacionamentos é algo natural que começa na nossa rotina de trabalho e se expande à maneira como lidamos com nossos clientes.

## Como se candidatar

Para se candidatar, enviar um e-mail com o Linkedin e pretensão salarial para monise@linte.com, com o assunto “GITHUB - TECH LEAD REACT FRONT-END NA LINTE"

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👴 Sênior
- ⚖️ PJ

**Comment by jeffersonlg** [comment]
Há vaga para Pleno?

**Comment by niisereis** [comment]
> Há vaga para Pleno?
Neste momento não, porém em breve estaremos abrindo vagas Jr/Pleno.
Me passa seu Linkedin ;)

**Comment by jeffersonlg** [comment]
@niisereis, Obrigado pela resposta.
Entendi, gostei bastante da vaga, mas perfil é pleno.

https://www.linkedin.com/in/jeffersonlg/
