### ISSUE TITLE
[Remoto, São Paulo] Front-End Developer na Somar Meteorologia

### ISSUE THREAD

**Issue by iamgbayer** [react-brasil/vagas#295]
## Descrição da vaga
Estamos procurando por um(a) Frontend Developer para nos ajudar a construir a próxima geração de ferramentas digitais para previsões de curto e longo prazo e informações em tempo real (forecast, nowcast, climatology).

Você fará parte de uma equipe altamente qualificada, abrangendo tecnologias espaciais abertas emergentes e novas formas de consumir dados meteorológicos.

## Local
A vaga aceita tanto remoto quanto no escritório da Somar, que fica localizado na Vila Leopoldina, São Paulo, SP.

## Requisitos
**Mandatórios:**
- Javascript (Vanilla)
- HTML5
- CSS3
- React
- Consumo de APIs REST
- Webpack
- GIT

**Desejáveis:**
- Vivência com React
- Pipeline de deploy em ambientes Cloud
- Ferramentas de controle de tarefas Jira
- Metodologias Lean/Agile
- Contato com opensource.

## Contratação
PJ a combinar

## Sobre a empresa
Junte-se a Somar Meteorologia, uma das principais empresas privadas do setor de meteorologia do país atuando desde 1995 atuando em diversos segmentos.

## Como se candidatar
**Desafio técnico**

É de grande interesse que você consiga realizar nosso desafio técnico para que possamos ter uma breve noção técnica relacionada a boas práticas, testes, organização, solução do problema proposto e outros. É claro que a avaliação técnica é apenas uma parte dentre outras que serão avaliadas.

[https://github.com/somarmeteorologia/challenge](https://github.com/somarmeteorologia/challenge)

## Mais detalhes
[Aqui](https://www.getoutline.com/share/d94b9d5b-ad03-49ed-b22c-dcd219b950d4) você encontra mais detalhes sobre a vaga.

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ

**Comment by jeffersonlg** [comment]
Gostei muito da vaga.

Enviei o email.

**Comment by Luiz-junior** [comment]
Boa tarde! A vaga ainda está em aberto? mandei um e-mail pra vocês a semanas mas ninguém respondeu.

**Comment by iamgbayer** [comment]
Oi @Luiz-junior, peço desculpas por deixar de lhe responder, foram tantas submissões para realizar o challenge nesses últimos dias que estou ainda respondendo e é claro colhendo feedbacks desse novo processo que estamos adotando.

**Comment by iamgbayer** [comment]
Ainda estamos com a vaga disponível

**Comment by Luiz-junior** [comment]
A contratação é PJ certo? Qual a faixa salarial?

Em qua, 14 de ago de 2019 às 13:16, Guilherme Bayer <
notifications@github.com> escreveu:

**Comment by Luiz-junior** [comment]
???

Em sáb, 17 de ago de 2019 às 11:13, junior rodrigues <
junior.rodrigues0222@gmail.com> escreveu:

**Comment by iamgbayer** [comment]
@Luiz-junior a faixa salarial seria entre R$3500 ~ R$4200, mas esse valor também pode depender muito do candidato em si

**Comment by Luiz-junior** [comment]
A vaga é pra Dev Júnior certo?

**Comment by iamgbayer** [comment]
Ainda estamos com uma vaga disponível, qualquer dúvida além do descrito na issue, fiquem a vontade que iremos esclarecer

**Comment by Wanhenri** [comment]
Boa tarde, tudo bom?
A vaga ainda esta disponível?

Em qua., 23 de out. de 2019 às 09:52, Guilherme Bayer <
notifications@github.com> escreveu:

**Comment by YuriBecker** [comment]
Ainda disponível?

**Comment by EdeiltonSO** [comment]
A vaga ainda está aberta?

**Comment by olavocarvlho** [comment]
Sim, manda um e-mail pra te mandarmos a chave.

**Comment by EdeiltonSO** [comment]
Ei, @olavocarvlho, mandei o e-mail

**Comment by info-bryanalves** [comment]
Boa tarde, tudo bem?

A vaga ainda está disponível?

**Comment by valdirSalgueiro** [comment]
Fulltime apenas?

**Comment by EdeiltonSO** [comment]
Boa tarde! Enviei o e-mail há alguns dias e não tive resposta. Tem alguma média de tempo pro envio do token?

**Comment by ARJOM** [comment]
A vaga ainda está disponível?
