### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor React Native na Super Revendedores

### ISSUE THREAD

**Issue by felipe-borges93** [react-brasil/vagas#297]
## Descrição da vaga

Estamos buscando um desenvolvedor React Native para integrar o Super time que está revolucionando o mercado de Venda Direta no Brasil!
Precisamos de alguém que já tenha experiência de pelo menos 2 anos, que preferencialmente já tenha lançado ou gerenciado aplicativos na Apple Store e que tenha empreendedorismo no sangue.
Você poderá se tornar sócio da empresa e impactar a vida de mais de 4 milhões de pessoas nesse projeto!
Além disso, você irá liderar o nosso projeto de expansão do nosso app para a plataforma IOS e participar de um novo projeto que estamos elaborando para o Android.

## Local

Remoto ou Escritório: Praia de Botafogo, 440, 22 andar - Botafogo - Rio de Janeiro

## Benefícios / Diferenciais

- Horário flexível
- VR de R$ 20,00 / dia
- VT se necessário
- Possibilidade de participação societária na empresa

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento React Native
- Já ter lançado apps ou participado de projetos que estão em produção na Play Store ou Apple Store
- Inglês avançado ou fluente 

**Desejáveis:**
- conhecimentos em GraphQL

## Contratação

PJ a combinar

## Nossa empresa

Super Revendedores é uma startup focada em revolucionar o mercado de Venda Direta no mundo! Esse é um gigantesco mercado, contando com mais de 4,5 milhões de revendedores no Brasil. 
Buscamos inovar na Venda Direta através da ampliação da produtividade, vendas e lucratividade dos revendedores e das empresas. Já contamos com mais de 26 mil usuários ativos e mais de R$ 100 milhões em vendas já foram transacionadas no nosso aplicativo. 
Somos um time de apaixonados por inovação, buscando gerar um grande impacto na vida de milhões de pessoas.

## Como se candidatar

Para se candidatar, enviar um e-mail com CV ou Linkedin e pretensão salarial para contato@superrevendedores.com.br com o assunto “GITHUB - RECT NATIVE DEVELOPER"

## Labels

- 🏢 Flexível
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by italomlp** [comment]
Essa vaga ainda está aberta?
