### ISSUE TITLE
[São Paulo] Vaga para desenvolvedor Front-end React 

### ISSUE THREAD

**Issue by LuisaALibanio** [react-brasil/vagas#299]
[São Paulo] React Developer na Spotz

O Spotz procura desenvolvedor front-end para trabalho freelancer. O trabalho consiste em implementar e ajustar novas funcionalidades. 

Tecnologias:

React
Go
MongoDB
RabbitMQ
Docker
Google Kubernetes Engine

Experiência com React
3 anos de experiência com front-end

Desejáveis:

Experiência em React 
Experiência com Go
Experiência com Kubernetes e Google Cloud Platform

Diferenciais:
Projetos opensource

Local: São Paulo 

Remoto ou Escritório, São Paulo - Itaim Bibi

O Spotz é um marketplace de locação de espaços pelo período de horas e diárias para pequenos eventos e produções audiovisuais. 

Por favor nos envie um email para vagas@spotz.com.br com seu CV anexado - enviar no assunto: Vaga desenvolvedor React Senior - freelancer

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ Freela
- ⚖️ PJ

**Comment by thiago-js** [comment]
tempo integral ?
