### ISSUE TITLE
[São Paulo] - Front-End Developer na Vitrine (ReactJS)

### ISSUE THREAD

**Issue by jversolato** [react-brasil/vagas#30]
## Descrição da vaga

Procuramos desenvolvedor Front-End React JS

## Local

Avenida Paulista 171 ou Remoto

## Benefícios

VT e VA

## Requisitos

**Obrigatórios:**
- ReactJS
- CSS/SASS
- GIT
- Experiência consumindo APIs Rest

**Diferenciais:**
- Redux
- Testes com Jest
- react-storybook
- highcharts
- React JS

## Contratação

- PJ (valor a combinar)
- CLT
- Full-time ou Remoto
- Pleno
- Sênior

## Nossa empresa

Somos uma startup inovadora com foco em gestão e métricas para o varejo. Estamos incubados na aceleradora ACE, a maior aceleradora da América Latina. (https://lnkd.in/dM565Bg)

## Como se candidatar

Interessados enviar CV ou Linkedin para vagas@vitrineretail.com com pretensão salarial e disponibilidade para inicio

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/PJ

**Comment by jvcjunior** [comment]
Rola um part-time?

**Comment by jversolato** [comment]
Infelizmente não Valter,

Precisamos de alguém focado 100%

Em seg, 2 de abr de 2018 16:43, Valter Júnior <notifications@github.com>
escreveu:
