### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack ou Frontend - REACT - Pleno

### ISSUE THREAD

**Issue by PtkFerraro** [react-brasil/vagas#303]
###Requisitos
-----------

- Bom conhecimento de Javascript & ReactJS & Redux;

- Já ter trabalhado com SPA;

- Json, Html5, Css3;

- Git;

- Conhecimento básico de desenv. web responsivo & mobile-first;

###Atividades
-----------

- Manutenção e aperfeiçoamento de módulos feitos em ReactJS;

- Criação de novos módulos e aplicação de regras de negócio;

- Integrações REST API;

- Garantir que funcionamento em diferentes navegadores & dispositivos;

###Diferencial 
------------

- Conhecimento básico .Net C# Web Api;

- Conhecer testes unitários (Jest, Chai, Enzyme, Mocka...);

- Conhecer testes E2E (End-to-end), testes funcionais, testes de integração;

###Benefícios & Local
-------------------

- Regime de contratação CLT

- Remuneração compatível com o mercado

- Av. Nove de Julho (próx. Rua Bandeira Paulista - Itaim)

### Contato
-----------------

patrick@boutique-pool.com

**Comment by JaderCleber** [comment]
Qual o contato?

**Comment by JIFerreira** [comment]
@PtkFerraro E eu envio pra quem? não tem beneficio nenhum? rola alguns dias home office pelo menos?

**Comment by PtkFerraro** [comment]
> @PtkFerraro E eu envio pra quem? não tem beneficio nenhum? rola alguns dias home office pelo menos?

Depende... depois das entrevistas e da experiência do candidato podemos ver alguns benefícios...
