### ISSUE TITLE
[São Paulo] Dev Javascript React Native e Node.js

### ISSUE THREAD

**Issue by ThaysdaCosta** [react-brasil/vagas#305]
## Descrição da vaga

Projeto supimpa com React Native, etc..

## Local

Remoto ou Escritório, São Paulo - Vila Madalena

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Android Nativo
- 2 anos de experiência com desenvolvimento iOS Nativo

**Desejáveis:**
- conhecimentos em GraphQL

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Estágio
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k
- 💰 10k-15k
- 💰 15k+

**Comment by juulhao** [comment]
@ThaysdaCosta esse email ta certo mesmo??

**Comment by danielGalvao** [comment]
@ThaysdaCosta Acredito que criou a Issue errado, corrija e reabra ou considere-a fechada.
Qualquer dúvida nos avise...
