### ISSUE TITLE
[Florianópolis] Desenvolvedor React na SOFTPLAN

### ISSUE THREAD

**Issue by PoloniaFernanda** [react-brasil/vagas#308]
## Descrição da vaga
Nosso desenvolvedor de front-end irá se envolver com uma comunidade interna engajada, compartilhando ou buscando conhecimento, além de contribuir em projetos internos, como nossa biblioteca de interface, criada para padronizar nossas aplicações React.  

## Local
Florianópolis, SC

## Benefícios

- Plano de saúde
- Plano odontológico
- Vale-alimentação
- Vale-transporte 
- Bonificação semestral por atingimento de metas

## O que esperamos:
- Conhecimento em JavaScript e na biblioteca ReactJs, incluindo conceitos de programação assíncrona, definições de escopo (clojures), componentização e ES6+; 
- Conhecimento em gerenciadores de estados, incluindo Redux e seus padrões de arquitetura. 
- Conhecimentos avançado em HTML e CSS, incluindo conceitos de layout, compatibilidade entre browsers e acessibilidade; 
- Conhecimento em paradigmas de orientação a objetos e funcional; 
- Conhecimento intermediário em GIT. 
- Conhecimento intermediário em apis REST e testes automatizados; 
- Conhecimento em algumas das bibliotecas Webpack, Gulp ou Grunt; 
- Conhecimento de técnicas e práticas de Clean Code; 
- Experiência em equipes dinâmicas e metodologias de desenvolvimento ágeis; 

**Desejáveis:**
- Formação completa em ciências da computação, sistemas de informação ou cursos equivalentes; 
- GraphQL 
 - Princípios de design de interação, UX e Design System; 
- Diretrizes de interfaces da Google (Material Design) e Apple; 
- Java, Go e outras linguagens backend; 
- Bancos de dados relacionais e não relacionais; 
- Frameworks JavaScript como Angular, Vue.js, etc; 

## Contratação

CLT

## Como se candidatar

Pode se increver no link: http://bit.ly/reactsoftplan. Qualquer dúvida por favor envie um email para nicole@softplan.com.br.

**Comment by raphaelcarreiro** [comment]
Parece que não existe o e-mail nicole@softplan.com.br.
