### ISSUE TITLE
[São Paulo] Desenvolvedor Frontend na TicketsForFun

### ISSUE THREAD

**Issue by lgavinho** [react-brasil/vagas#32]
## Descrição da vaga

Buscamos profissionais para desenhar e programar frontend dos nossos produtos digitais, principalmente a plataforma de tickets com experiência em Javascript, CSS, HTML e React.

## Local

Escritório, São Paulo - Santo Amaro

## Benefícios

- Plano de saúde e dentário
- VR
- VT

#### Diferenciais

- Lanches, frutas e sucos à vontade :P
- sala de jogos
- Estacionamento de graça

## Requisitos

**Obrigatórios:**
- 1 ano de experiência com desenvolvimento Javascript
- HTML, CSS 

**Desejáveis:**
- Design
- UX

## Contratação

CLT

## Nossa empresa

A TicketsForFun faz parte do grupo TIME FOR FUN que é líder no mercado de entretenimento ao vivo na América do Sul e a primeira empresa a atuar no segmento de forma diversificada e verticalizada. Acumula ampla experiência desde 1983, tendo promovido quase quatro mil eventos nas principais capitais e cidades do Brasil, Argentina, Chile e Peru. 
Com a atuação verticalizada, além de promover os espetáculos, a T4F se envolve diretamente em todos os aspectos relacionados ao evento, como a operação de casas de espetáculos e de bilheterias, a comercialização de produtos promocionais (merchandising) e a negociação de patrocínios. 
Realizamos e comercializamos as principais atrações na América do Sul, como: Lollapalooza, U2, Paul McCartney, Les Misérables, Disney On Ice, Mamma Mia e muitos outros.
A tecnologia já mudou e continua transformando todos os mercados. No segmento de entretenimento não é diferente. Venha trabalhar conosco e contribuir com a transformação do mercado de entretenimento ao-vivo. 

## Como se candidatar

Por favor, se inscreva em https://docs.google.com/forms/d/e/1FAIpQLScSEWc3Ax8wjdnVcm4UKV9UJy0QdAY4dqKObdcMAL97VVlwUA/viewform

## Labels

- alocação/Presencial
- experiência/Júnior
- experiência/Pleno
- regime/CLT

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criar uma nova issue, com informações mais atualizadas caso a vaga ainda esteja aberta.
