### ISSUE TITLE
[São Paulo] Desenvolvedor React Native

### ISSUE THREAD

**Issue by igoramsantana** [react-brasil/vagas#33]
## Descrição da vaga

Projeto super legal para empresa de cosméticos a nivel LATAM com React Native.

## Local

Escritório, São Paulo - Vila Leopoldina

#### Diferenciais

- 1 home office por semana

## Requisitos

**Obrigatórios:**
- Sólido conhecimento em Javascript
- React / React Native
- Uso da sintax JSX, linguagem JavaScript uso com (ES6)
- Router, navegação entre cenas/telas
- Domínio no controle de dados com (STATE e PROPS)
- Ciclo de vida do componente/aplicação
- Requisições http com (axios/fetch)
- Tratamento de dados JSON
- Integração com Web Services RESTFul

**Desejáveis:**
- Uso de Redux com React

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Toodoo nos prezamos por uma ambiente divertido e descontraido. Nossos projetos são bastante desafiadores e em diversas tecnologias (Native iOS / Android, Xamarin, IONIC e agora React Native), ou seja, um excelente lugar para se desenvolver como pessoa e profissional.

## Como se candidatar

Por favor envie um email para oi@toodoo.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criar uma nova issue, com informações mais atualizadas caso a vaga ainda esteja aberta.
