### ISSUE TITLE
[São Paulo] Desenvolvedor React - Cedro Technologies

### ISSUE THREAD

**Issue by PatriciaMourao** [react-brasil/vagas#332]
## Descrição da vaga

Apoio na criação e manutenção de sistemas atuais;
Identificar oportunidades evolutivas das aplicações atuais.

## Local
Berrini - SP

## Benefícios
Vale Refeição ou Vale Alimentação (485,00/mês)
Vale Transporte
Assistência Médica Unimed
Assistência Odontológica Odonto Prev

#### Diferenciais
- cerveja a vontade
- sala de jogos
- horário flexível

## Requisitos
**Obrigatórios:**
- Vivência com a linguagem Node.js;
- Conhecimento sólido em programação orientada a objetos e Design Patterns;
- Familiaridade com Docker e arquitetura de micro serviços.
- Conhecimento em Jenkins, JIRA, Nexus, Sonar, Git e Git Flow.
- Ensino superior em Ciências da Computação, Engenharia da Computação ou afins.
- Diferencial: conhecimento em Javascript, CSS, React; Git Flow;

## Nossa empresa
Fundada em 2005, a Cedro tem como objetivo transformar o mundo através de pessoas e tecnologias, com atuação global e sustentável.
A Cedro é uma empresa que tem o seu crescimento baseado na vontade de sempre criar e inovar.

## Como se candidatar
Por favor envie um email para th@cedrotech.com com seu CV anexado - enviar no assunto: Vaga React Native - SP

- 🏢 Presencial

## Contratação
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-11k

**Comment by jeffersonlg** [comment]
O e-mail está retornando, no endereço indicado, consegui enviar com o email sem o .br.

Uma vaga muito boa.
