### ISSUE TITLE
[REMOTO] Desenvolvedor Front-end na Upnid

### ISSUE THREAD

**Issue by lucasupnid** [react-brasil/vagas#35]
## Descrição da vaga

Você será responsável por desenvolver os recursos mais complexos dos projetos. Para isso é necessário ter um altíssimo conhecimento em padrões de desenvolvimento e qualidade de código.

**Você vai se encaixar se:**

- Tiver perfil driven e gostar de entregar novas funcionalidades

- Você gosta de sempre ser desafiado a prender mais

- Você abraça novos desafios e questiona o status quo

- Aprende rápido e se adapta facilmente a mudanças

- Você se dedica a criar um produto incrível em padrões internacionais

- Busca ter uma visão macro do projeto que entra para poder contribuir em diversas áreas.

- Para saber mais da vaga acesse: https://conheca.upnid.com/vaga-para-desenvolvedor-pleno/ 

## Local

Remoto - (Caso opte por trabalhar em escritório, possuímos frente em SP, BH e RJ)

## Benefícios

Possibilidade de PL

#### Diferenciais

- Bonificação extra para alto desempenho
- Incentivo a educação (cursos, livros, eventos, etc)
-Trabalho Remoto
- Horários flexíveis (você define a sua rotina)

## Requisitos

**Obrigatórios:**
- Experiência comprovada em React
- Conhecimentos em JavaScript, HTML, CSS
- Testes automatizados
- Foco em qualidade de código

**Desejáveis:**
- Conhecimento em Node.JS

## Contratação

PJ/CLT a combinar

## Nossa empresa

Somos um marketplace para venda de produtos físicos e digitais. Estamos a dois anos no mercado crescendo a cada mês. Temos Executivos de grandes empresas do ecommerce brasileiro como sócios.

## Como se candidatar

Por favor envie um email para lucas@upnid.com.br com seu CV e link do perfil no Github - enviar no assunto: "Vaga Desenvolvedor Pleno - GitHub"

## Labels

- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/PJ

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criar uma nova issue, com informações mais atualizadas caso a vaga ainda esteja aberta.
