### ISSUE TITLE
[Brasil] Vaga Programa Jovens Talentos 2019 - GRUPO VOTORANTIM

### ISSUE THREAD

**Issue by camilaintera** [react-brasil/vagas#351]
## Descrição da vaga

O programa Jovens Talentos 2019 fará a seleção de 6 candidatos para vivenciar a incrível experiência de trabalhar em projetos tecnológicos super desafiadores com o objetivo de levar a transformação digital às organizações. Os participantes terão um excelente programa de mentoria e de desenvolvimento de habilidades, assim como a chance de se conectarem com a rede de talento de todas as empresas que fazem parte do grupo!
A Votorantim está em busca de jovens apaixonados por tecnologia e que querem muito fazer a diferença a partir da transformação digital. Os requisitos básicos desse processo consistem em ter formação entre os anos 2016 e 2018 referentes a cursos da área de exatas, economia, tecnologia ou administração.

## Local

São Paulo

## Benefícios

- Bônus atrelados ao atingimento de objetivos
- Seguro de vida
- Assistência médica Bradesco Saúde
- Assistência odontológica (livre adesão)
- Reembolso creche (mulheres)
- Vale transporte
- Vale refeição
- GymPass
## Requisitos
Graduação COMPLETA entre os anos de 2016 a 2018;
Disponibilidade para trabalhar em São Paulo a partir de outubro de 2019;

**Diferenciais:**
- Domínio de inglês como diferencial.

## Nossa empresa

Somos uma holding investidora de longo prazo, brasileira e de controle familiar. A cultura de alta performance permeia as nossas atividades, focadas nas decisões de investimento e na transformação do portfólio. Atuamos nas empresas em que investimos por meio da influência, buscando fortalecer o propósito  de geração de valor e a perenidade dos negócios. 

## Como se candidatar

Link de inscrição e maiores informações no link: 

**https://bit.ly/31dehxv**

## Labels

- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ CLT

**Comment by Moonkzin** [comment]
Olá @camilaintera, tenho interesse, mas o link está quebrado, teria outra forma de se candidatar?
Obrigado!

**Comment by camilaintera** [comment]
> Olá @camilaintera, tenho interesse, mas o link está quebrado, teria outra forma de se candidatar?
> Obrigado!

Olá, @Moonkzin . Acabei de atualizar o link! Você pode testar para ver se consegue abri-lo?

**Comment by Moonkzin** [comment]
> > Olá @camilaintera, tenho interesse, mas o link está quebrado, teria outra forma de se candidatar?
> > Obrigado!
> 
> Olá, @Moonkzin . Acabei de atualizar o link! Você pode testar para ver se consegue abri-lo?

@camilaintera Sim, consegui acessar, obrigado!
