### ISSUE TITLE
[Curitiba] React + RN na Sei de Cor

### ISSUE THREAD

**Issue by fweffort** [react-brasil/vagas#355]
## Descrição da vaga

Estamos com 2 vagas para programadores React + React Native. Temos vaga temporária também.

## Local

Escritório - Centro Cívico

## Benefícios

- VR+VT

#### Diferenciais

- No dress code
- Horário Semi-Flexível
- Ambiente divertido

## Requisitos

**Desejáveis:**
- Conhecimento de frameworks de aplicações web (e.g. React, Vue).
- Experiência com State Management (e.g. Redux, Mobx, Vuex).
- Experiência com git.

**Diferenciais:**
- Familiaridade com criação de APIs e serviços REST.
- Experiência em desenvolvimento de integrações com serviços web.
- Conhecimento de técnicas de otimização para tempos de carregamento rápidos.
- Conhecimento de vulnerabilidades comuns em websites e como evitá-las.
- Conhecimento dos produtos da família Firebase

## Contratação
PJ

## Nossa empresa

Na Sei de Cor desenvolvemos tecnologias para auxiliar treinamentos para expansão comercial.

## Como se candidatar

Por favor envie um email para rh@seidecor.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels
- 🏢 Flexível
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Outros
- ⚖️ PJ
- 💰 5k-10k

**Comment by emersonbrs** [comment]
Boa noite. Aceita remoto?

**Comment by fweffort** [comment]
Fala mestre, a princípio somente presencial, mas manda seu CV,
rh@seidecor.com.br

Em seg, 5 de ago de 2019 às 19:04, Emerson Barbosa <notifications@github.com>
escreveu:
