### ISSUE TITLE
[São Paulo] Desenvolvedor React JS & React Native - [DeÔnibus]

### ISSUE THREAD

**Issue by Vinaum** [react-brasil/vagas#356]
Startup de tecnologia abre portas para um projeto supimpa em Javascript React e React Native.

  O profissional será responsável por realizar a manutenção e sustentação dos sistemas existentes, desenvolvimento de novas funcionalidades e entregas dentro dos padrões de qualidade exigidos. Entre as tecnologias necessárias, destacam-se:
React Native (dev mobile) e React (dev web).

Requisitos:
● Formação: Ensino Superior
● Experiência de 2 anos, no mínimo, em desenvolvimento de sistemas
● Javascript
● React e Redux
● HTML
● CSS, LESS e SASS
● Versionamento em GIT

**Diferenciais:**
- Projetos opensource

## Local

Escritório em São Paulo - Zona Sul (Próximo ao metrô Borba Gato)

## Benefícios
- VR (R$22,00/dia)
- Gympass

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para ja@sharerh.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Presencial

- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar

- ⚖️ PJ

- 💰 5k-10k

**Comment by ribeiroevandro** [comment]
Email enviado!
Mas fiquei com uma dúvida, quando se contrata como PJ, entendo que está contratando uma empresa e penso porque a exigência de uma graduação? Eu apliquei mesmo sem ter uma graduação, pois sou Front-End e não existe um curso focado e os que chegam mais próximos, não usam tecnologias que o mercado demanda, por esse motivo, escolhi fazer cursos pontuais ao invés de uma graduação.
