### ISSUE TITLE
[Porto Alegre/RS]  Senior React Developer 

### ISSUE THREAD

**Issue by jokapoa** [react-brasil/vagas#357]
## Vaga
Desenvolvedor front-end sênior para startup capitalizada com investmento e iniciando operações.
Previsão do projeto : 2 anos++

## Requisitos
- +de 5 anos de experiência com  desenvolvimento javascript;
- Domínio  total de  React /React Native;
- Vivência  sólida com   Javascript, Typescript, html5,css, e ajax;
- Vivência com metodologias ágeis é importante
- Vivencia  com desenvolvimento de aplicações baseadas em plataforma cloud (AWS)

## Contratação

PJ . ( 10 a 15K)

## Como se candidatar

Envie seu curriculo/linkedin para frontend@holdenrh.com.br

## Labels

- PJ
- Sênior

## Labels

- 🏢 Presencial
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 10k-15k

**Comment by kivervinicius** [comment]
Poxa, pensa ser presencial
