### ISSUE TITLE
[Sao Paulo] React Developer na We Pulse

### ISSUE THREAD

**Issue by ismaelrodrigues** [react-brasil/vagas#359]
## Descrição da vaga

Precisamos de Desenvolvedor Frontend React / React Native

## Local

Escritório (flexível), São Paulo - Pinheiros

## Requisitos

**Obrigatórios:**
- Experiência em algum framework — React, Angular, Vue ou Backbone
- JS vanilla, ES6
- Familiaridade com Restful API / SOAP / Socket
- HTML 5 / CSS-Less-Sass / Mobile first
- Git (Usamos Bitbucket)
- Experiência com ecossistema JS (babel, Redux, JSX, PUG, Webpack, gulp, etc)

**Desejáveis:**
- Familiaridade com metodologias Agile
- Interesse em trabalhar em um ambiente que possibilita aprendizado
- React Native
- Boa comunicação

## Contratação

PJ - R$8.000 a R$12.000 dependendo do nível de experiência

## Nossa empresa

Somos uma startup da área de **saúde e bem-estar** na fase de desenvolvimento do nosso produto piloto. Buscamos alguém com experiência em desenvolvimento web (Pleno ou Senior) e trabalho com ótimo acabamento visual.

## Como se candidatar

Por favor envie um email para vagas@wepulse.com.br

## Labels

- 🏢 Flexível
- 👴 Sênior
- ⚖️ PJ
- 💰 10k-15k

**Comment by assuncaojr** [comment]
aceita remoto 100%?

**Comment by ismaelrodrigues** [comment]
Vaga preenchida.
