### ISSUE TITLE
[SÃO PAULO-SP] Front end Engineer at International Team (confidential)

### ISSUE THREAD

**Issue by analuhcosta** [react-brasil/vagas#360]
## Descrição da vaga
We're hiring a front end engineer (Node or React) to be part of a international development team, to be located in Pinheiros (São Paulo-SP)
You're going to have a daily interface with USA team and be able to develop new features for more than 18 countries. The career growth possibilities are huge and you're going to work in a fast paced environment (and pet friendly)

## Local

Office at Pinheiros (next to Faria Lima station)

## Benefícios
•         Dog-friendly office- bring your dog to work with you.
•         Complimentary fruits and snacks available all day.
•         Long-Term Incentive Plan
•         Your choice between Mac or PC
•         Paid Health Plan with SulAmérica
•         Vale refeição of R$ 30,00 daily

## Requisitos

**Obrigatórios:**
At least 3 years of experience in front end development, using Node.js or React (after internships)
-Advanced English

## Contratação
CLT from R$6k to R$8k (depending on the seniority of the professional)

## Nossa empresa
Our client is an american multinational company of technology.

## Como se candidatar
Interested? Send your CV, linkedin or whatever to leandromari@pagepersonnel.com.br

## Labels
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT
- 💰 5k-10k

**Comment by MarcelloVSilva** [comment]
Uma dúvida, é remoto ou não?
