### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor Front-End React na Nodis

### ISSUE THREAD

**Issue by rtscosta** [react-brasil/vagas#363]
## Descrição da vaga

Desenvolvedor Front-End fulltime com um perfil entusiasta, pro-ativa e com espirito de equipe, para trabalhar com produtos digitais, principalmente voltados para o mercado do varejo. Buscamos uma pessoa que queira encarar o desafio de evoluir e estruturar novas soluções DO ZERO, sendo responsável pelas decisões técnicas e seus impactos no produto no médio/longo prazo e que queira ter bastante interação com o time de UX/UI para desenvolvimento das aplicações. Alguém capaz de traduzir o design de UI em interfaces Web responsivas com animações, boa usabilidade e performance.

## Local

Av. Gen. Justo, 375 - Centro, Rio de Janeiro - RJ, 20021-130.

## Benefícios

- Plano de saúde
- Vale Refeição ou Vale Alimentação
- Vale Transporte

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de soluções web de alta performance e missão crítica;
- Conhecimento em tecnologias (JavaScript, ReactJS, NodeJS);
- Conhecimento em HTTP/HTTPS, GraphQL e Rest/Json;
- Conhecimento em micro serviços;
- Orientação a objetos e padrões de desenvolvimento de software;
- Code refactoring e Arquitetura de software;
- Facilidade em se comunicar, aprender e ensinar;
- Gostar de escrever testes;
- Conhecer técnicas ágeis de desenvolvimento;
- Conhecimento de sistemas web (HTML/JS/CSS, servidores web), infraestrutura e redes;
- Conhecimentos de Linux;
- Saber se adaptar às mudanças.

**Desejáveis:**
- Trabalhar com software livre, contribuindo com a comunidade;
- Have great english skills;
- Conhecer um dos bancos de dados (postgres e mongo);
- Conhecimentos de Cloud Computing com experiência nos serviços Google Cloud GSP ou similar.

**Diferenciais:**
- Conhecimento em React Native

## Contratação

- ⚖️ CLT
- 🏢 Presencial

## Nossa empresa

A Nodis é uma Startup de tecnologia para varejo digital que nasce dentro do grupo StoneCo com a missão de ajudar o varejista do mundo físico a digitalizar seu estoque e vender mais, por meio dos marketplaces.

Desde o nosso nascimento, temos grandes desafios no nosso caminho de conectar os clientes Stone ao varejo digital, oferecendo soluções de tecnologia para impulsionar suas vendas. Para tornar nossa visão realidade, precisamos de pessoas que tenham paixão por resolver problemas, se sintam motivadas pela oportunidade de fazer a diferença na vida do varejista e estejam preparadas para se desenvolver pelo caminho. 

## Como se candidatar

Por favor se cadastre em https://forms.gle/GvBtyuAzapofjRps9. Qualquer dúvida, enviar email para Vitor.mendes@nodis.com.br

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by julioxavierr** [comment]
Por favor, adicione as labels para marcação.

**Comment by rtscosta** [comment]
> Por favor, adicione as labels para marcação.

Feito!
