### ISSUE TITLE
[Rio de Janeiro] FullStack React no Hotel Urbano

### ISSUE THREAD

**Issue by octamagalhaes** [react-brasil/vagas#37]
## Descrição da vaga

Oportunidade para Dev Full Stack Sr se juntar ao time de inovação do Hotel Urbano (Barra da Tijuca - RJ). 

É imprescindível ter experiência com Javascript (ECMAScript 2015+), Node.js, HTML, CSS, REST APIs, React, Koa || Express, Testes (Jasmine, Jest, Mocha, Chai ou outros). Um diferencial é ter experiência com com Build Systems/Bundlers (Grunt, Gulp, Webpack, Browserify, Rollup ou outros), camadas de agregação com GraphQL, React Native, plataformas mobile nativas (Android, iOS) e outras linguagens e frameworks.

Entre as principais responsabilidades estão construir e manter UIs expressivas para mobile e desktop; construir, manter e integrar API services (REST e GraphQL); criar e manter testes dos componentes do projeto; padronizar e documentar código do projeto e contribuir no planejamento e evolução do projeto.

## Local

Rio de Janeiro - Barra da Tijuca

octa@hu.com.br

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criar uma nova issue, com informações mais atualizadas caso a vaga ainda esteja aberta.
