### ISSUE TITLE
[São José dos Campos] Full Stack Junior/Pleno/Sênior [Sistema Pallas]

### ISSUE THREAD

**Issue by hugofialho** [react-brasil/vagas#370]
### Descrição da vaga
Desenvolvemos um sistema de ponto de venda e gestão para melhorar a vida dos pequenos e médios negócios.
Utilizamos tecnologia para transformar o varejo em uma experiencia simples, rápida e inteligente.

www.sistemapallas.com.br

### Local
São José dos Campos - Jardim Alvorada

### Atribuições:
Contribuir em decisões de arquitetura sobre novas partes do projeto;
Aderir às melhores práticas no desenvolvimento de UI e UX;
Criação de novas funcionalidades em Single Page Applications;

### Necessário:
Ter experiência em desenvolvimento web de, no mínimo, 1 ano;
Proficiência em CSS e Javascript;
Framework ReactJS;
Uso de SDKs e APIs REST;
Versionamento de Código Git;
Desenvolvimento de Código com boas práticas e bem estruturado;

### Comportamentos que valorizamos:
Autodidata;
Focado em resultados;
Proativo;
Motivado por desafios;
Gosta de sempre aprender coisas Novas;

### Contratação:
PJ a combinar.

[Para se candidatar preencha este formulário](https://forms.gle/NUCR7VNxEtDWgCnH6)

## Labels
- 🏢 Presencial
- 🏢 Flexível
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by pedroffd** [comment]
aceita remoto?

**Comment by hugofialho** [comment]
@pedroffd no inicio não, depois de se familiarizar com o projeto é possível ter 2 ou 3 dias remoto.

**Comment by thiagofrancisquete** [comment]
o processo ainda esta aberto?
