### ISSUE TITLE
[São Paulo/SP] - Vaga Front-End na vetfy (mercado pet)!

### ISSUE THREAD

**Issue by felipealvarenga** [react-brasil/vagas#380]
Vamos inovar com a gente?

Curriculo para felipe.alvarenga@vetfy.com.br !

```jsx
import React, { useState, useEffect } from 'react';
import * as database from 'firebase/firestore';
import { connect } from 'react-redux';
import {Vetfy, ApaixonadosPorPet, SeuLugar } from './cultura';
import { Local, Salario, NivelTecnico, Diferenciais} from './informacoes;'

function vetfy({ seuCurriculo }) {


    const [tecsVetfy, setTecsVetfy] = useState({});

    if (!seuCurriculo.javascript || !seuCurriculo.react) {
        return;
    }


    useEffect(() => {
        async function fetchTech() {

            const db = database.firestore();

            const tecnologias = await db.collection('vagas').doc('devs').get().data();

            setTecsVetfy(tecnologias);
        }

        fetchTech();
    }, []);


    const { firebase, nodeJS, ReactNative, ReactJs, javascript, redux, graphQL, gatsby, html, css } = tecsVetfy;

    return (
        <div>
            <Vetfy>
                <h1> Plataforma que está revolucionando a saúde dos Pets do Brasil</h1>
                <ApaixonadosPorPet>
                    <h2>{seuCurriculo.nome}, Venha empreender com a gente! Faça parte desse time!</h2>
                    <Tecnologias>
                        Você aprenderá e se desenvolverá em {firebase} , {nodeJS}, {ReactNative}, {ReactJs}, {javascript}, {redux}, {graphQL}, {gatsby}, {html}, {css}}
                    </Tecnologias>
                    <NivelTecnico>
                        Júnior (Vem com a gente!)
                    </NivelTecnico>
                    <Salario>
                        PJ - até R$3.000,00 - Compatível com a experiência e nível de mercado.
                    </Salario>
                    <Local>
                        Presencial - wework - av nações unidas 14261 - São Paulo/SP.
                    </Local>
                    <Diferenciais>
                        Empreender com a gente! Somos uma startup pioneira de tecnologia aplicada em atendimento veterinario em domicílio.
                        Flexibilidade de Horários
                        Muito crescimento profissional e possibilidade de virar sócio (somos meritocráticos!)
                    </Diferenciais> 
                </ApaixonadosPorPet>
            </Vetfy>
        </div>
    )

}

export default connect()(vetfy);
```

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- ⚖️ PJ
- 💰 1k-3k

**Comment by nicholasess** [comment]
@felipealvarenga se puder colocar o ganho mensal, será interessante pra galera filtrar a vaga

**Comment by felipealvarenga** [comment]
> @felipealvarenga se puder colocar o ganho mensal, será interessante pra galera filtrar a vaga

Feito! Obrigado!

**Comment by mrangel-jr** [comment]
@felipealvarenga , vcs aceitam part-time 100% remoto ?

**Comment by felipealvarenga** [comment]
> @felipealvarenga , vcs aceitam part-time 100% remoto ?

@mrangel-jr Neste momento agora não. Para esta vaga, precisamos de alguém presencial em SP com possibilidade de remoto por um período na semana.

**Comment by willianbvsanches13** [comment]
Não precisa do connect quando você usa os hooks... E o salário tá bem baixo! No mais bem criativa! Abraço!

**Comment by felipealvarenga** [comment]
> Não precisa do connect quando você usa os hooks... E o salário tá bem baixo! No mais bem criativa! Abraço!

@willianbvsanches13 Obrigado pelo feedback! A parte do connect no hooks, foi quase uma "licença poetica" pra reforçar o redux.

Sobre o salário baixo, somos uma startup sem dinheiro e com muito propósito. Você acha que até 3k p/ júnior (com noção em JS), com possibilidade de virar sócio no curto prazo está ruim? Nossa intenção é de achar jovens recém formados e dar um boost na carreira, com nosso time mais sênior.

Buscamos alguém que aceite esse desafio, pois crescerá junto com a empresa e no médio prazo o salário é muito superior do que a maioria das oportunidades e a pessoa se tornar mais um desenvolvedor no meio de vários!

Abraços

**Comment by ribeiroevandro** [comment]
Email enviado.

**Comment by willianbvsanches13** [comment]
@felipealvarenga claro, para jr está dentro da expectativa mesmo! Entendo a ideia de vocês e acho interessante...
Abraços

**Comment by willianbvsanches13** [comment]
@felipealvarenga para jr realmente é uma excelente oportunidade... se fosse remoto e pudesse ser no time off até me canditaria, boa vaga pra quem está iniciando mesmo!!
desculpe se causei algum constrangimento não era a intenção...
abraços

**Comment by felipealvarenga** [comment]
> @felipealvarenga para jr realmente é uma excelente oportunidade... se fosse remoto e pudesse ser no time off até me canditaria, boa vaga pra quem está iniciando mesmo!!
> desculpe se causei algum constrangimento não era a intenção...
> abraços

Imagina @willianbvsanches13  ! Não causou nenhum constrangimento. Pelo contrário, nos deu uma ótima oportunidade para explicar nossa cultura e valores. Todos os pontos de vistas são válidos, e não faço julgamento.

Quando tivermos oportunidades nesse perfil, entraremos em contato! Obrigado pelo interesse!!!

Abraços!

**Comment by guigaoliveira** [comment]
Se fosse remoto me canditaria também, está bem interessante pra quem quer iniciar.
