### ISSUE TITLE
[São Paulo] React Native Developer na RecargaPay

### ISSUE THREAD

**Issue by rodcast-recargapay** [react-brasil/vagas#384]
## About us

RecargaPay is the leading mobile payments enabler & wallet in Brazil. Since 2018, it is also the largest Brazilian fintech measured in downloads, having surpassed 10 million in Google Play alone. It's a company for everyday payments that embraces the needs of banked and unbanked in Brazil, from consumers to merchants, and has raised in 2018 US$29 million in Venture Capital in order to fuel its mission to democratize mobile payments in the country.  Investors include DN capital, IFC (a member of the World Bank Group), TheVentureCity, Ventech and Fjlabs. Also, notable entrepreneurs such as Fabrice Grinda, Martin Varsavsky and over 100 angel investors through Angellist and FundersClub are betting on RecargaPay.

## Description

Development is at the core of everything we do at RecargaPay. 

As React Native Developer you will work in a collaborative team environment on the design and execution of mobile products. We are looking for candidates who are excited to learn and to improve skills, who are eager to grow on a personal and professional level with our company.

Your main responsibilities will be:

- Write well designed, testable, efficient code by using best software development practices.
- Integrate data from various back-end services and databases.
- Gather and refine specifications and requirements based on technical needs.
- Create and maintain software documentation.
- Be responsible for maintaining, expanding, and scaling our mobile native applications.
- Up to date on emerging technologies/industry trends and apply them into operations and activities.
- Cooperate with web designers to match visual design intent.

## Requirements

- BS/MS degree in Computer Science, Engineering or a related subject.
- Proven working experience in Android and/or React Native.
- Top-notch programming skills and in-depth knowledge of modern mobile applications.
- Familiarity with at least one of the following programming languages: Java, Swift, Objetive-C.
- A solid understanding of how web applications work including security, session management, and best development practices.
- Knowledge of relational database systems and Object-Oriented Programming.
- Hands-on experience with network diagnostics, network analytics tools.
- Ability to work, learn and thrive in a fast-paced environment.
- Fluent in English or Spanish

## Benefits

- Competitive compensation package.
- Great health and dental insurance.
- Meal allowance (vale refeição).
- Transportation voucher (Vale Transporte).
- Cool office in a great location.
- Being part of a world-class team.

## How to apply

Please, follow the instructions [https://recargapay.workable.com/j/3F8C7A31C0](https://recargapay.workable.com/j/3F8C7A31C0)

## Labels

- ⚖️ CLT
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior

**Comment by julioxavierr** [comment]
Favor adicionar todas as labels contidas no template.
