### ISSUE TITLE
[Osasco] Desenvolvedor Apps [iProduce]

### ISSUE THREAD

**Issue by iproduce** [react-brasil/vagas#388]
Olá,

Tenho uma vaga aqui na empresa para desenvolvedor de APPs.
Será para alguns projetos. Precisa ser presencial.
É necessário ter conhecimento avançado em: HTML5, CSS3, Javascript, React, PHP, MySql, Firebase e Ionic.

A vaga é temporária pelo o período de 3 meses e é alocada no escritório em Osasco/SP
Tem interesse ou conhece alguém que esteja precisando? Então manda o seu portifólio e CV para no e-mail: freela@iproduce.com.br

Boa sorte!

**Comment by julioxavierr** [comment]
Favor seguir o template
