### ISSUE TITLE
[Remote] React Native Developer na DB1 Group

### ISSUE THREAD

**Issue by cristianeabe** [react-brasil/vagas#393]
## Descrição da vaga

Buscamos pessoas com alta capacidade crítica e analítica, fortes características de concentração e entrega de resultados, além de gostar de estabelecer relacionamentos saudáveis com equipes.
Participará do desenvolvimento de softwares e aplicativos, que integrarão um projeto extremamente inovador.

## Local

Remoto ou Presencial, Maringá/PR

## Benefícios

- Cesta de benefícios personalizada, com opções como:
- Vale Alimentação
- Vale Refeição
- Plano de Saúde
- Plano odontológico
- Auxílio Educação

#### Diferenciais

- Horário Flexível
- Dress Code casual

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de aplicações mobile multiplataforma
- Forte proficiência em JavaScript
- Experiência com React Native
- Experiência com ferramentas comuns de desenvolvimento de front-end como Babel, Webpack, NPM, Lint, JSX etc.
- Familiaridade com as ferramentas de controle de código (Git, GitHub, Bitbucket)
- Familiaridade com testes e depuração
- Familiaridade com o Agile

**Desejáveis:**
- Alto conhecimento em HTML5 e CSS3 ou (Sass)
- Experiência com NodeJs
- Experiência com ReactJs
- Experiência com iOS ou Android 

## Contratação

CLT

## Nossa empresa

A DB1 Group é uma empresa especializada em Fábrica de software, com atuação no Brasil e exterior, certificada no CMMI Nível 3.
Buscamos pessoas talentosas que queiram fazer parte deste time de Feras, que são responsáveis e tem influência em tudo o que ocorre à sua volta, que investem no crescimento profissional e humano, que AMAM tecnologia e desafios, que são e promovem LUZ na vida de outras pessoas através do desenvolvimento de softwares de qualidade.

## Como se candidatar

Por favor, cadastre seu currículo direto no link: https://vagasdb1.recruiterbox.com/jobs/fk03fje?source=Github ou envie um email para vagasdb1-vgsd0888@applications.recruiterbox.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- 💰 5k-10k

**Comment by julioxavierr** [comment]
Favor, adequar a postagem ao template.
