### ISSUE TITLE
[REMOTO ou ALOCADO AUSTRALIA] Front-End Developer [CSS] e [Atomic design] na Rocketlab

### ISSUE THREAD

**Issue by nativedone** [react-brasil/vagas#397]
![VAGA](https://user-images.githubusercontent.com/20998754/64810325-84dc5900-d5de-11e9-8ff7-a2054e263e07.png)

## Descrição da vaga

Oi pessoal,

Tem uma `1 vaga` de senior frontend do meu team aqui de Sydney/AU.

Basicamente, espera-se alguem que chegue e seja responsavel pela criacao e manutencao de components reutilizaveis usando principios de `atomic design`, `React` e `storybook`.

O time possui devs very very experientes em ReactJS, mas nao tao seniors em `CSS` pra resolver aqueles detalhes que garantem o famoso *pixel perfect*. Entao, essa vaga eh sua se `CSS` estah no seu coracao :)

## Local

Totalmente Remoto ou alocado com possibilidade patrocionio (sponsorship de visto)

#### Diferenciais

- Flexibilidade de horarios
- Pagamento em $AUD
- Contrato: `full-time`, `part-time` ou `freelance`
- Sponsorship e ajuda de custo pra realocacao

- Selecao sem enrolacao: 

1. Envie um codigo seu usando React
2. Call curta de 15 min em portugues
3. Test em real-time de 50 min em ingles (compartilhando a tela)
4. Contratacao ou feedback em `ateh 2 dias`  

## Requisitos

**Obrigatórios:**
- Top em CSS
- Experiência em Atomic design
- Experiência em React
- Experiencia em storybook
- Falar ingles (Nao precisa muita fluencia. O foco total eh comunicacao! Somos uma empresa de software. Pode falar ingles com erros? Pode! Mas, tem que falar. Tem que comunicar a sua idea e o seu trabalho.)

**Diferenciais:**
- Styled components.
- GraphQL

## Contratação

A combinar.

## Nossa empresa

https://www.rocketlab.com.au/

## Como se candidatar

- Me envie uma messagem privada em https://twitter.com/nativedone 

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- 💰 5k-10k
- 💰 10k-15k

**Comment by gabriellamas** [comment]
Mandei lá no twitter!
