### ISSUE TITLE
[Campinas - Belo Horizonte] Developer 

### ISSUE THREAD

**Issue by sapsico** [react-brasil/vagas#398]
## Descrição da vaga

Projeto supimpa com React Native, etc..

## Local

Remoto ou Escritório, São Paulo - Vila Madalena

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ X/dia
- Auxílio creche
- ...

#### Diferenciais

- 2 horas de almoço
- monte a sua máquina como desejar
- frigobar sempre cheio :P
- sala de jogos
- ...

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Android Nativo
- 2 anos de experiência com desenvolvimento iOS Nativo

**Desejáveis:**
- conhecimentos em GraphQL

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

Aqui na Corporação XPTO somos líderes em...

## Como se candidatar

Por favor envie um email para email@email.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Estágio
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k
- 💰 10k-15k
- 💰 15k+

**Comment by rafaelangical** [comment]
aparentemente o email está errado.

**Comment by julioxavierr** [comment]
Fechando a issue por falta de descrição
