### ISSUE TITLE
[Campinas- BH- RJ ou SP ] Developer React CI&T 

### ISSUE THREAD

**Issue by sapsico** [react-brasil/vagas#399]
Que tal fazer parte de um time que está com grande foco em transformar a linha de negócio do cliente. Nesse contexto você terá o desafio de expandir as hipóteses, testar e evoluir o produto do cliente que fica localizado nos EUA. 

**Procuramos pessoas que:**

Gostem de novos desafios e estão dispostas a aprender algo novo todos os dias;
Sejam criativos na concepção de soluções técnicas e consigam influenciar o cliente na adoção de novas tecnologias, fazendo o link para os ganhos potenciais;
Usem sua autonomia para propor e provar processos e técnicas que potencializem o impacto de valor de nossas entregas para o cliente.

**Você precisa ter:**
Experiência prática com React e React Native;
Sólidos conhecimentos de Javascript;
Inglês avançado para leitura escrita e conversação.
Conhecimentos de HTML e CSS;
Disponibilidade para atuar em Campinas ou Belo Horizonte, São paulo ou Rio de Janeiro.

**Você irá se destacar se:**
Tiver vivência prática em projetos internacionais;

**Você será responsável por:** 

Implementar as melhores práticas de código e design patterns, orientação a objetos e otimização de performance;
Desenvolver código limpo, testável e de fácil manutenção.
Contribuir com todo o processo de desenvolvimento de software.
Implementar features novas e investigar problemas em produção;
Participar do processo de code review, garantindo qualidade e consistência do código.

Link da vaga: https://www.linkedin.com/jobs/cap/view/1453872926/?pathWildcard=1453872926&trk=job_capjs

Gostou? Tem mais!

A CI&T também oferece:

Regime CLT, 40 horas semanais de segunda a sexta com horário flexível;
Remuneração a combinar;
Participação nos lucros e resultados;
Vale alimentação e refeição;
Assistência médica e odontológica (plano padrão custeado pela empresa);
Seguro de vida;
Licenças maternidade e paternidade estendidas;
Auxílio creche;
Ônibus fretado, estacionamento ou transporte intermunicipal de acordo com a base de atuação;
Descontos em estabelecimentos e parceria com o SESC;
Gympass.

Além disso...

Sem dress code: quem gosta de roupa social são nossos clientes. Aqui na base da CI&T você pode trabalhar de bermuda, chinelo, vestido, terno e gravata, do jeito que se sentir mais confortável!
Ambiente descontraído e acolhedor (adoramos cores, quadros e post-its);
Opções de lazer e relaxamento (videogame, sinuca, cadeira de massagem, etc);
Plano de carreira estruturado e acompanhamento individual;
CI&T University com cursos online disponíveis em diversos temas!
Prezamos pela diversidade, liberdade, flexibilidade e autonomia!

Todas as nossas vagas se destinam também para pessoas com deficiência.

**Comment by julioxavierr** [comment]
Favor, seguir o template.
