### ISSUE TITLE
[São Paulo] Front-End Developer no Grupo Método RH em TI

### ISSUE THREAD

**Issue by MTDRH** [react-brasil/vagas#4]
Descrição da vaga

O Grupo Método RH em TI está buscando profissionais para atuar em uma Startup.

Local de Trabalho: Zona Oeste – São Paulo.

Diferenciais

Salário competitivo, ambiente de trabalho desafiador, colaborativo e descontraído

Requisitos Obrigatórios:

Superior cursando em informática.
Experiência com HTML, CSS e React.

Diferenciais:

Conhecimento API e Node.JS

Contratação
CLT

Nossa empresa

O Grupo Método RH em TI é uma organização que possui sólida experiência em Recrutamento e Seleção de profissionais da área de Tecnologia da Informação, extensivo a área administrativa, Gestão de Pessoas e Treinamentos.

Como se candidatar
Favor enviar o currículo somente dentro do perfil solicitado com pretensão salarial para rh@mtdrh.com.br

**Comment by nicholasess** [comment]
@MTDRH a vaga ainda está em aberto?

**Comment by danielGalvao** [comment]
@MTDRH Vamos fechar a issue, se a vaga ainda estiver aberta reabrimos, ou você cria uma nova issue com novas informações.
