### ISSUE TITLE
[Valinhos] Programador SR - React Native - Sysmap

### ISSUE THREAD

**Issue by Jucilmarques** [react-brasil/vagas#401]
O Profissional será responsável pelo desenvolvimento e evolução de produtos, criando códigos limpos e bem documentados, seguindo as boas práticas do mercado. Irá atuar junto com a equipe de Design e Back-end, para criar a melhor experiência possível para os clientes.

Competências Técnicas:

Buscamos um profissional com sólida experiencia em desenvolvimento na tecnologia Javascript;
Experiência em React / React Native;
Capacidade em desenvolvimento de aplicações SinglePage;
Familiaridade com Git, Github, Jenkins;
Ter atuado com as tecnologias: jQuery, CSS, HTML, JSON, Bootstrap;
Desejável: Experiência em ExpressJS, TDD, Framework de testes.

Local: Valinhos - Escritório

Benefícios:

- Assistência Médica
- Assistência Odontológica (Opcional)
- Vale Refeição
- Vale Alimentação
- Auxílio creche
- Ajuda de custo (combustível e estacionamento)

 Contratação: CLT

Nossa empresa:

Somos uma empresa brasileira de tecnologia com pessoas apaixonadas por Inovação. Ao longo dos últimos 20 anos, ajudamos empresas a resolverem desafios de negócio complexos e acumulamos experiência em diferentes segmentos do mercado como Telecom, Varejo, Educação, Financeiro, Indústria/Cosméticos e Energia. 

O nosso time trabalha em parceria com o cliente, compartilhando ideias e conhecimento, entregando cada vez mais valor e melhor experiência para o usuário. 

Nós apoiamos os nossos clientes na Transformação Digital e acreditamos que essas ações irão contribuir e influenciar a nossa sociedade positivamente. 

Como se candidatar:

Por favor envie um email para jucileia.silva@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga React Native - Valinhos

**Comment by julioxavierr** [comment]
Favor, seguir o template.
