### ISSUE TITLE
[São Paulo - Zona Oeste] React Native Developer - Sysmap 

### ISSUE THREAD

**Issue by Jucilmarques** [react-brasil/vagas#402]
Profissional com experiência em desenvolvimento de sistemas Mobile Full Stack.

Local: Zona Oeste - Escritório

Conhecimentos técnicos imprescindíveis:

• Análise e desenvolvimento de sistemas
• Principais Linguagens: Typescript, JavaScript, Kotlin e Java.
• Sistemas Operacionais: Linux, MAC OS, Linux
• Frameworks JS: React Native, React, Webpack, MaterialUI, Redux, Mobx, Express, NestJS
• Database: MySQL, SQL Server e NoSQL (Mongodb e Redis)

Contratação: PJ a combinar

Nossa empresa:

Somos uma empresa brasileira de tecnologia com pessoas apaixonadas por Inovação. Ao longo dos últimos 20 anos, ajudamos empresas a resolverem desafios de negócio complexos e acumulamos experiência em diferentes segmentos do mercado como Telecom, Varejo, Educação, Financeiro, Indústria/Cosméticos e Energia. 

O nosso time trabalha em parceria com o cliente, compartilhando ideias e conhecimento, entregando cada vez mais valor e melhor experiência para o usuário. 

Nós apoiamos os nossos clientes na Transformação Digital e acreditamos que essas ações irão contribuir e influenciar a nossa sociedade positivamente. 

Como se candidatar :

Por favor envie um e-mail para jucileia.silva@sysmap.com.br com seu CV anexado - enviar no assunto: Vaga React Native - Zona Oeste

**Comment by MarcosSarges** [comment]
Qual o nível ? JR, PLENO OU SR?

**Comment by Jucilmarques** [comment]
Olá Seria nível Pleno.




[Descrição: Descrição: SysMap]<http://www.sysmap.com.br/>
[Descrição: Descrição: SysMap]
Jucileia Silva
Recursos Humanos
Tel. 11.99529-8039

www.sysmap.com.br<http://www.sysmap.com.br/>
[Descrição: Descrição: CMMI - mps]

                                     skype: jucleias
[Descrição: Descrição: untitled]

De: Marcos Sarges <notifications@github.com>
Enviada em: segunda-feira, 16 de setembro de 2019 10:07
Para: react-brasil/vagas <vagas@noreply.github.com>
Cc: Jucileia Aparecida Marques Silva <jucileia.silva@sysmap.com.br>; Author <author@noreply.github.com>
Assunto: Re: [react-brasil/vagas] [São Paulo - Zona Oeste] React Native Developer - Sysmap (#402)


Qual o nível ? JR, PLENO OU SR?

**Comment by julioxavierr** [comment]
Favor, seguir o template.

**Comment by Jucilmarques** [comment]
Ok

Obrigada!





[Descrição: Descrição: SysMap]<http://www.sysmap.com.br/>
[Descrição: Descrição: SysMap]
Jucileia Silva
Recursos Humanos
Tel. 11.99529-8039

www.sysmap.com.br<http://www.sysmap.com.br/>
[Descrição: Descrição: CMMI - mps]

                                     skype: jucleias
[Descrição: Descrição: untitled]

De: Júlio Xavier <notifications@github.com>
Enviada em: terça-feira, 17 de setembro de 2019 08:11
Para: react-brasil/vagas <vagas@noreply.github.com>
Cc: Jucileia Aparecida Marques Silva <jucileia.silva@sysmap.com.br>; Author <author@noreply.github.com>
Assunto: Re: [react-brasil/vagas] [São Paulo - Zona Oeste] React Native Developer - Sysmap (#402)


Favor, seguir o template.
