### ISSUE TITLE
[Jundiaí/SP] React Native - Júnior ou Pleno

### ISSUE THREAD

**Issue by OhRamalho** [react-brasil/vagas#403]
**React Native Developer na Monkey Dev / Jundiaí-SP**

## Descrição da vaga

Login utilizando as mesma credenciais já existentes no banco - API
- Autentica em /api/TokenAuth/Authenticate
- Salva Token Localmente para próximas requisições. Se o token vencer gerar novo

Página de Listagem de veículos/anúncios disponíveis - API
- Consumir o endpoint /api/services/app/Auctions/GetAllActiveAuctionsForCatalog e listar veículos (esse endpoint recebe ordenação e filtros)
- Os filtros para listagem do catálogo estão em:
p/ Marcas: /api/services/app/Auctions/GetMakesComboboxItems (select/option)
p/ Modelos: /api/services/app/Auctions/GetModelsComboboxItems	(select/option)
p/ Preços: /api/services/app/Auctions/GetHighestPriceForFilter (este componente de ser uma range slider de preferência)

Página de Detalhes de um veículo - API
- Consumir o endpoint passando o ID do leilão: /api/services/app/Auctions/GetAuctionForCatalogDetails (essa tela deve ter todas as características do veículo)
•	- Ao dar lance ou arrematar, fazer POST para o endpoint: /api/services/app/Auctions/BidIncrement

## Local

Remoto

## Benefícios

Pagamento por Projeto / Etapa

**Desejáveis:**
React Native / Rest API / UI / UX

## Contratação

PJ a combinar / Freelancer a combinar 

## Como se candidatar

Por favor envie um email para felipe@monkeydev.com.br com seus dados de contato, assim poderemos marcar uma call e tira todas duvidas sobre a oportunidade - 
Enviar no Assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno

- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ

- 💰 A Combinar, falaremos sobre isso na Call

**Comment by hladf** [comment]
Ainda está aberto? @OhRamalho

**Comment by pedroffd** [comment]
Já fechou a vaga?
