### ISSUE TITLE
[Londrina PR] Java Front End - React Developer na Kroton

### ISSUE THREAD

**Issue by Talentkroton** [react-brasil/vagas#410]
## Descrição da vaga

- Atuar no desenvolvimento e evolução de nossos produtos criando códigos limpos e bem documentados sempre seguindo as boas práticas de mercado;
- Trabalhar junto à equipe de Design e Backend para criar a melhor experiência possível ao cliente no que diz respeito principalmente a performance e a segurança das aplicações;
- Seguir as recomendações da W3C (ex.: SEO e Acessibilidade) no desenvolvimento.

## Local

Temos alguns escritórios espalhados pelo Brasil, mas você ficará alocado em Londrina (Paraná) - Unopar Piza!

## Benefícios

- Plano de saúde
- Plano odontológico 
- VR ou VA
- VT
- Desconto em cursos Graduação e Pós. 
- Seguro de vida
- Gympass
- Participação nos lucros

## Requisitos

**Obrigatórios:**

- Devs com formação em Cursos de Ciências da Computação e afins. Candidatos com capacitação em Tecnologia da Informação também são bem vindos;
- Buscamos alguém com experiência em desenvolvimento de softwares na tecnologia Javascript, incluindo manipulação de DOM;
- Experiência em REACT, REACT Native; 
- Facilidade de desenvolvimento de micro-interações;  
- Capacidade em desenvolvimento de aplicações SinglePage
- Experiência em otimização de interfaces para máximo de velocidade; 
- Capacidade de construir soluções com compatibilidade cross-browsers; 
- Conhecimentos de desenvolvimento de interfaces assíncronas realizando chamadas serviços REST; 
- Familiaridade com git, GitHub, Jenkins; 
- Capacidade de desenvolvimento utilizando pré-processadores de CSS como LESS, SAAS, Stylus etc;
- Experiências em desenvolvimento Web 2.0 utilizando tecnologias jQuery, CSS3, HTLM5, Less, AJAX, JSON, Bootstrap, PHP; 
- Experiência em construção de soluções de alta disponibilidade e alta resiliência; 
- Capacidade de evoluir tecnicamente parceiros de time com sua experiência e vivência técnica;
- Linguagem de programação PL/SQL;

**Estas aqui são nice to have:**
- Experiência no tratamento de imagens para web, Conhecimento e uso de bibliotecas modernas MVC Javascript: AngularJS, EmberJS, ReactJS; Conhecimentos de conceitos em acessibilidade e SEO; Alta visão de componetização construindo códigos de alta reutilização; Familiaridade com técnicas de Code-Review e Pair Programming; Experiência em ExpressJS; Automação de testes de interface; TDD; Frameworks de testes; Experiência em projetos de e-Commerce; AngularJS; Integração com APIs do Facebook, Google Maps, Instagram, LinkedIn, RD Station, entre outras; Gerenciadores de pacotes: Yarn, NPM, Componentjs; Testes: Protractor, Selenium, QUnit, Jasmine; Princípios e práticas de desenvolvimento ágil (Scrum, XP, Kanban). 

## Contratação

CLT

## Nossa empresa

A Kroton tem mais de 50 anos de tradição e é atualmente uma das maiores empresas do setor de educação, temos um modelo de negócio bastante abrangente, que atende a vários segmentos do ensino no país, desde o maternal até o mestrado e o doutorado. Mas, especialmente em nosso caso, tradição e liderança não são traduzidas em modelos antigos e ‘zona de conforto’. Pelo contrário. Temos em nosso DNA a inovação e o dinamismo de uma jovem startup. Um dos reflexos disso é a nossa busca constante pela #TransformaçãoDigital. Estamos em busca de transformação em todos os sentidos: de histórias, de vidas, do futuro. Agimos pensando no sucesso do aluno. Temos paixão por educar. Valorizamos as pessoas. Somos responsáveis. Fazemos acontecer. Buscamos inovação. Geramos valor sustentável e juntos, podemos mais. **Nós somos a Kroton!**

## Como se candidatar

Gostou do que leu? Legal! Então, é só se candidatar ou indicar para um amigo!
Por favor envie um email para daniele.f.oliveira@kroton.com.br com seu CV anexado - com o assunto: Vaga React Londrina

## Labels
- 🏢 Presencial
- 👨 Pleno
- ⚖️ CLT
- 💰 À combinar.

**Comment by Talentkroton** [comment]
17/09: Vaga divulgada e aberta

**Comment by julioxavierr** [comment]
Favor adicionar o restante das labels para marcação.
