### ISSUE TITLE
[São Paulo] React Native Developer na PIXTER

### ISSUE THREAD

**Issue by RecruiterFMonteiro** [react-brasil/vagas#411]
## Descrição da vaga

Temos uma oportunidade de desenvolvedor, para integrar equipe de desenvolvimento Mobile, onde você vai ter a oportunidade de trabalhar com React, React Native, Ionic, Node.js, etc.

## Local

São Paulo - Presencial.

## Requisitos

**Obrigatórios:**

- Interesse em aprender novas tecnologias e compartilhar conhecimento;

- Curtir trabalhar em equipe;

- Vestir a camisa da empresa;

- Adaptável a mudanças no decorrer do projeto;

- Saber se virar no JavaScript (usar um map, um sort, etc);

- Saber efetuar chamadas para APIs externas;

- Ciclo de vida do React;

- Conhecer e já ter utilizado alguma lib de Rotas;

- Conhecimento em Redux ou Context ou MobX (se não souber você aprende aqui);

- Conhecimento na estrutura de um app Android e IOS nativo;

- Conhecimento no fluxo de publicação de um app Android e IOS.

## Contratação

PJ - Salário a combinar.

## Nossa empresa
Somos uma boutique de software que tem em seu core desenvolvimento, inteligência e usabilidade.
Filtramos projetos que têm fit cultural com o que acreditamos e trabalhamos com poucos clientes.
Nos últimos três anos acumulamos cases de sucesso com empresas de grande porte.
Veja mais em: https://pixter.com.br/

## Como se candidatar

Por favor envie um email para fernanda.monteiro@pixter.com.br com seu CV anexo - enviar no assunto: Vaga React Native

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by julioxavierr** [comment]
Favor adicionar labels para marcação.
