### ISSUE TITLE
[São Paulo] Desenvolvedor React JS para OSF GLOBAL SERVICES

### ISSUE THREAD

**Issue by carolina-brand** [react-brasil/vagas#414]
## Descrição da vaga

Projeto React JS em uma empresa global!

## Local

Escritório, São Paulo - Vila Olímpia.

## Benefícios

Bradesco Saúde (pago 100% pela empresa)
Seguro de vida
VR de R$ 28,00/dia
Bônus Educação de R$150,00/mês
Bônus Esporte de R$40,00/mês
Programa de mentoring
Certificações pagas pela empresa
Plano de carreira bem delineado (avaliação de performance de 4 em 4 meses)

#### Diferenciais

Empresa global presente em mais de 19 países.

## Requisitos

Obrigatórios:

Sólida experiência com HTML 5, CSS 3 and Javascript (ES6+);
React;  
Redux;
Jest;  

Desejáveis:

S.O.L.I.D Concepts  
Styled components;  
Recompose;  
Redux-Saga;  
React-Testing-Library

## Contratação

CLT + Benefícios (citados acima)

## Nossa empresa

OSF Global Services is a trusted technology consultant and technology integrator enabling companies to succeed over the greatest challenges in the world’s rapidly changing business environment. With expertise in cloud and mobile application development, enterprise CRM solutions, leading ecommerce platforms and integrated content management solutions.

## Como se candidatar

Por favor envie um email para carolina.brand@osf-global.com com seu CV anexado - enviar no assunto: Vaga React JS

## Labels

Alocado
CLT
Pleno
Senior
React JS
Redux
Mobile

**Comment by julioxavierr** [comment]
Favor seguir as labels definidas no template

**Comment by carolina-brand** [comment]
A vaga ainda está aberta.
