### ISSUE TITLE
[São Paulo] React Native Developer na RADAR PROFISSIONAL

### ISSUE THREAD

**Issue by RADARProfissional** [react-brasil/vagas#42]
## Descrição da vaga

Desenvolvimento React e React Native

## Local

Alphaville - Barueri

## Benefícios

Contratação PJ

#### Diferenciais

Atuação com diversas tecnologias e desenvolvimento profissional

## Requisitos

**Obrigatórios:**

•	React Native
•	Redux
•	HTML/CSS
•	Json/XML;
•	APIs RESTful e SOAP;
•	GIT;
•	Adaptação de layouts de smartphones e tablets;
•	Arquitetura de Software;
•	Testes unitários e automatizados (TDD);

**Diferenciais:**
•	Clean Architecture;
•	Programação Reativa.

## Contratação

PJ a combinar

.

## Como se candidatar

Por favor envie um email para recrutadora@radarprofissional.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/PJ
- REACT NATIVE
- RADAR PROFISSIONAL

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by RADARProfissional** [comment]
Sim, está aberta.

 



 

Esta mensagem pode conter informações confidenciais e/ou privilegiadas. Se você não for o destinatário ou a pessoa autorizada a recebê-la, não pode usar, copiar ou divulgar as informações nela contidas ou tomar qualquer ação baseada nelas. Se você recebeu esta mensagem por engano, por favor, avise imediatamente o remetente, e em seguida, apague-a. Comunicações pela Internet não podem ser garantidas quanto à segurança ou inexistência de erros ou de vírus. O remetente, por esta razão, não aceita responsabilidade por qualquer erro ou omissão no contexto da mensagem decorrente da transmissão via Internet. "ECONOMIZE PAPEL - PENSE ANTES DE IMPRIMIR!"

 

De: Daniel Galvão <notifications@github.com> 
Enviada em: quarta-feira, 3 de outubro de 2018 11:45
Para: react-brasil/vagas <vagas@noreply.github.com>
Cc: RADAR Profissional - Consultoria de Recrutamento & Seleção <cristiane@radarprofissional.com.br>; Author <author@noreply.github.com>
Assunto: Re: [react-brasil/vagas] [São Paulo] React Native Developer na RADAR PROFISSIONAL (#42)

 

A vaga continua aberta?
