### ISSUE TITLE
[Florianópolis] Front-end Developer na Cheesecake Labs

### ISSUE THREAD

**Issue by cheesecakelabs-challenges** [react-brasil/vagas#420]
If you’re an enthusiastic, talented and resourceful Front-End Developer with the relevant skills & IT experience, let's talk about creating disruptive products, with an international and multidisciplinary team.

**Some activities you would do on a typical day at Cheesecake Labs:**

Develop and maintain Web Frontend applications
Interact with other teams and professionals, including other developers, designers, project managers and stakeholders
Create outstanding interfaces
Write beautiful, readable and scalable code
Review code of other developers
Make sure the application has a great user experience
Assist in the creation and implement mockups
Make sure the application solves real-world problems
Understand the needs of our partners and come up with solutions for their problems
Participate in Sprint Plannings and daily stand-up meetings
Build estimates and plan roadmaps

This is a full-time position (CLT) located on our cool Florianopolis/SC office.

We offer: health and dental care, meal allowance, stock options, career plan, quarterly bonus, additional benefits, above average salary, flexible working time, geek culture, 24/7 snacks, beers and a unique work environment.

**What will help you succeed**

Experience with Javascript, CSS and HTML
Familiar with ReactJS and/or others Single Page Application libraries
Knowledge about clean code, design patterns, and reactive programming
Knowledge about basic design principles
Being self-taught
Being up-to-date with latest news and technologies about Frontend
English proficiency
Good communication skills, both in verbal and writing
Experience with Git

Cheesecake Labs is a web/mobile development and design company headquartered in Florianópolis - Brazil, but with a solid integration with the Silicon Valley, in the US. We make partnership with startups with great disruption potential - and we develop mobile and web solutions for them.

Apply at: ckl.io/careers

#PLENO

**Comment by julioxavierr** [comment]
Please use the template
