### ISSUE TITLE
[São Paulo] Desenvolvedor FrontEnd JR (react) na SUPPLY LLABS 

### ISSUE THREAD

**Issue by thatigonc** [react-brasil/vagas#428]
**## Descrição da vaga**

Ajudar na prototipação de produto.
Participar de discussões para levantamento de hipóteses de solução, nos ajudando a pensar novos produtos e novos módulos.
Codificar os aplicativos e colocá-los em produção, garantindo a qualidade de cada entrega.
Participar ativamente de decisões de tecnologias, infraestrutura, etc.

**## Local**

São Paulo - Paraíso

**## Requisitos**

**Obrigatórios:**
- Ter trabalhado em ao menos um projeto utilizando ReactJS, e que seja um produto digital. 
- Ser fluente com tecnologias como HTML, CSS e Javascript

**Desejáveis:**
- Saber consumir APIs REST de forma otimizada.

**Diferenciais:**
- Saber versionar código e interagir com GIT.

## Contratação

PJ a combinar

## Nossa empresa

A supplyLabs surgiu da necessidade de aplicação de inteligência nas ferramentas de gestão e monitoramento de cadeias de fornecimento, trás o que há de mais inovador em inteligência e tecnologia para uma maior transparência e assertividade nas tomadas de decisão.

## Como se candidatar

Por favor envie um email para tatiane.goncalves@taking.com.br com seu CV anexado e pretensão

## Labels

- 🏢 Presencial
- 👦 Júnior
- ⚖️ PJ
- 💰 3k-5k

**Comment by MarcosSarges** [comment]
O nome da empresa está certo?

**Comment by thatigonc** [comment]
Boa tarde!

O nome foi com um "L" a mais.

Att


[cid:466a9085-5db8-4fc3-bc12-ded40f4b5788]

________________________________
De: Marcos Sarges <notifications@github.com>
Enviado: terça-feira, 24 de setembro de 2019 13:53
Para: react-brasil/vagas <vagas@noreply.github.com>
Cc: Tatiane Gonçalves <tatiane.goncalves@taking.com.br>; Author <author@noreply.github.com>
Assunto: Re: [react-brasil/vagas] [São Paulo] Desenvolvedor FrontEnd JR (react) na SUPPLY LLABS (#428)


O nome da empresa está certo?

**Comment by MarcosSarges** [comment]
O email voltou.

**Comment by thatigonc** [comment]
> O email voltou.

Marcos, envie em: tatiane.goncalves@taking.com.br ou pode me enviar via whatsapp no: 11 9 8530-4520.

**Comment by maxarouca** [comment]
Bom dia. Somente presencial ou aceitam remoto?

**Comment by thatigonc** [comment]
> Bom dia. Somente presencial ou aceitam remoto?

Boa tarde! Apenas presencial
