### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor(a) React Native na KLB Group

### ISSUE THREAD

**Issue by AmandaMercuri** [react-brasil/vagas#429]
## Descrição da vaga

- Atuação em projetos inovadores que irão transformar o setor de previdência e seguros no Brasil;
- Transformar ideias de negócios em software, participando do design técnico e implementando aplicações de última geração;
- Propor soluções inovadoras de serviços e bibliotecas, desde a concepção até a produção, garantindo alta performance e larga escala;
- Diagnosticar e corrigir bugs e gargalos de desempenho;
- Manter o código e escrever testes automatizados para garantir que o produto seja da mais alta qualidade.

## Local

Rio de Janeiro - RJ

## Benefícios

- VT
- VR ou VA
- Plano de saúde, plano odontológico e seguro de vida (Bradesco)
- Convênio farmácia (Vidalink)
- Auxilio creche/baba
- Parcerias com universidades e escolas de idiomas
- Academia de TI com + de 150 cursos

#### Diferenciais

- Espaço social com vídeo game

## Requisitos

**Obrigatórios:**
- Conhecimento sólido em JavaScript (ECMAScript 6);
- Ter experiência comprovada em projetos mobile React Native;
- Ter algum conhecimento sobre desenvolvimento nativo iOS (Objective-C/Swift) e Android (Java/Kotlin);
- Ter experiência no consumo de API's RESTful;
- Saber como resolver possíveis problemas na compilação de versões de release;
- Saber como publicar, administrar atualizações e versões de teste de um app nas lojas da Apple e Google;
- Saber versionar código e interagir com GIT;
- Escrever códigos limpos e de fácil entendimento.

## Contratação

CLT a combinar

## Nossa empresa

A KLB Group (www.klbgroup.com/pt-br/) é uma multinacional francesa presente em mais de 20 países e com 23 anos de experiência no mercado global. A empresa é especialista em implementação e execução de projetos, com forte atuação nas áreas de TI, Engenharia e R&S.

## Como se candidatar

Envie seu currículo para amercuri@klbgroup.com

Mais informações: (11)97458-1772
https://www.linkedin.com/in/amandamercuri

Labels

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by MarcosSarges** [comment]
Como deve identificar o email? (Assunto)

**Comment by AmandaMercuri** [comment]
> Como deve identificar o email? (Assunto)
Pode colocar como está aqui ([Rio de Janeiro] Desenvolvedor(a) React Native na KLB Group).
