### ISSUE TITLE
[SP - Vila Olímpia] Desenvolvedor Frontend React/React Native at ZxVentures/Ambev/Zé Delivery

### ISSUE THREAD

**Issue by leocadastro** [react-brasil/vagas#43]
## **Description**
We are developing a global platform where customers from many countries will be waiting for their cold beers! You will work with people with multidisciplinary skills (PO, UX / UI, Developers and QAs) in order to deliver the best experience for our users.

You will join a team where everyone share a common interest in distributed backend systems, their scalability and continued development. If you are passionate about working with high scalable backend infrastructure, and are motivated to make an impact in creating a robust and scalable software - this is the opportunity for you.

## **Requiriments**

**_Must have experience_**
React
HTML5, CSS3
Modern JavaScript ES6+
Webpack/Browserify
GIT
Responsive Layout
Good practices and front-end pattern knowledge
Advanced English

**_Nice if you have experience_**
React Native
Redux
Apollo/Relay
Flexbox
GraphQL
Some functional programming knowledge
Python/Ruby/Java/Scala

## **Benefits**
Attractive compensation package
Health, dental and life insurance
GymPass
Meal allowance

## **How to apply?**
[Apply for this job](https://zx-ventures.workable.com/j/2355DDAC69)

## Labels
alocação/Presencial
experiência/Senior
regime/CLT

**Comment by danielGalvao** [comment]
A vaga continua aberta?
