### ISSUE TITLE
[Curitiba] Desenvolvedor ReactJS e React Native na Esparta

### ISSUE THREAD

**Issue by cavarzan** [react-brasil/vagas#439]
## Descrição da vaga

3 Vagas relacionadas a ReactJS e React Native.

- Desenvolvedor Frontend ReactJS

- Desenvolvedor React Native

- Desenvolvedor Java e React Native

## Local

Curitiba - Água Verde

## Benefícios

Como CLT:

- Plano de saúde
- VR de R$ 500,00 mensais

#### Diferenciais

- Trabalho remoto
- Flexibilidade de horário

## Requisitos

**Obrigatórios:**
- Pelo menos 1 ano de experiência com desenvolvimento ReactJS + CSS, Java ou React Native

**Diferenciais:**
- Conhecimento em Spring Framework
- Conhecimentos de boas práticas e design de API
- Conhecimento de ferramentas de Integração Contínua.
- Conhecimento em Docker.
- Conhecimento em Testes unitários e de integração.

## Contratação

CLT ou PJ.

## Nossa empresa

Trabalhamos com metas e entregas a cada duas semanas, possibilitando assim um horário flexível e trabalho remoto nos dias que desejar. Toda liberdade e flexibilidade depende apenas do comprometimento de cada um com a qualidade de seu trabalho e entregas com clientes.

Valorizamos pessoas curiosas e que gostem de aprender coisas novas. Incentivamos troca de papeis na equipe, então quem estiver disposto terá a oportunidade de aprender um pouco de tudo que trabalhamos aqui: Java, Android/Kotlin, iOS/Swift, React Native, ReactJS, Angular, NodeJS, entre outras coisas.

Damos todo o apoio para o aprendizado, em compensação somos muito exigentes com a evolução, empenho e qualidade do trabalho.

## Como se candidatar

Envio de currículos através do site https://esparta.io/vagas/

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ CLT
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k

**Comment by LuanCassiano** [comment]
CV enviado

**Comment by PauloRev** [comment]
CV enviado :)
