### ISSUE TITLE
[São Paulo/Remoto] Front-End React Senior

### ISSUE THREAD

**Issue by vrbarros** [react-brasil/vagas#44]
## Descrição da vaga

HTML5, CSS3, Javascript, jQuery, AJAX, JSON
Sass, Grunt/Gulp
Bootstrap 3/4
React, Node.js
Experiência com versionamento utilizando GitHub.com

## Local

Remoto ou Escritório, São Paulo - WeWork Paulista

## Benefícios

- Seguro de vida
- Vale refeição de R$ 19,50/dia
- Vale transporte

#### Diferenciais

- Tudo que a WeWork disponibiliza (chopp, água, café, salão de jogos, etc)

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento React
- Formação na área de Engenharia ou Ciências da Computação

**Diferenciais:**
- Projetos publicados no GitHub
- Participação em projetos Open Source

## Contratação

CLT à combinar

## Nossa empresa

Já pensou em fazer parte de uma equipe com a missão de mudar a educação do país? A Eskolare está com vaga aberta para Desenvolvedor Front-End Pleno, para alguém com muita vontade de aprender e se desenvolver, que seja inovador em suas abordagens, além de saber se adaptar às adversidades diárias e aos problemas do dia-a-dia, com espírito de equipe e capaz de entender as necessidades do usuário, além de sempre buscar melhorar e desenvolver suas habilidades.

Somos uma empresa jovem, com uma missão desafiadora e queremos que em poucos anos todas as instituições educacionais do país realizem a comercialização de produtos e serviços educacionais dentro da nossa plataforma.

## Como se candidatar

Por favor envie um email para victor.b@eskolare.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Sênior
- regime/A-Combinar
- regime/CLT

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by vrbarros** [comment]
> A vaga continua aberta?

Sempre! Estamos com mais vagas!
