### ISSUE TITLE
[Belo Horizonte] Pessoa desenvolvedora frontend ReactJS na E-Conform [CLT] [Junior] [Pleno] [Remoto] [4K-6K]

### ISSUE THREAD

**Issue by maximilianocatarino** [react-brasil/vagas#443]
Empresa Endeavor procura profissional organizado, proativo, capaz de iniciar um projeto do zero. Que tenha sede por aprendizado e flexibilidade para adaptar-se às mudanças de cenário e prioridades. Projeto em fase inicial, abrangência nacional, frontend ReactJS, backend Node.js.

## Atividades e Responsabilidades
Entre outras coisas, nesta posição você terá a oportunidade de:
Analisar, projetar, programar, depurar e modificar software;
Escrever códigos, realizar testes e depurar aplicações;
Interagir com os interessados para entender os requisitos para o desenvolvimento de aplicações;
Dar manutenção em software legado em AngularJS;

## Requisitos
Domínio em HTML5, ReactJS e CSS3 (SASS);
Redux / Mobx;
Conhecimento em Javascript (Vanilla), ES6;
Vivência em estimar e analisar interfaces a partir de arquivos PSD, AI e Zeplin;
Controle de versão (Git);
Ambiente de desenvolvimento Linux;

Local de trabalho: Belo Horizonte. 
Possibilidade de trabalho remoto.

## Contratação
Forma de contratação, CLT. Salário de acordo com experiência do profissional. Até R$6000,00.

## Nossa empresa
A e|conform foi criada para solucionar um grande desafio de gestão presente na vida das empresas. Administrar licenças mantendo-as em conformidade com as leis e regras governamentais se tornou um complexo e custoso problema, que se agrava na mesma proporção do tamanho das redes.

Trata-se uma plataforma 100% digital, inédita e disruptiva para controlar a vida para-legal de sua empresa. Transforma o que era complicado em uma experiência intuitiva e de fácil operação, facilitando a visão completa das licenças em todos os CNPJs, reduzindo custos e o risco de multas e penalidades para os estabelecimentos e seus administradores.

O processo é simples. A partir do workflow criado para cada CNPJ o sistema consulta eletronicamente a receita federal e busca todos os CNAEs relacionados (código nacional de atividade econômica) . A plataforma utiliza a inteligência embarcada para apresentar todas as licenças necessárias vinculadas aos CNAEs. A partir dai, o sistema monta um dashboard de controle e realiza a gestão online disparando alertas de vencimento, avisando sobre impactos, complexidades e prazos para obtenção de cada licença.

A plataforma e|conform é contratada através do modelo SaaS, “Software as a Service”. A e|conform se responsabiliza por toda a estrutura necessária à disponibilização do sistema (servidores, conectividade, cuidados com segurança da informação) manutenção e atualização do software. O cliente utiliza a plataforma via internet, “na nuvem”, pagando um valor mensal recorrente pela licença de uso do software proporcional ao número de CNPJ’s administrados.

## Como se candidatar
Por favor envie um email para maximiliano.catarino@econform.com.br com seu CV anexado - enviar no assunto: Vaga ReactJS.

## Labels
- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- 💰 4k-6k

**Comment by maximilianocatarino** [comment]
Sim, ainda está disponível. Infelizmente.

Em sáb, 21 de dez de 2019 12:12, stale[bot] <notifications@github.com>
escreveu:

**Comment by KalZera** [comment]
Ainda está ofertando a vaga ?

**Comment by maximilianocatarino** [comment]
Sim, ainda estou.

Em qua, 29 de jan de 2020 09:18, Alexander Karuzoo <notifications@github.com>
escreveu:

**Comment by maxleon52** [comment]
Achei a ideia muito legal, já trabalhei como suporte/analista de sistemas tributários onde exercia atividades de treinamento e analista de sistemas para coletar, analisar, propor e solucionar eventuais problemas relacionados ao sistema. Fazer integração com o sistema municipal, que consequentemente é usado por todas as secretárias municipais, o controle por parte da empresa e prefeitura seria fenomenal.

Sou dev Jr, e não sei Angular, e fica ruim pra mim. Estudo apenas React, react native e node.

**Comment by guiedinger** [comment]
É 100% remoto a vaga?

**Comment by gutosoares** [comment]
CV enviado por email! 
Aguardo seu retorno @maximilianocatarino

**Comment by maximilianocatarino** [comment]
Preferencialmente não. Mas é possível.

Em ter, 4 de fev de 2020 17:57, Guilherme Edinger <notifications@github.com>
escreveu:
