### ISSUE TITLE
[São José dos Campos] Desenvolvedor React na GSW Software

### ISSUE THREAD

**Issue by marianabompean** [react-brasil/vagas#445]
## Descrição da vaga
Atuar em grande cliente, projeto com foco em desenvolvimento React.

## Local

São José dos Campos

## Benefícios
Á Combinar
- ...

#### Diferenciais
Flexibilidade de horário

## Requisitos

**Obrigatórios:**
1 ano de experiência com desenvolvimento React.

**Conhecimentos:**
- JavaScript ES6
- Redux
- KOA(para Nodejs)
- MongoDB
- RabbitMQ
- Mongoose
- Postgree

## Contratação

PJ á combinar

## Nossa empresa

A GSW é uma empresa referência, no desenvolvimento de soluções em Tecnologia da Informação, oferece a seus clientes sistemas de TI que se traduzem em melhorias significativas para o dia a dia do negócio, principalmente no que se refere à redução de custos e ao aumento da produtividade. Clientes: SPC Brasil, Embraer, Ericksson, Panasonic etc..

## Como se candidatar
Por favor, envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vaga React

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by Brunoalcau** [comment]
acho que é RabbitMq?

**Comment by nic** [comment]
@Brunoalcau Corrigi aqui por eles. Vlw!
