### ISSUE TITLE
[REMOTO] Desenvolvedor FullStack na Mensageiro.io

### ISSUE THREAD

**Issue by Marcosul** [react-brasil/vagas#45]
## Descrição da vaga

DESENVOLVEDOR JS FULLSTACK

Buscamos profissionais que curtem criar aplicações com Javascript.

## OPORTUNIDADE

Remuneração de R$ 2.500,00 por mês.
Trabalho remoto.
Carga de 30 horas semanais.

### REQUISITOS

Possuir graduação completa.
Ter familiaridade com tecnologias baseadas em Javascript, tais como NodeJS, ReactJS, Redux, Express, MongoDB.
Ter facilidade de aprender novas tecnologias
Estar comprometido com o time.

### QUEM SOMOS

O Mensageiro é uma Startup Catarinense que cria chatbots para negócios.

### INSCRIÇÃO

Interessados, chamar no Facebook Messenger da Empresa:

m.me/mensageiro.io ou facebook.com/mensageiro.io

## Local

Remoto

## Labels

- alocação/Flexível
- experiência/Pleno
- regime/Bolsista

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by Marcosul** [comment]
Você tem interesse na vaga?

Att,

Marco Sulzbacher
(48) 9 9683-9045


Em sex, 25 de jan de 2019 às 11:36, stale[bot] <notifications@github.com>
escreveu:
