### ISSUE TITLE
[São Paulo] Desenvolvedor Front End / React JS na Descola

### ISSUE THREAD

**Issue by grpaiva** [react-brasil/vagas#460]
## Descrição da vaga

A Descola quer transformar o modelo de educação com cursos leves, práticos que entregam uma nova habilidade para as pessoas aplicarem no trabalho e na vida pessoal. Como uma escola de cursos online, nossa plataforma é um dos pilares da experiência do aluno. Por isso estamos reconstruindo toda essa experiência com base em inputs dos próprios usuários. O desenvolvedor front end será responsável por construir o novo front, que está em fase final de design, consumindo dados da nossa API.

O candidato selecionado fará parte do squad de desenvolvimento, onde, junto com o desenvolvedor back end e o designer web, irão construir a nova plataforma de cursos da Descola. Nosso back end também está em processo de reconstrução, por isso será necessário o alinhamento profundo entre design/front/back.

## Local

CUBO - Alameda Vicente Pinzon, 54 - Vila Olimpia, SP

#### Diferenciais

- Ambiente informal e descontraído
- Autonomia e flexibilidade no trabalho
- Acesso a cursos online da Descola
- Acesso a cursos presenciais da ECHOS
- Acesso ao ecossistema do CUBO, com outros devs, startups e eventos diários no prédio
- Sinuca, tênis de mesa e totó (pebolim) no rooftop
- Ah, claro: chopp grátis todos os dias a partir das 18h (juro)

## Requisitos

**Obrigatórios:**
- React + Redux
- Sólido conhecimento em HTML5 e CSS3
- JavaScript Avançado (ES6 + ES7)
- Experiência com APIs RESTFul
- Bootstrap 4
- GIT
- Boas práticas e código limpo e reutilizável

**Desejáveis:**
- Experiência com AWS
- TDD em JS (Jest, enzyme e etc)

**Diferenciais:**
- React Native

## Contratação

PJ

## Nossa empresa

A Descola é uma escola de inovação online.

Ensinamos práticas, ferramentas, metodologias e aplicações para fomentar inovação e transformação digital nos ambientes de trabalho.

Com uma metodologia própria, selecionamos temas, professores e modelamos o conteúdo de ponta a ponta, permitindo que aluno aprenda e desenvolva uma nova habilidade para aplicar em sua vida ou no trabalho.

Na Descola o aluno aprende a se relacionar melhor, a se comunicar melhor, ser mais produtivo, a resolver problemas de uma maneira mais efetiva e a mudar sua maneira de pensar. Trazemos conhecimentos e aplicações para desenvolver pessoas em um mundo cada vez mais complexo.

## Como se candidatar

Envie seu github e linkedin para gustavo@descola.org. Se quiser escrever alguma coisa, fique a vontade, se não quiser, ta tudo bem!

Só me ajuda nessa, vai. Coloca isso no assunto: 
[react-brasil] Desenvolvedor Front End / React JS

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by VictorHCord** [comment]
Vaga de Jr ainda está em aberto ?
