### ISSUE TITLE
[Remoto] Desenvolvimento de app para grupos de meditação

### ISSUE THREAD

**Issue by hugomelo** [react-brasil/vagas#461]
## Projeto pontual de desenvolvimento de app com possibilidade de continuação

Trabalho remoto flexível com acompanhamento semanal. Outro desenvovedor criará a API para comunicação com o App.
O App é um sistema de cadastro e acompanhamento de presença de participantes em meditações coletivas periódicas e outros eventos.

## Requisitos

**Obrigatórios:**
2 anos de experiência com desenvolvimento em React / React-Native

**Diferenciais:**
- projetos opensource
- comprovação da experiência

## Contratação

PJ a combinar

## A Ananda Marga
O projeto é para a Ananda Marga, uma organização socio-espiritual internacional fundada na Índia em 1955 e presente hoje no mundo todo. Seu objetivo é a realização completa de todas as potencialidades humanas e baseia-se na filosofia do Yoga e na prática da meditação.

## Como se candidatar

Por favor envie um email para jobs@d4all.org com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- ⚖️ A-Combinar
- ⚖️ Freela
- 💰 3k-5k

**Comment by gtfuhr** [comment]
Bom dia, esta vaga ainda está disponível?

**Comment by prxg22** [comment]
@hugomelo ainda estão procurando desenvolvedor para esse app?

**Comment by hugomelo** [comment]
@prxg22 Ainda não fechamos, mas já recebemos muitos CVs. Devo escolher um em pouco tempo.
