### ISSUE TITLE
[Barueri] Desenvolvedor Frontend React no Grupo GBI

### ISSUE THREAD

**Issue by lbraga** [react-brasil/vagas#47]
## Descrição da vaga

Projeto de Educação com Frontend em React+Redux

## Local

Escritório em Barueri - Alphaville

## Benefícios
Salário + Benefícios
Vale Transporte
Vale Refeição valor R$ 396,00 mês
Assistência Médica e Odontológica Amil
Seguro de Vida

## Requisitos

**Obrigatórios:**
- experiência com desenvolvimento React+Redux para frontend
- conhecimentos em API Restfull

**Desejáveis:**
- microserviços em PHP Lumen
 
## Contratação

Contratação CLT

## Nossa empresa

Nosso foco é a Transformação de Negócios Digitais de nossos Clientes. Com o advento da 4ª Revolução Industrial, as empresas enfrentam o desafio da Transformação Digital de seus negócios. A missão hoje é acompanhar a jornada do Cliente, tomando ações em tempo real, otimizando as estruturas existentes e promovendo seus produtos e serviços em múltiplos canais, aproveitando assim o mundo conectado. Utilizamos plataformas tecnológicas de ponta para desenvolver soluções de negócios eficazes que contribuam para a Atenção e Retenção do Cliente, Aumento das Receitas, Redução dos Custos e a Excelência Operacional. Nós fornecemos visão, conhecimento e capacidade para projetar, implementar e operar uma plataforma aberta 3.0, integrar os sistemas Legados às novas camadas de aplicações móveis e à Internet das Coisas (IoT) na velocidade do seu negócio e fornecemos tecnologia de ponta focada em sistemas de cliente e Business Analytics. Bem-vindo ao futuro da Tecnologia. 
 
## Como se candidatar

Por favor envie um email para selecao@grupogbi.com com seu CV anexado - enviar no assunto: Vaga React

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/CLT

**Comment by Finacio** [comment]
Enviado!

**Comment by danielGalvao** [comment]
A vaga continua aberta?
