### ISSUE TITLE
[Remoto] App de Mobilidade Urbana

### ISSUE THREAD

**Issue by diegobraga15** [react-brasil/vagas#471]
Precisamos de um dev que saiba React Native para o app e Laravel para o backend.
Utilizamos Expo para as versões e versionamento no git, a máquina de testes está na AWS, então conhecimento prévio é um diferencial. Ferramentas de gestão utilizamos Trello

Procuramos alguem para também fazer parte do nosso time com possivel % de participação

Oferecemos uma pequena ajuda de custo inicial para que este MVP esteja no ar o mais rápido possível.

Contato 21 973110611 Diego

**Comment by matheuslipk** [comment]
Ola Diego, eu tenho interesse

**Comment by helenapaixao** [comment]
Olá tenho interesse, caso queira ver meus trabalhos segue o link do meu git
https://github.com/helenapaixao

Att,

Em qua, 30 de out de 2019 15:44, MATHEUS ARAUJO DE ALCANTARA <
notifications@github.com> escreveu:
