### ISSUE TITLE
[SP - Metrô Faria Lima] React.js Developer | SmartMEI

### ISSUE THREAD

**Issue by jpventura** [react-brasil/vagas#48]
# Our company

![SmartMEI](https://www.konkero.com.br/revistawp/wp-content/uploads/2018/01/smartmei-e1517427668436.png)

[SmartMEI](https://www.smartmei.com.br/) are inspired by a dream: accounting must be so easy, intuitive and cheap that micro-entrepreneurs don't even realize it.

Our intuitive, inclusive and innovative accounting solutions are the first step towards to end bureaucracy. We are proud of our amazing and challenging working environment.

Excited about building a striking fintech to empower millions of Brazilian microentrepreneurs? Join the team!

The SmartMEI office in São Paulo is now hiring for the position of **Front-end Developer**!

You'll reshape the core experience of entrepreneurs who are using the Android App on a daily basis.

## Job description

Refactor and later maintenance of the admin console and [homepage](https://www.smartmei.com.br) that power [SmartMEI app](https://play.google.com/store/apps/details?id=br.com.smartmei) using HTML5 and JavaScript/Java language.

## Place

[Metrô Faria Lima, São Paulo - BR](https://goo.gl/maps/XT6gwrJc8ZG2)

## Benefits

- Work remotely or at the office
- Near subway station
- Bike parking place
- Relaxed place with snacks
- Happy-hour with board games
- Periodic tech presentations
- Opportunity to hands-on backend, frontend, chatbot as well

## Requirements

**Required knowledge**

- 2+ years of front-end experience
- Standard MVC, MVP, MVVM, Clean Architecture and derivatives
- React.js and Redux
- Promise, Async/Await, or RxJS
- Jasmine, Mocha, or Karma unit test

**Desirable knowledge**

- 4+ years of front-end experience
- Firebase Realtime Database and Firebase Analytics
- Advanced React components patterns
- Server-side rendering with Next.js
- Firebase Queue, Amazon SQS, Automatic Kue, Apache Kafka, Google Pub/Sub, or Google Tasks

**Expert knowledge**

  - Creation of RESTful APIs
  - Express.js, hapi.js, Koa.js, or Sails.js
  - Amazon EC2, Amazon S3, Amazon Lambda
  - Heroku
  - React Native development
  - Native Android
  - Native iOS

## Hiring

PJ

## How to Apply

Please send an email to [dejavite@smartmei.com.br](mailto:dejavite@smartmei.com.br) with your attached resume (subject: **Front-end Developer**).

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by jpventura** [comment]
@danielGalvao 👍
