### ISSUE TITLE
[São Paulo/SP] React Native Developer na [PLATFORM BUILDERS] 

### ISSUE THREAD

**Issue by Ana300** [react-brasil/vagas#491]
Estamos procurando um desenvolvedor React para se juntar a nós na mudança que move o mundo, para que a criatividade e o crescimento possam inspirar cada vez mais pessoas a fazer mais daquilo que amam, construindo um roadmap de impacto e valor.

Aqui é o lugar onde suas ideias são bem vindas, frutos da construção do pensamento coletivo, prontas para ganharem vida.

Saca só os requisitos que pensamos:
#SejaBuilder

**Tecnologias que vão gerar valor nos projetos:**
React (Redux/Mobx)
Fluência em JavaScript (ES6)
APIs REST
Trabalhar com diferentes dimensões de dispositivo (tablet, celular, etc)
Conhecimento geral do ambiente móvel
Versionamento de código com Git
Conhecimento em arquitetura de software
Metodologias ágeis

**O que te torna mito ou uma maga por aqui:**
Conhecimento em CI/CD (App Center, Fastlane)
Conhecimento em Firebase (Analytics, Crashlytics, configurações)
Experiência em linguagens nativas e construção de bridges

**INFORMAÇÕES ADICIONAIS**

- Oportunidades reais de empreender e impactar
- Fazer parte de uma comunidade de empreendedores de ponta, o Movimento
- Inovação e criação liberados
- Participar de um processo único de geração de valor
- Contribuir na criação de métodos disruptivos
- Colocar suas ideias no mercado, na prática! :)
- Possibilidade de atuação societária
- Prestador de Serviços (PJ)
- Horário flexível
- Férias remuneradas

**APAIXONADOS POR DESENVOLVER CULTURA, PESSOAS E NEGÓCIOS**
Por aqui você não será tratado como um funcionário. Nosso movimento é para pessoas disruptivas e empreendedoras, que querem diariamente desafiar seu próprio status quo, fazendo de sua liberdade e autonomia o oxigênio para a inovação e construção de resultados com alto impacto. Gere valor e tenha a oportunidade de construir o seu próprio legado.
Quer saber mais? #SóBora #GoBuilders #SejaBuilder

**Labels**
Possibilidade de trabalho remoto
PJ
Flexível

**Como se Candidatar**
https://sejabuilder.gupy.io/jobs/109320

**Comment by tiagocharo** [comment]
Olá @Ana300
Qual é o email para contato?

**Comment by Ana300** [comment]
ana.alvares@platformbuilders.io

**Comment by tiagocharo** [comment]
@Ana300 teste enviado!

**Comment by tiagocharo** [comment]
@Ana300  finalizei o teste e enviei na plataforma da gupy

**Comment by Ana300** [comment]
A vaga ainda está disponível, favor permanecer com a Issue ativa.

Att,

[image: Platformbuilders] <https://platformbuilders.io>   * Ana Paula
Alvares *
*Tech Recruiter *|* M:* 21 98285 3140
*Hangout:* ana.alvares@platformbuilders.io
LinkedIn <https://www.linkedin.com/company/platform-builders/> | Facebook
<http://facebook.com/platformbuilders.io> | Instagram
<https://www.instagram.com/platformbuilders.io/> | Youtube
<https://www.youtube.com/channel/UCxetN8SXKy2CEf3dX09a4mA>
*www.platformbuilders.io <http://platformbuilders.io/> *
