### ISSUE TITLE
[Uberlândia-MG|Remoto] Front-End Developer no Arena.im

### ISSUE THREAD

**Issue by rodrigoreis22** [react-brasil/vagas#493]
## Descrição da vaga

Empresa americana fundada por brasileiros contrata front-end developer Júnior ou Pleno, veja mais detalhes da empresa abaixo.

## Local

Uberlândia-MG. Trabalho remoto também poderá ser considerado dependendo do candidato.

## Requisitos

**Obrigatórios:**
- Javascript utilizando algum framework ou biblioteca como React e Redux e seu ecossistema;
- HTML/CSS, responsive design
- Github/Gitflow
- Inglês intermediário/avançado, conseguir ler e escrever bem (toda nossa comunicação escrita é em Inglês).

## Contratação

PJ

## Nossa empresa

O [Arena](https://arena.im) é uma plataforma para sites de notícias e esportes cobrirem eventos em tempo real utilizando conteúdo de redes sociais e inteligência artificial.

A empresa foi fundada nos Estados Unidos em 2016 por dois desenvolvedores de Uberlândia, e hoje conta com milhões de usuários em 86 países, com investimento do Vale do Silício.

Saiba mais sobre nossa história [aqui](https://www.startse.com/noticia/mercado/47387/conheca-arena-maior-plataforma-em-tempo-real-para-eventos).

No Arena você:

- Terá a oportunidade de aprender muito com um time de alto nível;
- Integrará uma equipe internacional e poderá acompanhar de perto como funciona uma startup do Vale do Silício;
- Fará parte de um projeto impactante que afeta a vida de milhões de pessoas ao redor do mundo;
- Terá autonomia para tomar decisões sem precisar investir tempo e energia em reuniões longas e desnecessárias;
- Trabalhará em um ambiente informal que não se prende à hierarquia tradicional, com um time super dinâmico e colaborativo que trabalha e também se diverte junto.

## Como se candidatar

Se interessou? [Preencha o formulário para iniciar o processo](https://forms.gle/FFsk1VrqjD5nQVPf8).

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k

**Comment by Vini-Dev** [comment]
Rodrigo, tudo bem? Qual o tempo médio de resposta da empresa? Agradeço desde já!

**Comment by zeyuri** [comment]
ola, a vaga ja foi preenchida?

**Comment by rodrigoreis22** [comment]
Vaga preenchida. Obrigado!
