### ISSUE TITLE
[Remoto] Desenvolvedor Fullstack (MERN Stack) 

### ISSUE THREAD

**Issue by philxavier** [react-brasil/vagas#495]
## Descrição da vaga

Posição remota para desenvolvedor Fullstack (MERN stack).

## Local

Remoto 

## Benefícios

-Opções de ações
-Grande equipe na bela Califórnia

#### Diferenciais
+ Trabalho remoto
+ Salario Inicial: US$ 1.300
+ Aumento de salário com base no desempenho após 90 dias
+ opções de ações
+ oportunidade de crescer com a empresa
+ trabalhe conosco na Califórnia

## Requisitos

• 4+ anos de experiência profissional
• Experiência Fullstack, construindo aplicativos escaláveis de ponta a ponta
• Excelentes habilidades em JavaScript e forte proficiência em React
• Familiaridade com MERN stack (MongoDB, Express.JS, React.JS e Node.JS)
• Experiência com React, Redux, ES6
• Experiência na criação de APIs de back-end usando NodeJs e ExpressJs
• Experiência com bancos de dados NoSQL, como MongoDB, mangusto, estrutura de agregação e Redis
• Experiência com Web sockets e frameworks relacionadas (por exemplo, Socket.IO)
• Experiência usando APIs RESTful e mecanismos básicos de autenticação
• Criacao e Manutencao de microsserviços
• Devera mostrar trabalhos anteriores via páginas da web ao vivo e Github / Gitlab
• Compreensão básica de inglês

## Contratação

A combinar

## Nossa empresa

Uma inovadora startup construindo uma moderna plataforma para produtores de podcast!

## Como se candidatar

Por favor envie um email para mike4main@gmail.com com seu CV anexado - enviar no assunto: Vaga fullstack developer

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- 💰 3k-5k
- 💰 5k-10k

**Comment by julioxavierr** [comment]
Por favor, ajuste o título da vaga de acordo com o padrão. Obrigado por contribuir.

**Comment by philxavier** [comment]
Ola @julioxavierr. Espero que esteja tudo ok agora

**Comment by italomlp** [comment]
Olá  @philxavier, sou pleno, e tenho 3 anos de experiência profissional. Posso me candidatar?

**Comment by philxavier** [comment]
Sim, claro. Tendeu currículo/ LinkedIn?

**Comment by italomlp** [comment]
@philxavier enviei currículo e LinkedIn para o e-mail da vaga. Aguardo feedback. Poderia falar um pouco mais sobre a empresa?
