### ISSUE TITLE
[Wiesbaden/Germany] React Native Developer at ClipMyHorse.TV

### ISSUE THREAD

**Issue by osantana** [react-brasil/vagas#497]
## Description

We are looking for a mobile developer with React Native experience to architect and develop our client application for multiple platforms. Our customers are in a solid move to migrate from our current web platform to mobile, and our existing iOS/Android native applications are not offering an excellent experience to them. For that reason, we are building a team of mobile developers to create the next generation of our client applications.

The main idea is to use React Native to develop a single code base that would run on iOS and Android devices and, in the future, with our support and sponsorship, enable this app to run on all other platforms which we want to be present:

1. Mobile devices (iPhone/iPad and Android Phones & Tablets)
2. FireTV / Chromecast / AppleTV
3. Smart TVs
4. Set-top boxes
5. Game Consoles
6. etc.

There are also plans to replace our current Web site with this Client using ReactJS. But that would depend on some restructuring of our current system and the maturation of some tools.

This position is for work in Germany (or remotely for countries with similar timezone), and the contract is for an indefinite period (no date to end). The team communicates in English (some documents still need to be translated from German).

## Responsibilities

- Architect and Develop React Native application for multiple platforms;
- Produce high-quality code using the best software engineering practices (like automated testing);
- Be responsible for the quality and support of our client applications.

## Local

Locally in Wiesbaden (Germany), or remote work for developers that lives between -0200 to +0200 time zones.

## Perks

- Unlimited vacation period
- Package for a move to Germany (help to get Visa approval, three months of rent, travel ticket, etc.).
- English / German classes
- Dogs at the office :)

### Mandatory

- Long experience with React Native or Native Mobile development for iOS and Android;
- Good experience architecting applications for multiple platforms;
- Good English spoken language skills

### Desirable

- Contributions with opensource projects;
- Previous experience with video applications;

## Contract

The contract is for full employment for an indefinite period (similar to CLT in Brazil).

## Our company

[ClipMyHorse.TV](https://clipmyhorse.tv) is a broadcasting company that provides content related to equestrian sports (jumping, dressage, etc.), and it is becoming the biggest company in this segment. We currently have ~45,000 paid subscribers, but we Livestream some of our events for over 1.5 million viewers per year. Our company is responsible for everything from content production to the software where our customers access this content.

We are a small company that is funded by its customer subscriptions and the investment of some partners who are passionate about equestrian sports, and we treat everyone as part of a big family. We work at a calm and smooth pace without crazy deadlines or time pressure. We will try hard to keep teams very lean.

## How to apply

Send an email to o.santana@clipmyhorse.tv with your CV or Linkedin profile (and Github if you have one).

## Labels

- 🏢 Flexible
- 🏢 Local
- 🏢 Remote (restrictions with timezone)
- 👴 Sênior
- ⚖️ Full Employment Contract
- 💰 5k-10k (€)

**Comment by LucasCastelo** [comment]
@osantana , eu tenho planos para imigrar para Alemanha sabe se existe algum sponsor para React.Js Junior ? Consegue dar alguma orientação neste sentido ?

**Comment by osantana** [comment]
Oi @LucasCastelo eu não sei de nenhum mas eu imagino que existam sim. Dá uma olhada nas páginas com vagas nas startups de Berlin.
