### ISSUE TITLE
[Porto Alegre] React developer (react, redux e testes unitários) na Grifo

### ISSUE THREAD

**Issue by renatho** [react-brasil/vagas#50]
## Descrição da vaga

A vaga é pelo período de 1 ano (com possibilidade de renovação) em um fee com um cliente. Buscamos parceiros PJ.
O objetivo é trabalhar em um produto bem bacana com a stack em cima de React e Redux, criando novas features e evoluindo o produto.

## Local

Remoto ou Escritório, Porto Alegre - Bairro Três Figueiras

## Benefícios

- Apenas pagamento PJ, porém com valor bom a negociar

#### Diferenciais

- Flexibilidade de horário

## Requisitos

**Obrigatórios:**
- Responsabilidade
- Compromisso
- Bom domínio de React, Redux
- Trabalhar com testes unitários (se já trabalhar com Jest, melhor)

**Desejáveis:**
- Inglês

**Diferenciais:**
- Node.js
- Devops
- Residir em Porto Alegre

## Contratação

PJ a combinar

## Nossa empresa

A Grifo é uma empresa que presta serviços de tecnologia, com foco principal em desenvolvimento front-end.

## Como se candidatar

Por favor envie um email para vagas@gri.fo com sua apresentação - enviar no assunto: [React Brasil] Vaga React + Redux.
Enviar no e-mail materiais para avaliarmos seus skills. Caso não tenha nenhum material publicado, não tem problema. Verificamos juntos uma forma de avaliar seus skills.

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Sênior
- regime/Freela
- regime/Outros
- regime/PJ

**Comment by danielGalvao** [comment]
A vaga continua aberta?
