### ISSUE TITLE
[Remote] UI Engineer for open source blockchain platform! [Indefinite contract]

### ISSUE THREAD

**Issue by SecretWizard** [react-brasil/vagas#501]
## Descrição da vaga

Our client, a decentralized blockchain governance platform, is looking to bring to their global remote team a talented React / React Native UI Engineers with a love for beautiful, well-crafted interfaces. 

## Local

Remote, anywhere in the world

## Benefícios

- 25-day flex holidays
- You get your own hardware
- Parental leave
- Auxílio creche

#### Diferenciais

- Fully remote!
- Payment in Dai, a stablecoin that is easily convertible to USD
- Indefinite contract
- It's fully open source!

## Requisitos

**Obrigatórios:**
- Expert understanding of modern JavaScript (ES6+) and Web APIs, CSS, React (Web and Native), resource optimization, development tools.
- Proven ability to ship quality, well-crafted code within tight deadlines.
- Being passionate about open source and decentralization.
- Being an autonomous individual with a proactive attitude and a love for time self-management. We work focus-driven, not hours-driven.

**Desejáveis:**
- Previous experience contributing or managing open source projects.
- Experience working with Web 3.0 technologies.
- Previous experience working remotely.
- Very good written communication skills.
- Attention to UX/UI design.

**Diferenciais:**
- Love for open source
- Portfolio with attractive UI designs

## Contratação

Indefinite-term contractor

## Como se candidatar

Send an email with your updated resume to jobs@southtalent.co with the subject "React Brasil Application!"

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ Contractor
- 💰 65k-90k USD per year

**Comment by emirdeliz** [comment]
Fluent English required?
