### ISSUE TITLE
[Curitiba - PR] Desenvolvedor React (N240WJ) na CINQ TECHNOLOGIES

### ISSUE THREAD

**Issue by cezarsg** [react-brasil/vagas#513]
## Descrição da vaga
Ei, Dev. React: temos uma super oportunidade para você entrar no #TimeCINQ e trabalhar em um projeto nacional cheio de desafios!

Sobre o Projeto:
Venha construir o futuro do comércio exterior!
Vamos construir do zero um sistema de rastreamento em tempo real de cargas, essa plataforma vai transformar a forma como o comércio exterior opera no Brasil.

O que você irá fazer por aqui:
Desenvolver o front-end da plataforma de monitoramento utilizando o React.

## Local
Curitiba - PR

## Benefícios
- Plano de Saúde
- Plano Odontológico
- Seguro de vida
- Previdência Privada
- Vale Refeição
- Vale Alimentação
- Auxílio Estudo
- GymPass

#### Diferenciais
- Videogame in company

## Requisitos
- Profissionais com experiência em React
- Será considerado um diferencial conhecimento em HTML, CSS, Javascript, Azure e Git para versionamento de código.

**Obrigatórios:**
- 3 anos de experiência com desenvolvimento Android Nativo
- 2 anos de experiência com desenvolvimento iOS Nativo

**Desejáveis:**
- conhecimentos em GraphQL

## Contratação
A Combinar 

## Como se candidatar
Por favor envie um email para c.gomes@cinq.com.br com seu CV anexado - enviar no assunto: Desenvolvedor React (N240WJ)

## Labels
- ⚖️ A-Combinar

**Comment by guilhermecostalopes** [comment]
Esta vaga é presencial ?
