### ISSUE TITLE
Startup de Ingressos - Vaib Tickets

### ISSUE THREAD

**Issue by IngrdOliveira** [react-brasil/vagas#523]
## Descrição da "vaga"

Preciso de 2 programadores FullStacks, pode ser só Back End e a gente da um jeitinho, pra poderem produzir o MVP pra captar investidor. Estou juntando contatos e explicarei os detalhes apenas aos interessados. 

## Local

Remoto

## Benefícios

- Cliff (12 meses)
- Vesting (4 anos)

#### Diferenciais

- Pode ser home office :)
- Uma empresa nova com valores novos
- Tera participação da empresa se decidir ficar

## Requisitos

**Obrigatórios:**
Perdão caso eu explique mal, pois não sou muito boa com conhecimento de programação.
Preciso de 2 FullStacks

Que entenda de;
- Compras com cartão / pagamentos / transferências
- Cadastros de dados pessoais
- Segurança online (código de barras, keys)
- Adição de contatos (agenda)
- Convites e notificações

## Contratação

PJ com contrato Cliff

## Startup Vaib Tickets

Estou em processo de aceleração com a aceleradora Amazonas Cap, com minha Startup Vaib Tickets, que é uma plataforma para compra de ingressos para grupos fornecendo descontos. 

## Aos interessados como se candidatar

Por favor envie um email para ingrdoliveira2@gmail.com  com o assunto:
"Quero entrar nessa budega - [seu nome]"

É dificil e bizarro, mas é assim que as melhores coisas acontecem! Aguardo contatos!!

**Comment by jhefflg** [comment]
Quais tecnologias são usadas?
