### ISSUE TITLE
[São Paulo] React Native Developer na Lab123

### ISSUE THREAD

**Issue by felipeds2** [react-brasil/vagas#53]
## Descrição da vaga

Estamos em busca de desenvolvedor React Native para trabalhar em um aplicativo de cashback.

O desenvolvedor ficará responsável por implementar toda UI (já pronta) e consumir as APIs.

## Local

Remoto ou Escritório, São Paulo - AV. Paulista

## Benefícios

- 30 dias de férias remuneradas

#### Diferenciais

- Faça seu horário
- monte a sua máquina como desejar

## Requisitos

**Obrigatórios:**
- Experiencia com desenvolvimento de aplicativos react native.

**Desejáveis:**
- conhecimentos em angular 2+

**Diferenciais:**
- projetos opensource

## Contratação

PJ a combinar

## Nossa empresa

A Lab nasceu com o intuito de construir soluções de qualidade e dar vida às ideias através da união das melhores práticas de mercado, agilidade e profissionais apaixonados pelo que fazem.

Desenhar e entregar soluções de qualidade que de fato atendam às necessidades das pessoas e empresas, criando, para tanto, um ambiente profissional saudável e que estimule o crescimento dos nossos colaboradores tanto como indivíduo quanto como profissional.

## Como se candidatar

Por favor envie um email para felipe.santos@lab123.com.br com seu CV anexado - enviar no assunto: [Vaga React Native]

## Labels

- alocação/Presencial
- alicação/Remoto
- experiência/Júnior
- experiência/Pleno
- regime/PJ

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by felipeds2** [comment]
Não, ja conseguimos o profissional.
