### ISSUE TITLE
[São Paulo] React Native em uma Startup (Confidencial)

### ISSUE THREAD

**Issue by lucastonon** [react-brasil/vagas#54]
## Descrição da vaga

Projeto de uma rede social em React Native para Android e iOS em uma Startup.
Começamos desenvolvendo para Android, e como ainda precisaríamos do app iOS,
decidimos apostar no React Native.

## Local

Remoto ou em um escritório em Jardins - São Paulo

## Benefícios

- Participação por esforço

## Requisitos

**Obrigatórios:**
- Portfólio de aplicativos desenvolvidos em React Native para Android e iOS
- Experiência com Android ou iOS nativo
- REST

## Contratação

Freelancer fixo mensal

## Como se candidatar

Por favor envie um email para xlucastonon@gmail.com com seu CV anexado e com seu protfólio de apps em React Native (importante) - enviar no assunto: Vaga React Native

## Labels

- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/A-Combinar
- regime/Freela
- regime/PJ

**Comment by nic** [comment]
@lucastonon Faltou a descrição na seção "Nossa empresa".
