### ISSUE TITLE
[São Paulo] Desenvolvedor React Native na Bitfy

### ISSUE THREAD

**Issue by m4rtinsp** [react-brasil/vagas#545]
## Descrição da vaga

Desenvolvimento de aplicações para Android e iOS utilizando React Native, atuará na continuidade do produto da empresa desenvolvendo novas features, e identificando e corrigindo eventuais bugs.

## Local

Presencial, São Paulo - Santo Amaro (próximo da estação de trem)

#### Diferenciais

- Trabalhar em uma startup que está revolucionando a forma como as pessoas utilizam suas criptomoedas.

## Requisitos

**Obrigatórios:**
- Proficiência em Javascript ES6;
- 2 anos de experiência com desenvolvimento React Native;
- Bons conhecimentos em gerenciadores de estado (ContextAPI, Redux, Flux, etc), armazenamento local, gerenciamento de rotas e Hooks;
- Bons conhecimentos dos padrões de design das plataformas iOS e Android.

**Desejáveis:**
- Conhecimentos básicos sobre as IDEs nativas (Xcode e Android Studio) para resoluções de questões relacionadas a build

## Contratação

- Modalidade: PJ
- Remuneração competitiva

## Nossa empresa

A Bitfy é a primeira carteira multi-uso de criptomoedas do Brasil, conheça mais em www.bitfy.app

Estamos em período de expansão e você trabalhará numa equipe multidisciplinar focada em Javascript e que ama compartilhar conhecimento;

## Como se candidatar

Por favor envie um email para vagas@bitfy.app com seu CV/Linkedin - enviar no assunto: Vaga React Native

## Labels

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by ribeiroevandro** [comment]
E-email, enviado!
