### ISSUE TITLE
[REMOTO] VAGA PARA DESENVOLVEDOR FRONT-END

### ISSUE THREAD

**Issue by carloscavalcanti** [react-brasil/vagas#55]
## Descrição da vaga

Você será responsável por implementar novas funcionalidades, propor melhorias, manter a qualidade do código e versionamento.

## Local

Remoto

## Benefícios

- 30 dias de férias remuneradas

#### Diferenciais

- Horário flexível

## Requisitos
- ReactJS
- HTML
- CSS
- Git
- Experiência consumindo APIs REST

**Diferenciais:**
- Conhecimento em UX e UI
- Conhecimento básico em back-end
- ReactNative ou Ionic

## Contratação

PJ

## Nossa empresa

A BEARIN é uma plataforma global de notificações de operações reais em tempo real para que traders sem consistência possam seguir e operar como profissionais vencedores.

## Como se candidatar

Envie email para cavalcanti@bearin.com.br com assunto "Vaga FRONT" com as seguintes informações:

- Pretensão salarial
- Resumo sobre:
	Sua experiência, projetos em que trabalhou
	Perfil no Github (caso possua)
	Perfil no LinkedIn (caso possua)

## Labels

- alocação/Flexível
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by nicholasess** [comment]
não acredito, ia mandar agora o cv @carloscavalcanti hahahaha
