### ISSUE TITLE
[São Paulo] React Developer na Confere

### ISSUE THREAD

**Issue by joaovescudero** [react-brasil/vagas#552]
## Descrição da vaga

Estamos buscando alguém que já possua experiência em React, e que esteja disposta a trabalhar no front e talvez no mobile(Flutter).

## Local

Escritório, São Paulo - Pinheiros

## Benefícios

- Remuneração Fixa
- Plano de saúde
- VR
- VT

#### Diferenciais

- No dress code
- Horário flexível
- Frutas e bolachas a vontade

## Requisitos

**Obrigatórios:**
- React
- JavaScript / ES6, incluindo DOM
- React Hooks
- Git
- Design Patterns tanto para JS quanto para React
- Redux
- Styled Components
- Scrum

**Desejáveis:**
- Unit test com JEST
- Testes E2E com Cypress
- Testes com storybook

**Diferenciais:**
- Flutteer

## Contratação

CLT

## Nossa empresa

Sobre a Confere - nós somos um "GuiaBolso" de maquininhas de cartão, integramos os diferentes dados em um único app/plataforma para que os pequenos lojistas possam ter visibilidade financeira das vendas do seu negócio :rocket: :credit_card: .

## Como se candidatar

Por favor envie um email para je@confere.com.br com seu CV anexado e Linkedin - enviar no assunto: Vaga Front-end Developer

## Labels

- 🏢 Presencial
- 👨 Pleno
- ⚖️ CLT

**Comment by LucasCastelo** [comment]
Enviado!
