### ISSUE TITLE
[Curitiba] React Developer na Polvo

### ISSUE THREAD

**Issue by aline-matos** [react-brasil/vagas#56]
## Descrição da vaga

Procuramos um desenvolvedor front-end entusiasta em react e apaixonado por novas tecnologias, com espírito de equipe e pró atividade.

## Local

Shopping Itália - Curitiba

## Requisitos

**Obrigatórios:**
- Profundo conhecimento em HTML, CSS e JS
- React/Redux
- Bom conhecimento em qualquer outra linguagem de programação;
- Saber utilizar bem Node/NPM, Composer, Git e JIRA;
- Inglês básico

**Desejáveis:**
- React Native
- PHP
- Blade (Laravel)

## Contratação

CLT

## Nossa empresa

Somos uma agência full service que mergulha no negócio do cliente para elaborar e executar estratégias personalizadas e comprometidas com resultados.

## Como se candidatar

Efetuar o teste 
https://www.figma.com/file/E9nCB9jXkJKBLH71ljdnZ80k/Desafio-Desenvolvedor-Front-End---Grupo-Polvo, enviar um e-mail com o seu CV anexado para rh@polvo.com.br e no assunto mencionar "Vaga React Developer"

## Labels

- experiência/Estágio
- experiência/Júnior
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/Estágio

**Comment by danielGalvao** [comment]
A vaga continua aberta?
