### ISSUE TITLE
[Rio de Janeiro] Front-End Developer na Caren.app

### ISSUE THREAD

**Issue by gVirtu** [react-brasil/vagas#561]
Você, desenvolvedor(a) React **pleno / sênior** tem interesse em viver intensamente o dia-a-dia em uma startup de saúde no Centro do Rio de Janeiro? Ter liberdade para protagonizar inovações e impactar clientes relevantes? Crescer exponencialmente como profissional e como pessoa?

Somos uma **healthtech** focada em inovação e novas tecnologias de software. Em 2019 fomos selecionados para os programas BNDES Garagem Criação e Artemísia Lab, e estamos hoje em processo de expansão e crescimento. Aqui na Caren não temos formalidades, dress code ou regras rígidas.

Temos projetos desafiadores em fase inicial e estamos à procura de profissionais talentosos, com autonomia, vontade de resolver problemas com excelência e disposição para aprender sempre.

Requisitos
----------

:computer: São **obrigatórios**:

*   Domínio de boas práticas em JavaScript (ES6+) e conceitos CSS
*   Conhecimento de versionamento com Git
*   Experiência prévia em projetos React
*   Boa comunicação e trabalho em equipe

:muscle: São **desejáveis**:

*   Conhecimento de Inglês
*   TDD (Jest + Enzyme)
*   Boas práticas em acessibilidade e segurança na web
*   Familiaridade com Redux e Material UI
*   Domínio de frameworks e preprocessadores CSS
*   Experiência de colaboração com designers ou equipe criativa

:1st_place_medal: São **diferenciais**:

*   Fluência em Docker, Webpack e Service Worker (para PWA)
*   Experiência com React Native
*   Conhecimentos em infraestrutura cloud AWS
*   Experiência em projetos da área de saúde

Modelo
------

Nosso modelo de contratação é PJ com remuneração proposta de R$ 7.000,00, nossa equipe é enxuta e dedicada, trabalhamos em horário flexível e nosso escritório fica a apenas 5 minutos da estação de metrô da Carioca.

Se interessou?

Agende um horário [neste link](https://calendly.com/carenapp/reuniao-front-end-react) para conversarmos.

Labels
------

- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k

**Comment by araujooleticiaa** [comment]
Olá, a vaga ainda está disponível?
