### ISSUE TITLE
[São Paulo] Front-end/React Developer no Hospital Israelita Albert Eistein

### ISSUE THREAD

**Issue by adhenrique** [react-brasil/vagas#562]
## HIAE - Innovation Lab

Nós aqui da Innovation Lab - Hospital Israelita Albert Einstein, estamos em busca de um(a) desenvolvedor(a) React (16+ hooks, redux, redux-thunk, reselect, react-router, Material UI, etc). Ufa… bastante coisinha.

Mas calma, vamos por partes. O Innovation Lab é um departamento de inovação do qual cuida da idealização de novos produtos para o Einstein. Internos ou externos, vc pode fazer parte de projetos reais e mundiais na área de Educação e Saúde.

Agora falando do seu espaço, você fará parte de um time focado no front-end da nossa aplicação, caminhando juntamente com nossos Ui’s/Ux’ers. Criando telas e componentes reutilizáveis.

Sobre você, esperamos que vc seja um(a) cara/mina legal 😎! Só isso. 

## Dá uma olhada nos requisitos:
- Pró atividade
- Parceria no momento do fogo 🔥 
- Lógica de programação (Algoritmos, soa assustador pra vc? Deve ser o básico!)
- Analista de problemas (Não pode ficar com medo de pegar código legado 😋)
- React, react e react sempre. (Pra que serve o useCallback() ?)
- Javascript avançado. (Vamos e convenhamos, spread operator é um sucesso?!)
- Antenado(a). (Tem muitas tecnologias novas surgindo. Você poderia nos indicar uma?)
- Se vc souber desenvolver um bom Container, HoC, hooks, render props 🐎  ou souber algo sobre testes unitários, já é um grande diferencial.
- Vc gosta de café? 🤔 

Bem…
Atualmente, nós temos diversos problemas - mas é claro! Qual aplicação não tem? E você pode ser o(a) **Cara/Mina** ou nos indicar o(a) **Cara/Mina** para resolvê-los haha.

## Benefícios e diferenciais:
- Nosso espaço: Estamos localizados na Vila Mariana, bem pertinho da estação do metrô.
- Disponibilizamos pra vc: Qualidade de vida com muito espaço verde, muita cultura e diversidade, e o melhor, um **Macbook** só seu 💻 
- Alocação: Presencial, imediata e infelizmente, não temos alocação remota.
- Contratação: PJ - 1 ano com possibilidade de renovação.
- Experiência: Junior, Pleno, Senior… Não importa. Só vem!
- Horário: Flexível, 8h

Se vc se interessou, deixe um comentário ou envie um e-mail para adenilton.ribeiro@inovacaoeinstein.com.br | camila.pina@inovacaoeinstein.com.br com o assunto **Vaga Front-end/React**

## Labels
- Alocado
- PJ
- Júnior
- Pleno
- Sênior

**Comment by nicholasess** [comment]
@adhenrique a vaga está focada somente em homem ou mulher? Por que o *Cara*, só vão se identificar quem for homem

**Comment by adhenrique** [comment]
> @adhenrique a vaga está focada somente em homem ou mulher? Por que o _Cara_, só vão se identificar quem for homem

Cara, muito obrigado por pontuar. Vou editar a descrição agora.

**Comment by LucasCastelo** [comment]
Enviado, da uma olhada com carinho la. <3 haha

**Comment by ruanlinos** [comment]
To muito interessado <3
