### ISSUE TITLE
[Remoto] Dev Full Stack Node, React e React Nativena WA Project

### ISSUE THREAD

**Issue by Andrea-wa** [react-brasil/vagas#575]
Estamos com algumas vagas em aberto para integrar ao nosso super time.
Descrição da empresa:
Desenvolvemos aplicativos e softwares para empresas. Nossa foco é na entrega.
Atividades e Responsabilidades:
Desenvolvimento de projetos sob demanda para nossos clientes, utilizando tecnologias web e mobile. Implementação de novas features e manutenção.
Compartilhar conhecimento e estar disposto a ajudar o time.
Requisitos:
Experiência com as tecnologias: NodeJs, React, React Native, Typescript, Docker, HTML, CSS, Rest, NPM/Yarn, banco de dados SQL e GIT.
Obrigatórios:
Experiência com Node
Experiência com React ou/e React Native
Metodologias utilizadas:
Scrum e KanBan.
Modelo de Contratação:
-PJ a combinar
Diferenciais:
MongoDB, RxJs e Testes.
Capacidade analítica para resolução de problemas.
Comprometimento e ótima comunicação.
Duas semanas de férias remuneradas
Para se candidatar, envie seu currículo para vagas@waproject.com.br .

**Comment by MarcwL22** [comment]
Enviei meu CV umas 3 semanas atrás e não obtive nenhum feedback

**Comment by maxleon52** [comment]
Aceita Dev Jr?

**Comment by Andrea-wa** [comment]
Maxwell, bom dia. Tudo bem?
No momento a vaga é para desenvolvedor pleno, mas em breve abriremos
novas vagas.

Atenciosamente,




Em sex., 31 de jan. de 2020 às 20:56, Maxwell Alves <
notifications@github.com> escreveu:

**Comment by EduardoAugusto2015** [comment]
Boa tarde @Andrea-wa 
Vaga ainda disponivel?
