### ISSUE TITLE
[São Paulo] Desenvolvedor Full-Stack Java e React

### ISSUE THREAD

**Issue by esterpaganini** [react-brasil/vagas#577]
**Enviar LinkedIn ou currículo para vagas@rebelbank.com.br** 

**Descrição do cargo:**
Reunir requisitos e transformá-los em soluções funcionais;
Trabalhar em conjunto com outros desenvolvedores para criar e manter soluções robustas;
Padronização para criação de soluções multiplataforma;
Otimização de desempenho de aplicativos;
Manter-se atualizado sobre tendências e novas tecnologias;
**Principais responsabilidades:**
Escrever códigos compatíveis com padrões, incluindo teste/depuração em várias plataformas
Trabalhar com designers para traduzir conceitos visuais em websites funcionais
Projeta e implementa componentes do sistema
Colabora estreitamente com colegas de equipe para criar soluções inovadoras e orientadas para o desempenho
Traga-nos ideias de novas tecnologias que podem ser usadas para melhorar nossos sistemas
**Conhecimento técnico:** 
Conhecimento de padrões de design de software
Ensino superior em ciência da computação, engenharia da computação ou experiência de trabalho equivalente
Foco em Back-end, Java com Docker, Spring boot e Cloud AWS.
**Benefícios:**
Vale Refeição – R$ 31,00 ao dia
Vale Transporte
Seguro Saúde Sul América – plano especial 100 – Para colaborador e dependente
Snacks, toda semana disponíveis na copa (incluindo cerveja, salgadinho, chocolate, suco entre outros).
Ambiente descontraído
Oportunidade de grande crescimento profissional
Confraternizações que a Rebel oferece (almoços em datas comemorativas; Happy Hour de integração, comemoração de acordo ccom a meta batida, campeonato de poker e de vídeo game, etc...)
Salario à combinar.

**Comment by guilhermecostalopes** [comment]
Esta vaga é presencial ?
