### ISSUE TITLE
[Remoto] Dev de Front React.js na i10digital

### ISSUE THREAD

**Issue by carol-monteiro** [react-brasil/vagas#578]
## Descrição da vaga

Procuramos um(a) desenvolvedor(a) de Front-end com experiência em React.js, que goste de desafios e de resolver problemas. O candidato vai compor o time de desenvolvimento da nossa plataforma de WebBanking para empresas.

## Local

Remoto

## Benefícios e Diferenciais

- Remuneração competitiva
- Final de semana de 3 dias
- Autonomia na escolha de horário de trabalho
- Auxílio atividade física

## Requisitos

**Obrigatórios:**
- Já ter trabalhado na prática com o React

**Desejáveis:**
- Redux

**Diferenciais:**
- Flutter
- PHP e/ou Node

## Contratação

PJ

## Nossa empresa

A i10 é um banco digital focado em empresas que traz soluções financeiras direto para a plataforma do cliente. Queremos pessoas que tenham a ambição de crescer junto com a gente, em um ambiente de aprendizagem e dedicação.

## Como se candidatar

Preencha o seguinte formulário com suas informações básicas, de contato e profissionais.
http://app.pipefy.com/public/form/mGr6EdGp

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 3k-5k

**Comment by Mickaelsjb** [comment]
Tenho interesse na vaga contato 016 991580802
mickaelsjb@gmail.com

**Comment by Binotto** [comment]
Boa noite Recrutador.

Tenho interesse na vaga, o meu whatsapp é 042 999095469.
Tem alguns projetos pessoais que desenvolvi em React, que estão públicos no Github, acredito que vocês vão gostar.

Desde já agradeço a atenção.
Att, 
Matheus Binotto

**Comment by gutosoares** [comment]
### Formulário preenchido! 0/

Aguardo retorno de vcs 😄

**Comment by paulohpf** [comment]
Preenchido!

Espero que eu possa demonstrar as minhas skills :)

**Comment by victorbiasibetti** [comment]
esta vaga ainda está aberta?

**Comment by robertov8** [comment]
Enviado! =D

**Comment by secodigo** [comment]
Olá a vaga ainda está disponível?
