### ISSUE TITLE
[Natal/RN] React Native na Dibs.digital [Remoto]

### ISSUE THREAD

**Issue by gilvaju** [react-brasil/vagas#58]
## Descrição da vaga

Construção de uma carteira de pagamentos utilizando paypal e blockchain da waves...

## Local

Remoto

#### Diferenciais

- Caso o case de desenvolvimento conosco seja positivo, um vínculo profissional é altamente considerável

## Requisitos

**Obrigatórios:**
- Aplicações desenvolvidas com react native publicadas ou disponíveis para análise

**Desejáveis:**
- conhecimentos em blockchain
- conhecimentos com a api do paypal

**Diferenciais:**
- conhecimento em processos de ico
- conhecimentos no blockchain da waves

## Contratação

- Oferecemos participação dos tokens da ICO
ou
- Freelancer

## Nossa empresa

http://dibs.digital (soluções inteligentes)

## Como se candidatar

Por favor entrar em contato via twitter: @gilvaju

## Labels

- alocação/Remoto
- experiência/Júnior
- experiência/Pleno
- regime/A-Combinar

**Comment by mateuzor** [comment]
aberto ?

**Comment by gilvaju** [comment]
Vaga preenchida. Obrigado pela atenção.
