### ISSUE TITLE
[Ribeirão Preto/SP] Front-End React Senior na iClinic

### ISSUE THREAD

**Issue by fabianaiclinic** [react-brasil/vagas#581]
## Descrição da vaga

A iClinic está à procura de um Desenvolvedor Front-End Sênior (remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: obcecado por qualidade e desenvolvimento ágil. Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

O que esperamos de você:

- Vontade de repassar conhecimento, ensinar, criar ou já ter criado artigos de programação;
- Já ter implementado testes com Selenium ou Cypress;
- Não ter receio em alterar um código que você não escreveu;
- Empatia por seus colaboradores;
- Capacidade de comunicar ideias de forma clara;
- Desejamos proatividade para adquirir novos conhecimentos rapidamente.

## Local

Trabalho remoto 

## Benefícios

- Vale refeição/alimentação;
- Plano de saúde;
- Plano de Carreira;
- Plano de participação nos resultados (PPR);

#### Diferenciais

- Bônus por indicação de outros profissionais para trabalhar na iClinic;
- Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- Sem dress code,  Trabalhe do jeito que achar confortável;
- Café da manhã, frutas e o sagrado cafezinho ao longo do dia;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Incentivo financeiro para desenvolvimento técnico;

## Requisitos

**Desejáveis:**
- Experiência comprovada em React + Redux + Saga como front-end;
- Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;
- Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
- Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, back-end, QA tester;
- Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
- Conhecimentos em paradigmas funcionais e suas práticas;
- Conhecimentos em metologias de testes unitários, integração e E2E.

## Contratação

CLT com benefícios

## Nossa empresa

A iClinic é uma das startups de tecnologia em saúde que mais cresce no Brasil.

Nossa missão é Descomplicar a saúde no Brasil.

E como fazemos isso hoje? 

Oferecendo o melhor software de gestão para clínicas e consultórios médicos.

E como atingir este objetivo?

Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento.

## Como se candidatar

Por favor faça sua candidatura no link: https://iclinic.gupy.io/jobs/153837

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ CLT

**Comment by nicolascbarbosa** [comment]
@gabrielferreiraa essa é a empresa que você trabalha né? Me apliquei, vou me esforçar para conseguir ser aprovado :smile:

**Comment by gabrielferreiraa** [comment]
Exato, pode aplicar! Aqui é incrível 😄

**Comment by LucasMallmann** [comment]
Olá @gabrielferreiraa , a vaga ainda está aberta? :smile:

**Comment by mauriciord** [comment]
@LucasMallmann https://iclinic.gupy.io/jobs/153837?jobBoardSource=gupy_public_page
SIM

**Comment by gabrielferreiraa** [comment]
@LucasMallmann abrimos mais vagas, caso ainda tenha interesse: https://vagas.iclinic.com.br/
