### ISSUE TITLE
[Ribeirão Preto - SP] Front / Full Stack na Gedanken

### ISSUE THREAD

**Issue by hugopenna** [react-brasil/vagas#586]
## Descrição da vaga

Estamos expandindo nosso time de desenvolvimento e estamos procurando pessoas que curtem desafios e que queiram trabalhar comoFront ou Full Stack. Trabalhamos com React, Redux no front e Python com Flask no back. 
Temos diversos desafios para certificar a segurança de informação para as maiores empresas do Brasil.

## Local

Escritório, Ribeirão Preto - SP

#### Diferenciais

- Ambiente dinâmico
- Você terá voz e liberdade para propor coisas
- Tecnologia

## Requisitos

**Obrigatórios:**
- React
- Redux
- API rest
- Git 

**Desejáveis:**
- Hooks
- Web socket
- SQL
- React Native

**Diferenciais:**
- Projetos opensource
- Python
- Teste unitário e de ingeração

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa de Big Data, Inteligência Artificial e estatística avançada que transforma dados e fluxos complexos em inteligência de negócio.​ Identificamos de forma automática riscos e oportunidades, transformando dados em informação e conteúdo claros para a tomada de decisão

## Como se candidatar

Por favor envie um email para tais@gedanken.com.br com seu CV anexado - enviar no assunto: Vaga React / Full Stack

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k
- 💰 10k-15k

**Comment by guilhermecostalopes** [comment]
Esta vaga é presencial ?

**Comment by hugopenna** [comment]
@guilhermecostalopes essa vaga já foi fechada, valeu :)
