### ISSUE TITLE
[Barueri - SP] Mobile Developer no [Grupo Flamboyant]

### ISSUE THREAD

**Issue by livialdias** [react-brasil/vagas#59]
## Descrição da vaga

Grupo focado no desenvolvimento de soluções em empregabilidade. Inicialmente o profissional atuará em projeto de novo aplicativo mobile e depois nos demais produtos digitais do grupo.

## Local

Escritório, Barueri - Alphaville Empresarial

## Requisitos

**Obrigatórios:**
- Conhecimento em linguagens de programação: React Native OU Ionic OU Xamarin .NET
- jQuery

**Desejáveis:**
- Java para Android (desenvolvimento nativo)
- Objective C, Ionic, HTML5 (responsivo)
- MS SQL
- Angular, TypeScript

## Contratação

PJ

## Nossa empresa

O Grupo Flamboyant trabalha em soluções para interligar profissionais e oportunidades.

## Como se candidatar

Por favor envie um email para livia.dias@supervagas.com.br com seu CV anexado - enviar no assunto: Vaga Mobile

## Labels

- alocação/Presencial
- experiência/Pleno
- regime/PJ

**Comment by nicholasess** [comment]
@livialdias poderia colocar no padrão que definimos no template da issue, por gentileza? ;)

**Comment by livialdias** [comment]
Bom dia Nicholas.

Poderia indicar, por gentileza, qual o padrão que devo seguir?

Obrigada.


Em qui, 10 de mai de 2018 23:45, Nicholas Eduardo <notifications@github.com>
escreveu:

**Comment by nic** [comment]
Oi @livialdias, bom dia, tudo bem?

Você poderá visualizar o padrão aqui:
https://github.com/react-brasil/vagas/blob/master/.github/issue_template.md

**Comment by livialdias** [comment]
Obrigada!

Já vou corrigir.

*Lívia Dias*
*Operações*
*Tel:* (11) 5084-1994 / *Ramal:* 8713
*Site:* supervagas.com.br <http://www.supervagas.com.br>
*E-mail:* livia.dias@supervagas.com.br

<http://supervagas.com.br/>



2018-05-11 10:55 GMT-03:00 nic <notifications@github.com>:
