### ISSUE TITLE
[Remoto] Pleno full-stack developer na Gnar

### ISSUE THREAD

**Issue by yuriploc** [react-brasil/vagas#599]
## Descrição da vaga

(Remote)
We're looking for a Jr to Mid-level Frontend Engineer to be part of our team developing features and delivering UX improvements by proving simple yet performant interfaces and ensuring long term stability and scalability.

💪 What's my mission?
As a member of such a small team at GNAR (we’re just 5 people company-wide!), you’ll work closely with our product team in our biggest project.

We have great (and big) new features to be implemented during the next 2 years and need someone with good frontend experience to help us deliver them with quality. At the same time, we’ve been building this project for the past 2 years, and we have lots of opportunities to improve our React SPA.

🤗 Who will I be working with?
You will be working closely with our engineers @osmanpontes, @yuriploc and our Head of Product.

📖 What do I need?
- JavaScript experience - you have front-end development experience using ES6. Ideally, you have also worked with React (without hooks for now) and Redux.
- CSS experience - you had worked with pure CSS before, and know how difficult it is. Will be an advocate of best practices and (who knows), of styled components.
- Excellent engineer - you understand and advocate for testing, analytics, observability, error tolerance.
- Product mindset - you can challenge product features, propose simpler implementation to fasten the iterations, and propose excellent technical decisions to improve user experience.

Why join GNAR?
- Work with talented & passionate people with diverse experiences and backgrounds (Physics, Psychology, Computer Science..).
- Feel your impact: GNAR is a small company, everything we do matters and your impact is critical.

What do I get?
☕️ 20h to 30h / week (initially)
💰 US$21 to US$28 / h (initially)
🏝 3 Weeks PTO

Interested? Send:
- CV and/or Portfolio
- Cover letter
📬 yuri@gnar.io with title: Frontend Engineer

## Local

Remoto

## Benefícios

- 3 semanas de férias pagas

#### Diferenciais

- Sem overwork
- Sem crunch time

## Requisitos

**Obrigatórios:**
- 3 anos de experiência com JavaScript ES6
- 2 anos de experiência com CSS

**Desejáveis:**
- Conhecimentos em React e Redux

**Diferenciais:**
- Projetos opensource ou Portfolio
- Experiência em migrar projetos React para `styled components`

## Contratação

PJ a combinar

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by allanreges** [comment]
Olá, o envio do currículo deve ser feito em inglês?

**Comment by italomlp** [comment]
Qual o nível de inglês necessário?

**Comment by yuriploc** [comment]
@allanreges CV pode ser pt-br, sem problemas;

@italomlp Você precisa compreender um americano nativo falando e precisa ser compreendido por ele ao falar;

**Comment by mauricio-jmmendes** [comment]
Tenho 5 anos de experiência com Java, e nesse meio tempo lidando com Javascript em algumas situações pontuais, até trabalhei exclusivamente com Javascript durante 6 meses, mais recentemente venho estudando a stack Javascript (Node.js/React) mais a fundo através de cursos, principalmente da Rocketseat. Enfim vou tentar a sorte.😅

**Comment by yuriploc** [comment]
Pessoal, vou fechar a issue porque já recebemos bastante CVs e precisamos seguir com o processo.

Sucesso a todos!
