### ISSUE TITLE
[São Paulo] Desenvolvedor Front-end na EcoStage

### ISSUE THREAD

**Issue by phillipp-oliveira** [react-brasil/vagas#6]
Buscamos desenvolvedores apaixonados por tecnologia e trabalhar com o que há de melhor, pessoas que queiram crescer e aprender com a gente.
Temos um time de alto nível, nosso stack é moderno e está sempre em constante evolução. Valorizamos o desempenho e comprometimento da equipe.

---
### Local

- Próximo à Av. Paulista (Ao lado da estação Bridadeiro) - São Paulo/SP

---
### Diferenciais

- Horários flexíveis
- Ambiente descontraído
- Possibilidade de home office alguns dias da semana

---
### Requisitos

**Obrigatórios**
- Experiência com desenvolvimento Javascript- Webpack
- React / Redux
- TDD
- Ser comprometido com o projeto e a qualidade do código.
- Espírito empreendedor e pró-atividade
- Experiência com times auto-gerenciáveis e metodologias ágeis(XP, SCRUM, Kanban, Lean).

**Desejáveis**

- Ruby ou Elixir
- Functional & Reactive Programming

**Diferenciais**

- Participar da comunidade open source
---

### Contratação

- PJ ou CLT
---
### Nossa empresa

A EcoStage é líder no desenvolvimento de plataformas sócio-ambientais. Nossos projetos têm grande impacto em políticas e estratégias sobre o tema.

Somos uma empresa com ambiente descontraído e horários flexíveis. Você trabalhará em uma equipe pequena, multi-disciplinar e auto-gerenciável.

---
### Como se candidatar

Clique aqui: https://ecostage.breezy.hr/p/e599e2233364-desenvolvedor-front-end

**Comment by nicholasess** [comment]
@phillipp-oliveira a vaga ainda está em aberto?

**Comment by viniciusoliveira01** [comment]
Mandei email e marcaram entrevista. Pelo visto está sim!

**Comment by danielGalvao** [comment]
@phillipp-oliveira A vaga ainda está aberta? Senão fecharemos a issue.

**Comment by phillipp-oliveira** [comment]
Bom dia @danielGalvao !
A vaga continua aberta :)

**Comment by danielGalvao** [comment]
Vamos fechar as Vagas com mais de 6 meses abertas, para poderem criarem uma nova issue, com informações mais atualizadas.
