### ISSUE TITLE
[Barueri] Frontend Developer na DOMVS

### ISSUE THREAD

**Issue by thaisvilladal** [react-brasil/vagas#601]
## Descrição da vaga
Para atuar no desenvolvimento frontend de programas de fidelidade, campanhas de incentivo e recompensa para o mercado de Loyalty.

## Local
Presencial, Barueri, SP

## Benefícios
Férias remuneradas

## Requisitos
Experiência em UX, Design, React, redux, HTML5, CSS3, Git, Scrum.

**Desejáveis:**
Desejável conhecimentos em React Native.

## Contratação
PJ por prazo indeterminado - a combinar

## Nossa empresa
A DOMVS possui experiência em gestão de empresas, onde efetivamente participam de decisões de negócios embasadas pela utilização estratégica da tecnologia da informação.
Estamos presentes no Brasil e também em Portugal.

## Como se candidatar
Por favor envie um e-mail para consultoria_villadal@domvs.com.br com seu CV anexado - enviar no assunto: Des.Frontend

## Labels
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-11k

**Comment by IuryBrasileiroMaiaSilva** [comment]
Tem possibilidade de remoto?

**Comment by thaisvilladal** [comment]
Infelizmente não, somente presencial.
tenho vagas front também para a região do Paraíso, próximo a Paulista, também presencial, com direito a férias remuneradas e saídas as sextas-feiras as 14h00.


________________________________
De: Iury Brasileiro Maia Silva <notifications@github.com>
Enviado: quinta-feira, 20 de fevereiro de 2020 07:30
Para: react-brasil/vagas <vagas@noreply.github.com>
Cc: Thais Villadal <villadalrh@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [react-brasil/vagas] [Barueri] Frontend Developer na DOMVS (#601)


Tem possibilidade de remoto?
