### ISSUE TITLE
Petronect contrata:  Analista de Desenvolvimento de Sistemas / Desenvolvedor SCP - Site RJ

### ISSUE THREAD

**Issue by rosangelapmancuso** [react-brasil/vagas#602]
Petronect contrata: 
 Analista de Desenvolvimento de Sistemas / Desenvolvedor SCP - Site RJ

 Atribuições:
1.	Realiza todas as atividades inerentes a um desenvolvedor dentro do ambiente Cloud da SAP (SCP)
2.	Definir e criar soluções técnicas de utilizando a tecnologia SCP
3.	Compreender a arquitetura e adaptar-se a ela
4.	Identificar e construir os testes de desenvolvedor que cubram o comportamento desejado dos componentes técnicos
5.	Comunicar o design de uma forma que os outros membros da equipe compreendam
6.	Integrar o sistema com os novos componentes de software produzidos ou alterados.
7.	Colaborar com as equipes e nossos líderes de produtos nas entregas de novas funcionalidades suportando nossa ampliação de negócios.

Requisitos:
Experiênciaem Sap Cloud Plataform enovas soluções SAP, tais como SAP HANA, SAP Fiori, UI5 ;testes unitários ; testes integrados; integrações e interfaces (RFC’s eWeb Services).
Conhecimentodosmódulos  SAP MM ou SRM;desenvolvimento ABAPe WEB DYNPRO;Gestão de projetos de software; Programação front-end : HTML, CSS, JavaScript, Angular; Desenvolvimentoback-end :Java Spring Boot,  NodeJs,Python,  Serverless; SAPS/4HANA; Usabilidade– User eXperience; ProgramaçãoMobile : Android eIOS / HTML Web APP

Se você gosta de novas tecnologias e se identificou com a vaga, vem trabalhar conosco!
Os interessados devem se candidatar através do endereço abaixo:
:Vagas.com.br/v2033249

**Comment by pauloedurezende** [comment]
Olá @rosangelapmancuso, tudo bem?

Este repositório é dedicado a empresas que desejam contratar desenvolvedores, seja ele front-end ou full-stack que trabalhem principalmente com o framework React ou ferramentas do seu ecossistema (assim como também descrito no momento de abrir esta issue). Infelizmente pela descrição da vaga, ela apenas cita o Angular...

Estarei fechando devido a mesma não preencher os requisitos anteriormente citados e a inconsistência no link apresentado por você, estarei a disposição para sanar qualquer dúvida que possa aparecer 😄
