### ISSUE TITLE
[Remoto] Desenvolvedor Front-end na Dialog

### ISSUE THREAD

**Issue by rod-stuchi** [react-brasil/vagas#613]
## Descrição da vaga

Procuramos desenvolvedor(a) de front-end com experiência em React (e ecossistema) e UX, que goste de performance e de entregar uma ótima experiência ao usuário. O(a) candidato(a) irá trabalhar ao lado de um time senior de desenvolvedores do Dialog.

## Nossa empresa

O Dialog (www.dialog.ci) é uma startup de rede social corporativa gamificada para grandes empresas.
Há 4 anos no mercado, oferecemos uma plataforma SaaS que melhora a comunicação entre grandes empresas e seus colaboradores.
Somos a startup brasileira líder no segmento, reconhecida como Top 100 no ranking 100 Open Startups, e atendendo clientes como Carrefour, PepsiCo, BRF, SBT, Klabin e Via Varejo.

## Local

Presencial ou Remoto

## Benefícios

- A combinar

## Requisitos

**Obrigatórios:**

- React: 3 anos de experiência
- ECMAScript 2019
- PWA (service workers, cache)
- styled-components
- Apollo Client
- Git
- Figma

**Desejáveis:**
- conhecimentos em Node

## Modelo de Contratação

PJ (emissão NF)

## Como se candidatar

Enviar pull-request de um pequeno teste no repositório:

    https://github.com/criticalmassbr/cm-pwa-test

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após o envio do pull-request.

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ 5k-8k
- 👴 Sênior
- ⚖️ 8k-13k
- ⚖️ PJ

**Comment by rod-stuchi** [comment]
@mauriciord poderia adicionar os ranges de salário?

**Comment by diegowendel** [comment]
@rod-stuchi Até quando vocês estarão analisando os pull-requests?

**Comment by rod-stuchi** [comment]
@diegowendel indeterminado, imagino que 3 semanas.
depende das PRs que receberemos

**Comment by Luiz-junior** [comment]
É aceitável usar flexbox ao invés do css grid?

**Comment by rod-stuchi** [comment]
@Luiz-junior pode usar flexbox, mas precisa ter css-grid.

**Comment by maxarouca** [comment]
Ainda aceitam testes?

**Comment by rod-stuchi** [comment]
@maxarouca sim, pode enviar.
as 2 vagas ainda estão aberta.

Quem já submeteu as PRs, serão todas analisada ainda, como estamos em fase final pra entregar um cliente, não tivemos tempo para avaliar, me desculpem.

**Comment by LucasMallmann** [comment]
@rod-stuchi tranquilo! Obrigado pelo feedback!

**Comment by rod-stuchi** [comment]
Opa, ainda está aberta.
pretendemos finalizar o processo até o final de jun/2020.

Obrigado 👊
