### ISSUE TITLE
[Florianópolis] React Native Developer na Compasso UOL

### ISSUE THREAD

**Issue by cleiton-goncalves** [react-brasil/vagas#615]
## Descrição da vaga

A Compasso está procurando pessoas talentosas, inovadoras, comprometidas, inteligentes e que queiram ajudar a fazer a transformação digital acontecer em nossos clientes.

Queremos conhecer você, que está em busca de carreira desafiadora e oportunidades de crescimento profissional.  

### Responsabilidades e Atribuições

- Desenvolvimento de software com foco em REACT NATIVE
- Levantamento de requisitos técnicos e estimativas para desenvolvimento de projetos rodando metodologia ágil;
- Documentação de serviços, componentes e elaboração de diagramas;
- Participar da definição das soluções e ser propositivo e apresentar as suas ideias ou críticas;
- Utilizar boas práticas de desenvolvimento;
- Ter experiência de trabalho em modelo de time ágil;
- Fazer a interface entre o cliente e equipes internas envolvidas.

## Local

Santa Mônica - Florianópolis - SC

## Benefícios

Além dos benefícios contratuais da Compasso, nossos colaboradores contam com trilhas de capacitação para aprendizado de novas tecnologias e métodos, além de subsídios de até 100% para a realização de certificações.

## Requisitos

**Obrigatórios:**

- Conhecimento em Javascript, ES6+;
- Conhecimento dos componentes ReactNative;
- Gerenciamento de estado com Redux;
- CSS/Styles;
- React Hooks;
- Integração com API's Rest;
- UnitTests;
- Git;

**Diferenciais:**

- Scrum;
- Conhecimento das novidades do React Native 0.60 ou posterior;
- Familiaridade em plataformas nativas Androis/iOS;
- Experiência com administração e deploy das lojas Play Store e App Store;
- Experiência em criação de pipeline (CI/CD) para React Native;
- Conhecimento em KnockoutJS;
- Conhecimento em OCC (Oracle Commerce Cloud).

## Contratação

CLT

## Nossa empresa

Nossa missão é transformar o mundo, construindo soluções que permitem que empresas de diversos tamanhos e segmentos ingressem na era digital.

Fazemos isso, contando com um time talentoso, aplicando tecnologias em estado-da-arte e modelo ágil.

Queremos conhecer você, que busca desafios, conhecimento e crescimento profissional!

## Como se candidatar

https://compasso.gupy.io/jobs/181795

## Labels

- 🏢 Presencial
- 👦 Pleno
- ⚖️ CLT

**Comment by IuryBrasileiroMaiaSilva** [comment]
Possibilidade de remoto?

**Comment by cleiton-goncalves** [comment]
Bom dia @IuryBrasileiroMaiaSilva, infelizmente não temos a opção de trabalho remoto, apenas alocado em sede mas em projetos remotos. Da uma olhada no https://compasso.gupy.io/ que estamos com vagas abertas em todas nossas sedes, e pode ser que tenha alguma perto de você.

**Comment by kaluabentes** [comment]
Possuem um email do RH pra enviar o curriculo direto? Estou tendo dificuldades com plataforma, nao consigo submeter o formulario mesmo satisfazendo as requisições

**Comment by cleiton-goncalves** [comment]
Boa tarde @kaluabentes, tudo bem?
Por gentileza, encaminhe seu currículo para cv@compasso.com.br informando a dificuldade no cadastro da plataforma.
