### ISSUE TITLE
[Remoto ou São Paulo] React Dev na Hivelocity [em HOLD]

### ISSUE THREAD

**Issue by davinirjr** [react-brasil/vagas#617]
## Descrição

A [Hivelocity](https://www.hivelocity.net/) está procurando por dev React apaixonado por entregar produtos excepcionais em um time de desenvolvimento ágil composto por devs americanos e brasileiros. 

Neste papel, você trabalhará em nossa Edge Compute Platform, onde clientes podem efetuar deploy de servidores bare metal instantaneamente em mais de 30 cidades diferentes ao redor do globo. Nossas soluções de infraestrutura e produtos afetam milhares de companhias em âmbito mundial.

Você trabalhará com múltiplas apps SPA React que alimentam nosso portal de clientes, store, e ferramentas internas. 

Um candidato bem-sucedido mostrará paixão ao tomar para si as responsabilidades de seus entregáveis, produzindo código performático e bem testado. 

Esta é uma oportunidade de fazer parte de uma empresa que cresce rapidamente, com grandes benefícios, desafios gratificantes e horário flexível (reuniões/eventos virtuais comumente em [EST](https://www.timeanddate.com/time/zones/est)).

## Localização

Remoto ou (em breve) localmente em nosso escritório em São Paulo.

## Requisitos e Qualificações

- Paixão por entrega de experiência excepcional de usuário.
- Fluente em JavaScript e React.
- Fluente em tecnologias web, tais como HTML5 & CSS3.
- Minimo de 3 anos de experiência em JavaScript.
- Excelência no Inglês escrito. Nível intermediário em Inglês falado. Fluência não é requerida. Existem pessoas nativas em Língua Portuguesa no time.
- Experiência com Python é um diferencial.
- Conhecimento em styled components é um diferencial.
- Experiência demonstrada com design de SPA e software de controle de versão (Git, Mercurial).

### Outros diferenciais

- Docker, SaltStack, OpenStack, Systems Administration em Linux, MySQL, Redis, Redux, WebPack
- Formação superior em Ciência/Engenharia da Computação é preferida, mas não requerida.
- Full-time (40 hrs / semana) 

## Contratação

PJ a combinar.

## Como aplicar

Para aplicar, envie um email com seu CV (serve LinkedIn também, mas ambos devem estar em inglês) e link para Github/Gitlab (se possível) para [Zach Kazansk em zkazanski@hivelocity.net](mailto:zkazanski@hivelocity.net).

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Outros
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-15k
- 💰 15k+

**Comment by flakesrc** [comment]
3 anos de exp pra Jr.?

**Comment by swlucas** [comment]
> 3 anos de exp pra Jr.?

Acho que tempo de experiência, não caracteriza um dev.

**Comment by davinirjr** [comment]
> 3 anos de exp pra Jr.?

Olá, @flakesrc. Lá consta "3 anos de experiência **em Javascript**".

Exemplo: tenho +5 anos de experiência em Java, +5 anos de experiência com Python, +2 anos de experiência em Oracle Fusion Middleware. Sabe como eu iria concorrer a essa vaga? Como Júnior, pois estou começando agora com React.

E concordo com @swlucas no tangente ao tempo não implicar em maturidade profissional/pessoal.

O que estamos procurando é (**preferencialmente**) alguém que se vire sozinho com o ecosistema React, ou seja, um pleno. Mas não descartamos conhecer devs com menos ou mais experiência.

Essa caracterização de Jr/Pleno/Senior é utilizada pra saber basicamente duas coisas:

- Se o dev vai precisar de assistência contínua (Jr), pontual (Pleno) ou praticamente nenhuma e/ou vai ajudar com outros devs (Senior).

- Entender o valor que o dev consegue entregar pra encaixá-lo numa faixa adequada para pagamento (para receber um pagamento justo pelo valor entregue/gerado, nem underpaid e nem overpaid).

Mas se não ficou claro, cola lá no Telegram que podemos conversar mais sobre: @DavinirJr.


Abraço!

**Comment by thejoaov** [comment]
Cv enviado.

**Comment by ThalesAlonso** [comment]
@davinirjr melhor resposta que eu vi até agora sobre jr/pleno/senior. Parabéns mano.

**Comment by flakesrc** [comment]
@davinirjr  "Exemplo: tenho +5 anos de experiência em Java, +5 anos de experiência com Python, +2 anos de experiência em Oracle Fusion Middleware. Sabe como eu iria concorrer a essa vaga? Como Júnior, pois estou começando agora com React." Mas a vaga tá pedindo exp na tecnologia que a pessoa tem conhecimento, essa parte do comentário não faz o menor sentido aplicado a esse contexto. Tá pedindo 3 anos de exp em js pra vaga Jr. js, não 5 anos + de Python.

Quanto a "Se o dev vai precisar de assistência contínua (Jr), pontual (Pleno) ou praticamente nenhuma e/ou vai ajudar com outros devs (Senior).", creio que alguém com 3 anos + de exp e "Excelência no Inglês escrito. Nível intermediário em Inglês falado." não vá precisar de "assistência contínua", a não ser que o cara seja muito ruim no que faz. 

Enfim, não tô discutindo sobre a vaga em si, só o texto/requerimento mesmo que pra mim não fez sentido algum nesses quesitos.

**Comment by davinirjr** [comment]
@flakesrc 

Se você tem interesse e ainda tiver dúvidas sobre a oportunidade, acho melhor você mandar elas direto para o Zach, dado minha ineficácia em esclarecê-las.

Mas se você acredita que essa oportunidade não serve pra você, seja por qualquer motivo que for, fica em paz e ignora ela de boas.

**Comment by davinirjr** [comment]
Fala, pessoal, muitas pessoas entratam em contato sobre dúvidas acerca da ausência de respostas.

Conversei há pouco com o Zach pra alinhar com todos vocês.

Ele não será capaz de responder a todos em tempo hábil como usualmente faz - e sim, também está relacionado a sobrecarga pelas ações para conter a pandemia.

Então ele pediu pra tomarmos como base uma régua de 3 dias: **se ele não responder em 3 dias, por favor, considere que não houve match candidato-vaga**.

Desde já agradecemos a atenção. 

Eu conversei com alguns de vocês pelo Telegram, e sei das expectativas. Não desanimem, continuem procurando e participando das seleções.

E cuidem uns dos outros.

Novamente, se precisarem de esclarecimentos, estou à disposição aqui ou no Telegram.

Abraço!

**Comment by davinirjr** [comment]
Quero agradecer a todos que participaram.

No momento o Zach pediu pra dar uma segurada até processar todo mundo que já está em processo de seleção, então a vaga fica em hold, ok?

Volto em breve para encerrar ou prosseguir.

Desde já, deixo aqui meus parabéns a comunidade React BR. Só tenho recebido elogios das iterações até agora! Vocês são foda! :clap: :clap: :clap:

**Comment by davinirjr** [comment]
Ah, esqueci de deixar o MEU agradecimento. 

Foi muito legal iteragir com vocês! Conheci pessoas excepcionais, espero que tenha sido tão gratificante pra elas quanto foi pra mim!

Prometo que assim que passar essa confusão toda vou me dedicar ao ecossistema React e participar efetivamente da comunidade.

Muito, mas muito obrigado mesmo, comunidade React BR! Sintam-se devidamente abraçados.

Stay safe!
