### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack (Node, React, React Native) na MUDEii

### ISSUE THREAD

**Issue by feliperodalves** [react-brasil/vagas#619]
## Descrição da vaga

- Desenvolvimento de funcionalidades no Back e/ou Front-End / Mobile;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;

## Local

Escritório, São Paulo - Moema

## Requisitos

**Obrigatórios:**
- Javascript é essencial!
- Conhecer Nodejs (com Adonisjs), React e/ou React Native;
- Styled Components ou outra abordagem de CSS no Js;
- Controle de Estado com Redux (Sagas);
- Controle de Versões (Git preferencialmente);
- Paixão por aprender e programar;

**Desejáveis:**
- Padrões de códigos e Linters (eslint / prettier)
- Testes automatizados;

**Diferenciais:**
- Inglês
- Python
- Infraestrutura Azure;
- Build & Deployment

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa de tecnologia resolvendo antigos problemas do mercado imobiliário de uma forma totalmente inovadora. Somos uma plataforma de serviços financeiros para o mercado imobiliário que reúne e facilita a vida de inquilinos, administradores e proprietários, desburocratizando o processo de locação de um imóvel residencial urbano.

A MUDEii nasce com a missão de facilitar a vida das pessoas resolvendo as dores de quem precisa alugar um imóvel. Agora basta o inquilino se cadastrar no App, ver o valor de locação aprovado e sair para buscar o imóvel que deseja (pode escolher qualquer imóvel anunciado em qualquer plataforma existente no mercado). Depois que escolher o imóvel, é só avisar ao Administrador ou ao Proprietário que irá pagar com a MUDEii e começar a se preocupar com a mudança.

## Como se candidatar

Por favor envie um email para rh@foii.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor FullStack
E/ou comente aqui na issue

## Labels

- 🏢 Presencial
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by thejoaov** [comment]
Tem alguma possibilidade de ser remoto?

Em sex, 6 de mar de 2020 21:43, Felipe Alves <notifications@github.com>
escreveu:

**Comment by feliperodalves** [comment]
@thejoaov infelizmente esse primeiro momento não!
como é o início da startup, precisamos das pessoas por perto! Tanto para aprender, quanto para ensinar!

**Comment by ricardojunior02** [comment]
Boa noite Felipe, encaminhei o email com o cv em anexo

**Comment by ribeiroevandro** [comment]
Email enviado!

**Comment by cnfreitax** [comment]
Email enviado!

**Comment by Henriquepb22** [comment]
Vaga continua aberta?
