### ISSUE TITLE
[São Paulo] React Native Developer na Everymind

### ISSUE THREAD

**Issue by iredhd** [react-brasil/vagas#620]
## Local
Chácara Sto. Antônio, São Paulo

## Benefícios
- Tickets refeição e alimentação
- Convênios de saúde e odontológico
- Auxílio creche
- Seguro de vida
- Auxílio educação
- Convênio com farmácias

#### Diferenciais
- Convênio com BioRitmo e Smartfit
- PLR
- Trabalho remoto para alguns dias da semana
- Política horizontal

## Requisitos
**Obrigatórios:**
- JavaScript 
- SQL
- GIT

**Diferenciais:**
- Já ter trabalhado com Expo

## Contratação
CLT - 3,5k a 7k

## Como se candidatar
Realizar o [teste](https://github.com/iredhd/evmd-front-end-test) seguindo os passos descritos.

## Labels
- 🏢 Flexível
- 👦 Júnior
- 👨 Pleno
- ⚖️ CLT
- 💰 3k-5k
- 💰 5k-10k

**Comment by thejoaov** [comment]
Alguma possibilidade de remoto? Tenho uma boa experiência com expo e react
native

Em ter, 10 de mar de 2020 18:18, Ighor Rios Redhd <notifications@github.com>
escreveu:

**Comment by iredhd** [comment]
@thejoaov infelizmente não :(

**Comment by luancma** [comment]
Olá. qual o prazo mínimo para a entrega do teste?

**Comment by iredhd** [comment]
@luancma enquanto o post tiver ativo aqui ainda está no prazo, pode fazer se quiser. Abraços.
