### ISSUE TITLE
[Voluntariado] Desenvolvedor React e/ou Node na WeChan.ge

### ISSUE THREAD

**Issue by gabrielmmontenegro** [react-brasil/vagas#627]
## Descrição da vaga

Projeto que irá revolucionar a filantropia e acelerar as transformações sociais por meio de uma plataforma social projetada especialmente para elevar a efetividade de organizações e de seus apoiadores, sejam eles voluntários ou doadores. 

## Local

Remoto

## Benefícios

- Contribuir para uma sociedade mais justa através da tecnologia 

## Requisitos
- Conhecimento intermediário/avançado em Javascript
- Para reactjs: conhecimento intermediário/avançado em Redux
Para nodejs: conhecimento intermediário/avançado em Express, RESTful API, Sequelize, Jest

**Desejáveis:**
- Para react: conhecimentos em PWA e Onsen-ui
- Para nodejs: conhecimentos em AWS SDK, Elasticsearch

## Contratação

Termo de adesão de voluntariado. 

## Como se candidatar

Basta se cadastrar no nosso website https://wechan.ge/pt#voluntariado que entraremos em contato. 

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ Outros

**Comment by EnosGomes** [comment]
Não teria vaga de JR. para voluntário ?

**Comment by gabrielmmontenegro** [comment]
> Não teria vaga de JR. para voluntário ?

Olá @EnosGomes. Especificamos Junior, Pleno e Senior no cadastro da oportunidade. Contudo é importante que o/a interessado/a tenha conhecimento intermediário nas tecnologias base, pois como voluntário/a irá doar ao projeto apenas algumas horas livres por semana.

**Comment by renatobenks** [comment]
o projeto é/será open-source @gabrielmmontenegro?

**Comment by gabrielmmontenegro** [comment]
@renatobenks, não será

**Comment by mauriciord** [comment]
@gabrielmmontenegro Existe algum quadro onde mostra todos os "voluntários"?

**Comment by paulogdm** [comment]
@gabrielmmontenegro Algum motivo para a plataforma não ser OSS? Vocês terão alguma estratégia de monetização?

Esse tipo de oportunidade me interessa muito, mas sinto que faltam detalhes pra realmente tomar uma decisão de pelo menos ir atrás de + infos sobre o projeto...

**Comment by gabrielmmontenegro** [comment]
@mauriciord atualmente contamos com 13 voluntários em diversas frentes de atuação como dev, devops, segurança, UX/UI comunicação, relações públicas, design gráfico. Dentre esses voluntários temos profissionais de instituições públicas, privadas e do terceiro setor dentro e fora do Brasil, incluindo AWS, F5 Networks, Serpro.

**Comment by gabrielmmontenegro** [comment]
Olá @paulogdm 

Entendo perfeitamente, assim como você eu preciso ter segurança necessária pra colocar minha energia em qualquer projeto. Então vamos a suas dúvidas:
 
1) O WeChan.ge está sendo desenvolvido para ser uma plataforma social gratuita, assim com Facebook ou Twitter, mas dedicada a organizações da sociedade civil e em especial as pessoas que as apoiam, sejam voluntários ou doadores. É um projeto ousado, de alta complexidade, envolvendo não apenas a codificação e integração de diversos serviços na cloud, mas o planejamento e manutenção de uma infraestrutura escalável para permitir que as organizações foquem em suas missões, ou seja, direcionem tempo para suas atividades fim, e não em atividades meio como tecnologia. O modelo open source não consegue gerar o impacto que buscamos, . Portanto essa é uma questão de altruísmo eficaz. 
2) Sem dúvidas. A sustentabilidade da plataforma será essencial para que possamos continuar operando e evoluindo, portanto necessária.
3) Somos uma startup com seu MVP em desenvolvimento. Nossa missão é conectar pessoas e organizações da sociedade civil para conduzir mudanças reais no mundo. 4) Como uma startup em desenvolvimento, o projeto conta com a minha dedicação integral e a dedicação do tempo livre de outros 13 voluntários de várias regiões do mundo, e crescendo. 

Se tiver interesse em conhecer melhor o projeto, basta me enviar um e-mail que agendamos uma call pra tirar outras possíveis dúvidas: gabrielm@wechan.ge. Será um prazer falar contigo.

**Comment by paulogdm** [comment]
1. Existem projetos opensource altamente escaláveis e inclusive monetizáveis sem nenhum prejuízo ao projeto em si.
- https://nextjs.org/
- https://nuxtjs.org/
- https://tailwindcss.com/

  Não há razão para buscar voluntário no projeto fechado ao meu ver

2. Qual o nível de monetização aqui? Ainda não está claro... É "self-sustained" ou "for-profit"? Isso **seve estar bem claro no seu projeto**.

3. Novamente não ficou claro. Na minha opinião a falta de transparência é para confundir todas as partes. Se isso é intencional ou acidental fica à cirtério do leitor.

**Comment by duduribeiro** [comment]
Como você pensa em distribuir os lucros dessa monetização com os voluntários ?

**Comment by jay-jlm** [comment]
@nic This looks fishy as heck 😕.  I suggest removal unless you have referrals of who they are.

**Comment by nic** [comment]
Desculpa @gabrielmmontenegro,
As pessoas realmente precisam fechar as contas no fim do mês. Seus argumentos sobre não deixar o projeto aberto para a comunidade não faz sentido. "Altruísmo eficaz"? "Open source não consegue gerar o impacto que buscamos"?

Faz sentido ter vagas só pra contribuir voluntariamente, mas não faz sentido você esconder os nomes dos voluntários e muito menos de não abrir o código que os voluntários estão gerando.

Você está indo completamente na contramão do que você mesmo diz: "para um bem maior, para a sociedade".

Muito cuidado com essas ideias, pois a internet não perdoa e você poderá, eventualmente, cair aqui: https://www.facebook.com/vagasVTNC (o que seria uma exposição extremamente negativa para você e sua empresa)

--- 

Paulogdm fará uma call com o Gabriel às 20h para esclarecer, e quando voltar destravará a issue com um posicionamento final.

**Comment by paulogdm** [comment]
Olá pessoal!

Tive uma call com o @gabrielmmontenegro e acredito que o que existe aqui é uma falha de comunicação. Na minha visão está faltando:

1. Uma apresentação clara do projeto com visão, missão e valores. Qual o nosso propósito? Essencial para entregar "_ownership_" aos voluntários.
2. Roadmap com realidades e expectativas: Onde estamos e para onde vamos? Vai ser uma ONG ou empresa? Qual é a do projeto de verdade? Isso é importante para existir "_accountability_" desde cedo.
3. Breve descrição de quem está envolvido no projeto. Exemplo: https://vuejs.org/v2/guide/team.html

Sugeri ao Gabriel que respondesse a todos os comentários com transparência e descrevendo tudo o que for possível. Ao meu ver o modelo que ele tem está diferente do descrito aqui e a galera está assumindo o pior dos casos. Você só quebra esse tipo de visão sendo bem claro em tudo. No mais, marquem uma call e entendam o projeto. Se compartilharem da visão é só contribuir...

**Comment by nic** [comment]
Conclusão e percepções:
- Apesar das boas intenções, essa vaga da WeChan.ge trás muita subjetividade à respeito das contrapartidas esperada da empresa pelos voluntários
- Infelizmente @gabrielmmontenegro não possui conhecimento suficiente sobre OSS para estruturar a empresa de forma que ela possa seguir aberta.
- Hoje a empresa realmente não teria condições de pagar alguém para codar

Recomendação e conselhos:
- Procurar entender melhor como os cases de sucesso OSS conseguiram se manter em pé (Ex: Wikipédia, Wordpress, Ubuntu, Git, Magento e tantos outros)
- Procurar alguém para ajudar na comunicação (não subestimar a capacidade das pessoas aqui, elas realmente tem muito para ensinar, não só sobre código, mas também sobre empreendedorismo)
- Dar visibilidade para as pessoas que já são voluntários hoje (coloca-los em um mural), afinal: essas pessoas que são hoje seu time
- E principalmente: Formalize a empresa, criar um CNPJ, page os impostos, levante capital e dê participações em ações (stocks) para os voluntários.

Por hora, esta vaga estará fechada. Iremos aguardar o novo momento da WeChan.ge para poder recebe-los aqui. Obrigado a todos que participaram da thread.
