### ISSUE TITLE
[São Paulo] - Desenvolver Front Pleno ou Sênior  - AMCOM

### ISSUE THREAD

**Issue by marcosnastri** [react-brasil/vagas#628]
Descrição da vaga
Irá desenvolver  novos sistemas que irão dar suporte a operação de nosso cliente, utilizando Scrum como framework, Phyton como BackEnd em ambiente opensource.
Local
Vila Clementino – SP . 5 minutos do metro
Benefícios
    • Plano de saúde 
    • Seguro de vida 
    • VR 
Requisitos
    • Necessário:
        ◦ Domínio de tecnologias essenciais ao front-end (HTML, CSS e JS);
        ◦ Sólidos conhecimentos em JS (ES6);
        ◦ Conhecimento em ReactJS;
        ◦ Desenvolvimento de Single Page Applications;
        ◦ Experiência em desenvolvimento responsivo com e sem Bootstrap;
        ◦ Versionamento de código com Git;
    • Desejável:
        ◦ Python, Django Rest Framework e Flask;
        ◦ Experiência com pré-processadores como Less, Sass ou Stylus;
        ◦ banco de dados relacional - PostgreSQL;
        ◦ Metodologias ágeis;
        ◦ Experiência com Docker.
      
Contratação
CLT 
Nossa empresa
Estamos há mais de 20 anos no mercado da tecnologia da informação e fornecemos soluções inovadoras para empresas de diferentes segmentos. Inovamos a partir do uso de tecnologias emergentes e de metodologias e práticas ágeis, cocriando produtos que atendam às demandas específicas de cada negócio, levando eficiência operacional da produção ao atendimento pós-venda.
Maiores informações : https://www.amcom.com.br/sobre/
Como se candidatar
Por favor envie um email para marcos.nastri@amcom.com.br com seu CV anexado - enviar no assunto: Vaga React Native
Labels
    •  Flexível 
    •  Presencial 
    •  Pleno 
    •  Sênior 
    •  CLT

**Comment by nic** [comment]
@marcosnastri Poderia colocar no padrão do template, por favor: https://github.com/react-brasil/vagas/blob/master/.github/issue_template.md ?

**Comment by marcosnastri** [comment]
Feito !


Atenciosamente,

Marcos Nastri
11 9 9589-2176



Em seg., 16 de mar. de 2020 às 20:38, nic <notifications@github.com>
escreveu:

**Comment by marcosnastri** [comment]
,.,,
