### ISSUE TITLE
[São Paulo] Frontend developer React Júnior no Stoodi

### ISSUE THREAD

**Issue by thiagopadula** [react-brasil/vagas#632]
## Descrição da vaga

Estamos procurando pessoas desenvolvedoras front-end Júnior que consigam se virar com HTML, CSS e Javascript (experiência com React é bem-vinda!) e que queiram muito aprender e contribuir para o nosso projeto de transformar o futuro dos brasileiros por meio da educação.

## Local

Escritório, São Paulo - próximo ao metrô Butantã (presencial flexível)
(devido ao cenário atual, no momento estamos todos de home office)

## Benefícios

- Vale refeição e alimentação
- Vale transporte
- Plano de saúde
- Plano odontológico
- Auxílio educação
- Programa de remuneração variável

#### Diferenciais

- Ambiente ágil, descontraído e inovador em uma startup em crescimento.
- Horário flexível
- Dress code livre

## Requisitos

**Obrigatórios:**

- Saber se virar com HTML, CSS e JS
- Ter muita vontade de aprender e compartilhar conhecimento

**Desejáveis:**

- Experiência com React
- Ter alguma experiência na área

## Contratação

CLT

## Nossa empresa

O Stoodi transforma o futuro dos brasileiros por meio da educação. Somos uma empresa jovem com uma grande ambição de democratizar o acesso ao ensino superior para milhões de brasileiros. Fazemos parte do maior grupo de educação do mundo (sim, do mundo!), combinando a agilidade, autonomia e alto crescimento de uma startup com a força e estabilidade de um gigante.

A nossa plataforma online de estudos serve mais de 100 mil exercícios e 50 mil vídeos por dia a alunos de todo Brasil! Além disso temos diversas outras soluções como simulados, planos de estudo personalizados, os apps mais bem rankeados de orientação vocacional, gabarito Enem, entre tantos outros.

Mas não são apenas os números que nos movem. Mudamos diariamente a vida de milhares de pessoas e acreditamos que ter um propósito de impacto é o que nos diferencia.

## Como se candidatar

Envie seu currículo pelo link [nessa página](https://jobs.kenoby.com/stoodi/job/pessoa-desenvolvedora-front-end-junior/5dc1e8a0272dbd20d9fea690)

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👦 Júnior
- ⚖️ CLT

**Comment by maxarouca** [comment]
Apenas presencial ou aceitam remoto?

**Comment by thiagopadula** [comment]
> Apenas presencial ou aceitam remoto?

Fora o momento que estamos passando (em que todos estamos remotos), a ideia é que a pessoa precise ir ao escritório ao menos alguns dias da semana.

**Comment by allancarlos123** [comment]
Olá, boa tarde!
A vaga ainda está disponível @thiagopadula?

**Comment by maxarouca** [comment]
> > Apenas presencial ou aceitam remoto?
> 
> Fora o momento que estamos passando (em que todos estamos remotos), a ideia é que a pessoa precise ir ao escritório ao menos alguns dias da semana.

Entendi. Obrigado @thiagopadula . Se fosse possível ser full-remoto... Sou de Salvador e preencho todos os requisitos.
