### ISSUE TITLE
[REMOTO] Desenvolvedor(a) React

### ISSUE THREAD

**Issue by andreas-monday** [react-brasil/vagas#634]
## Descrição da vaga

Desenvolvedor React. (Júnior / Pleno / Sênior )

## Local

Remoto

## Contratação

PJ a combinar

## Nossa empresa

Nosso foco é criar soluções para ecommerce.

## Como se candidatar

Candidate-se pelo link https://empreender.hrpartner.io/jobs

## Labels

- 🏢 Remoto
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by nicholasess** [comment]
@andreas-monday não existe desenvolvedor Backend React, pois o React é uma biblioteca para Front End

**Comment by andreas-monday** [comment]
Muito obrigado, fiz a correção do anuncio.
Até mais!

**Comment by lffranca** [comment]
@nicholasess Como é para soluções em ecommerce eu imaginei que fosse com o NextJS ou similar..

**Comment by arielff3** [comment]
Não achei a vaga.

**Comment by mauriciord** [comment]
@andreas-monday Por favor, corrigir o link da vaga e inserir maiores detalhes detalhes sobre a vaga.

Está confuso essa postagem

Essa vaga aqui: https://empreender.hrpartner.io/jobs/-remoto--desenvolvedor-a--back-end---react-kbpdm não condiz com o propósito desse canal de vagas
