### ISSUE TITLE
[São José dos Campos] DESENVOLVEDOR FULLSTACK (React Nodejs) [GSW]

### ISSUE THREAD

**Issue by marianabompean** [react-brasil/vagas#638]
## Descrição da vaga
Atuar em grande projeto voltado para desenvolvimento React e Nodejs

## Local
São José dos Campos - Atuar diretamente em cliente

## Benefícios
- VR
 - Férias Remuneradas

## Requisitos

**Obrigatórios:**
Experiência com: React e Nodejs
Repositório de código fonte (Ex: Bitbucket, GitHub);
System Design.

**Conhecimentos**
DevOps;
Integração, Deploy contínuo.

**Desejáveis:**
- NOSQL

## Contratação
PJ a combinar

## Como se candidatar
Por favor envie um email para mariana.bompean@gsw.com.br com seu CV anexado - enviar no assunto: Vaga FullStack

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

**Comment by ribeiroevandro** [comment]
Email enviado!
