### ISSUE TITLE
[REMOTO] React Developer na INVILLIA

### ISSUE THREAD

**Issue by GabriellyLeonel** [react-brasil/vagas#639]
## Descrição da vaga
Liderança técnica; desenvolver código da documentação e histórias de usuário; corrigir defeitos; executar testes; automatizar (unitários, BDD); ser um profissional com perfil T (conhecimento profundo em Java, porém desejável no mínimo abertura para conhecer outras áreas de conhecimento).

## Local
Remoto.

## Benefícios
• Plano de Saúde: Coletivo – Desconto de contribuição mensal de R$21,89 (por pessoa); 
• Plano Odontológico: Desconto de contribuição mensal R$ 16,77 (Titular) R$ 33,54 (dependente); 
• Seguro de vida: Apólice no valor de R$ 100.000,00 (Sem Descontos); 
• Cartão Farmácia: Valor limite de crédito R$ 200,00 (Descontado em folha após 45 dias); 
• Vale alimentação/refeição: R$ 409,64 (Sem Descontos); 
• Auxilio Creche: Filhos de 0 a 24 meses R$ 481,98 / 24 a 60 meses R$ 421,00;
• Participação de Lucros atrelado a metas;
• Convênio com escola de idiomas e universidades; 
• Apoio a certificações; 
• Educação corporativa; 
• Auxílio Teletrabalho - R$ 250,00.

## Requisitos
Ter experiência como desenvolvedor frontend com as tecnologias: Javascript, JQuery, HTML, CSS, React , AngularJS, e SASS;
Ter experiência com testes unitários (Protractor, Seleniun ou Jasmine);
Ter experiência com micro frontend;
Ter experiência com os versionadores Git e SVN. Ter tido contato com metodologias ágeis como Kanban, SCRUM, XP, etc e práticas como TDD, BDD e Pair Programming;
Desejável: Conhecimento de configuração de servidores WEB como Apache ou NGINX;
Conhecimento em ferramenta de Continous Integration (Jenkins);
Conhecimento em serviços REST e WEB Standards (protocolos, verbos e respostas http, certificados, URI´s, etc);
Conhecimento em gerenciadores de dependência/pacotes (Bower, Maven e Gradle, NPM);
Conhecimento em automatizadores de tarefas como o Grunt;
SQL básico;

## Contratação

CLT - REMOTO. 

## Nossa empresa

Nós somos a Invillia,
Somos mais de 400 Invillianos atuando dentro e fora do Brasil, gerando oportunidades todos os dias para clientes potenciais em diversos segmentos e tecnologias. 
Faça uma imersão aqui https://invillia.com/ 

## Como se candidatar

Por favor envie um e-mail para gabrielly.leonel@invillia.com com seu CV anexado e pretensão salarial CLT - enviar no assunto: Vaga React / Front

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👴 Sênior
- ⚖️ CLT

**Comment by edusorcerer** [comment]
Oi @GabriellyLeonel, apenas uma dúvida

> conhecimento profundo em Java

Está correto em Java?
