### ISSUE TITLE
[São Paulo] Tech Lead na Traders Club

### ISSUE THREAD

**Issue by TradersClub1** [react-brasil/vagas#645]
Somos uma startup de educação financeira que tem como propósito a democratização do acesso a informações sobre o mercado de investimentos, tornando acessível para pessoas físicas o mesmo conhecimento de grandes traders. Tivemos um 2019 incrível e 2020 não está sendo diferente, temos oportunidades para o nosso time de Tech:

**Tech Lead**

Atividades:
Ser referência técnica para equipe: desenvolvedores, Quality Assurance e Engenheiro de Software;
Atuar em todo o processo, desde o levantamento de requisitos, desenvolvimentos, qualidade, medição do desempenho do aplicativo, com identificação e prevenção de bugs;
Criação de padrões e boas práticas de desenvolvimento.

Requisitos:
Experiência com todo o processo de desenvolvimento de melhorias e criação de novos produtos.
Sólida experiência com desenvolvimento em React Native para mobile, C e C++.

Local: Vila Olímpia.
Assistência médica, Vale Refeição e bônus anual.

Interessados encaminhar o currículo para o email: rh@tradersclub.com.br
Assunto: Tech Lead

**Comment by GleidsonDaniel** [comment]
@TradersClub1 Se fosse remoto seria top kkk
Inclusive um dos meu mentorados é um funcionário dai o Rafael rsrs

**Comment by TradersClub1** [comment]
Gleidson, boa noite!
Tudo bem?
Temos a possibilidade de atuação remota também, caso tenha interesse ;)

**Comment by wilkhp29** [comment]
enviei meu curriculum no email, já que tem a possibilidade de trabalho remoto
