### ISSUE TITLE
[São Paulo] Desenvolvedor Full Stack Traders Club

### ISSUE THREAD

**Issue by TradersClub1** [react-brasil/vagas#648]
Somos uma fintech que tem o propósito de democratizar o acesso a educação financeira. Nossa plataforma é hoje a maior comunidade de traders da América Latina, com mais 200 mil usuários cadastrados.
Estamos crescendo e buscamos um Desenvolvedor para nosso time de Tech. O principal foco das atividades é implementação de melhorias e novos produtos na nossa plataforma.

Requisitos:
- Conhecimento pleno em React e Reac Native.
- Experiência com desenvolvimento de API com Node ou Go.
- Conhecimento em banco de dados MySQL e MongoDB.
- Desejável experiência em Linux.

Jornada de trabalho flexível.
Local: Vila Olímpia.
Temos como benefícios Assistência Médica, Vale Refeição e bônus anual.

Interessados podem encaminhar o currículo para o email: rh@tradersclub.com.br
Assunto: Dev. Full Stack

**Comment by victorbiasibetti** [comment]
Essa vaga é somente presencial?

**Comment by julioxavierr** [comment]
Por favor, siga o template para marcação das tags.

**Comment by gregorispielmann** [comment]
Aceita remoto?

**Comment by TradersClub1** [comment]
> Essa vaga é somente presencial?

Sim, é presencial com flexibilidade de horário e alguns dias de trabalho home office.

**Comment by TradersClub1** [comment]
> Aceita remoto?

Olá, a vaga é presencial. Porém temos flexibilidade de horário e em alguns dias há a possibilidade de atuação home office.
