### ISSUE TITLE
[Franca - SP] React Native Developer na MazzaFC (MazzaTech)

### ISSUE THREAD

**Issue by brunoti** [react-brasil/vagas#65]
## Descrição da vaga

Diversos projetos supimpas com React Native! Projetos de edução, financeiros, empresarias (internos) e etc..

Precisamos de desenvolvedores que aprendem rápido e se dedicam de maneira equivalente ao que falam que dão conta!

## Local

Preferência é alocado em Franca SP (bem no centro). Remoto é necessário organizar mas seriam necessárias diversas viagens.

Estamos organizando para colocar salas de desenvolvimento em Ribeirão e Campinas. Então vagas remotas para essas cidades são mais interessantes.

#### Diferenciais

- Horário Livre
- Salário Equivalente com a experiência
- Workshops internos
- Diversos projetos para aprender

## Requisitos

**Obrigatórios:**
- Experiência comprovada com React Native
- Passar no teste criado por nós

**Diferenciais:**
- Redux
- Experiências de builds para  iOS e toda a tristeza do xCode
- CodePush
- Fastlane
- Conhecimento e vontade de trabalhar com Backend (Node/PHP) 
- Conhecimentos de Machine Learning (temos projetos na área)

## Contratação

PJ, valor a combinar. **ENVIAR PRETENSÃO POR EMAIL**

## Nossa empresa

A MazzaFC realiza o desenvolvimento de projetos sob demanda nas tecnologias PHP, .Net, Mobile (Hibrido, Android, IOS), Java, Python, NodeJS, API.

Trabalhamos também com a sustentação de sistemas já existentes e demandas específicas para criação de aplicativos e programas.

Atuamos como fábrica de software ou com células exclusivas de desenvolvedores – das duas formas, nossa equipe, altamente especializada, age com excelência em todo o processo de desenvolvimento, gestão de testes e sustentações.

## Como se candidatar

Envie um email para bruno.oliveira@mazzafc.tech e lais.bernardes@mazzafc.tech com:
- CV
- Pretenção Salarial
- O que precisa para se mudar pra Franca (já explicando se viria sozinho ou mais familiares)
- Descreva suas habilidades e dê informações sobre você. Isso pode te ajudar a conseguir a vaga.

## Labels

- alocação/Flexível
- alocação/Presencial
- alocação/Remoto
- experiência/Pleno
- experiência/Sênior
- regime/PJ

**Comment by brunoti** [comment]
Quem tiver um GitHub ou conseguir mostrar alguns projetos, ou testes feitos para outras em presas, não precisa de teste!

**Comment by brunoti** [comment]
Temos vagas ainda! Projeto novo não ta faltando haha

Entra em contato comigo. Estamos dando preferencia a quem quer mudar... Temos alguns devs que mudaram pra Franca, caso queiram conversar sobre.

**Comment by raivieiraadriano92** [comment]
Boa tarde Bruno, e-mail enviado :) (raivieiraadriano92@gmail.com)

**Comment by brunoti** [comment]
Podem reabrir? Ainda há vagas!
