### ISSUE TITLE
[REMOTE/PART-TIME] React Native na NetConv

### ISSUE THREAD

**Issue by fabiancarlos** [react-brasil/vagas#650]
## Descrição da vaga

Olá, somos a NetConv Delivery & Conveniência, basicamente um loja virtual de produtos de consumo.
Estamos a procura de um desenvolvedor com experiência Web/Mobile, React e React-Native.
Principalmente saiba de testes automatizados, e seguir styleguide de código.

Cargo: Engenheiro - Desenvolvimento de Software
Modelo: Remoto Home Office (Segunda a Sexta, 3hrs por dia)
Carga horária: Part-Time, flexível
Remuneração: R$3.000,00/mês

- Sendo assim focamos mais em produtividade do que tempo, não contamos horas, ou exigimos que se cumpra algum horário, apenas que envie PR curtos.
- Não iremos aplicar Slave-Scrum-Kanban, temos demandas que apenas devem ser feitas, e com testes.
- Faremos apenas 2 call semanais no máximo, e se tiver algum impedimento.
- As atividades tem prioridades, são estipuladas, mas priorizamos em estabilidade e qualidade.

## Local

Remoto/Part-time

## Requisitos

**Obrigatórios:**
- Conhecimentos em React-Native, React, Redux, Flow, Jest, Enzyme, Cypress.
- 3+ anos de experiência.
- Conhecimentos gerais de JSON, CSS/SASS, HTML5, JavaScript, React, Bootstrap, SQL/Postgres, Git, etc...

**Desejáveis:**
- conhecimentos em Ruby on Rails

## Contratação

PJ

## Como se candidatar

Por favor envie um email para contato@netconv.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Outros
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k

**Comment by diegowendel** [comment]
A vaga é temporária?

**Comment by mdlucas** [comment]
curriculo enviado

**Comment by allanreges** [comment]
O valor é fixo em 3k ou varia entre 3 e 5?

**Comment by ribeiroevandro** [comment]
Email enviado

**Comment by victorbiasibetti** [comment]
enviado

**Comment by fabiancarlos** [comment]
@allanreges por enquanto 3k.. depende da demanda

**Comment by DevVand** [comment]
é obrigatorio experiencia de 3 anos até para junior?

**Comment by fabiancarlos** [comment]
não é pra júnior @DevVand ... corrigi! valeu

**Comment by JoaquimAlvesFN** [comment]
ainda precisando?

**Comment by guilhermecostalopes** [comment]
Email enviado
