### ISSUE TITLE
Dev React Native SP - Dr. Vida Telemedicina

### ISSUE THREAD

**Issue by tasoeiro** [react-brasil/vagas#654]
## Descrição da vaga

Desenvolvimento e manutenção de aplicativos Mobile utilizando React Native
Colaborar com soluções técnicas e melhorias em ambientes ágeis
Implementar testes automatizados
Ajudar no desenvolvimento da equipe e de seus membros
Ajudar no refinamento e definição de histórias do usuário

Requisitos:
Experiência mínima com desenvolvimento de aplicativos Mobile utilizando React Native
Conhecimento de metodologias ágeis
Integração com APIs REST

## Local

Remoto ou Escritório, São Paulo - Paulista

#### Diferenciais

Horário Flexível
Ecossistema de startups no grupo
Prédio com ecossistema digital
Stock option mediante metas
Ambiente agregador e de inovação
100 mts do metrô
VT

## Requisitos

**Obrigatórios:**
Experiência em desenvolvimento de Apps

**Desejáveis:**
Git, HTML, CSS, JavaScript, Node.js e Gerenciadores de pacotes (npm, yarn, pnpm)
Context API, Redux ou MobX
Ciclo de vida de aplicativos mobile

## Contratação

PJ a combinar

## Nossa empresa

Doutor vida tem o propósito popularizar o acesso a saúde através de tecnologia, com telemedicina e tele saúde. 
Se você se identifica com nosso propósito, tem “sangue no olho”, obsessão por aprender, comprometimento e preza pela qualidade, você é a pessoa certa para fazer parte do nosso time!

## Como se candidatar

Por favor envie um email para contato@doutorvida.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k

**Comment by ribeiroevandro** [comment]
Email enviado!
