### ISSUE TITLE
Desenvolvedor Back End (Node.JS) - Dr vida telemedicina

### ISSUE THREAD

**Issue by tasoeiro** [react-brasil/vagas#655]
Descrição da vaga
Desenvolvimento e manutenção de aplicativos Mobile de telemedicina
Colaborar com soluções técnicas e melhorias em ambientes ágeis

Requisitos:
Experiência mínima - API RESTfull;
- Desenvolvimento com NodeJS usando Express ou Restify;
- Documentação de API (Swagger, OpenAPI);
- Desenvolvimento em Cloud (GCloud ou AWS);
- Modelagem de banco de dados PostgreSQL ou MySQL;
- Práticas de desenvolvimento seguro;
- Git (padrão GitFlow);
- Metodologia Ágil (Scrun, XP);
- Testes de Integração e Unidade;
- Servidores Linux;
- Criação de scripts em Shell, Python ou Ruby;

Local
Remoto ou Escritório, São Paulo - Paulista

Diferenciais
Horário Flexível
Ecossistema de startups no grupo
Prédio com ecossistema digital
Stock option mediante metas
Ambiente agregador e de inovação
100 mts do metrô
VT

Requisitos
Obrigatórios:
Experiência em backend

Desejáveis:
- Padrão WebServices SOAP;
- Ruby in Rails;
- Typescript;
- TDD / BDD

Experiência Diferencial:
- Cultura DevOps / DevSecOps;
- Melhores práticas de segurança do OWASP;
- Desenvolvimento com Docker;
- Continuous Integration / Continuous Deploy;

Contratação
PJ a combinar

Nossa empresa
Doutor vida tem o propósito popularizar o acesso a saúde através de tecnologia, com telemedicina e tele saúde.
Se você se identifica com nosso propósito, tem “sangue no olho”, obsessão por aprender, comprometimento e preza pela qualidade, você é a pessoa certa para fazer parte do nosso time!

Como se candidatar
Por favor envie um email para contato@doutorvida.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Back End (Node.JS)

Labels
🏢 Flexível
🏢 Presencial
🏢 Remoto
👦 Júnior
👨 Pleno
👴 Sênior
⚖️ A-Combinar
⚖️ PJ
💰 1k-3k
💰 3k-5k
💰 5k-10k

**Comment by breno-alves** [comment]
A vaga ainda está aberta?

**Comment by tasoeiro** [comment]
Positivo!
Manda no email thiago.soeiro@doutorlvida.com.br

**Comment by breno-alves** [comment]
Enviado, obrigado :)
