### ISSUE TITLE
[REMOTE] React PLENO/SENIOR na Tamovip

### ISSUE THREAD

**Issue by mltamovip** [react-brasil/vagas#657]
## Descrição da vaga

Olá, a [TamoVip](http://tamovip.com.br) é uma plataforma digital que conecta ídolos e fãs, criando experiências memoráveis ao permitir que sua audiência tenha acesso a videomensagens personalizadas e exclusivas.

Estamos a procura de um desenvolvedor com experiência Web, React e Ruby on Rails.

Cargo: Engenheiro - Desenvolvimento de Software

Modelo: Remoto Home Office - Presencial (SP, capital)

Carga horária: Full-time

Remuneração: A negociar

Requisitos

*Obrigatórios:*

Conhecimentos em JS, TypeScriptReact, React.
4+ anos de experiência.
Conhecimentos gerais de Ruby, JSON, CSS, HTML5, JavaScript, React, SQL/Postgres, etc...

**Desejáveis:**
conhecimentos em Ruby on Rails

**Contratação**
PJ

## Como se candidatar

Por favor envie um email para ml@tamovip.com com seu CV anexado - enviar no assunto: Vaga React

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 2k-6k

**Comment by Luiz-junior** [comment]
Boa tarde! tentei enviar o currículo no e-mail porém recebi uma mensagem de volta que talvez esse e-mail pode não existir ou que não tenho permissão para enviar algo para esse grupo

**Comment by thivalls** [comment]
Faltou o br no email eu acho, porque acessei o site e o domínio possui o br.

**Comment by Luiz-junior** [comment]
Vlw @thivalls mas tentei enviar aqui e recebi uma resposta de e-mail inexistente ainda

**Comment by mltamovip** [comment]
Foi mal pessoal, falha minha.
Podem tentar enviar agora para o hr@tamovip.com , testei aqui e tá ok
Se não funcionar podem mandar direto para pv@tamovip.com

**Comment by maxarouca** [comment]
> Vlw @thivalls mas tentei enviar aqui e recebi uma resposta de e-mail inexistente ainda

Mesma coisa aqui.

**Comment by mltamovip** [comment]
> > Vlw @thivalls mas tentei enviar aqui e recebi uma resposta de e-mail inexistente ainda
> 
> Mesma coisa aqui.

Estamos recebendo emails. Aparente está tudo normal

**Comment by ribeiroevandro** [comment]
Email enviado!
