### ISSUE TITLE
[Remoto] React Native Pleno/Senior para projeto inovador

### ISSUE THREAD

**Issue by hdoria** [react-brasil/vagas#662]
## Descrição da vaga

A [Popcode](https://www.popcode.com.br) é uma empresa especializada no desenvolvimento de aplicativos para iOS e Android. Recentemente passamos a utilizar react-native em todos os projetos. No momento, estamos com duas vagas para desenvolvedor react native, em projetos do ramo financeiro.

## Local
Remoto

#### Diferenciais
* Homeoffice
* Flexibilidade de horarios
* 100% de autonomia
* Alta probabilidade de crescimento
* Projeto inovador em seu seguimento

## Requisitos
**Obrigatórios:**

* Experiência com React Native
* Experiência com Node.js
* Experiência com Java Script

## Contratação
PJ

## Como se candidatar
Por favor envie um email para [queroser@popcode.com.br](mailto:queroser@popcode.com.br) com seu CV anexado - enviar no assunto: Vaga React Native - Pleno/Senior

**Comment by ribeiroevandro** [comment]
E-mail enviado!

**Comment by thejoaov** [comment]
Email enviado!

Em ter, 5 de mai de 2020 11:23, Hugo Doria <notifications@github.com>
escreveu:

**Comment by DevTeles** [comment]
E-mail enviado.
