### ISSUE TITLE
[Full Remote] React Js Developer na Squadra Tecnologia

### ISSUE THREAD

**Issue by VictoriaBoaventura** [react-brasil/vagas#663]
Se você é apaixonado(a) por tecnologia, engajado(a), quer trabalhar em um ambiente colaborativo e cool, aqui é o seu lugar!

Venha ser um dos nossos Digital Thinkers!

Estamos em busca de Pessoa Desenvolvedora React Pleno ou Sênior.

## Local

Remoto

## Benefícios

- Plano de saúde
- VR
- VT
- PLR
- Bolsa certificação
- Acesso ao Alura, Udemy e Pluralsigth
- Outros

## Requisitos

**Obrigatórios:**
- JavaScript;
- Reactjs;
- Arquitetura Front-end

**Desejáveis:**
- Estamos à procura de profissionais que gostem de ser protagonistas, se destaquem em suas atividades, seja criativo para ir além e engajado com os resultados.

## Contratação

CLT 40h/semanais

## Como se candidatar

Envie seu currículo para recrutamento@squadra.com.br - enviar no assunto: React Js Developer

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by maxarouca** [comment]
Olá @VictoriaBoaventura, estou tentando enviar, mas recebo a mensagem de que a caixa de entrada está cheia e não pode receber mensagens.

**Comment by VictoriaBoaventura** [comment]
Oi max. Recebemos o seu currículo.

A mensagem apareceu para você porque uma pessoa do grupo esta com a caixa
cheia hehehe.



Em ter, 12 de mai de 2020 09:31, Max Arouca <notifications@github.com>
escreveu:

**Comment by maxarouca** [comment]
Entendi. Obrigado pela resposta @VictoriaBoaventura .
