### ISSUE TITLE
[REMOTO] Fullstack Pleno (Java e React)

### ISSUE THREAD

**Issue by GabriellyLeonel** [react-brasil/vagas#666]
## Descrição da vaga
Desenvolver código da documentação e histórias de usuário; entender o problema do cliente e propor soluções; 
Corrigir defeitos;  executar testes;  automatizar (unitários, BDD).

## Local
REMOTO

## Benefícios
- Plano de saúde;
- Seguro de vida;
- VR, VA;
- Auxílio creche;
- Ajuda de custo;
- 2h de almoço.

## Requisitos

**Obrigatórios:**
Conhecimentos e experiência em Java 8 ou superior
Desenvolvimento Ágil - Scrum, Kanban
Experiência na stack de Spring, JPA e Hibernate
Conhecimentos de FrontEnd Html, css j Javascript
Conhecimentos em React e Redux.

## Contratação
CLT, REMOTO

## Nossa empresa
Nós somos a Invillia,
Somos mais de 500 Invillianos atuando dentro e fora do Brasil, gerando oportunidades todos os dias para clientes potenciais em diversos segmentos e tecnologias. 
Faça uma imersão aqui https://invillia.com/ 

## Como se candidatar
Por favor envie um e-mail para gabrielly.leonel@invillia.com com seu CV anexado e sua pretensão salarial - enviar no assunto: Vaga React Native

## Labels
- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT
- 💰 5k-7k

**Comment by guilhermecostalopes** [comment]
Curriculo enviado
