### ISSUE TITLE
[São Paulo] React Native Developer na PIXTER

### ISSUE THREAD

**Issue by RecruiterFMonteiro** [react-brasil/vagas#672]
## Descrição da vaga

Estamos em busca de um(a) Desenvolvedor(a) Mobile com foco em React Native, com conhecimentos nível Pleno nessa tecnologia, para fazer parte do nosso time - que tenha um bom relacionamento com equipes, seja proativo(a) e tenha ótima comunicação.
Projeto de grande porte, desafio bem interessante.

## Local

Inicialmente remoto - Localização da empresa São Paulo/SP

## Requisitos

**Obrigatórios:**
Domínio em Javascript nativo (ES6>).
Domínio em React Native, tanto no seu ciclo de vida quanto em itens de performance.
Domínio em Redux e/ou Context
Estrutura de um aplicativo nativo (IOS e Android)
Integrações com APIs externas (Rest e SOAP)
Conhecimento em bancos de dados SQL e NOSQL (MySQL, DynamoDB, MongoDB, etc)
Conhecimento em NodeJS
Experiência de no mínimo um ano com React Native

**Desejáveis:**
Conhecimento na infraestrutura da Google Cloud e AWS

## Contratação

PJ a combinar

## Nossa empresa

Somos uma boutique de software que tem em seu core desenvolvimento, inteligência e usabilidade.

Filtramos projetos que têm fit cultural com o que acreditamos e trabalhamos com poucos clientes.

Nos últimos três anos acumulamos cases de sucesso com empresas de grande porte. 

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado ou perfil atualizado do LinkedIn - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto Inicialmente
- 👦 Júnior
- 👨 Pleno
- ⚖️ PJ
(Remuneração - estamos trabalhando com pretensão)

**Comment by nicholasess** [comment]
@RecruiterFMonteiro faltou as faixas salárias

**Comment by RecruiterFMonteiro** [comment]
Obrigada @nicholasess , no momento estamos trabalhando com pretensão, já add a informação.

**Comment by ribeiroevandro** [comment]
E-email enviado!
