### ISSUE TITLE
[ABC] React e/ou React Native Developer na Vela Bikes

### ISSUE THREAD

**Issue by diogoviannaaraujo** [react-brasil/vagas#673]
## Descrição da vaga

Nós da [Vela](velabikes.com.br) desenvolvemos e produzimos bicicletas elétricas. Somos um time de desenvolvimento de produto pequeno e multidisciplinar. Nosso Stack de software é focado em JS, usando React e GCP.

Estamos procurando um desenvolvedor júnior a pleno, da região ou outras cidades, para nesse primeiro momento nos ajudar com manutenção e adaptações necessárias para nosso App e Loja virtual visando alguns mercados externos. 

## Local

Nosso escritório de desenvolvimento fica justo da nossa fabrica entre Diadema e São Bernardo do campo. O trabalho pode ser feito tranquilamente remoto, mas disponibilidade para ocasionalmente comparecer ou se relocar futuramente é bem vinda também

## Benefícios

- Refeitório com almoço gratuito
- Costumamos incluir uma Bike no contrato
- VR e/ou VT e outros benefícios negociaveis
- Tempo para estudo/projetos.

#### Diferenciais

- Flexibilidade de horario
- Time próximo e empático.
- Aqui na fabrica sempre rola uma cerveja
- Diversas areas pra se aprofundar

## Requisitos

**Obrigatórios:**
- Ter alguma experiencia profissional com JS
- Estar confortável escrevendo ES6
- Estar atualizado com React (Hooks, Context, etc)

**Desejáveis:**
- Ter usado GCP ou Firebase
- Ja ter passado raiva com o Android Studio usando RN
- Consiga se comunicar em ingles

**Diferenciais:**
- Redux Saga
- React Native Web
- C/C++/Rust/Python
- Linux no dia a dia
- Interesse em IoT, Eletronica e outras engenharias

## Contratação

PJ ou CLT a combinar

## Como se candidatar

Enviar um email para diogo@velabikes.com.br se apresentando e falando o que você faz/fez, se tiver currículo é bom também, a gente conversa a partir dai.

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Outros
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by raivieiraadriano92** [comment]
Boa tarde Diogo, existe a possibilidade de ser remoto?

**Comment by diogoviannaaraujo** [comment]
Boa tarde, existe sim, sem problemas.

**Comment by devartwa** [comment]
Enviado!!
