### ISSUE TITLE
[remoto] Front-end react na Santos Lab

### ISSUE THREAD

**Issue by FelipeAfonso** [react-brasil/vagas#674]
## Descrição da vaga

Projeto de agricultura de precisão com uso de imagens de drones e de satélite para a criação de uma plataforma de gestão de análises agrícolas. Já existe um produto mínimo em produção, e agora precisamos adaptá-lo para novos requisitos. A contratação é bem flexível e aceitamos também freelancers.

## Requisitos

**Obrigatórios:**
- Conhecimento prático com React utilizando HOC/Hooks e Redux

**Desejáveis:**

- conhecimentos com libs de mapa, de preferência Leaflet

**Diferenciais:**
- experiência prévia na área de agronomia

## Contratação

PJ/CLT/Freela a combinar

## Nossa empresa

A Santos Lab, aliada à proposta de desenvolver inovações integradas ao Sistema Aéreo Não Tripulado, está a cada dia ultrapassando novas barreiras para encontrar soluções eficazes resultantes da metodologia autoral, das tecnologias de ponta e dos softwares avançados. Tudo aplicado especialmente para o avanço do setor de gestão agrícola.

## Como se candidatar

Por favor envie um email para felipemunhoz@santoslab.com com cópia para bruno@santoslab.com com seu CV ou LinkedIn/Github - enviar no assunto: Vaga Front-end

## Labels

- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar

**Comment by victorbiasibetti** [comment]
isso é uma vaga real ou só um teste?

**Comment by FelipeAfonso** [comment]
é uma vaga real, meu enter que escorregou cedo de mais :P

Felipe Munhoz Afonso
Desenvolvedor Front End, Mestre em Engenharia de Software

(19) 99659-1558 (tel:(19)%2099659-1558)

**Comment by FelipeAfonso** [comment]
é uma vaga real, meu enter que escorregou cedo de mais :P

**Comment by ribeiroevandro** [comment]
E-mail enviado!

**Comment by pedroffd** [comment]
Email enviado.

**Comment by FelipeAfonso** [comment]
Obrigado a todos os participantes, finalizamos o processo de entrevistas, e receberão feedback até esta segunda feira!
