### ISSUE TITLE
[Santa Bárbara d'Oeste / Remoto] Front-end / mobile developer

### ISSUE THREAD

**Issue by yuritoledo** [react-brasil/vagas#679]
## Descrição da vaga
- Criação e manutenção de apps web e mobile;
- Integração do frontend com APIs e microsserviços internos;
- Escrever testes para garantir as funcionalidades já existes, em conjunto com as novas;
- Buscar novas ferramentas e técnicas para a melhoria contínua de nossos sistemas;
- Construir componentes reutilizáveis - internamente e entre sistemas;
- Participar do processo criativo e auxiliar na construção/elaboração dos sistemas;
- Ajudar a enriquecer a cultura na empresa :)

## Local

Remoto ou Escritório, Santa Barbara D'Oeste/SP

## Requisitos

**Obrigatórios:**
- Experiência relevante em front-end
- Experiência com React
  - Hooks
  - ContextAPI
  - Redux
  - Router
  - testing-library
- Experiência com Angular (Ionic)
- Bons conhecimento em JavaScript puro e CSS
- Clean code

**Desejáveis:**
- Conhecimento em Typescript
- Conhecimento em SemanticUI
- Conhecimento em styled-components
- Conhecimento em TDD ou testes automatizados
- Conhecimento em GraphQL

## Benefícios

- Vale Alimentação
- Reembolso de viagens caso seja remoto e venha para a empresa esporadicamente.
- No caso de home office, ou caso o profissional deseje trabalhar com seu próprio equipamento, há um reembolso mensal pelo uso.

**Diferenciais:**
- Área de descanso
- Café expresso ou coado
- Cachorro no ambiente de trabalho

## Contratação

CLT presencial ou remoto

## Como se candidatar

Por favor envie um email para yuri@cacdigital.com.br com seu CV anexado - enviar no assunto: Vaga Front-End e com a pretensão salarial, se possível :)
 
## Labels
 
- 🏢 Presencial
- 🏢 Remoto 
- 👦 Júnior
- 👨 Pleno 
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by pedroffd** [comment]
Enviado

**Comment by moacirandretti** [comment]
Já selecionaram o candidato para esta vaga? Obrigado.

**Comment by yuritoledo** [comment]
> Já selecionaram o candidato para esta vaga? Obrigado.

Ainda não @moacirandretti 
Estamos na primeira filtragem dos candidatos :)

**Comment by Henriquepb22** [comment]
Precisa ter experiência com Angular e React ou só uma das duas já serve?

**Comment by yuritoledo** [comment]
@Henriquepb22 
A maior parte do tempo é relacionada com react, então essa lib é necessário conhecer.

**Comment by niltonbsgi** [comment]
Fechou por motivo de cancelamento ou já contratou ?

**Comment by yuritoledo** [comment]
@niltonbsgi congelei, estou com bastante candidato pra entrevistar.

**Comment by yuritoledo** [comment]
@niltonbsgi se quiser mandar, boa sorte

**Comment by niltonbsgi** [comment]
ok
