### ISSUE TITLE
[Remoto] React Native Developer na 3xWiser

### ISSUE THREAD

**Issue by alexalxs** [react-brasil/vagas#688]
## Descrição da vaga

Projeto a ser desenvolvido em React Native semelhante ao Ankidroid, contudo mais simplificado.

## Local

Remoto

#### Diferenciais

- Flexibilidade de horário

## Contratação

Por hora.

## Nossa empresa

3xWiser é uma escola de inglês focada em aprendizdo acelerado e por isso deseja desenvolver um app próprio que traduza a filosofia da empresa.

## Como se candidatar

Por favor aplicar para a vaga preenchendo o formulário no link: https://forms.gle/wRNEX1GhH86Dbi9PA

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k

**Comment by ribeiroevandro** [comment]
Vaga interessante, porém meio que dei uma bugada... Nas labels coloca `Pleno/Sênior` porém nos requisitos, está como obrigatório ser pelo menos `Sênior`, tipo, algo de errado não está certo... Fora que a range de salário, também não está muito de acordo com a senioridade buscada... Mas enfim, irei aplicar, conhecer a ideia, não irá fazer mal!

**Comment by alexalxs** [comment]
Vaga preenchida.
