### ISSUE TITLE
[São Paulo] React Developer na Vitrine

### ISSUE THREAD

**Issue by jversolato** [react-brasil/vagas#69]
## Descrição da vaga

Procuramos desenvolvedor Front-End React JS

## Local

Avenida Paulista 171

## Benefícios

VT e VA

## Requisitos

**Obrigatórios:**
- ReactJS/Redux
- CSS/SASS
- GIT
- Experiência consumindo APIs Rest

**Diferenciais:**
- Testes com Jest
- react-storybook
- highcharts

## Contratação

- PJ (valor a combinar)
- CLT
- Full-time
- Pleno
- Sênior

## Nossa empresa

Somos uma startup inovadora com foco em gestão e métricas para o varejo. Estamos incubados na aceleradora ACE, a maior aceleradora da América Latina. (https://lnkd.in/dM565Bg)

## Como se candidatar

Interessados enviar CV ou Linkedin para vagas@vitrineretail.com com pretensão salarial e disponibilidade para inicio

## Labels

- alocação/Flexível
- alocação/Presencial
- experiência/Pleno
- experiência/Sênior
- regime/CLT
- regime/PJ

**Comment by danielGalvao** [comment]
A vaga continua aberta?
