### ISSUE TITLE
[FORTALEZA] React Native Developer na Agenda Edu

### ISSUE THREAD

**Issue by alinevds** [react-brasil/vagas#692]
## Descrição da vaga

Desenvolver e entregar uma experiência mobile incrível para os alunos e responsáveis usuários do nosso aplicativo;
Realizar entregas com código limpo, legível, usando boas práticas de desenvolvimento e performance e coberto com testes automatizados;
Avaliar, discutir e definir com o time melhorias de arquitetura, processos e desenvolvimento, participar do processo na revisão de pull requests, manter e melhorar o fluxo de entrega;
Participar da concepção das APIs internas junto ao time de backend.

## Local

Remoto ou Escritório, Fortaleza - CE

## Benefícios

- Plano de saúde
- Seguro de vida
- VR ou VA

## Requisitos

**Obrigatórios:**
Graduação em Ciência ou Engenharia da Computação, Sistema da Informação, Análise e Desenvolvimento de Sistemas, ou afins;
Experiência com React e React Native
Experiência com padrão Redux com Redux Saga

**Diferenciais:**
Ter trabalhado com testes funcionais (Jest, Jasmine, Mocha...)
Conhecimento sobre design systems e como construí-los
Experiência com delivery de aplicações mobile com Fastlane

## Nossa empresa

A Agenda Edu é uma startup de comunicação e engajamento escolar. Ajudamos escolas a darem o próximo passo frente ao novo, engajar os alunos e responsáveis na rotina escolar, fortalecer laços e, mais do que isso, conectar pessoas para transformar jornadas educacionais.

## Como se candidatar

Por favor envie um email para aline@agendaedu.com com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 3k-5k

**Comment by jjairojr** [comment]
Olá, a vaga é 100% remoto?

**Comment by alinevds** [comment]
Oi Jairo!

Nós temos em aberto as duas possibilidades, remoto ou presencial.

Com carinho ♥ ,


------------------------------
Aline Vasconcelos | Coordenadora de Desenvolvimento Humano

aline@agendaedu.com
(85) 9.9690-0185
www.agendaedu.com


Em ter., 16 de jun. de 2020 às 10:27, Jairo Júnior <notifications@github.com>
escreveu:

**Comment by jjairojr** [comment]
Enviei meu cúrriculo aline, muito obrigado pelo retorno!
