### ISSUE TITLE
[Remoto/Brasília] Nodejs/React developer

### ISSUE THREAD

**Issue by alexanderbraga** [react-brasil/vagas#693]
## Descrição da vaga

A Vary é uma empresa especializada em Investimentos, com sede em Brasilia e temos a alma de uma Startup. Recentemente passamos a utilizar React e Node.JS e em todos os projetos. No momento, estamos com duas vagas para desenvolvedor react native, em projetos do ramo financeiro..

## Local

Remoto ou Escritório, Brasília - DF

## Aqui você irá:

- Desenvolver código limpo, testável e de fácil manutenção.
- Contribuir com todo o processo de desenvolvimento de software.
- Implementar features novas e investigar problemas em produção.
- Contribuir nas discussões técnicas sobre os desafios encontrados.
- Participar do processo de code review, garantindo qualidade e consistência do código.

## Procuramos por pessoas que:

- Sejam detalhistas e analíticas;
- Gostem de lidar com projetos grandes e desafiadores;
- Consigam trabalhar em equipe de forma colaborativa e em função de um objetivo comum;
- Busquem aprendizado constante;
- Naveguem bem entre back-end e front-end;
- Queiram construir um ambiente de trabalho de respeito e apoio mútuo.

## Requisitos

**Obrigatórios:**
- Experiência desenvolvendo aplicações complexas;
- Conhecimentos avançados em Nodejs e Reactl;
- Conhecimentos avançados em HTML, CSS, JavaScript.
- Conhecimentos em MySql
- Git workflow

**Desejáveis:**
- conhecimentos em Material UI
- conhecimentos em BlockChain

## Contratação

Freela PJ a combinar

## Como se candidatar

Por favor envie um email para tecnologia@vary.com.br com seu CV anexado - enviar no assunto: Node.js & React Developer

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ Freela
- ⚖️ PJ
- 💰 3k-5k

**Comment by pedro-surf** [comment]
a vaga é apenas react native ou web tb? Obrigado :D

**Comment by alexanderbraga** [comment]
> a vaga é apenas react native ou web tb? Obrigado :D

E Web e Mobile

**Comment by yuritoledo** [comment]
Quantas horas semanais?

**Comment by alexanderbraga** [comment]
> Quantas horas semanais?
Temos de 4 horas por dia até Full Time, vai depender quanto tempo você pode está no projeto.

E os valores a ajustado por quantas horas por dia você está trabalhando.
