### ISSUE TITLE
[Remoto] Desenvolvedor Sr. React Native + Ruby

### ISSUE THREAD

**Issue by LiviaMaron** [react-brasil/vagas#699]
## Descrição da vaga

Startup de filantropia busca Desenvolvedor Sênior em React Native + Ruby on Rails para atuar em seu aplicativo.

## Local

:house: Remoto 

#### Diferenciais

Empresa com cultura horizontal e clima muito leve. Quer usar seus talentos e habilidades para fazer uma contribuição positiva para a empresa e para o mundo.

## Requisitos Obrigatórios:

- Profissional com bastante experiência de mercado com **React native (Android e Ios) ; Ruby on Rails; Javascript e Flutter**
 - Experiência com startup.

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A Robert Half combina profissionais de TI com algumas das melhores empresas em caráter temporário, de projeto ou em período integral. Desde funções em software e aplicativos até infraestrutura e operações de TI, fornecemos acesso sem paralelo a emocionantes oportunidades de carreira. Nossa abordagem personalizada, tecnologia inovadora de correspondência e rede global com experiência no mercado local ajudam a encontrar rapidamente os trabalhos de tecnologia que correspondem às suas habilidades e prioridades. Ao trabalhar conosco, você tem acesso a oportunidades desafiadoras, remuneração e benefícios competitivos e treinamento para aprimorar seu conjunto de habilidades.

## Como se candidatar

Por favor envie um email para livia.mello@roberthalf.com.br com seu CV anexado.

## Labels

- 🏢 Remoto
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT ou ⚖️ PJ
- 💰 15k+

**Comment by saimonventura** [comment]
email@email.com.br tá certo esse email?

**Comment by LiviaMaron** [comment]
Oi @saimonventura! Não estava certo não, eu salvei sem querer, mas já está ok.
