### ISSUE TITLE
[São Paulo] Front End Developer (React) na AMARO

### ISSUE THREAD

**Issue by vithoriaamaro** [react-brasil/vagas#707]
## Descrição da vaga

A AMARO é uma empresa de tecnologia e moda que veio para revolucionar o varejo.

Buscamos desenvolvedores front-end (pleno e sr) para compor nosso time :)

Qualificações:
Extensivo conhecimento em javascript
Experiência atuando com React
3+ anos de experiência como desenvolvedor front-end.
Inglês intermediário ou avançado

infos da vaga no link: http://bit.ly/2MCllPw

## Local

Remoto ou Escritório, São Paulo - Região Av. Paulista

## Benefícios

plano de saúde e odontológico
benefícios flex (Vale Refeição e utilidades)
convênio com escolas de idiomas e planos de academias

## Contratação

CLT

## Como se candidatar

Por favor envie um email para vithoria.duarte@amaro.com com seu CV anexado - enviar no assunto: Vaga FrontEnd ou se candidatar pelo seguinte link: http://bit.ly/2MCllPw

## Processo Seletivo

Bate papo por telefone
Entrevista com o time
Testes técnicos
Entrevista final e fit cultural

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by elisoaresr** [comment]
Já enviei o meu currículo por e-mail! :D
