### ISSUE TITLE
[São Paulo] Desenvolvedora Front-end Pleno/Sênior na Fisher Venture Builder

### ISSUE THREAD

**Issue by aka-ray** [react-brasil/vagas#708]
## Descrição da vaga

A procura por conteúdo de qualidade nunca esteve tão alta, e na Fisher Content, acreditamos que um conteúdo
de qualidade só está completo se acompanhado de uma plataforma a altura. Por isso, estamos desenvolvendo uma
série de iniciativas para melhorar a experiência de consumo da nossa audiência, e para chegar lá,
estamos procurando a ajuda de uma desenvolvedora Front-End de nível pleno ou sênior.

## Local
Atualmente remoto, devido a pandemia. Porém estamos à procura de alguém com disponibilidade de frequentar nosso escritório após a normalização. 
Nosso escritório está localizado na Rua dos Pinheiros, São Paulo - SP, a uma quadra do metrô Fradique Coutinho da linha amarela.

##  Responsabilidades:
- Você irá participar do desenvolvimento de novas funcionalidades para as nossas plataformas de conteúdo desenvolvidas
com React.js e Next.js, por isso ter o domínio de JavaScript é muito importante;
- Participar da elaboração e propor novos projetos para a nossa frente de conteúdo, aqui, sugestões são sempre bem vindas;
- Como estamos falando de uma plataforma de conteúdo, é importante que você entenda e domine a semantica do HTML, assim como as boas práticas SEO in-page;
- Ser organizada, ter um código padronizado e saber versionar o seu código é um must;

## Requisitos

**Obrigatórios:**
- Ter pelo menos dois anos de experiência com JavaScript/React.js;
- Domínio de HTML semântico e práticas de SEO in-page;
- Ter alguma experiência com SASS/SCSS;
- Se sentir confortável com consumo e integrações com APIs Restful;
- Versionamento com Git deve ser algo natural para você;
- Conhecer as boas práticas de HTML para E-mail;

**Diferenciais:**
- Ter alguma experiência com Node.JS, GraphQL ou d3.js

## Contratação

PJ a combinar

## Nossa empresa

Fisher Content é uma plataforma de conteúdo sobre inovação, tecnologia e startups. Aqui criamos reports, analisamos o mercado e resumimos para nossa audiência o que de principal acontece no ecossistema de inovação, seja em vídeo, post, artigo, relatório ou podcast. O Fisher Content faz parte da Fisher, uma venture builder criada em 2017 e focada na criação de fintechs.

## Como se candidatar
Por favor envie seu CV e perfil do GitHub com o assunto "Desenvolvedor(a) Front-End React Pleno/Sênior" para contato@fishervb.com

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-15k

**Comment by mrangel-jr** [comment]
Há a possibilidade de ser 100% remoto ?

**Comment by aka-ray** [comment]
Olá @mrangel-jr a vaga já foi preenchida e estou fechando a Issue para evitar mais contra-tempos, em contra partida, te adicionei no LinkedIn para podermos conversar em futuras oportunidades ;)

Grande abraço!
