### ISSUE TITLE
[Rio de Janeiro] Front End Developer na VTEX

### ISSUE THREAD

**Issue by nroussille** [react-brasil/vagas#721]
## Descrição da vaga

ABOUT US

VTEX is the only multitenant commerce platform capable of unifying experiences in all sales channels. With a robust solution, scalable cloud infrastructure and powerful tooling, our platform accelerates the transformation of complex operations.

More than 2900 renowned companies of varying sizes and segments, with operations in 42 countries and in global expansion, have at VTEX the solution for the online sale of their products, among them major names such as Sony, Motorola, Walmart, Whirlpool, Coca-Cola, Stanley Black & Decker, and Nestlé.

OUR CHALLENGES

We're building the infrastructure for global commerce. We create solutions that range from e-commerce to physical store solutions, but also extend to financial services and even tools to empower partner and client's devs. Among our biggest technical challenges:

		- Build services and workflows that are adaptable enough to fit our current and future enterprise demands
		- Evolve and scale our infrastructure to keep up with our 50% YOY growth
		- Deliver our engineering expertise through our serverless development platform

HOW WE WORK

Our team is built by bringing together bright and inquisitive engineers and a lot of tough problems. We've seen this setting fostering ownership, allowing engineers to deeply understand and have the initiative to solve our daily challenges.

Our stack consists mostly of .NET for CPU-bound applications, Node.js + Typescript for IO-bound services and a pinch of Golang here and there. On the frontend, we leverage React stuffed with Typescript and served with GraphQL on the side.

As an engineer who builds our frontend systems, you'll get to:
		- Design and build our core store components with a mobile-first approach - if you're interested to take a look at our design system
		- Define and implement standards and frameworks that bootstrap thousands of VTEX partner agencies
		- Profile and optimize our components performance focusing on improving UX
 
 We also expect and encourage every engineer to join our tech discussions, elaborate processes and build tools that raise the bar of our engineering practices and to take part in the hiring and onboarding of new team members.

## Local

Rio de Janeiro - Botafogo

## Benefícios

- Plano de saúde
- Plano odontológico
- Seguro de vida
- VR de R$ 35/dia
- Gympass
- PLR anual

## Requisitos

YOU SHOULD APPLY IF

Working with our tech and learning about commerce sounds exciting
You are keen to learn new concepts and not afraid to adapt to new paradigms
Working in a team that values initiative and ownership feels right to you
You are able to design simple solutions to complex problems
You are willing to question and suggest alternatives to existing approaches

Even though we value familiarity with our technology stack, we don't require that you have any previous knowledge of it. We’ve found that people who have a solid grasp of fundamental software engineering skills combined with a growth mindset fit in well at VTEX - and all the people we've found with this profile proficient in at least one programming stack.

If you like how we think and want to see more about our challenges, let's talk!

## Contratação

CLT

## Nossa empresa

OUR CULTURE

TRUST TO BE TRUSTED: We believe with eyes closed and delegate responsibilities. To be trustworthy you need honesty, transparency and consistency in quality and performance. This is the great pillar of all relationships that involve VTEX within and outside the company. We’re trust-first.

BUILD FOR COMMUNITY: It’s all about being ready to grow and reach new levels with others. Have a clear purpose, collective thinking and a flexible essence, and you’re building for community. We are global but we’re audacious enough to aim for the stars.

BE BOLD: Boldness is about challenging the status quo and not being afraid to make mistakes or take risks. We test new alternatives, walk into the unknown and explore possibilities no one thought about. To be bold is to apologize instead of asking for permission.

## Como se candidatar

É só se aplicar nesse link: https://jobs.lever.co/vtex/f511ffff-1068-4fbe-9e42-d71d83cc3f32 ;)

## Labels

- 🏢 Flexível
- 👶 Estágio
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by Loumier** [comment]
Is there any possibility to work remotely?
