### ISSUE TITLE
[REMOTO] [PART-TIME] Instrutor React

### ISSUE THREAD

**Issue by felipefontoura** [react-brasil/vagas#733]
## Descrição da vaga

Precisamos de Devs que sejam experientes em React e possuem desejo de ensinar outras pessoas a criarem aplicações React.

## Local

Remoto/Part-time

## Requisitos

**Obrigatórios:**

- Expert em React
- Afinidade em ensinar outras pessoas
- Disponibilidade de pelo menos 1/dia para responder dúvidas dos seus alunos.

**Desejáveis:**

- conhecimentos em Node.js
- conhecimentos em React Native

## Contratação

- Por demanda de gravação. Valor da hora/aula gravada - R$120,00.
-  % sobre as vendas do seu curso.

## Como se candidatar

Envie um WhatsApp que conversamos - (12) 98204-1640.

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ Freela
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by yuritoledo** [comment]
Uma dúvida: 
Disponibilidade de 1 dia por semana para suporte aos alunos e quanto mais, para a gravação das aulas?
