### ISSUE TITLE
Vaga Desenvolvedor Fullstack - Node, React e React Native - [⚖️ Freela]

### ISSUE THREAD

**Issue by dprado75** [react-brasil/vagas#734]
_(LEIA ATÉ O FINAL "Como se candidatar")_

## Estamos com algumas vagas para colaborar em uma nova plataforma de reuniões online.

Toda a equipe trabalha remotamente.

## Passos para aplicação:

envio de CV, Git e portfolio por email - jobs@xronxr.com
agendamento da entrevista - https://calendly.com/xronxr-jobs/book30

## Etapas após a entrevista:

análise do candidato: feedback em até 10 dias.

## Etapas após aprovação:

job inicial de 30 dias - com objetivos pré-estabelecidos e valor fechado.
revisão do trabalho: qualidade do código, facilidade e clareza de comunicação, disponibilidade.
contratação para aberto para integrar ao time que está construindo a plataforma.

## Obrigatório:

Fullstack Developer - Node, React e React Native

## Desejado:

A-Frame, CSS, vontade de inovar!

## Remuneração:

A combinar, compatível com o mercado!

## Outros Requisitos:

domínio do inglês. Equipe multinacional e documentação em inglês.

## Contratação:

Freelancer - PJ

## Sobre nós:

Startup multidisciplinar focada em inovação. 

## Como se candidatar:

email para jobs@xronxr.com contendo apresentação, cv, portfolio/git. Incluir a data agendada utilizando o link https://calendly.com/xronxr-jobs/book30!

Obrigado por aplicar!

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ Freela
- ⚖️ PJ
- 💰 1k-3k
- 💰 3k-5k
- 💰 5k-10k

**Comment by yuritoledo** [comment]
Quantas horas semanais?
