### ISSUE TITLE
[Remoto/São Paulo] Desenvolvedor Mobile React Native

### ISSUE THREAD

**Issue by brenooliveira** [react-brasil/vagas#738]
Estamos desenvolvendo uma nova oferta na Grão e por isso precisamos de um Desenvolvedor Mobile React Native para nos ajudar na construção desse produto. Essa pessoa vai ter a oportunidade de ajudar a construir uma linha de negócio nova dentro da Grão.

## Área de atuação
Desenvolvimento Mobile

## Principais atividades
 - Desenvolvimento do nossos aplicativos Mobile(Android e iOS)

## Requisitos
 - Experiência em lançamento de apps nas lojas (Google Play e Apple Store);
 - JavaScript (ES6+);
 - React, React Native, Redux, Flow, Jest, JSX;
 - Conhecimento 
 - Experiência prévia na posição;
 - Consumo de APIs restful;
 - Ter capacidade de compreender como seu trabalho afeta a empresa como um todo, muito além do código.
 
## Diferencial
- Conhecimento em Funcional;
- Swift ou Kotlin;
- RxJS;
- Styled Components;
- Entendimento de serviços financeiros, uma pessoa com experiência no mercado financeiro também é um plus.

Benefícios
- Trabalho remoto;
- Ambiente early stage de alto crescimento. Somos investidos pelos fundos Astella, Vox e Domo;
- Possibilidade de Stock Option;
- Possibilidade de contribuir com a construção de um produto que tem como propósito ajudar as pessoas através da educação financeira.

## Como se candidatar

Para se candidatar basta acessar o link https://cubo.network/jobs/e82f4580-c502-11ea-8d7f-8fcea5ab6cd9

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

- 💰 4k-6k

**Comment by ribeiroevandro** [comment]
Preenchido.
