### ISSUE TITLE
[Florianopolis] React Native Developer na nKey

### ISSUE THREAD

**Issue by danielladv** [react-brasil/vagas#75]
### **Front-end** Developer React Native Pleno
Desenvolvimento front-end: Javascript, ReactNative.
Analisar, entender demandas de negócio, prototipar, desenhar e implementar o front-end.
Gerar assets de layout.
Analisar tecnicamente a performance, qualidade de codificação, cobertura de testes e outros aspectos técnicos de front-end.
Acompanhar e coordenar testes e homologações de sistemas.
Conduzir e apoiar a execução de projetos dentro da metodologia ágil (Scrum e Kanban)

### **Local**
Alocação presencial, inicialmente na Grande Florianópolis (BR-101) e posteriormente na sede da empresa no bairro Itacorubi em Floripa.

### **Benefícios**
Vale Transporte
Vale Refeição ou Vale Alimentação
Plano Odontológico
Desc. Plano de Saúde

**Requisitos**

- Obrigatórios:

Experiência em desenvolvimento Javascript, React Native, RESTful APIs, Git, HTML, CSS, Webpack, Babel, Node.JS.
Experiência de gestão de projetos ágil (Scrum e Kanban).
Inglês avançado.

- Desejáveis:

Redux, GraphQL (Apollo ou Relay), Docker, SASS, LESS, Jest.
Conhecimento de conceitos de gestão de produto (Product Owner).
Contratação
CLT Full - Salário a combinar

### **Nossa** empresa
A nKey é uma empresa dedicada ao desenvolvimento de aplicativos móveis corporativos, localizada em Florianópolis, Santa Catarina. Nosso objetivo é criar soluções eficientes que proporcionam uma ótima experiência aos usuários.
Temos uma equipe talentosa, experiente e pronta para ajudá-lo no processo de criação de apps para seu negócio, desde a concepção da ideia, planejamento até o desenvolvimento, publicação e suporte..

### **Como se candidatar
Por favor envie um email para daniel.ladv@gmail.com, com seu CV anexado - enviar no assunto: Vaga React Native

**Labels**
alocação/Presencial
experiência/Júnior
experiência/Pleno
regime/CLT

**Comment by danielGalvao** [comment]
A vaga continua aberta?

**Comment by danielladv** [comment]
não mais... ---- On Wed, 03 Oct 2018 11:49:10 -0300 Daniel Galvão <notifications@github.com> wrote ---- A vaga continua aberta? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
