### ISSUE TITLE
[Rio de Janeiro] Desenvolvedor React Freelancer na iNova 

### ISSUE THREAD

**Issue by carlosoliveiradev** [react-brasil/vagas#752]
## Descrição da vaga

Vaga voltada para um projeto em andamento, utilizando React para o frontend e Express para o backend. O projeto consiste em um sistema para Plano Assistencial.

## Local

Remoto, Rio de Janeiro - Itaperuna

## Requisitos

**Obrigatórios:**
- Experiência com React

**Desejáveis:**
- conhecimentos em GraphQL
- conhecimentos em TypeScript

**Diferenciais:**

- disponibilidade

## Contratação

- a combinar

## Contato

Enviar e-mail para: carlosoliveiradev@gmail.com 

## Labels

- 🏢 Flexível
- 🏢 Remoto
- ⚖️ Freela
- 💰 1500

**Comment by gugagranato** [comment]
Quanto tempo de projeto?

**Comment by carlosoliveiradev** [comment]
Não tenho como definir o tempo total agora, mas enquanto rolar o projeto, seria R$ 1500, 00 por mês

**Comment by gugagranato** [comment]
@carlosoliveiradev isso é full time?

**Comment by ViniciusOl1** [comment]
Ainda disponível?

**Comment by cleberson-dev** [comment]
Ainda disponível?
