### ISSUE TITLE
[Chapecó / SC] React e/ou React Native Developer na TwoWeb

### ISSUE THREAD

**Issue by Brunomm** [react-brasil/vagas#753]
## Descrição da vaga

Estamos em busca de um Desenvolvedor React/ReactNative com pelo menos 1 ano de experiência para atuar em Chapecó-SC.
O profissional trabalhará em uma equipe multidisciplinar de maneira colaborativa.

Aqui na TwoWeb trabalhamos com diversos projetos diferentes e desafiadores, mantendo a pró-atividade em alta e buscando novos conhecimentos constantemente.

## Local

Escritório, R. Afonso Pena, 420-D - São Cristóvão, Chapecó - SC

## Benefícios

- Plano de saúde Unimed (50%) (CLT)
- Vale alimentação (CLT)

#### Diferenciais

- Horário comercial de segunda a sexta
- Utilize o editor de texto/IDE que desejar
- Sempre tem Café fresquinho
- Sala de descanso
- Qualidade de vida na cidade é excelente
- https://twoweb.com.br/cultura

## Requisitos

**Pessoais:**
- Proativo e organizado; 
- Focado;
- Comunicativo;
- Bom relacionamento interpessoal;
- Aberto às diferenças e a novos desafios;
- Busca constante por aprendizado.

**Obrigatórios:**
- 1 anos de experiência com desenvolvimento React ou React Native

**Desejáveis:**
- Node Js;
- HTML/CSS;
- Controle de versão Git;
- Formado ou cursando graduação na área de TI;

**Diferenciais:**
- Inglês
- Facilidade em aprender novas tecnologias
- Docker
- Ruby on Rails;
- MySQL/PostgreSQL;

## Atividades e Responsabilidades
- Desenvolvimento e manutenção de aplicações mobile;
- Desenvolvimento de funcionalidades no Back-End;
- Aplicar melhores práticas de documentação de código desenvolvido;
- Desenvolver e sustentar integrações;

## Contratação

CLT Presencial
PJ Remoto

## Nossa empresa

Nosso propósito é ajudar empreendedores do Brasil na transformação digital.

Paixão! Isso é o que nos move desde o início. Viramos referência quando o assunto é tecnologia, porque somos motivados pelo que fazemos: DESENVOLVER E INOVAR.

Nossa riqueza humana, engrandece nosso portfólio de serviços de tecnologia. Existimos para facilitar o desenvolvimento de pequenos, médios e grandes empreendedores que buscam o sucesso de seus negócios por meio da transformação digital.

Trabalhamos com uma ampla gama de clientes e uma equipe interdisciplinar de pensadores, criadores e realizadores, decididos a entregar boas experiências conectadas a múltiplas tecnologias e plataformas.

Com mais de 7 anos no mercado, somos especialistas em ajudar empresas em suas jornadas de transformação digital, trabalhando com o desenvolvimento de soluções tecnológicas sob medida e modelagem de negócios.

## Como se candidatar
Cadastre-se [neste link](https://twoweb.com.br/trabalhe-conosco/) ou envie um email para rh@twoweb.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by matheusPinheiroP** [comment]
Opa, diz que não é possível enviar o e-mail pq ele não "existe". O e-mail está correto?

**Comment by Brunomm** [comment]
Olá @matheusPinheiroP
Realmente a configuração do e-mail estava com um problema, agora já está ok.
Obrigado por avisar :+1: 
Também pode cadastrar o currículo no link a seguir https://twoweb.com.br/trabalhe-conosco
