### ISSUE TITLE
React Developer

### ISSUE THREAD

**Issue by GabrieleRecruiter** [react-brasil/vagas#76]
## Descrição da vaga

Desenvolvimento (análise e programação) de Aplicativo Web (Web application).

## Local

São Paulo - Vila Madalena

## Benefícios

   - Vale Refeição;
   - VT;
   - Assistência Médica
   - Seguro de Vida

#### Diferenciais

- Horário Flexível
- Plano de Carreira
 - Benefícios concedidos sem desconto em folha

## Requisitos

**Obrigatórios:**
-  Experiência com React Native
- Experiência com desenvolvimento iOS e Android

## Contratação

CLT

## Como se candidatar

Por favor envie um e-mail com pretensão salarial para ingrid.moreira@mirante.net.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- alocação/Flexível
- experiência/Júnior
- experiência/Pleno
- regime/CLT

**Comment by joabalvesdosantos** [comment]
Remoto?

**Comment by GabrieleRecruiter** [comment]
Alocação presencial.
