### ISSUE TITLE
[Remoto] Pessoa Desenvolvedora Front-end React Pleno na iClinic

### ISSUE THREAD

**Issue by fabianaiclinic** [react-brasil/vagas#775]
## Descrição da vaga

A iClinic está à procura de uma pessoa desenvolvedora front-end (remoto) para fortalecer e expandir nossas capacidades técnicas. Buscamos uma pessoa responsável para o cultivo de uma cultura técnica de excelência: obcecado por qualidade e desenvolvimento ágil. Procuramos alguém para refletir, validar ideias e ajudar-nos a encantar nossos clientes.

Você vai trabalhar com times multidisciplinares, com pessoas incríveis, capazes de realizar trabalhos incríveis e produzir resultados incríveis para os nossos usuários. Será responsável por desenvolvimento contínuo diariamente e irá garantir a qualidade que almejamos.

Tecnologia é o nosso core, então terá autonomia para arquitetar ou sugerir algo novo, deve ter uma mentalidade analítica, aptidão para solução de problemas e preocupação com a qualidade do código e boas práticas.

Temos serviços em Python/Django, Node, sistemas na AWS com e sem Kubernetes. Nossa aplicação front-end é desenvolvida em React + Redux.

## Local

100% Remoto

## Benefícios

- Vale refeição/alimentação;
- Convênio médico nacional;
- Plano de participação nos resultados (PPR);
- Fornecemos equipamento para desenvolvimento do seu trabalho;
- Ajuda de custo para modalidade remota (cadeira, mesa, acessórios para ergonomia etc);
- Bônus por indicação de outros profissionais para trabalhar na iClinic;
- Relacionamento próximo aos fundadores e diretores da empresa;
- Incentivo financeiro para desenvolvimento técnico;

#### Diferenciais

Quando fizer uma visita em nosso escritório - pós pandemia :) - você encontrará:

- Ambiente jovem, descontraído, escritório confortável, videogame, puffs para descanso;
- Sem dress code,  Trabalhe do jeito que achar confortável;
- Café da manhã, frutas e o sagrado cafezinho ao longo do dia;

## Requisitos

**Obrigatórios:**

- Experiência comprovada em React + gerenciamento de estado (Redux, Hooks, Saga) como front-end;
- Alta capacidade de auxiliar os outros membros do time a se desenvolverem, sendo capaz de comunicar ideias de forma clara;
- Visão ampla sobre processos de desenvolvimento e fluxo de trabalho em metodologias ágeis;
- Conhecimentos abrangentes em todas as partes do software, podendo conversar com diversas frentes do produto, pesquisa, dev-ops, back-end, QA tester;
- Conhecimentos em arquitetura de projetos, design patterns e boas práticas de desenvolvimento;
- Conhecimentos em paradigmas funcionais e suas práticas;
- Conhecimentos em metodologias de testes unitários, integração e E2E.
- 

**Desejáveis:**

- Ter conhecimentos de back-end e Docker;
- Inglês avançado em leitura e escrita;
- Conhecimento em ferramentas da AWS;

**Diferenciais:**
O que esperamos de você:

- Vontade de repassar conhecimento, ensinar, criar ou já ter criado artigos de programação;
- Já ter implementado testes com Selenium ou Cypress;
- Não ter receio em alterar um código que você não escreveu;
- Empatia por seus colaboradores;
- Capacidade de comunicar ideias de forma clara;
- Desejamos proatividade para adquirir novos conhecimentos rapidamente

## Contratação

CLT com benefícios

## Nossa empresa

A iClinic é uma das startups de tecnologia em saúde que mais cresce no Brasil.

Nossa missão é Descomplicar a saúde no Brasil.

E como fazemos isso hoje? 

Oferecendo o melhor software de gestão para clínicas e consultórios médicos.

E como atingir este objetivo?

Montando um time de pessoas incríveis, capazes de colocar os nossos clientes no centro do processo de criação e desenvolvimento do nosso sistema. Aqui são os clientes quem mandam e você será uma das vozes deles dentro da empresa e do time de Pesquisa e Desenvolvimento.

## Como se candidatar

Por favor candidate-se em nossa plataforma: https://iclinic.gupy.io/jobs/246873

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ CLT

**Comment by pauloedurezende** [comment]
Estarei fechando está issue pois esta vaga já havia sido postada anteriormente, vide issue #760 para mais informações
