### ISSUE TITLE
[REMOTO] React Native Developer@Pixter

### ISSUE THREAD

**Issue by D440** [react-brasil/vagas#780]
## Descrição da vaga
A Pixter é uma boutique de software, focada em grandes clientes. Com um time de mais de 100 pessoas, trabalhando em projetos nos EUA, Portugal e Brasil, a Pixter está guiando a transformação digital de algumas das principais empresas do mundo.

 
Estamos em busca de React Native Developer, com experiência sólida em nível Pleno, excelente comunicação, boa desenvoltura em reuniões de planejamento, organização e bom relacionamento interpessoal.

## Local

Remoto ou Escritório na Paulista(Opicional)

## Requisitos

Experiência em Javascript nativo (ES6>).
Experiência em React Native, tanto no seu ciclo de vida quanto em itens de performance.
Experiência em Redux e/ou Context
Estrutura de um aplicativo nativo (IOS e Android)
Integrações com APIs externas (Rest e SOAP)
Conhecimento em bancos de dados SQL e NOSQL (MySQL, DynamoDB, MongoDB, etc)
Conhecimento em NodeJS
Experiência de no mínimo um ano com React Native
**Desejáveis:**
- conhecimentos em GraphQL

## Contratação

PJ a combinar

## Como se candidatar

Por favor envie um email para danilo.vieira@pixter.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 5k-10k

**Comment by powilliam** [comment]
Enviado! :rocket:
