### ISSUE TITLE
Desenvolvedor Front End React  Pleno/Senior - 100% Home Office 

### ISSUE THREAD

**Issue by eullercdr** [react-brasil/vagas#782]
Descrição
Estamos procurando um Desenvolvedor Front End React Pleno/Senior - 100%  Home Office para integrar o nosso time de inovação.

Candidatar em: https://jobs.solides.com/gsaeducacional/vaga/27433
 
O que temos a oferecer:

Salário: Informar pretensão salarial
Horário de Trabalho: 220 horas mensais
Horário:  Integral, Segunda a Quinta, 9h ás 19h, Sexta 9h as 18h  

Valorizamos competências e habilidades como:

- ser  inovador
- ter responsabilidade com prazos
- ser legal com as pessoas
- pensar fora da caixa
- ter senso crítico,
- ser comunicativo(a)
- trabalhar em equipe.
- repassar o conhecimento

- Atribuições:

- Trabalhar em implementações de funcionalidades de sistemas existentes, bem como desenvolver novos produtos.

Requisitos
Requisitos Essenciais Indispensáveis

GIT
API REST
HTML
CSS3 Avançado
JAVASCRIPT Avançado
REACT
REACT NATIVE
REDUX E REDUX SAGA
Conhecimento em SQL

Será um diferencial
- Conhecimentos em Docker
- Conhecimentos em Node.js

**Comment by elisoaresr** [comment]
Só possível se candidatar pelo site em questão? O currículo não pode ser enviado para algum e-mail?

**Comment by eullercdr** [comment]
> Só possível se candidatar pelo site em questão? O currículo não pode ser enviado para algum e-mail?

Somente pelo site: https://jobs.solides.com/gsaeducacional/vaga/27433
