### ISSUE TITLE
[VAGA] Devolper front-end React em São Paulo - SP

### ISSUE THREAD

**Issue by Camila-Palha** [react-brasil/vagas#786]
Olá, Devs. Tudo bem?

Busco por desenvolvedores Front-end - React.js para uma startup no segmento alimentício (rede de restaurantes) que está em crescimento de modo acelerado. 
Vamos lá, vou explicar sobre o desafio: A ideia é a criação de uma plataforma de gestão de estoque e futuramente construção de e-commerce. É necessário forte vivência em React e caso tenha experiência com marketplace será um diferencial. :)

- 🏢 Presencial (No momento 100% home office e só retomarão as atividades presenciais em 2021)

- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ

E aí, faz sentido para você embarcar nesse desafio?
Caso faça, fique à vontade para me contatar pelo linkedIn: https://www.linkedin.com/in/camila-antunes-palha-58bb9014a/

Abraços.

**Comment by efraxpc** [comment]
oi Camila boa tarde, mandei um convite para vc no linkedin
