### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Senior node.js React

### ISSUE THREAD

**Issue by easycarrostech** [react-brasil/vagas#79]
## Descrição da vaga

Estamos em busca de um profissional jedi para integrar nossa equipe de desenvolvimento, então, se você tem desejo de trabalhar com projetos desafiadores, tecnologias inovadoras e participar de algo realmente grande, sua oportunidade pode estar aqui! 

## Local

Estamos no bairro de Pinheiros em SP, próximo à estação Fradique Coutinho (Linha Amarela - ViaQuatro)

## Benefícios

- Trabalhar em projetos para grandes marcas do mercado nacional;
- Ambiente alegre com pessoas inteligentes, fora da curva; 
- Flexibilidade de horários;
- No dress code;
- 30 dias de férias;

## Requisitos

**Obrigatórios:**
- Domínio em Node.js
- Domínio em NoSQL (MongoDB, REDIS etc..) 
- ReactJS, Angular, Vue.js ou algum framework SPA.
- Front-end, bootstrap, CSS3, Sass, Less ..
- Arquitetura de Webservices (Microserviços) 
- Modelagem de Banco de dados (Relacional MYSQL, PostgreSQL etc..) 

**Desejáveis:**
- Docker
- Rancher (Container Manager) 

## Contratação

PJ a combinar

## Nossa empresa

Somos uma startup que trabalha com foco em soluções tecnológicas para gestão de frotas. Uma empresa jovem, com mentes brilhantes e pessoas cheias de energia! 

## Como se candidatar

Por favor envie um email para fabiosarmento@easycarros.com com seu CV anexado - enviar no assunto: Vaga FullStack Senior React Nodejs

**Comment by nicholasess** [comment]
@easycarrostech faltou as Labels para facilitar o filtro nas vagas
