### ISSUE TITLE
[SÃO PAULO] Desenvolvedor Back End - CLT

### ISSUE THREAD

**Issue by anagarcia-2020** [react-brasil/vagas#790]
## Descrição da vaga

Desenvolvimento e manutenção de plataforma própria de ecommerce. O desenvolvedor irá atuar na revisão e atualização de parte do código e
também em novas frentes de negócio, como desenvolvimento de modais de
entrega, criação de market place, modelo de clube de assinatura. Em paralelo, terá
oportunidades no desenvolvimento de plataformas internas de comunicação
(intranet) e sistemas de suporte a plataforma atual. Requisitos: Domínio de sistema
de e-commerce em PHP puro, MySQL e JavaScript. Conhecimentos em estrutura de
base de dados, GIT e GitHub, Sass, Less, NPM, Bootstrap, Responsive Web Design,
consumo e criação de APIs. Experiência na área. Desejável:Conhecimentos em
Laravel ou Symfony, SEO e teste A/B.Diferencial: Desenvolvimento de
funcionalidades no front-end e produção de telas HTML.Desenvolvimento e
manutenção de plataforma própria de e-commerce, desenvolvimento de
funcionalidades no Front-End, produção de telas HTML a partir de PSDs para sites,
hot site e plataformas. Estruturar o HTML produzido nos projetos já estruturados,
respeitando arquitetura da aplicação.

## Local

Escritório - Bairro Água Funda (Próximo ao Jardim Botânico de São Paulo)

## Benefícios

- Assistência Médica
- Assistência Odontológica
- Cesta básica
- Convênio com farmácia
- Seguro de vida em grupo
- Vale-transporte.

## Requisitos

Domínio de sistema de e-commerce em PHP e MySQL, JavaScript. Conhecimentos
em estrutura de base de dados, GIT e GitHub, Sass, Less, NPM, Bootstrap,
Responsive Web Design SCRUM, consumo de APIs. Experiência na área. Desejável:
WebPack, Typescript, React Node JS, SEO e teste A/B.

## Contratação 

CLT

## Nossa empresa

Empresa do segmento varejista com lojas físicas e comércio eletrônico. A empresa está passando por processo de digitalização, com ênfase nas vendas online. A área de desenvolvimento terá grande foco da empresa, em um ambiente desafiador e com muitas oportunidades.

## Como se candidatar

Os interessados deverão enviar o Curriculum Vitae com PRETENSÃO SALARIAL para o e-mail selecao2346@gmail.com ou para o whatsapp 11 97199-0791

## Labels

- 🏢 Presencial
- ⚖️ CLT

**Comment by nicholasess** [comment]
@anagarcia-2020 não permitimos vagas de Backend nesse repositório, mas agradecemos a intenção

**Comment by anagarcia-2020** [comment]
Boa tarde,
backend-br/vagas

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
backend-br/vagas

:v: Espaço para divulgação de vagas para backenders - backend-br/vagas
 |

 |

 |



Veja que no tutorial é falado que posso fazer o anuncio de Desenvolvedor Back EndNão entendi o que aconteceuVoce teria como me ajudar ?



    Em segunda-feira, 10 de agosto de 2020 14:44:08 BRT, Nicholas Eduardo <notifications@github.com> escreveu:  
 
 


Closed #790.

**Comment by anagarcia-2020** [comment]
Bom dia, 

Veja que no tutorial é falado que posso fazer o anuncio de Desenvolvedor Back EndNão entendi o que aconteceuVoce teria como me ajudar ?
backend-br/vagas

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
backend-br/vagas

:v: Espaço para divulgação de vagas para backenders - backend-br/vagas
 |

 |

 |







    Em segunda-feira, 10 de agosto de 2020 14:44:08 BRT, Nicholas Eduardo <notifications@github.com> escreveu:  
 
 


@anagarcia-2020 não permitimos vagas de Backend nesse repositório, mas agradecemos a intenção

**Comment by nicholasess** [comment]
@anagarcia-2020 esse é o link correto

https://github.com/backend-br/vagas/issues/new?template=adicionar-nova-vaga.md&title=%5BCidade%5D+Back-end+Developer+%40+Nome+da+Empresa
