### ISSUE TITLE
[Florianópolis/REMOTO] Desenvolvedor Full Stack na Kartado - React + Django

### ISSUE THREAD

**Issue by marcosh72** [react-brasil/vagas#791]
## Descrição da vaga

A [Kartado](https://kartado.com.br/) busca um(a) novo(a) integrante para a equipe, para trabalhar em desafios de todas as partes da nossa plataforma (front-end e back-end), com React e Django.

## Local

A Kartado está em Florianópolis - SC, e a posição pode ser preenchida tanto presencial quanto remoto.

## Benefícios

- Parceria com Plano de saúde / UNIMED

## Requisitos

**Obrigatórios:**
- Autodidata, vontade de aprender, espírito inovador, 2 anos de experiência com desenvolvimento de software;
- JavaScript / ReactJS;
- Python / Django / DRF;
- Versionamento de código / Git / Scrum;
- Inglês intermediário;
- Familiaridade com trabalho remoto.

**Diferenciais:**
- Conhecimento em Linux ou Mac;
- Standard JSONAPI ou react-admin;
- Testes unitários e de integração.

## Contratação

CLT ou PJ, a combinar.

## Nossa empresa

A Kartado otimiza o processo operacional e gerencial da conservação de grandes infraestruturas. Nossa plataforma, que conta com centenas de usuários, recebe semanalmente importantes atualizações para introduzir novas funcionalidades ou melhorar a experiência do usuário. Junte-se ao nosso time de tecnologia e produto neste desafio!

- Ambiente de trabalho descontraído, com horários e dress code flexíveis;
- Possibilidade de trabalho remoto (durante a pandemia estamos 100% remotos);
- Foco em aprendizado contínuo e abertura para opiniões em todos os aspectos da empresa, promovendo a participação de todos frente a novos desafios;
- Estamos no MIDITEC, incubadora da ACATE em parceria com o SEBRAE, eleita pelo UBI Global Top 5 do Mundo na categoria - Incubadoras de empresas privadas. É uma ampla comunidade de empreendedores e mentores experientes, com eventos e workshops sobre os mais diversos assuntos.

## Como se candidatar

Por favor envie um email para marcos@kartado.com.br com seu CV anexado ou preencha o formulário disponível na página https://www.kartado.com.br/vagas/

## Labels

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ PJ
- 💰 3k-5k

**Comment by flakesrc** [comment]
Enviei por email e pelo formulário. Agradeceria se pudessem dar uma olhada especial no meu email enviado pelo flakesrc@protonmail.com

Att.
