### ISSUE TITLE
[Florianópolis] Full Stack Developer React Native

### ISSUE THREAD

**Issue by mauscoelho** [react-brasil/vagas#8]
### O que você precisa? 
Saber desenvolver para aplicativos mobile (Android e IOS) e conhecer bem sobre: 
- React Native; 
- Redux; 
- Flexbox; 
- Javascript ECMAScript 6. 

Plus: 
- RxJS; 
- Immutable.js; 
- Fastlane. 

### Por que não é nada legal trabalhar na Segware? 

Porque aqui você não está recebendo ordens o tempo inteiro, não tem ninguém no seu ouvido dizendo "faça assim!" ou "não faça isso!". E como você vai realizar suas tarefas se não tem nenhum figurão lhe dizendo toda hora o que fazer e como fazer? Impossível, logo de cara. 

Sabe aquela sensação maravilhosa de manter tudo como está, fazer as mesmas coisas do mesmo jeito até o final dos tempos? Então, na Segware não tem isso. A empresa aceita mudanças se você estiver disposto a liderá-las. Berro! 

Na Segware, você nunca sabe o dia de amanhã, pode começar exercendo uma função inicialmente, mas se os seus interesses mudaram e você quer novos desafios, a empresa permite mobilidade interna e você conquista um novo papel. Já imaginou ter que aprender algo novo e ser incentivado para isso? Terrível. 

Imagine trabalhar aqui e ter a oportunidade de fazer as coisas melhores sempre na sua mão? Quer fazer? Então, faz! Se você precisa de algo de algum outro time, você vai lá e pede, sem burocracia. O que fazer com essa tal liberdade? Surreal. 

Sabe aquela pressão gostosa de não poder levantar para ir ao banheiro ou tomar um café? É impressionante como a Segware não liga para isso. Aqui, você sobe, toma um café, come um sandubão, estica as pernas na rede, joga uma partida de Fifa e volta para trabalhar sem ninguém te olhar de cara feia. Um absurdo! 

E como seria acordar todos os dias e ter à disposição o espaço e as ferramentas que você precisa para crescer como profissional e ser valorizado pela empresa e pelo mercado de trabalho ao mesmo tempo? Um dilema diário, certamente. 

E tem mais! Dar autonomia para seus colaboradores, profissionais com experiência diária em suas atividades, e colocar gerência e diretoria como coadjuvantes nesse processo, mostra que a empresa não internalizou as vantagens de ser autoritária. Francamente! 

Mas se depois de todos os meus argumentos você continua achando que a Segware, na verdade, é uma baita, então tá, queridinho, assiste ao vídeo para descobrir quem tem razão. 

#SouSegmaker

Link da visita virtual: https://www.facebook.com/Segware/app/205634793251779/ 

Vídeo sobre a empresa e sobre o que é um Segmaker: https://www.facebook.com/pg/Segware/videos/?ref=page_internal

## Local
Local. Florianópolis - SC

## Como se candidatar?
Pelo [link](http://www.selecaodevagas.com.br/vacancies/view/149/TI+e+Informatica+Desenvolvedor(a)+React+Native) ou contato: gestaorh@segware.com.br

**Comment by nicholasess** [comment]
@mauscoelho a vaga ainda está em aberto?

**Comment by mauscoelho** [comment]
@nicholasess opa, tem sim. Manda ai o que tiver para fmpinheiro@segware.com.br que já agilizamos

**Comment by nicholasess** [comment]
@mauscoelho estou organizando o repositório, por isso a pergunta. 
A vaga é para qual nivel? Junior, Pleno ou Senior (Se tiver é claro)
Sei que é presencial, mas é CLT ou PJ?

**Comment by danielGalvao** [comment]
@mauscoelho a vaga ainda está aberta? Senão fecharemos a issue.

**Comment by mauscoelho** [comment]
@danielGalvao desulpe pela demora, não está mais disponivel :) 

closes #8
