### ISSUE TITLE
[São Paulo (SP), Novo Hamburgo (RS), Natal (RN)] 3 Vagas desenvolvedor React Native

### ISSUE THREAD

**Issue by viniciuspalma** [react-brasil/vagas#81]
# Front-end Developer React Native - 87Labs

Site: http://www.87labs.com/

## Local
Escritórios:
  - Novo Hamburgo (RS)
  - São Paulo (SP)
  - Natal (RN)

## Remoto
a combinar

## Benefícios
- Vale Transporte
- Vale Refeição ou Vale Alimentação
- Plano de Saúde

### Obrigatórios:
- Experiência em desenvolvimento
  - Javascript
  - React Native
  - REST API
  - Git
  - HTML
  - CSS
  - Webpack
  - Babel
  - Node.JS.
- Inglês avançado.

### Desejáveis:
  - Redux
  - GraphQL (Apollo ou Relay)
  - Jest.

## Contratação
CLT Full - Salário a combinar

## Nossa empresa
Era para a 87 ser uma empresa de consultoria de TI.
Mas a 87 não quer só escrever código.

Queremos ajudar nossos clientes a lançarem um produto e atingir suas metas. E não só as de curto ou médio prazo. Queremos ajudar a dar uma visão para que seus produtos tenham vida longa. E com resultados consistentes.
Mas para tudo isso acontecer, também somos diferentes de uma consultoria de TI nos processos: contratamos diferente, temos um time diferente e cuidamos dos nossos clientes de um jeito diferente.

# Como se candidatar
Por favor envie um email para contato@87labs.com, com seu CV anexado - enviar no assunto: Vaga React Native

Labels
alocação/Presencial
experiência/Júnior
experiência/Pleno
regime/CLT

**Comment by joabalvesdosantos** [comment]
Enviado.

**Comment by John-Luke** [comment]
Aceitam estágio para o escritório em Natal?
