### ISSUE TITLE
[Remoto] Fullstack developer (2 vagas) - SHARECARE

### ISSUE THREAD

**Issue by viperdigo** [react-brasil/vagas#811]
## Descrição da vaga

Fullstack developer (Pleno/Sênior):

## Local

Remoto

## Requisitos

**Obrigatórios:**
		Javascript ES6 e TypeScript;
		NodeJS e Express;
		Bom entendimento de programação assíncrona, suas peculiaridades e alternativas;
		Conhecimento intermediário de tecnologias front-end (HTML5, CSS3);
		Experiência com arquiteturas RESTful;
		Controle de versão de código-fonte em Git (Gitflow);
		Boas práticas de desenvolvimento (S.O.L.I.D);

**Desejáveis:**
		Testes automatizados (BDD e TDD);
		Capacidade de autogestão e aprendizado;
		Familiaridade com scrum;
		Desejável conhecimento em ReactJS e VueJS;
		Conhecimento do funcionamento de containers com Docker;
		Integração contínua e entrega contínua (CI/CD);

**Diferencial:**
		Conhecimento em Desenvolvimento Mobile (Kotlin, Swift, Java, Flutter);
 		Inglês (contato com os times de Berlim, EUA, França e Nova Zelandia);

## Contratação

PJ 

## Nossa empresa

A Sharecare (HealthTech) inova constantemente, apresentando tecnologias premiadas, protocolos cientificamente validados e ferramentas de assistência consideradas como as melhores, ajudando provedores de saúde, empregadores e planos de saúde a implantar de forma eficaz soluções de saúde e bem-estar a toda sua população.

## Como se candidatar

Por favor envie um email para rodrigo.alfieri@sharecare.com com seu CV anexado - enviar no assunto: Vaga Fullstack

## Labels

- 🏢 100% Remoto (mesmo após pandemia)
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 5k-10k
- 💰 10k-15k

**Comment by lucasalmeida92** [comment]
Currículo enviado
