### ISSUE TITLE
[Rio de Janeiro] Estágio Full Stack React + Node @ Incentive-me

### ISSUE THREAD

**Issue by thiagolinsx** [react-brasil/vagas#83]
![recrutamento](https://user-images.githubusercontent.com/798331/42724772-a28f8902-874e-11e8-838a-7c37c42ba014.png)

## Descrição da vaga

Procuramos um(a) estagiário(a) Full Stack para ajudar a compor a nosso time.

Buscamos pessoas engajadas e motivadas, temos um time enxuto onde a atuação de cada membro é muito importante. Todos tem espaço para expor suas ideias e participar das tomadas de decisão.

**Ativides:**

- Desenvolvimento de componentes React reutilizáveis;
- Desenvolver protótipos e POCs;
- Estar sempre atento a comunidade, buscando e seguindo boas práticas de desenvolvimento;
- Desenvolver APIs para consumo dos sistemas Web e Mobile;

## Local

Estamos em um escritório na Península, Barra da Tijuca - Rio de Janeiro

## Benefícios
- Trabalhar com grandes empresas do mercado nacional;
- Muita possibilidade de aprender;
- Ambiente informal e alegre;
- No dress code;

## Requisitos

**Obrigatórios:**
- Ter interesse em novas tecnologias.
- Ser engajado e ter muita vontade de aprender.

**Desejáveis:**
- React
- JavaScript
- Node.js

## Contratação

Estágio 6h

## Como se candidatar

Por favor envie um email para thiago.lins@incentive-me.com com seu CV anexado - enviar no assunto: `Vaga React Brasil - [SEU NOME]`

## Labels

- alocação/Presencial
- experiência/Estágio
- experiência/Júnior
- regime/A-Combinar

**Comment by nicholasess** [comment]
@thiagolinsx sua vaga não condiz com a realidade, você quer um desenvolvedor junior e pagar como estagiário?

**Comment by joabalvesdosantos** [comment]
Qual o valor do estagio?

**Comment by thiagolinsx** [comment]
@nicholasess Você poderia explicar melhor o que você está querendo dizer?

**Comment by nicholasess** [comment]
@thiagolinsx 
Sua chamada da vaga não está dizendo que é estágio.
Quem está em busca de estágio não tem experiência e dessa forma você acaba desestimulando por requerer conhecimento em tecnologias que tem uma curva de aprendizado alta.

**Comment by thiagolinsx** [comment]
@joabalvesdosantos Nessa fase inicial não pode ser remoto, mas pode ser negociado para frente. Sobre o valor, não temos vagas bem definidas, somos uma startup, então estamos negociando com cada candidato de acordo com a experiência e o potencial.

**Comment by thiagolinsx** [comment]
@nicholasess Na descrição da vaga está escrito: "Procuramos um(a) estagiário(a) Full Stack para ajudar a compor a nosso time."
Nos requisitos obrigatórios colocamos "vontade de aprender", nos desejáveis colocamos as tecnologias que utilizamos, não colocamos exigência de experiência em emprego anterior... Apenas listamos as tecnologias, muitos já estudaram por conta própria, fazem cursos online e podem já ter certo conhecimentos nessas tecnologias.

**Comment by lffranca** [comment]
@nicholasess  Pelo que eu entendi, o estagiário não precisa possuir esse requisitos, ele apenas irá exercer essas atividades, não é isso @thiagolinsx ?

**Comment by nicholasess** [comment]
@thiagolinsx só trocar o titulo de Desenvolvedor, para Estagiário e está tudo certo :)

**Comment by lffranca** [comment]
@nicholasess Também acho uma boa alterar o titulo, confunde mesmo com uma vaga para desenvolvedor.
