### ISSUE TITLE
[Remoto] React Native Developer Pleno/Sênior na Skilopay

### ISSUE THREAD

**Issue by ssscassio** [react-brasil/vagas#857]
## Descrição da vaga

Que tal resolver problemas do mercado financeiro e impactar milhões de pessoas? A Skilopay é uma empresa de tecnologia que desenvolve produtos e serviços financeiros. Atualmente está em busca de pessoas incríveis para ajudar a revolucionar a maneira que lidamos com dinheiro no Brasil.

## Local

100% Remoto (somos uma empresa _remote-first_)

## Benefícios

- Trabalhe de onde quiser;
- Horário flexível;
- Tecnologias de ponta;
- Participação nos lucros da empresa;
- Ajuda de custo para montar seu Home Office;

## Requisitos

**Obrigatórios:**
- React Native

**Desejáveis:**
- TypeScript
- GraphQL/Apollo

## Contratação

CLT ou PJ

## Nível
- Pleno
- Sênior

## Nossa empresa

Somos uma empresa com pouco mais de um ano, em fase de tração, possuímos milhares de clientes na nossa base e pretendemos crescer MUITO :rocket: nos próximos meses. Queremos impactar milhões de pessoas!

## Como se candidatar

Por favor, envie um email para [jonata@skilopay.com.br](mailto:jonata@skilopay.com.br) com seu currículo ou linkedin - enviar com assunto: Vaga Mobile Developer

**Comment by MatSa20** [comment]
Aceitam Jr?

**Comment by ssscassio** [comment]
@MatSa20 No momento estamos procurando Pleno ou Sênior.
