### ISSUE TITLE
[São Paulo] Desenvolvedor Mobile React Native na Ucorp Mobilidade Urbana

### ISSUE THREAD

**Issue by tanadamajori** [react-brasil/vagas#864]
## Descrição da vaga

Você fará parte de um Projeto incrível e desafiador, no desenvolvimento de APP Mobile para frotas corporativas com carros elétricos e à combustão.

👨 Pleno
👴 Sênior

## Local

🏢 Remoto 
Temos também um QG que nos permite atuar de forma híbrida, na região da Vila Olímpia - SP. (SPACES)

## Benefícios

- Horário
 🏢 Flexível

#### Diferenciais

Ser um Ucorper é: 🚘🔌🔋🦄🚀

- Fazer parte de uma squad disruptiva
- Vivenciar a experiência de atuar com carros elétricos, e todo seu ecossistema.
- Ser ativo e parceiro com todas as áreas envolvidas no projeto.
- Fazer parte de um modelo de negócio promissor e "futurista". 
- Liberdade em auto gestão.
- Atuar, e ter olhar de dono.

## Requisitos

**Obrigatórios:**
- Experiência de 3 anos ou mais com:
- Javascript 
- Node.js 
- React Native 
- HTML
- CSS

**Desejáveis:**
- Conhecimentos em Metodologia Ágil

**Diferenciais:**
- Vivência em Startups 

## Contratação

⚖️ PJ 
Estamos trabalhando conforme a pretensão de cada candidato 💰 10k-15k 

## Nossa empresa

🚘🔋Quer ser um Ucorper? 🚘🔋

Somos um time apaixonado e colaborativo.
Buscamos perfis que queiram caminhar conosco nessa constante evolução, aprendendo e construindo um processos ágil e produtivo!
Nosso propósito é Eletrificar as frotas Corporativas!! 

MANIFESTO UCORP - https://youtu.be/oHVFvQTyqEM 

## Como se candidatar

Quer ser um Ucorper ?! Se identificou com a vaga?
Envie um currículo para embarqueaqui@ucorp.app
Assunto: Dev Mobile

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ PJ
- 💰 10k-15k

**Comment by wsilvadev** [comment]
Oi, tudo bem? Espero que sim!
 Sou Willian e estou iniciando na programação há três anos.
 Preencho todos os requisitos para está vaga!

**Comment by tanadamajori** [comment]
Boa tarde @wsilvadev tudo bem!? Espero que sim!!

Fico muito feliz que tenha interesse pela vaga postada!

Peço por gentileza que envie um cv atualizado para embarqueaqui@ucorp.app com o assunto "Dev Mobile".

Assim que receber seu cv, enviarei para avaliação técnica e entro em contato contigo!

Qualquer dúvida só me contatar no whatsapp 11-98755-2853

Att

Májori Tanada

**Comment by lucaspedronet** [comment]
Olá, tudo bem? Fique muito entusiasmado com essa vaga, possuo todos os requisitos. Por isso encaminhei um e-mail. Obrigado!

**Comment by brunocrpontes** [comment]
Olá, enviei meu CV para concorrer a vaga!

**Comment by tanadamajori** [comment]
> Olá, tudo bem? Fique muito entusiasmado com essa vaga, possuo todos os requisitos. Por isso encaminhei um e-mail. Obrigado!

Oi Lucas!! Tudo bem?
Consegue me chamar no whats da vaga para conversarmos melhor?

Obrigada!

**Comment by lucaspedronet** [comment]
> > Olá, tudo bem? Fique muito entusiasmado com essa vaga, possuo todos os requisitos. Por isso encaminhei um e-mail. Obrigado!
> 
> Oi Lucas!! Tudo bem?
> Consegue me chamar no whats da vaga para conversarmos melhor?
> 
> Obrigada!

Olá Majori!! Vou entrar em contato via whats ainda hoje.

Obrigado!
