### ISSUE TITLE
[SÃO PAULO] Software Engineer Mobile - CREDITAS

### ISSUE THREAD

**Issue by ThaynaPortella** [react-brasil/vagas#870]
## Descrição da vaga

O desafio é para ser Software Engineer Mobile na Creditas, sendo responsável por desenvolver garantindo funcionalidade e velocidade, além de práticas de teste e qualidade e assim garantindo soluções técnicas que estejam alinhadas à estratégia do negócio. 

## Local

São Paulo (Vila Olímpia) ou REMOTO

## Benefícios

- Plano de saúde
- Plano Odontológico e Seguro de Vida
- VT, Estacionamento, Fretado ou Bicicletário
- Snacks e frutinhas frescas todos os dias no escritório

## Requisitos

**Obrigatórios:**
Experiência com React Native.

**Desejáveis:**
- Experiência em construção de pixel-perfect UIs para IOS e Android

## Contratação

CLT + Benefícios.
Início remoto, mas previsão de ser 100% presencial a partir de janeiro.
 
## Nossa empresa

Somos a maior fintech de empréstimo com garantia do Brasil que utiliza tecnologia open source e segue a filosofia agile. Estamos desenvolvendo a melhor arquitetura e as melhores tecnologias para fornecer a melhor performance aos nossos clientes. Aqui prezamos ambientes de trabalho colaborativos, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads.

## Como se candidatar

Mais informações sobre a vaga e Link de Inscrição: https://byintera.in/12c

## Labels

- 🏢 Flexível
- 👴 Sênior
- ⚖️ CLT

**Comment by julioxavierr** [comment]
Favor adicionar tags para marcação

**Comment by wsilvadev** [comment]
Está vaga é pra júnior? Tenho uma boa experiência com desenvolvimento Mobile

**Comment by ThaynaPortella** [comment]
Olá Wilian, no momento estamos buscando para nível Senior.
