### ISSUE TITLE
[Remoto] - React/Nextjs na Conta Stone

### ISSUE THREAD

**Issue by danferreira** [react-brasil/vagas#871]
## Descrição da vaga

Estamos buscando Front-End Developers que tenham interesse em trabalhar com React/Nextjs e queiram encarar conosco o desafio de construir a Conta Stone, nos ajudando nas principais decisões técnicas e seus impactos no produto no médio/longo prazo.

## Local

Remoto ou Escritório Rio/São Paulo

## Requisitos

**Obrigatórios:**
- Experiência em aplicações React/Nextjs;
- Experiência com ferramentas de versionamento e colaboração como git e github;

**Desejáveis:**
- Conhecimentos em Nodejs (express);

**Diferenciais:**
- Experiência em trabalho remoto;
- Experiencia com mercado de pagamentos;
- Projetos opensource;

## Contratação

A contração será em regime CLT, com possibilidade de trabalho presencial nos escritórios do Rio de Janeiro e São Paulo ou 100% remoto. Sim, você pode trabalhar de qualquer lugar do Brasil :)

## Nossa empresa

SOMOS O TIME DE BANKING DA STONE :)

Somos a Business Unit da Stone responsável pela construção da Conta Stone, uma conta de pagamento feita para empreendedores. Queremos construir na empresa um banco sem banqueiros, e estamos fazendo isso do nosso jeito.

Queremos mudar a forma como lojistas gerenciam as finanças dos seus negócios e realizam suas operações bancárias. Para isso, contamos com um time fora da curva e distribuído por diversas cidades do Brasil (sim, somos um time remote-first!). Além disso, não temos medo de inovar na tecnologia para entregar os melhores produtos!

Conheça mais o nosso produto: stone.com.br/conta

## Como se candidatar

https://www.linkedin.com/jobs/view/1953173434/

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by iredhd** [comment]
@danferreira 

Candidatura enviada!
