### ISSUE TITLE
[Vila Olímpia/SP] Software Engineer Mobile na Creditas

### ISSUE THREAD

**Issue by AmandaBadaro** [react-brasil/vagas#878]
## Descrição da vaga

- Desenvolverá garantindo funcionalidade, manutenibilidade e velocidade, além de práticas de teste e qualidade;
- Garantirá que todas as soluções técnicas estejam alinhadas a estratégia do negócio;
- Entenderá o impacto das soluções que o time desenvolve no usuário final;
- Ajudará o time no desenho de soluções com arquitetura evolutiva, além de investigar constantemente novas tecnologias e formas de trabalho;
- Colaborará com a evolução das skills técnicas do time e esforços de melhoria contínua que impactam vários times;
- Trabalhará em um ambiente colaborativo, em que práticas de pareamento, feedbacks e motivação para se desenvolver são comuns a todos os squads.

## Local

São Paulo - Vila Olímpia

## Benefícios

Plano de Saúde
 Plano Odontológico
 Seguro de Vida
Vale-Refeição
VT
Estacionamento, Fretado ou Bicicletário; 									
										
## Requisitos

- Experiência em desenvolvimento de aplicações em React Native e desenvolvimento nativo para IOS ou Android é considerado diferencial;
- Experiência em construção de pixel-perfect UIs para IOS e Android;
- Conhecimento prático no mundo mobile, arquiteturas, tendências e tecnologias emergentes;
- Implementar APIs;
- Embasamento teórico, habilidade e preocupação com a excelência técnica e boas práticas de desenvolvimento (DDD, TDD, arquitetura, design de código, paradigmas, etc.)

## Contratação

CLT

## Nossa empresa

A Creditas é a principal plataforma online de crédito com garantia do Brasil. Com sede em São Paulo e escritórios em Porto Alegre, Valencia (Espanha) e Cidade do México, a Creditas conta com mais de 1500 tripulantes. Reconhecimentos por rankings do Linkedin Top Startups e Melhores Lugares para se Trabalhar do Glassdoor, consolidam a preocupação que a empresa tem em proporcionar a melhor experiência para o seu time.

## Como se candidatar

Quer aproveitar a oportunidade e participar dessa experiência de somar com a tripulação Creditas? Então vem conferir mais informações nesse link:  https://bit.ly/3m7R3Ef

**Comment by emersonbrs** [comment]
Feito! ;D
