### ISSUE TITLE
[Remote] React Front-end Developer na Razzo.tech

### ISSUE THREAD

**Issue by neomarbassani** [react-brasil/vagas#880]
## Descrição da vaga

Somos uma Software House e buscamos profissionais front-end para complementar nossos times de desenvolvimento. Este profissional atuará em diversos projetos, sendo responsável pelo desenvolvimento das aplicações.

## Local

Remoto

## Requisitos

**Obrigatórios:**
- Experiência com React / React Native
- Experiência com Redux
- Conhecimentos sólidos em Javascript

**Desejáveis:**
- Animações com React
- NodeJS
- MongoDB

**Diferenciais:**
- Facilidade de aprendizado
- Muita vontade de aprender
- Bom relacionamento interpessoal

## Contratação
PJ a combinar

## Nossa empresa

A Razzo é uma Software House gaúcha focada no desenvolvimento de softwares e soluções inovadoras, sempre buscando encarar novos desafios. Nosso time é composto por gerentes de negócio, designers e um seleto time de desenvolvedores, que atuam em conjunto com seus lideres em diversos projetos.

## Como se candidatar

Por favor envie um email para contato@razzo.tech com seu CV anexado - enviar no assunto: Vaga React Front End

## Tempo médio de feedbacks

Costumamos enviar feedbacks em até 3 dias após cada processo.
E-mail para contato em caso de não haver resposta: neomar@razzo.tech

#### Alocação
- Remoto

#### Regime
- PJ

#### Nível
- Júnior
- Pleno

**Comment by powilliam** [comment]
Fala, Neomar! Não consegui entrar em contato através do e-mail ```contato@razzo.tech```, acusando de que o email é inexistente. Há outra maneira para contato?

**Comment by wsilvadev** [comment]
Sim

**Comment by pedropjr** [comment]
@wsilvadev Poderia informar um e-mail válido para contato?

Agradeço desde já!

**Comment by pedropjr** [comment]
@neomarbassani Poderia informar um e-mail válido para contato?

Agradeço desde já.

**Comment by neomarbassani** [comment]
Bom dia @powilliam @wsilvadev e @pedropjr... Realmente estavam retornando os e-mails do contato, mas já foi corrigido.

Se retornar novamente, pode enviar diretamente para neomar@razzo.tech.

**Comment by deeborges** [comment]
Há possibilidades de CLT, se sim, já quero.  :)

**Comment by neomarbassani** [comment]
Boa noite @deeborges 

No momento não temos muito interesse em contratação CLT, devido a algumas crenças internas.
Mas nos encaminhe seu Curriculo que vamos analisar com certeza.

Favor, cita no email essa possibilidade de CLT apenas.

Abraço.

**Comment by neomarbassani** [comment]
Pessoal... Recebemos um grande número de curriculos em 3 dias e estamos fechando a vaga aqui enquanto finalizamos os contatos e entrevistas com estes.

Desde já agradecemos e desejamos sucesso a todos!
