### ISSUE TITLE
[Florianópolis/SC] Desenvolvedor(a) React na Cognyte

### ISSUE THREAD

**Issue by felipegb34** [react-brasil/vagas#884]
A Cognyte está buscando um desenvolvedor fullstack fera em React e Java para completar o time. Se identificou? Vem entender mais sobre essa oportunidade!

**Como será o seu dia-a-dia?**

- Trabalhará com desenvolvimento de produtos e soluções na área de telecomunicações e segurança;
- Fará parte do time, trocando experiências e trabalhando em equipe;
- Avaliará tecnologias para desenvolvimento de novas soluções;
- Terá incentivos para crescimento e desenvolvimento profissional;
- Atuará ativamente com os membros da equipe na criação de novos produtos/funcionalidades, buscando o aprimoramento da experiência dos usuários e mantendo padrões visuais da empresa;
- Atuará na criação de mockup e protótipos que permitam validar novos conceitos, novas funcionalidades ou para demonstrar novas versões;
- Desenvolverá e manterá atualizados os guias/frameworks/padrões que permitam a outros desenvolvedores utilizarem a identidade visual e seus componentes na construção de novos produtos ou funcionalidades;
- Pesquisará e desenvolverá novas ferramentas/produtos para área de telecomunicação e segurança;
- Identificará, analisará e corrigirá problemas em sistemas.

**E aí, gostou? Tem mais!**

Atualmente estamos trabalhando em modelo Home Office em função da pandemia e, até o momento, não temos previsão para voltar ao escritório. Mas algo é certo: quando a situação for normalizada, manteremos o trabalho home office (ao menos em alguns dias da semana) como uma possibilidade - além de uma jornada de trabalho flexível!

**Mas as vantagens não param por aí:**

- Fazer parte de um time global, desenvolvendo não só suas habilidades técnicas, mas também sua capacidade de comunicação e interação com outros países;
- Verba disponível para treinamentos, participação em eventos, cursos EaD;
- Benefícios para deixar o seu dia mais saudável: frutas, iogurte, granola;
- Café, Capuccino, Chocolate quente e chá liberados!
- Folga no dia do aniversário;
- Banco de horas;
- Ginástica laboral;
- Massagem;
- Casual dress code;
- Convênios diversos com restaurantes, academias e outros;
- Participação nos lucros e resultados;
- Pacote de benefícios tradicionais com valores diferenciados: VT, VR/VA, Plano de saúde, Plano odontológico, Seguro de vida.

**Parece maravilhoso! Mas, afinal, o que a Cognyte faz?**

Somos uma multinacional americana que desenvolve produtos e soluções de alta tecnologia para as áreas de Defesa e Segurança e empresas de telecomunicações. Nosso amplo portfólio de produtos é utilizado em mais de 100 países, ajudando governos, infraestruturas críticas e organizações empresariais a neutralizar e prevenir o terror, crime e ameaças cibernéticas. Somos líderes de mercado no que fazemos e estamos sempre em busca de novos produtos que façam a diferença para os nossos clientes. Nossa missão é fazer do mundo um lugar mais seguro!

E aí, topa o desafio? Manda o seu currículo e vamos conversar!
https://www.cognyte.com/careers/C3.812/react-java-fullstack-developer/
 
**O que você precisa ter?**

- Ensino superior completo ou em andamento na área de Tecnologia;
- Experiência com tecnologias como Java, Springboot, APIs REST, Git, entre outras.
- Experiência com React;
- Experiência em JavaScript / JQuery / CSS;
- Conhecimento na arquitetura microsserviços;
- Flexibilidade e interesse para estar sempre aprendendo novas tecnologias; 
- Inglês intermediário.

 **O que será um diferencial?**

- Experiência com Cloud (AWS / Azure);
- Conhecimento em GitLab - CI/CD e Docker
- Linux
- Pós-graduação em Engenharia de Software ou Sistemas de Informação.

Fez sentido? Manda o seu currículo no link abaixo e vem conversar com a gente ;)
https://www.cognyte.com/careers/C3.812/react-java-fullstack-developer/

- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by guilhermeorcezi** [comment]
júnior cursando bootcamp não tem chance? :/

**Comment by felipegb34** [comment]
> Essa issue foi marcada como inativa por não ter nenhuma atividade recente. A vaga ainda está disponível? Caso não haja nenhuma atividade esta issue será fechada nos próximos 7 dias. Obrigado por contribuir.

Ainda temos vagas em aberto para essa descrição.

**Comment by felipegb34** [comment]
Ainda temos vagas em aberto para essa descrição.

**Comment by amaralc** [comment]
@felipegb34, cliquei no link para realizar a inscrição, mas a página não foi encontrada. Existe alguma outra maneira de me inscrever, talvez enviando o currículo para algum email?

**Comment by felipegb34** [comment]
@amaralc https://www.cognyte.com/careers/locations/br/
Link atualizado
