### ISSUE TITLE
[SÃO PAULO/SP][CAMPINAS/SP][QUALITY ASSURANCE]

### ISSUE THREAD

**Issue by biarsi** [react-brasil/vagas#886]
Oi, pessoal! Nós da Intera temos uma ótima oportunidade para você que é analista de testes. Estamos em busca de talentos que tenham experiência consolidada com Testlink e Jira, nível sênior, para integrar o time da Zup.

A Zup desenvolve produtos digitais disruptivos que impactam a vida de milhares de usuários. A empresa cresceu mais de 30 vezes nos últimos cinco anos, contando com mais de 850 zuppers e em seis cidades. Liderar times de QA, desenvolver planos de testes, projeções de testes, casos de testes funcionais, scripts de testes não- funcionais.

• Alguns pontos que são vitais para a vaga:

o Possuir disponibilidade de atuação em projetos vários
o Possuir foco em disseminar o conhecimento
o Ser organizado tendo vistas o trabalho em equipe
o Ser atento a pequenos detalhes
o Facilidade de relacionamento
o BDD
o Ferramentas de gestão de testes (Testlink)
o Ferramentas de gestão de defeitos (Jira)
o Planejamento de Testes Execução de Testes Manuais e Automatizados
o RESTful services
o Framework de automação de testes (Selenium Web Driver, Cucumber, SoapUi, Calabash)
o Web Services
o Análise de Requisitos
o Planejamento e execução de testes de performance/stress/segurança/massa
o Preparar ambiente para testes
o JUnit
o SQL
o Metodologias Ágeis
o Jmeter
o JSON
o Análise de Riscos
o Continuos Integration utilizando GIT, Maven, Jenkins, Sonar e Docker

Se identificou com a oportunidade? Vem aqui nesse link se inscrever:

https://byintera.in/178

Conhece alguém que esteja em busca de oportunidades como essa? Compartilha o link ou fala comigo no privado.
Estou disponível para qualquer dúvida. Desejo um ótimo dia e um sorriso de orelha a orelha =D

**Comment by nicholasess** [comment]
@biarsi peço desculpas, mas a vaga não se enquadra nos nossos requisitos.

Só aceitamos vagas de React/ React Native
