### ISSUE TITLE
[Remoto] Desenvolvedor Frontend React.js

### ISSUE THREAD

**Issue by audora-cto** [react-brasil/vagas#900]
## Descrição da vaga

Faça parte de uma equipe espetacular que trabalha em grandes projetos de software Saas e On-Premises. Você irá contar com a colaboração de mais de 50 outros colegas que assim como você almejam vencer novos desafios diariamente e comprometer-se com o atendimento das necessidades dos clientes.

## Local

100% Remoto

#### Diferenciais

- flexibilidade de horário
- work from home
- participação em palestras exclusivas
- possibilidade de ganhos extras opcionais com hackathons e multirões

## Requisitos

**Obrigatórios:**
- Conhecimentos sólidos em React

**Desejáveis:**
- conhecimentos em Java

## Contratação

PJ ou CLT a combinar

## Nossa empresa

A Audora é uma empresa com 15 anos de vida que fornece soluções para o setor jurídico e empresas que desejam melhorar seus processos internos. Contamos com uma equipe multidisciplinar que evolui constantemente.

## Como se candidatar

Por favor envie um email para jobs@audora.com.br com seu CV anexado - enviar no assunto: Vaga React Js

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ CLT
- ⚖️ Estágio
- ⚖️ Freela
- ⚖️ Outros
- ⚖️ PJ

**Comment by ceelsoin** [comment]
Não precisa de conhecimentos em React e Javascript pra essa vaga de React Native?

**Comment by audora-cto** [comment]
Sim. A vaga não é para React Native e sim para React.
Eu me enganei quando fiz o post mas de pronto corrigi.

**Comment by luca-henrique** [comment]
Mandei o curriculum, esperando o feedback

**Comment by adhamlucas** [comment]
Enviei o curriculum, no aguardo de feedback ;)
