### ISSUE TITLE
[Remoto] React Native Developer no Olist

### ISSUE THREAD

**Issue by DirleiDionisio** [react-brasil/vagas#907]
## Descrição da vaga

Nosso time mobile continua crescendo e precisando da ajuda de devs com experiência em ReactNative.

Olist é uma startup em crescimento super acelerado com a missão de ajudar quem quer vender a encontrar quem quer comprar. Somos a maior loja nos marketplaces brasileiros e estamos em processo de expansão internacional. Nosso mais novo app, em menos de 6 meses, já ajudou pequenos lojistas em mais de 100 países a começar a vender online. Temos muita coisa pra evoluir e pra isso precisamos da ajuda de gente boa e ágil, que curta a nossa cultura.

Se você tem senso de dono, faz acontecer, é mão na massa e vê oportunidade onde outros vêem problemas, se liga nos detalhes abaixo e faça a inscrição pelo link no final. (Se quiser bater um papo sem compromisso antes de se candidatar, basta me procurar no LinkedIn)

## Local

Remoto 100% ou escritório em São Paulo ou escritório em Curitiba (você escolhe)

## Benefícios

Já imaginou decidir o quanto você vai receber no seu vale-alimentação? No Olist isso é totalmente possível. Isso acontece porque disponibilizamos um pacote de benefícios flexíveis baseado em um sistema de pontuação. Com ele, você decide onde colocar seus pontos e monta a sua própria combinação de benefícios. Confira abaixo os benefícios que os olisters têm acesso:

- Vale-Alimentação
- Vale-Refeição 
- Vale-transporte
- Auxílio Mobilidade
- Plano de Saúde
- Plano Odontológico
- GymPass
- Incentivo aos estudos (cursos de extensão, graduação, especialização, pós-graduação e MBA)

#### Diferenciais

- Desconto em universidades e estabelecimentos online parceiros
- Programa de indicação de funcionários
- Universidade Olist: programa de desenvolvimento interno com mais de 15 cursos 
- Seguro de Vida
- Magnetis (plataforma de investimento)
- Vittude (plataforma de terapia)

## Requisitos

**Obrigatórios:**
- Experiência com desenvolvimento em React Native para criação de aplicativos para iOS e Android;
- Bons conhecimentos de JavaScript e suas nuances, incluindo a sintaxe ES6+;
- Capacidade de escrever código Javascript limpo e bem documentado;
- Conhecimentos sobre APIs REST e seu consumo;
- Experiência com testes automatizados;
- Experiência com metodologias ágeis.
- Ter autonomia, capacidade de autogestão e auto-organização do trabalho;
- Iniciativa e colaboração em equipe
- Flexibilidade
- Comunicação 

**Diferenciais:**
- Ter trabalhado em projeto no setor de e-commerce;
- Ter se relacionado diretamente com as áreas de negócio;
- Inglês avançado.

## Contratação

CLT

## Nossa empresa

https://olist.com/sobre-o-olist/

## Como se candidatar

https://olist.gupy.io/jobs/551630

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by emersonbrs** [comment]
Done.
