### ISSUE TITLE
[Remoto/São Paulo/Salvador] Engenheiro(a) Frontend React na Sanar

### ISSUE THREAD

**Issue by Allan1** [react-brasil/vagas#910]
## Descrição da vaga

A Sanar é uma MedTech que existe para transformar os profissionais da Medicina em super profissionais, atuando em toda sua jornada - desde o dia que pisam na faculdade até o dia de alcançar o máximo da sua maturidade profissional. Para isso, temos uma linha de produtos focados nas etapas de formação e educação e em como ser mais eficaz.

Como vamos alcançar essa missão? Através de tecnologia! Por isso estamos evoluindo um time incrível de tecnologia. Recebemos recentemente um investimento Series B e estamos crescendo bastante nossos times.
 
A nossa estrutura é divida em squads multidisciplinares, com Engenheiros(as), Designers e Product Managers colaborando para construir produtos que entreguem valor de forma excepcional para nossos clientes.

Aqui você pode conhecer mais sobre os nossos produtos: https://www.sanarmed.com/sobre

E nesse momento estamos buscando uma pessoa motivada por grandes desafios para atuar como Engenheiro Frontend e nos ajudar a continuar essa construção.

## Local

Remoto ou Escritórios em São Paulo e Salvador

## Benefícios

- Vale Transporte ou Auxílio Gasolina ou Auxílio Internet (para os remotos)
- Vale Alimentação ou Refeição
- Plano de Saúde
- Plano Odontológico
- Horário de Trabalho Flexível. Aqui você que irá montar seus horários a partir das suas demandas e das demandas do seu time.
- Não temos Dress Code. Você pode vir vestido como quiser (respeitando sempre o outro).
- Aula de Inglês na própria sanar. Independente do quanto você já sabe, aqui você tem a possibilidade de ter aulas toda semana com nosso teacher, pra aprimorar, aprender, praticar...
- Happy Hour Semanal. Toda semana temos um momento de descontração para nossos sanáticos.
- Sala de Descanso feita pra quem precisa relaxar e descansar um pouco ou pra aquela sonequinha depois do almoço.
    
## Requisitos

**Obrigatórios:**
- Mínimo de 2 anos de experiência como Engenheiro(a) Frontend
- Mínimo de 1 ano de experiência com React

## Desafios
- Escalar um produto voltado para profissionais da saúde utilizando React e seu ecossistema;
- Aprender a fazer a entrega e consumo de dados para a aplicação web utilizando GraphQL (Apollo ou Relay);
- Construir os testes automatizados do projeto em JavaScript;
- Definir os padrões arquiteturais da plataforma, estabelecendo boas práticas, através do clean code, design patterns e dos princípios de SOLID.

## Contratação

CLT

## Nossa empresa

Conheça um pouco mais da Sanar aqui:
- https://www.sanarmed.com/carreiras
- https://www.sanarmed.com/sobre
- https://www.linkedin.com/company/sanar/

## Como se candidatar

Podem falar diretamente comigo via LinkedIn: https://www.linkedin.com/in/allanoliveira1/

## Labels

- 🏢 Remoto
- ⚖️ CLT
- 💰 5k-10k
- 💰 10k-15k

**Comment by italo-lima** [comment]
Boa tarder, full time ou part time?

**Comment by alangabrielbs** [comment]
> Boa tarde, full time ou part time?

Full time Italo
