### ISSUE TITLE
Desenvolvedor Full Stack, Node, React- Home Office e PJ

### ISSUE THREAD

**Issue by Andrea-wa** [react-brasil/vagas#911]
## Descrição da vaga

Buscamos desenvolvedores com um perfil generalista, pois irá trabalhar com diferentes tecnologias. 
Tecnologias / Stacks mais prováveis 
- Node 
- PHP / Wordpress 
- React 
- Vue 
- MongoDB 
- SQL 
- GraphQL 
- AWS 
- Docker 
- Git 
- HTML(5) 
- CSS(3) 
- TDD 

## Local

Remoto, 100% Home Office

## Benefícios

- Duas semanas de férias remuneradas

## Requisitos
- Saber trabalhar em times participativos para entender todas as demandas; 
- Ter um perfil analítico e interessado em discutir as soluções dos problemas e 
demandas; 
- Ter vontade de ajudar os outros integrantes do time para as entregas aconteçam 
com qualidade, difundindo conhecimento; 
- Ser capaz de mudar de projetos/produto com alguma frequência (de acordo com a 
definição do backlog e sprints); 
- Saber trabalhar com metodologias ágeis (diferencial) 

**Obrigatórios:**

- Experiência com Node e React.

**Desejáveis:**
- conhecimentos em PHP

**Diferenciais:**
- Vue 
- MongoDB 
- SQL 
- GraphQL 
- AWS 
- Docker 
- Git 
- HTML(5) 
- CSS(3) 

## Contratação

PJ a combinar

## Nossa empresa

Somos uma empresa de desenvolvimento de sistemas, com o formato diferenciado do home office, projetos organizados e uma equipe foda!!! 

## Como se candidatar

Por favor envie um email para vagas@waproject.com.br com seu CV anexado - enviar no assunto: Vaga Full Stack

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ
- 💰 3k-5k
- 💰 5k-10k

**Comment by emersonbrs** [comment]
Done! ;D
