### ISSUE TITLE
[São Paulo][English] React Developer na Regera

### ISSUE THREAD

**Issue by Toasterson** [react-brasil/vagas#926]
## Descrição da vaga

We are looking for a Junior developer willing to learn and work with a fun team in a startup environment.  
This Job requires writing code in English. 

## Local

Flexível, São Paulo ou Remoto

## Benefícios
- Plano de Saúde + VT + VR;
- Salário (via distribuição dividendos): a depender do do perfil/experiência;
- Bônus anual (baseado em metas);
- 30 dias de férias remuneradas.

#### Diferenciais

- Fun and open Team
- On the Job Training opportunity
- Plural and diverse Team

## Tasks and responsibilities
- Write a frontend application in ReactJs with help of ReduxJs and linguiJs.
- Write Mobile apps with React Native.
- Manage and deploy the apps to Production with the GitFlow and GitLab processes.
- Participate in CodeReviews in GitLab.
- Deploy and help manage the application infrastructure.
- Help design and implement the future capabilities of the Regera Platform.

## Preferred Attributes
- Wants to work in smaller teams / startups
- Has previously worked with these technologies or would like to engage with them
    - Kubernetes
    - GitLab
        - AutoDevOps
    - CI/CD
    - Docker
    - Helm
    - ReactJs
    - ReduxJs
    - Gatsby
    - Typescript
    - styled-components
- Is Open to learn new technologies and practices

## Contratação

PJ

## Nossa empresa

We are a CivicTech/Fintech Startup making Judicial claims accessible to everyone. Our current cause: 
[Dieselgate](https://dieselgate.com.br)

## Como se candidatar

Por favor envie um email para [contato@regera.vc](mailto:contato@regera.vc) com seu CV anexado

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👦 Júnior
- 👨 Pleno
- 👴 Sênior
- ⚖️ Freela
- ⚖️ PJ
- 💰 5k-10k

**Comment by tech3br** [comment]
Há possibilidade de trabalho em modalidade freelancer?

**Comment by Toasterson** [comment]
Hi, yes it is possible to do so, however we already have enough frontend devs for what we need. Closing this issue. Thanks for all the Interest, I will contact people that have sent their CV's individually.
