### ISSUE TITLE
[São Paulo] Desenvolvedor FullStack Javascript - React / React Native

### ISSUE THREAD

**Issue by bilicio** [react-brasil/vagas#928]
## Descrição da vaga

Procuramos alguém compromissado que queira seguir na carreira de desenvolvedor web e mobile.
Preciso também de alguém com experiência, que saiba lidar com adversidades no código, solucionar e resolver problemas de peso, carregamento, estado etc.

## Local

Escritório, São Paulo - Butantã

## Requisitos

**Obrigatórios:**
- Dominio de React Native IOS/ANDROID
- Dominio React ( hooks, reducer ) 
- NODEJS
- Programação de frontend com backend ( fullstack )

**Desejáveis:**
- Configuração de servidores / cloud.

**Diferenciais:**
- RXDB / POUCHDB / COUCHDB
- Meteor
- Mongo
- NOSQL

## Contratação

PJ a combinar

## Nossa empresa

Antidoto Tecnologias Interativas
[http://www.antidotodesign.com.br](http://www.antidotodesign.com.br)
Somos uma empresa de tecnologia especializada em soluções inovadoras e precisamos de pessoas que queiram crescer conosco. Atuamos em eventos presenciais e virtuais, óculos de realidade virtual, aumentada, totens interativos etc.

## Como se candidatar

Eu sou o PH, encaminhem um email para mim no endereço [ jobs@antido.to]( jobs@antido.to) com seu CV anexado - enviar no assunto: Vaga React com sua pretenção salarial. Obrigado e vejo vocês logo mais!

**Comment by emersonbrs** [comment]
Enviado. 👍

**Comment by bilicio** [comment]
@nic eu precisava modificar essa vaga e publicá-la novamente, como devo proceder?
