### ISSUE TITLE
[REMOTO] ReactJs Pleno

### ISSUE THREAD

**Issue by procodestudio** [react-brasil/vagas#935]
## Descrição da vaga

Desenvolvedor ReactJs pleno para início imediato. 

## Local

Remoto

## Requisitos

Disponibilidade em horário comercial

## Contratação 

PJ

## Como se candidatar

Por favor envie um email para sergio@procode.studio com seu CV anexado - enviar no assunto: Vaga ReactJs

## Labels

- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar
- ⚖️ PJ

**Comment by willianbvsanches13** [comment]
Qual a faixa salarial?
