### ISSUE TITLE
[São Paulo] Front-end Developer no Mercado Pago

### ISSUE THREAD

**Issue by freddybrasileiro** [react-brasil/vagas#943]
## Descrição da vaga

Meu nome é **Freddy Brasileiro** e sou **Líder de Projetos** da equipe de **Checkout Web** aqui do **Mercado Pago**. 

Se você é **frontend sênior** e está interessado em fazer parte da equipe de Checkout Web do Mercado Pago, vem comigo!

Nosso objetivo em Checkout é criar soluções simples, escaláveis, tolerantes a falhas e mensuráveis para suportar milhares de requests por minuto. Aspiramos ter um uptime de 99.9% e hoje estamos muito perto de alcançar.

Nosso Checkout Web é o que faz a junção entre o ecossistema do Mercado Pago e os usuários que querem comprar e vender utilizando Mercado Envios, Mercado Pontos e Mercado Créditos.

Procuramos um desenvolvedor com experiência sólida, autonomia, forte conhecimento técnico e com grande capacidade analítica para enfrentar os desafios técnicos que envolvem trabalhar em um projeto para milhões de usuários.

Tá esperando o que?
Entra em contato comigo via LinkedIn e a gente bate um papo https://www.linkedin.com/in/freddybrasileiro/

## Local

No momento, estamos trabalhando 100% remoto devido ao contexto do COVID-19. Mesmo assim, continuamos tendo apoio para enfrentar da melhor maneira nossos desafios pessoais e profissionais.

Meli Cidade, em Osasco

## Diferenciais

- Ser parte de uma empresa com espírito empreendedor, na qual adoramos pensar grande e em longo prazo.
- Ser protagonista de seu desenvolvimento em um ambiente de oportunidades, aprendizagem, crescimento, expansão e projetos desafiadores.
- Compartilhar e aprender em equipe, com excelentes profissionais e especialistas.
- Um excelente clima de trabalho, com tudo o necessário para você viver uma grande experiência. :)

## Requisitos

- Contar com experiência prévia com desenvolvimento Front-End em ambientes de alto desempenho e escalabilidade.
- Ter experiência com tecnologias Web abertas, como JavaScript, HTML e CSS.
- Possuir conhecimento de Vanilla JavaScript, Sass, NodeJS, Backbone, Angular, React, Express, WPO ou SEO.

## Contratação

CLT

## Como se candidatar

Por favor em contato comigo via LinkedIn e a gente bate um papo https://www.linkedin.com/in/freddybrasileiro/

## Labels

- 🏢 Presencial
- 👴 Sênior
- ⚖️ CLT

**Comment by nic** [comment]
Opa @freddybrasileiro!
Poderia colocar no formato, pls?
https://github.com/react-brasil/vagas/blob/master/.github/issue_template.md
