### ISSUE TITLE
[Campo Grande - MS] React Developer na SCV Sistemas

### ISSUE THREAD

**Issue by anaelj** [react-brasil/vagas#945]
## Descrição da vaga

O projeto será iniciado do zero, com base em outro produto consolidado que temos, não é uma migração, é outro produto para suprir uma grande demanda que temos.

## Local

Escritório, Campo Grande - MS

## Benefícios

- Plano de saúde
- Ajuda de Custo

## Requisitos

**Obrigatórios:**
- 2 anos de experiência com desenvolvimento React e Node

**Desejáveis:**
- React Native
- Banco de Dados

## Nossa empresa

Temos uma grande base de clientes espalhada por todo o país, temos demanda para expandir essa base de clientes com um produto novo.

## Como se candidatar

Por favor envie um email para anael@scvsistemas.com.br - enviar no assunto: Vaga React Native

## Labels

- 🏢 Presencial
- 👨 Pleno
- ⚖️ A-Combinar
- ⚖️ CLT

**Comment by raulccb** [comment]
Em época de pandemia precisa ser presencial ou vai como remoto e pós pandemia começa como presencial ?

**Comment by anaelj** [comment]
Devido a forma que a equipe está estruturada hoje e os processos que temos precisa ser presencial de início, mesmo com a pandemia. Não temos previsão de quando, mas temos o objetivo de tornar isso mais flexível.
