### ISSUE TITLE
[Brasil] React-Native Profissional na DOCTORWEB

### ISSUE THREAD

**Issue by robleds** [react-brasil/vagas#953]
## Descrição da vaga

Contrato de 5 horas diárias para profissionais com conhecimentos PLENO em React-NATIVE

## Local

Hangout, Meet, Whereby ou Zoom

## Benefícios

- Pagamento semanal
- Gerente de Projetos

#### Diferenciais

- Pagamento em dia
- Contrato flexível

## Requisitos

**Obrigatórios:**
- Portfólio ou repositório com aplicativos (mais de 1) publicados e acessíveis para visualização
- Boa comunicação

**Desejáveis:**
- Envolvimento com o projeto

## Contratação

PJ

## Nossa empresa

www.doctorwebbrasil.com.br

## Como se candidatar

Por favor envie seu CV anexado por email para [tech@doctorwebbrasil.com](url) - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Remoto
- 👨 Pleno
- ⚖️ PJ
- 💰 3k-8k

**Comment by GuilhermeLis** [comment]
Olá, boa tarde, o gmail não conseguiu achar o endereço de e-mail que você informou
