### ISSUE TITLE
[Belo Horizonte/Remoto] React Native Developer Sênior na Rethink

### ISSUE THREAD

**Issue by rethink-eder** [react-brasil/vagas#962]
## A Empresa - Rethink Tecnologia
A Rethink é uma empresa mobile-first que procura desenvolver produtos que entreguem design, conteúdo e funcionalidade.
Nós prezamos pela experiência do usuário com nossos aplicativos, e também com a qualidade que entregamos para nossos clientes: qualidade de código e eficiência na entrega.
Nossos clientes são parceiros de longa data, não saímos fazendo projetos soltos ou de clientes aleatórios. Convidamos você a conhecer nosso [site](https://rethink.dev), a seção de [Carreiras](https://rethink.dev/carreiras) e os projetos e clientes que trabalhamos!
Nossa empresa tem espírito jovem e inovador. Somos de Belo Horizonte mas trabalhamos principalmente para clientes em São Paulo. Já éramos uma empresa que sabia trabalhar remoto desde antes da pandemia (vários colaboradores não são de BH), então essa adaptação de home office para nós foi fácil.

## Descrição da vaga
Desenvolvimento de aplicativos usando Reactive Native com grande foco em usabilidade e performance.

## Local
Remoto ou Escritório em Belo Horizonte

### Diferenciais
- Remuneração compatível com o seu nível de conhecimento;
- Ferramentas de apoio que facilitam o seu trabalho e a comunicação no dia-a-dia da empresa como Jira, Confluence, Slack, Git, AWS,...
- No Dress Code;
- Horário flexível;
- Excelente ambiente de trabalho;
- Treinamentos de desenvolvimento profissional;
- Office / Home Office.

### Obrigatórios
- Possuir excelente conhecimento técnico em JavaScript;
- Mínimo de 3 anos de experiência em desenvolvimento React Native;
- Experiência com utilização de Redux e Mobx;
- Experiência com desenvolvimento Typescript;
- Conhecimento em testes unitários e testes de integração;
- Experiência com ferramentas de versionamento de código e desenvolvimento colaborativo (ex.: GitHub, Bitbucket etc);
- Estar atualizado com as principais arquiteturas e boas práticas para desenvolvimento Mobile;
- Preocupar com a abstração de código, quebrando grandes módulos em componentes reutilizáveis;
- Experiência com armazenamento off-line, processamento em segundo plano, threading e notificações por push;
- Gostar de trabalhar em equipe;
- Prezar por código limpo e bem estruturado;
### Desejáveis
- Possuir inglês fluente;
- Experiência com desenvolvimento nativo iOS e Android;
- Conhecimento avançado em UX;
- Experiência com desenvolvimento de backend ou micro-serviços;
### Diferenciais
- Projetos opensource / repositorios no github;

## Contratação
À combinar

## Como candidatar:
Enviar currículo através do link: https://secure.collage.co/jobs/rethink/18960

## Labels
- 🏢 Flexível
- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ A-Combinar

**Comment by rodgomesc** [comment]
@rethink-eder o link para aplicar a vaga está quebrado

**Comment by rethink-eder** [comment]
Vaga ainda ativa.

**Comment by rethink-eder** [comment]
Vaga reativada.
