### ISSUE TITLE
[Itaperuna - RJ] Desenvolvedor React Native na empresa iNova

### ISSUE THREAD

**Issue by carlosoliveiradev** [react-brasil/vagas#964]
## Descrição da vaga

Projeto que consiste na construção de aproximadamente 40 telas, com entrega para 23/10. Todas as telas estão prontas no photoshop.

## Local

Remoto, Rio de Janeiro, Itaperuna, Aeroporto

## Requisitos

**Obrigatórios:**
- Experiência com React Native

## Contratação

PJ a combinar

## Nossa empresa

A iNova nasceu da expertise de transformar pessoas em influencers digitais, através do melhor que elas têm a oferecer. Transformamos marcas e pessoas em expressões digitais, através de uma metodologia própria.

## Como se candidatar

Por favor envie um email para carlosoliveira@inovany.com.br com seu CV anexado - enviar no assunto: Vaga React Native

## Labels

- 🏢 Flexível
- 🏢 Remoto
- ⚖️ A-Combinar
- ⚖️ Freela
- ⚖️ PJ

**Comment by LuanCassiano** [comment]
São 40 telas pra entregar até amanhã, isso mesmo ?
