### ISSUE TITLE
[Rio de Janeiro/REMOTO] Desenvolvedor Full Stack SENIOR na Enter Sistemas

### ISSUE THREAD

**Issue by merciomedina** [react-brasil/vagas#970]
- Descrição da Empresa

A Enter Sistemas é uma empresa focada no desenvolvimento de soluções para o mercado de marketing digital.
Estamos no processo de criação de plataforma específica para o mercado e contratando pessoas que tenham
vontade de participar de um projeto grandioso e desafiador.

- É fundamental que:

O analista desenvolva aplicações ReactJS e React native;
Conhecer e desenvolver em NodeJS é um diferencial;
Tenha Disponibilidade em período integral;
Esteja disposto a aprender e ensinar. Compartilhar conhecimento é um diferencial.

- Requisitos

É ESSENCIAL ter experiência mínima de 3 anos;
Capacidade de tocar um projeto sozinho;
Cumprimento de prazos;
Ter sangue nos olhos;
Estar envolvido em todo o processo de entrega;
Compartilhar e sugerir melhorias que tornem a plataforma mais competitiva;
Conhecer e implementar novos processos do GIT;
Experiência anterior com desenvolvimento em React e trabalhado em equipe;
Ter ótimo raciocínio lógico;
Entregar código limpo;
Ter foco e disciplina;
Conhecimento em UI Design;

- Local de trabalho

Remoto

- Remuneração

Salário PJ de 4k a 6k;

** NÃO SERÃO CONSIDERADOS CURRÍCULOS DE DEVS JUNIOR OU PLENO **

- Diferenciais

Bancos relacionais e não relacionais;
Estar sempre antenado as novidades do mercado;
Ser pró ativo e comprometido com os resultados;

- Contratação 

Pessoa Jurídica;
Vaga 100% remota.

- Como se candidatar

Por favor envie um email para atacoshi@entersistemas.com.br com seu CV anexado - enviar no assunto: Vaga Desenvolvedor Full Stack.

## Labels

- 🏢 Remoto
- 👨 SÊNIOR
- ⚖️ PJ
- 💰 4k-6k

**Comment by lfnandoo** [comment]
Curriculo enviado!

**Comment by boldrini31** [comment]
Pede para trocarem as labels que estão invertidos.
