### ISSUE TITLE
Vaga React JS - Rio de Janeiro

### ISSUE THREAD

**Issue by tomefavre** [react-brasil/vagas#972]
https://www.linkedin.com/jobs/view/2218992615/

Vaga para React JS. Inglês obrigatório.

**Comment by VictorHCord** [comment]
Por favor detalhar mais a vaga.

**Comment by tomefavre** [comment]
Esta é uma oportunidade para trabalhar em um projeto internacional (outsourcing), onde o inglês fluente para conversação é necessário.


Como desenvolvedor, esperamos que você seja orientado a resultados, responsável por suas entregas, sendo hábil no trabalho colaborativo e participativo em um time. 


No dia-a-dia- você fará:

Compreender os objetivos do projeto e interagir com outros membros da equipe para implementar as melhores soluções técnicas disponíveis;
Desenvolver a nova versão - a "Next Generation" - de um sistema existente e expandi-lo através do uso de novas tecnologias e plataformas;
Prototipar, Redesenhar e Customizar interfaces conforme a necessidade do cliente;
Utilizar as boas práticas de mercado para desenvolvimento e segurança de aplicações;
Reunir-se com o cliente e com o time, interagindo continuamente e oferecendo informações e atualizações conforme planejado;
Buscar soluções e interagir com os demais membros do time visando o atingimento dos objetivos propostos.

Para esta posição é necessário:

Curso superior completo em TI (e suas variantes), com experiência relevante na área de atuação e/ou função;
Experiência de trabalho com equipes pequenas/médias (6-10 profissionais);
Experiência em ambiente Linux;
Compreensão (e aplicação) dos conceitos de User Experience (UX);
Desejo de aprender novas tecnologias e rapidez na sua implementação;
Ter o inglês fluente para conversação é pré-requisito.

O Stack solicitado:

Experiência com HTML, HTML5, JS, jQuery, CSS, SASS
ReactJS
Conhecimento em arquitetura de APIs / JSON / REST;
Banco de Dados Oracle ou MS-SQL Server;
Conhecimentos em Git e/ou similares (controle de versão, pipelines, integração, etc);

Diferenciais:

Conhecimento em ambientes Cloud e seus serviços (preferencialmente AWS, Azure);
Microsserviços e segurança de APIs;
Multithreading;
Conhecimentos em metodologia DevOps / DevSecOps;

Espera-se de você:

Curiosidade e espírito de equipe;
Responsabilidade com o projeto, prazos, código, segurança, pessoas, e objetivos finais de entrega;
Proatividade na identificação de problemas e soluções.

Oferecemos:

Ambiente estruturado em um dos maiores centros de coworking mundiais;
Contrato CLT;
Plano de saúde Bradesco;
VT + VA;
Posição no RJ/RJ.
