### ISSUE TITLE
[Fortaleza/Remoto] Front-end React Native Developer na Agenda Edu

### ISSUE THREAD

**Issue by thejoaov** [react-brasil/vagas#977]
## Descrição da vaga

Buscamos por uma pessoa desenvolvedora, nível pleno e sênior. É necessário que tenha um bom conhecimento de Javascript e boa familiaridade com React Native. Você irá atuar na evolução do nosso aplicativo. Nosso app, é a solução de comunicação de mais de um milhão de usuários que acompanham diariamente a rotina escolar por meio dele. Assim, você estará impactando diretamente na jornada educacional de escolas, alunos, famílias e educadores. Venha fazer parte dessa revolução!

## Local

Remoto ou Escritório, Fortaleza - Dionísio Torres

## Benefícios

- Plano de saúde (Amil 400) 100% pago pela empresa
- Plano odontológico (Amil) 100% pago pela empresa
- VR ou VA de R$ 21/dia (Alelo)
- Clube de benefícios

#### Diferenciais:

- Flexibilidade combinada de horários
- Ambiente informal onde cada um sabe das suas responsabilidades

## Requisitos
**Obrigatórios:**

Conhecimento na stack usada na aplicação:

- React Native
- Redux
- Redux Saga
- Javascript (ES6+)
- HTML/CSS3
- Frameworks de testes unitários e funcionais

**Desejáveis:**

- Gerenciamentos de aplicações usando as lojas da google play e app store.

**Diferenciais:**

- Conhecimento em Typescript, Styled Components
- Experiência com delivery de aplicações mobile com Fastlane.

## Contratação

CLT

## Nossa empresa

Surgimos em 2014 para ajudar a resolver o problema de um pai, mas vimos que poderíamos ir além e nos tornamos a solução de milhares de responsáveis. Conseguimos, assim, construir juntos uma comunicação escolar simples, rápida e eficiente que ajuda diariamente mais de meio milhão de pessoas.

Nosso propósito é ajudar, é estar lado a lado na jornada educacional, construindo uma rede inteligente para troca de ideias e experiências. Aproximamos famílias e escolas com interações que geram valor e fortalecem laços.

Conquistamos amigos, parceiros e estamos presentes em mais de 2.000 escolas em todo o Brasil e com mais de 1 milhão e meio de usuários. Temos o apoio do programa Promessas da Endeavor e da Fundação Lemann, uma das maiores fundações educacionais do país, além de sermos a solução oficial da empresa líder mundial em educação. Também somos reconhecidos pela inovação através de prêmios como Santander Universidades, Desafio Brasil, Você Empreendedor e Campus Party. Atualmente fazemos parte do grupo Eleva Educação, referência nacional.

Nossa missão é engajar, tornar alunos e responsáveis participantes ativos da rotina escolar e, juntos, prepararmos para dar o próximo passo na construção de um saber plural e globalizado.

## Como se candidatar

Aplicar em [agendaedu.gupy.io](https://agendaedu.gupy.io)

## Labels

- 🏢 Presencial
- 🏢 Remoto
- 👨 Pleno
- 👴 Sênior
- ⚖️ CLT

**Comment by CatianoNorberto** [comment]
Eu sou o Catiano Norberto Ermelinda, estudante de Engenharia da computação na Universidade Anhembi Morumbi, atualmente no 8° semestre. 
O meu foco sempre é trabalho em equipe, procuro realizar minhas tarefas, sou humilde quando eu não sei de alguma coisa procuro alguém mais capacitado que eu para aprender as coisas. É algo que me motiva a continuar sempre inovando e encontrando novas formas de me conectar com o público. Isso me impulsiona a melhorar cada vez mais as minhas habilidades de desenvolvimento.
É por isso que acho que eu seria um profissional de alto impacto aqui, pois vocês valorizam muito duas coisas: tomar decisões objetivas baseadas em dados e contar boas histórias. Acho que posso ajudar nas duas coisas. Sou uma pessoa movida pelos estudos, adoro aprender novas coisas e tenho a certeza que esse time procura por pessoas assim, foi isso que me motivou aceitar esse desafio de querer fazer parte do time.

**Comment by CatianoNorberto** [comment]
Estou super animado para fazer parte desse time, e poder aceitar mais um desafio, porque confio plenamente nas minhas capacidade.

**Comment by CatianoNorberto** [comment]
Estou super animado para fazer parte desse time, e poder aceitar mais um desafio, porque confio plenamente nas minhas capacidade para poder ajudar o time a cumprir com os objetivos e alcançar a uma meta desejada.

**Comment by iurybrasileiro** [comment]
@thejoaov man boa noite, qual a faixa salarial pra pleno?

**Comment by CatianoNorberto** [comment]
Salário de 3000 a 4500, não procurando trabalho salário quero ganhar mais
experiência.

Em seg., 26 de out. de 2020 às 22:02, Iury Brasileiro <
notifications@github.com> escreveu:

**Comment by Juliohn** [comment]
Bom dia, alguma possibilidade dessa vaga aceitar contra proposta para contrato PJ ?

**Comment by CatianoNorberto** [comment]
Pode sim

Em ter, 27 de out de 2020 08:37, Juliohn <notifications@github.com>
escreveu:

**Comment by thejoaov** [comment]
> Bom dia, alguma possibilidade dessa vaga aceitar contra proposta para contrato PJ ?

Bom dia Júlio, infelizmente não :/

**Comment by gurgelrenan** [comment]
@CatianoNorberto Nós não estamos aceitando PJ no momento. Por favor não passe informações erradas.

**Comment by CatianoNorberto** [comment]
@renangurgel desculpa eu não sabia

Em ter., 27 de out. de 2020 às 10:02, Renan Gurgel <notifications@github.com>
escreveu:

**Comment by thejoaov** [comment]
Ainda está aberta sim.

**Comment by thejoaov** [comment]
Passando pra lembrar, da nossa nova plataforma de vagas: [agendaedu.gupy.io](https://agendaedu.gupy.io)
